// quiz/chiffres.ts — Les nombres qu'on devrait savoir par cœur, et ceux qui sont propres à Attic.
//
// POURQUOI UN THÈME POUR DES NOMBRES. Parce qu'un ordre de grandeur faux ne se rattrape pas : qui
// croit qu'une case de FFT vaut deux hertz à 2048 points cherchera longtemps pourquoi ses graves
// sont faux, et qui croit le masquage symétrique dégagera un mixage à l'envers. Ces nombres
// servent de garde-fou mental, et c'est pour cela qu'ils s'apprennent séparément des formules
// dont ils sortent.
//
// LA MOITIÉ SONT DES NOMBRES DU MÉTIER — 1200 cents, 24 bandes critiques, 44 100 échantillons par
// seconde. L'AUTRE MOITIÉ SONT CEUX D'ATTIC : les quarante caractéristiques d'une piste, les dix
// minutes au-delà desquelles le régime mémoire change, les trente secondes d'extrait que la
// classification analyse. Ceux-là ne s'apprennent nulle part ailleurs, et ce sont eux qu'on
// cherche dans le code quand on a oublié.
//
// LES LEURRES SONT DES VOISINS CRÉDIBLES, jamais des ordres de grandeur absurdes : 100 contre
// 1200, 12 contre 22, 0,5 contre 0,707. Un leurre dix fois trop grand se repère sans rien savoir.
//
// UN NOMBRE N'EST PAS TOUJOURS LA MÊME CHAÎNE DANS LES DEUX LANGUES, et l'oublier était une faute
// que ce fichier a d'abord commise : « 3,57 » se lit en anglais comme trois mille cinq cent
// soixante-dix, et « environ 46 ms » n'est pas de l'anglais du tout. Les propositions qui portent
// une virgule décimale ou un mot ont donc leur version anglaise ; celles qui sont un entier nu
// passent `null`, parce qu'elles s'écrivent vraiment pareil.

import type { Question } from "./types";

const chiffre = (
  id: string, enonce: string, enonceEn: string,
  choix: [string, string, string, string],
  /** `null` quand les propositions s'écrivent à l'identique dans les deux langues. */
  choixEn: [string, string, string, string] | null,
  pourquoi: string, pourquoiEn: string, niveau: 1 | 2 = 1,
): Question => ({
  id: `chiffre-${id}`, theme: "chiffres", niveau, enonce, enonceEn, choix,
  ...(choixEn ? { choixEn } : {}), pourquoi, pourquoiEn,
});

export const CHIFFRES: Question[] = [
  chiffre("cents-octave",
    "Combien de cents compte une octave ?",
    "How many cents are there in an octave?",
    ["1200", "100", "1000", "702"], null,
    "Cent cents par demi-ton, douze demi-tons par octave. L'unité a été choisie pour que le demi-ton tempéré fasse un nombre rond — ce qui rend visible, par contraste, que la quinte juste vaut 702 et non 700.",
    "A hundred cents per semitone, twelve semitones per octave. The unit was chosen so that the tempered semitone is a round number — which makes visible, by contrast, that the pure fifth is 702 and not 700."),
  chiffre("bandes-critiques",
    "Combien de bandes critiques couvrent l'audible ?",
    "How many critical bands cover the audible range?",
    ["24", "12", "40", "88"], null,
    "De 0 à 24 barks, l'échelle de Zwicker couvre l'audible jusqu'à 15,5 kHz. C'est le nombre de « canaux » dont l'oreille dispose réellement : deux sons dans la même bande se masquent et battent, deux sons séparés cohabitent.",
    "From 0 to 24 barks, Zwicker's scale covers the audible range up to 15.5 kHz. It is the number of « channels » the ear really has: two sounds in the same band mask and beat with each other, two separated ones coexist.", 2),
  chiffre("mono-decorrele",
    "Deux canaux parfaitement décorrélés : que garde leur somme mono ?",
    "Two perfectly decorrelated channels: what does their mono sum keep?",
    ["0,707, soit 1/√2", "0,500", "1,000", "0,000"],
    ["0.707, that is 1/√2", "0.500", "1.000", "0.000"],
    "Leurs énergies s'ajoutent quand leurs amplitudes se moyennent : la géométrie ne permet pas mieux. Un élargisseur qui atteint 0,71 en étant complètement décorrélé n'a donc rien perdu — il paie exactement ce que la largeur coûte. Le vrai défaut serait de descendre SOUS ce plancher.",
    "Their energies add where their amplitudes average: geometry allows no better. A widener reaching 0.71 while fully decorrelated has therefore lost nothing — it pays exactly what width costs. The real fault would be to go BELOW that floor.", 2),
  chiffre("la-midi",
    "Quel numéro de note MIDI porte le la du diapason, à 440 Hz ?",
    "What MIDI note number does the tuning A, at 440 Hz, carry?",
    ["69", "60", "57", "72"], null,
    "60 est le do central, qu'on confond volontiers avec le point d'ancrage. Neuf demi-tons plus haut se trouve le la 440, note 69 — et c'est ce 69 qui figure dans toutes les conversions note-fréquence du dépôt.",
    "60 is middle C, readily confused with the anchor point. Nine semitones higher sits A 440, note 69 — and it is that 69 that appears in every note-to-frequency conversion in the repository."),
  chiffre("canal-percussions",
    "Sur quel canal MIDI se trouvent les percussions, par convention ?",
    "On which MIDI channel do drums sit, by convention?",
    ["le canal 10", "le canal 1", "le canal 16", "le canal 9"],
    ["channel 10", "channel 1", "channel 16", "channel 9"],
    "Une convention du General MIDI, et non une règle du protocole : sur ce canal, un numéro de note ne désigne plus une hauteur mais un instrument. C'est pourquoi les sorties MIDI des boîtes à rythmes d'Attic s'y placent — 36 pour la grosse caisse, 38 pour la caisse claire, 42 pour le charley fermé.",
    "A General MIDI convention rather than a rule of the protocol: on that channel a note number no longer means a pitch but an instrument. That is why the MIDI outputs of Attic's drum machines sit there — 36 for the kick, 38 for the snare, 42 for the closed hi-hat."),
  chiffre("velocite-max",
    "Quelle est la vélocité maximale d'une note MIDI ?",
    "What is the maximum velocity of a MIDI note?",
    ["127", "128", "100", "255"], null,
    "Sept bits : de 0 à 127. Et la vélocité 0 ne veut pas dire « très doux » mais « note relâchée », ce qui est l'un des pièges du format. Un fichier MIDI n'a pas de volume, seulement des vélocités — c'est pourquoi les nœuds d'Attic convertissent leur réglage de volume en vélocité à l'export.",
    "Seven bits: from 0 to 127. And velocity 0 does not mean « very soft » but « note released », which is one of the format's traps. A MIDI file has no volume, only velocities — which is why Attic's nodes turn their volume control into a velocity on export."),
  chiffre("echantillonnage-cd",
    "Quelle est la fréquence d'échantillonnage du disque compact ?",
    "What is the sample rate of the compact disc?",
    ["44 100 Hz", "48 000 Hz", "22 050 Hz", "96 000 Hz"], null,
    "Choisie pour que la limite de Nyquist — 22 050 Hz — tombe juste au-dessus de l'audible, avec de la marge pour le filtre. 48 000 est la fréquence du cinéma et de la vidéo : les deux mondes cohabitent depuis quarante ans, et c'est la source d'innombrables rééchantillonnages.",
    "Chosen so that the Nyquist limit — 22 050 Hz — falls just above the audible range, with room for the filter. 48 000 is the rate of film and video: the two worlds have coexisted for forty years, and that is the source of countless resamplings."),
  chiffre("case-fft",
    "À 44 100 Hz sur une fenêtre de 2048 points, combien de hertz vaut une case du spectre ?",
    "At 44 100 Hz over a 2048-point window, how many hertz is one spectrum bin?",
    ["21,5 Hz", "2,15 Hz", "215 Hz", "43 Hz"],
    ["21.5 Hz", "2.15 Hz", "215 Hz", "43 Hz"],
    "44 100 / 2048. Le chiffre est le meilleur rappel du défaut de la FFT en musique : 21,5 Hz est fin devant un la 440, et grossier devant un mi 82 — où un demi-ton vaut moins de cinq hertz. C'est pourquoi les octaves graves d'un glissando spectral tombent à côté, avec un rapport de 1,67 au lieu de 2.",
    "44 100 / 2048. The figure is the best reminder of the FFT's shortcoming in music: 21.5 Hz is fine next to an A 440, and coarse next to an E 82 — where a semitone is less than five hertz. That is why the low octaves of a spectral glissando fall wide, with a ratio of 1.67 instead of 2.", 2),
  chiffre("fenetre-2048",
    "À 44 100 Hz, quelle durée couvre une fenêtre d'analyse de 2048 points ?",
    "At 44 100 Hz, what duration does a 2048-point analysis window cover?",
    ["environ 46 ms", "environ 4,6 ms", "environ 460 ms", "environ 21 ms"],
    ["about 46 ms", "about 4.6 ms", "about 460 ms", "about 21 ms"],
    "2048 / 44 100. Cette durée est la raison du flou temporel de toute analyse spectrale : deux frappes séparées de vingt millisecondes tombent dans la même trame, et rien ne les distinguera plus. C'est l'autre moitié du compromis dont la résolution fréquentielle est la première.",
    "2048 / 44 100. This duration is the reason for the temporal blur of any spectral analysis: two hits twenty milliseconds apart fall in the same frame, and nothing will tell them apart any more. It is the other half of the trade-off whose first half is frequency resolution.", 2),
  chiffre("quarante-features",
    "Les quarante caractéristiques qu'Attic extrait d'une piste se décomposent en :",
    "The forty features Attic extracts from a track break down into:",
    [
      "tempo (1), centroïde (1), chroma (12), moyenne et variance de 13 coefficients cepstraux (26)",
      "tempo (1), centroïde (1), chroma (12), 26 coefficients cepstraux distincts",
      "40 coefficients cepstraux",
      "tempo (2), centroïde (2), chroma (12), 24 coefficients cepstraux",
    ],
    [
      "tempo (1), centroid (1), chroma (12), mean and variance of 13 cepstral coefficients (26)",
      "tempo (1), centroid (1), chroma (12), 26 distinct cepstral coefficients",
      "40 cepstral coefficients",
      "tempo (2), centroid (2), chroma (12), 24 cepstral coefficients",
    ],
    "1 + 1 + 12 + 26 = 40. La variance compte autant que la moyenne : elle dit si le timbre BOUGE, ce qu'aucune moyenne ne peut dire. Le nœud « Caractéristiques de piste » les expose une à une, et « Classification de pistes » les emploie pour ranger une collection entière.",
    "1 + 1 + 12 + 26 = 40. Variance counts as much as mean: it says whether the timbre MOVES, which no mean can say. The « Track Features » node exposes them one by one, and « Track Classification » uses them to sort a whole collection.", 2),
  chiffre("mfcc-treize",
    "Combien de coefficients cepstraux Attic garde-t-il pour décrire un timbre ?",
    "How many cepstral coefficients does Attic keep to describe a timbre?",
    ["13", "26", "40", "12"], null,
    "Treize, dont il rend la moyenne et la variance — d'où les vingt-six composantes cepstrales du vecteur. C'est aussi ce qui limite la synthèse inverse : treize coefficients ne peuvent pas redire ce que vingt-six bandes mel contenaient, et c'est précisément à cela que servent les MFCC.",
    "Thirteen, of which mean and variance are returned — hence the vector's twenty-six cepstral components. It is also what limits inverse synthesis: thirteen coefficients cannot restate what twenty-six mel bands held, and that is precisely what MFCCs are for.", 2),
  chiffre("trente-secondes",
    "Quelle durée d'extrait la classification de pistes analyse-t-elle, au maximum ?",
    "What excerpt length does track classification analyse, at most?",
    ["30 secondes", "10 secondes", "2 minutes", "la piste entière, sans plafond"],
    ["30 seconds", "10 seconds", "2 minutes", "the whole track, with no cap"],
    "Le plafond des jeux de données de genre usuels, GTZAN compris. Un test le justifie : au-delà de trente secondes, allonger la piste ne change plus le vecteur — et sans ce plafond, une collection de plusieurs centaines de titres deviendrait très lente à classer.",
    "The cap of the usual genre datasets, GTZAN included. A test justifies it: beyond thirty seconds, lengthening the track no longer changes the vector — and without that cap, a collection of several hundred titles would become very slow to classify.", 2),
  chiffre("dix-minutes",
    "Au-delà de quelle durée de piste Attic change-t-il de régime mémoire ?",
    "Beyond what track length does Attic change memory regime?",
    ["10 minutes", "1 minute", "30 minutes", "3 minutes"], null,
    "Six cents secondes. En deçà, tout tient en mémoire sans qu'on y pense ; au-delà, un aperçu par nœud coûte environ cent dix mégaoctets pour dix minutes, et les nœuds que personne ne regarde — ceux qui sont pris dans un méta-composant — cessent d'en garder un.",
    "Six hundred seconds. Below it, everything fits in memory without a thought; beyond it, one preview per node costs about a hundred and ten megabytes for ten minutes, and the nodes nobody looks at — those caught inside a meta-component — stop keeping one.", 2),
  chiffre("shrutis",
    "Combien de degrés compte l'octave indienne classique ?",
    "How many degrees does the classical Indian octave have?",
    ["22", "12", "24", "7"], null,
    "Vingt-deux shrutis, en rapports justes et non en divisions égales. Un raga en choisit sept ou huit ; c'est pourquoi il ne s'écrit pas au clavier, et pourquoi le nœud « Gammes du monde » rend ses degrés en cents.",
    "Twenty-two shrutis, in pure ratios rather than equal divisions. A raga picks seven or eight of them; that is why it cannot be written on a keyboard, and why the « World Scales » node returns its degrees in cents.", 2),
  chiffre("comma",
    "Combien de cents vaut le comma pythagoricien ?",
    "How many cents is the Pythagorean comma?",
    ["23,46", "2,35", "100", "702"],
    ["23.46", "2.35", "100", "702"],
    "L'écart entre douze quintes justes et sept octaves. Toute l'histoire des tempéraments consiste à décider où le mettre : étalé sur les douze quintes, c'est le tempérament égal ; concentré sur une seule, c'est la quinte du loup du mésotonique.",
    "The gap between twelve pure fifths and seven octaves. The whole history of temperaments is deciding where to put it: spread over all twelve fifths, that is equal temperament; concentrated on one, that is meantone's wolf fifth.", 2),
  chiffre("tierce-juste",
    "Combien de cents vaut une tierce majeure juste, de rapport 5/4 ?",
    "How many cents is a pure major third, of ratio 5/4?",
    ["386", "400", "316", "702"], null,
    "Quatorze cents plus étroite que la tierce du tempérament égal, qui vaut 400 : c'est un écart qu'on entend, et c'est la faiblesse connue du tempérament égal. 316 est la tierce MINEURE juste, de rapport 6/5.",
    "Fourteen cents narrower than the equal-tempered third, which is 400: that gap is audible, and it is equal temperament's known weakness. 316 is the pure MINOR third, of ratio 6/5.", 2),
  chiffre("precedence",
    "En deçà de quel délai l'oreille fusionne-t-elle franchement une réflexion avec le son direct ?",
    "Below what delay does the ear firmly fuse a reflection with the direct sound?",
    ["une quarantaine de millisecondes", "quelques microsecondes", "environ 300 millisecondes", "une seconde"],
    ["some forty milliseconds", "a few microseconds", "about 300 milliseconds", "one second"],
    "La fenêtre de précédence. Au-delà d'une centaine de millisecondes, les réflexions commencent à s'entendre comme des échos séparés. C'est entre les deux que se règle une pièce : le nœud « Ampleur » travaille sur quatre-vingts millisecondes, où la décorrélation est franche sans que rien ne se détache.",
    "The precedence window. Beyond a hundred milliseconds or so, reflections start to be heard as separate echoes. A room is set between the two: the « Spaciousness » node works over eighty milliseconds, where decorrelation is clear without anything standing out."),
  chiffre("chaos-logistique",
    "À partir de quelle valeur de r la suite logistique devient-elle chaotique ?",
    "From what value of r does the logistic map become chaotic?",
    ["environ 3,57", "environ 2,0", "environ 1,0", "environ 4,5"],
    ["about 3.57", "about 2.0", "about 1.0", "about 4.5"],
    "En dessous de 3, la suite se fixe ; entre 3 et 3,57, elle se dédouble encore et encore ; au-delà, elle ne se répète plus jamais tout en restant bornée. Au-delà de 4, elle s'échappe — d'où le réglage borné dans les nœuds qui s'en servent.",
    "Below 3 the sequence settles; between 3 and 3.57 it keeps doubling; beyond that it never repeats again while staying bounded. Beyond 4 it escapes — hence the bounded control in the nodes that use it.", 2),
  chiffre("touches-piano",
    "Combien de touches compte un piano de concert ?",
    "How many keys does a concert piano have?",
    ["88", "76", "61", "108"], null,
    "La 21 à do 108 en numéros MIDI, soit un peu plus de sept octaves. C'est l'étendue que montrent les claviers d'Attic, et la référence dont se sert le nœud de jouabilité pour dire si une partition tient sous deux mains.",
    "A 21 to C 108 in MIDI numbers, a little over seven octaves. It is the span Attic's keyboards show, and the reference the playability node uses to say whether a score fits under two hands."),
  chiffre("audible",
    "Quelle est l'étendue de fréquences conventionnellement audible ?",
    "What is the conventionally audible frequency range?",
    ["20 Hz à 20 kHz", "50 Hz à 15 kHz", "1 Hz à 40 kHz", "100 Hz à 10 kHz"],
    ["20 Hz to 20 kHz", "50 Hz to 15 kHz", "1 Hz to 40 kHz", "100 Hz to 10 kHz"],
    "Une convention généreuse : passé la trentaine, le haut descend sensiblement. Ces trois décades tiennent en dix octaves — dont la dernière, de 10 à 20 kHz, ne porte presque aucune note et beaucoup de matière de timbre.",
    "A generous convention: past thirty the top drops appreciably. These three decades hold ten octaves — of which the last, 10 to 20 kHz, carries almost no notes and a great deal of timbral matter."),
  chiffre("demi-ton-pourcent",
    "De combien de pour cent un demi-ton tempéré monte-t-il une fréquence ?",
    "By what percentage does a tempered semitone raise a frequency?",
    ["environ 6 %", "environ 12 %", "environ 2 %", "environ 50 %"],
    ["about 6 %", "about 12 %", "about 2 %", "about 50 %"],
    "La racine douzième de deux vaut 1,0595. Le chiffre est utile à l'oreille comme au calcul : un décalage de six pour cent est un demi-ton, et un pour cent, c'est dix-sept cents — soit déjà plus que le comma qui a occupé trois siècles de facteurs d'orgues.",
    "The twelfth root of two is 1.0595. The figure is useful to the ear as well as to arithmetic: a six per cent shift is a semitone, and one per cent is seventeen cents — already more than the comma that occupied three centuries of organ builders."),
  chiffre("trois-db",
    "Que signifie « à −3 dB » pour la fréquence de coupure d'un filtre ?",
    "What does « at -3 dB » mean for a filter's cutoff frequency?",
    [
      "la moitié de la puissance passe encore",
      "le signal est atténué de moitié en amplitude",
      "le signal est divisé par mille",
      "le filtre n'atténue plus rien à partir de là",
    ],
    [
      "half the power still gets through",
      "the signal is halved in amplitude",
      "the signal is divided by a thousand",
      "the filter stops attenuating anything from there on",
    ],
    "10 · log₁₀(0,5) = −3,01. En amplitude, cela correspond à 0,707 — le même 1/√2 qui plafonne la somme mono de deux canaux décorrélés, et pour la même raison : c'est la racine d'un facteur deux en énergie.",
    "10 · log10(0.5) = -3.01. In amplitude that corresponds to 0.707 — the same 1/sqrt(2) that caps the mono sum of two decorrelated channels, and for the same reason: it is the square root of a factor of two in energy."),
];
