// quiz/formules.ts — Les formules qui tournent vraiment dans le code.
//
// AUCUNE FORMULE ICI N'EST DE CULTURE GÉNÉRALE : chacune est écrite quelque part dans `src/`, et
// l'explication dit où quand c'est utile. C'était la seule façon d'écrire ce thème honnêtement —
// une formule recopiée d'un manuel et jamais exécutée aurait pu être fausse d'un facteur deux
// sans que personne ne s'en aperçoive. Celles-ci passent des tests tous les jours.
//
// LES LEURRES SONT DES FAUTES QU'ON FAIT VRAIMENT : le logarithme en base dix là où il faut la
// base deux, le facteur 10 là où il faut 20, la référence à 60 plutôt qu'à 69 pour le la du
// diapason. Ce sont les erreurs qu'on commet en réécrivant une formule de mémoire, et c'est
// précisément ce que le quiz doit attraper.
//
// UNE FORMULE NE S'ÉCRIT PAS TOUT À FAIT PAREIL DANS LES DEUX LANGUES : la virgule décimale y est
// un point, et la fréquence d'échantillonnage s'abrège fₑ ici et fₛ là. Les propositions qui
// portent une virgule, un mot ou cette abréviation ont donc leur version anglaise ; les autres
// passent `null`, parce qu'elles s'écrivent vraiment à l'identique.

import type { Question } from "./types";

const formule = (
  id: string, enonce: string, enonceEn: string,
  choix: [string, string, string, string],
  /** `null` quand les propositions s'écrivent à l'identique dans les deux langues. */
  choixEn: [string, string, string, string] | null,
  pourquoi: string, pourquoiEn: string, niveau: 1 | 2 = 1,
): Question => ({
  id: `formule-${id}`, theme: "formules", niveau, enonce, enonceEn, choix,
  ...(choixEn ? { choixEn } : {}), pourquoi, pourquoiEn,
});

export const FORMULES: Question[] = [
  formule("cents",
    "Comment convertit-on un rapport de fréquences en cents ?",
    "How is a frequency ratio converted into cents?",
    ["1200 · log₂(f₂/f₁)", "1200 · log₁₀(f₂/f₁)", "100 · log₂(f₂/f₁)", "1200 · (f₂/f₁ − 1)"], null,
    "Une octave vaut 1200 cents, et une octave est un rapport de 2 : le logarithme en base deux est donc ce qui rend l'unité additive. C'est la formule qui permet de dire qu'une quinte juste vaut 702 cents et la quinte du tempérament égal exactement 700.",
    "An octave is 1200 cents, and an octave is a ratio of 2: the base-two logarithm is therefore what makes the unit additive. It is the formula that allows saying a pure fifth is 702 cents and the equal-tempered fifth exactly 700."),
  formule("midi-hz",
    "Quelle est la fréquence de la note MIDI n ?",
    "What is the frequency of MIDI note n?",
    ["440 · 2^((n − 69) / 12)", "440 · 2^((n − 60) / 12)", "440 · (n − 69) / 12", "440 · 12^((n − 69) / 2)"], null,
    "La note 69 est le la du diapason, à 440 Hz : c'est le point d'ancrage, et le 60 du leurre est le do central, qui n'y sert à rien. Douze demi-tons doublent la fréquence, d'où l'exposant divisé par douze.",
    "Note 69 is the tuning A, at 440 Hz: that is the anchor point, and the decoy's 60 is middle C, which plays no part here. Twelve semitones double the frequency, hence the exponent divided by twelve."),
  formule("db-amplitude",
    "Comment exprime-t-on un rapport d'AMPLITUDES en décibels ?",
    "How is an AMPLITUDE ratio expressed in decibels?",
    ["20 · log₁₀(A/A₀)", "10 · log₁₀(A/A₀)", "20 · log₂(A/A₀)", "10 · log₂(A/A₀)"], null,
    "Vingt pour une amplitude, dix pour une puissance — et c'est la confusion la plus répandue du métier. La raison en est simple : la puissance va comme le carré de l'amplitude, et un carré sort du logarithme en facteur deux.",
    "Twenty for an amplitude, ten for a power — and this is the commonest confusion in the craft. The reason is simple: power goes as the square of amplitude, and a square comes out of the logarithm as a factor of two."),
  formule("db-puissance",
    "De combien de décibels monte-t-on en DOUBLANT la puissance ?",
    "By how many decibels does DOUBLING the power raise a level?",
    ["3 dB", "6 dB", "10 dB", "1 dB"], null,
    "10 · log₁₀(2) vaut 3,01. Doubler l'AMPLITUDE, en revanche, donne 6 dB — c'est la même règle vue par les deux bouts, et l'origine du fameux « −3 dB » qui marque la coupure d'un filtre : la moitié de la puissance.",
    "10 · log10(2) is 3.01. Doubling the AMPLITUDE, on the other hand, gives 6 dB — the same rule seen from both ends, and the origin of the famous « -3 dB » marking a filter's cutoff: half the power."),
  formule("nyquist",
    "Quelle est la plus haute fréquence représentable à la fréquence d'échantillonnage fₑ ?",
    "What is the highest frequency representable at sample rate fₛ?",
    ["fₑ / 2", "fₑ", "fₑ / 4", "2 · fₑ"],
    ["fₛ / 2", "fₛ", "fₛ / 4", "2 · fₛ"],
    "La limite de Nyquist : il faut au moins deux points par période pour distinguer une sinusoïde d'une autre. À 44 100 Hz, la limite est à 22 050 Hz — juste au-dessus de l'audible, et ce n'est pas un hasard.",
    "The Nyquist limit: at least two points per period are needed to tell one sinusoid from another. At 44 100 Hz the limit is 22 050 Hz — just above the audible range, and that is no accident."),
  formule("bin",
    "Dans une FFT de N points à la fréquence fₑ, quelle fréquence porte la case k ?",
    "In an N-point FFT at sample rate fₛ, what frequency does bin k carry?",
    ["k · fₑ / N", "k · fₑ / 2", "fₑ / (k · N)", "k · N / fₑ"],
    ["k · fₛ / N", "k · fₛ / 2", "fₛ / (k · N)", "k · N / fₛ"],
    "La largeur d'une case vaut fₑ/N, et la case k se trouve k largeurs plus haut. À 44 100 Hz sur 2048 points, une case vaut 21,5 Hz : assez fin dans l'aigu, beaucoup trop grossier dans le grave, où un demi-ton peut valoir moins de deux hertz.",
    "A bin's width is fs/N, and bin k sits k widths higher. At 44 100 Hz over 2048 points a bin is 21.5 Hz: fine enough in the treble, far too coarse in the bass, where a semitone can be less than two hertz."),
  formule("resolution",
    "Comment gagne-t-on en résolution fréquentielle dans une analyse ?",
    "How is frequency resolution gained in an analysis?",
    [
      "en allongeant la fenêtre d'analyse, au prix de la précision temporelle",
      "en augmentant la fréquence d'échantillonnage, sans autre conséquence",
      "en réduisant la taille de la fenêtre d'analyse",
      "en appliquant une fenêtre de Hann plutôt que rectangulaire",
    ],
    [
      "by lengthening the analysis window, at the cost of temporal precision",
      "by raising the sample rate, with no other consequence",
      "by shortening the analysis window",
      "by applying a Hann window rather than a rectangular one",
    ],
    "Δf = fₑ/N : à fréquence d'échantillonnage donnée, seule la longueur de la fenêtre joue. Et le compromis est indépassable — c'est l'inégalité de Gabor, le même principe que celui d'incertitude : une fenêtre longue situe bien les fréquences et mal les instants.",
    "Delta f = fs/N: at a given sample rate, only the window length matters. And the trade-off cannot be beaten — it is Gabor's inequality, the same principle as the uncertainty one: a long window locates frequencies well and instants badly."),
  formule("mel",
    "Quelle est l'échelle mel ?",
    "What is the mel scale?",
    [
      "2595 · log₁₀(1 + f/700)",
      "1200 · log₂(1 + f/700)",
      "2595 · log₁₀(1 + f/1000)",
      "700 · log₁₀(1 + f/2595)",
    ], null,
    "L'échelle qui approche la façon dont l'oreille espace les hauteurs : presque linéaire jusqu'à 700 Hz, logarithmique au-delà. C'est elle qui replie le spectre avant le calcul des MFCC, et son usage explique le « mel » de leur sigle.",
    "The scale that approximates how the ear spaces pitches: nearly linear up to 700 Hz, logarithmic beyond. It is what folds the spectrum before MFCCs are computed, and its use explains the « mel » in their acronym.", 2),
  formule("mel-deux-ecritures",
    "Attic écrit l'échelle mel de deux façons : 2595 · log₁₀(1 + f/700) et 1127 · ln(1 + f/700). Que faut-il en conclure ?",
    "Attic writes the mel scale two ways: 2595 · log10(1 + f/700) and 1127 · ln(1 + f/700). What should be concluded?",
    [
      "que c'est la même formule, puisque 2595 / ln(10) ≈ 1127",
      "que l'une est l'échelle mel et l'autre l'échelle bark",
      "que l'une vaut pour la voix et l'autre pour la musique",
      "qu'il y a une incohérence dans le code",
    ],
    [
      "that it is the same formula, since 2595 / ln(10) is about 1127",
      "that one is the mel scale and the other the bark scale",
      "that one holds for speech and the other for music",
      "that there is an inconsistency in the code",
    ],
    "Changer de base logarithmique ne change qu'un facteur : 2595 / 2,302585 = 1127,0. Les deux écritures se trouvent dans le dépôt et donnent le même nombre — la bonne réaction devant deux constantes qui ne se ressemblent pas est de faire la division.",
    "Changing logarithm base changes only a factor: 2595 / 2.302585 = 1127.0. Both spellings are in the repository and give the same number — the right reaction to two constants that look unalike is to do the division.", 2),
  formule("bark",
    "Quelle est l'échelle des bandes critiques de Zwicker ?",
    "What is Zwicker's critical-band scale?",
    [
      "13 · arctan(0,00076 · f) + 3,5 · arctan((f/7500)²)",
      "13 · log₁₀(1 + f/7500) + 3,5 · arctan(0,00076 · f)",
      "24 · arctan(f/7500)",
      "13 · arctan(0,00076 · f) seulement",
    ],
    [
      "13 · arctan(0.00076 · f) + 3.5 · arctan((f/7500)²)",
      "13 · log10(1 + f/7500) + 3.5 · arctan(0.00076 · f)",
      "24 · arctan(f/7500)",
      "13 · arctan(0.00076 · f) only",
    ],
    "Deux arc-tangentes, parce qu'une seule ne rend pas la courbure aux deux bouts. De 0 à 24 barks, l'échelle couvre l'audible jusqu'à 15,5 kHz — et c'est en barks, non en hertz, que se calcule le masquage : l'étalement y est une fonction simple, là où, en hertz, il dépendrait de la fréquence.",
    "Two arctangents, because one alone does not render the curvature at both ends. From 0 to 24 barks the scale covers the audible range up to 15.5 kHz — and masking is computed in barks, not hertz: spreading is a simple function there, where in hertz it would depend on frequency.", 2),
  formule("schroeder",
    "Quelle est la fonction d'étalement de Schroeder, Atal et Hall, en décibels ?",
    "What is the Schroeder, Atal and Hall spreading function, in decibels?",
    [
      "15,81 + 7,5 · (Δz + 0,474) − 17,5 · √(1 + (Δz + 0,474)²)",
      "15,81 − 7,5 · (Δz + 0,474) + 17,5 · √(1 + (Δz + 0,474)²)",
      "15,81 + 7,5 · Δz − 17,5 · Δz²",
      "7,5 · (Δz + 0,474) − 17,5 · (Δz + 0,474)",
    ],
    [
      "15.81 + 7.5 · (Δz + 0.474) − 17.5 · √(1 + (Δz + 0.474)²)",
      "15.81 − 7.5 · (Δz + 0.474) + 17.5 · √(1 + (Δz + 0.474)²)",
      "15.81 + 7.5 · Δz − 17.5 · Δz²",
      "7.5 · (Δz + 0.474) − 17.5 · (Δz + 0.474)",
    ],
    "Δz est l'écart en barks, et le décalage de 0,474 est ce qui rend la courbe ASYMÉTRIQUE : elle décroît plus vite vers le grave que vers l'aigu, ce qui est exactement ce que fait l'oreille. C'est la fonction des codeurs perceptifs, et celle du nœud « Masquage ».",
    "Delta z is the distance in barks, and the 0.474 offset is what makes the curve ASYMMETRIC: it falls faster towards the bass than towards the treble, which is exactly what the ear does. It is the function of perceptual coders, and of the « Masking » node.", 2),
  formule("plomp-levelt",
    "Dans la courbe de dissonance de Plomp-Levelt, à quoi sert le terme s = 0,24 / (0,0207 · f₁ + 18,96) ?",
    "In the Plomp-Levelt dissonance curve, what is the term s = 0.24 / (0.0207 · f₁ + 18.96) for?",
    [
      "à mettre l'écart de fréquences à l'échelle de la bande critique locale",
      "à normaliser la dissonance entre zéro et un",
      "à convertir les amplitudes en décibels",
      "à pondérer les partiels selon leur rang harmonique",
    ],
    [
      "to scale the frequency distance to the local critical bandwidth",
      "to normalise the dissonance between zero and one",
      "to convert the amplitudes into decibels",
      "to weight the partials by their harmonic rank",
    ],
    "La rugosité ne dépend pas de l'écart en hertz mais de l'écart RAPPORTÉ à la largeur de la bande critique à cette hauteur : un demi-ton bat dans le grave et ne bat plus dans l'aigu. Le facteur s est ce qui porte cette dépendance, et le reste de la formule — une différence de deux exponentielles — donne la forme de la courbe.",
    "Roughness does not depend on the distance in hertz but on the distance RELATIVE to the width of the critical band at that pitch: a semitone beats in the bass and no longer beats in the treble. The factor s carries that dependence, and the rest of the formula — a difference of two exponentials — gives the curve's shape.", 2),
  formule("tenue-mono",
    "Que garde la somme mono de deux canaux dont la corrélation vaut ρ ?",
    "What does the mono sum of two channels with correlation ρ keep?",
    ["√((1 + ρ) / 2)", "(1 + ρ) / 2", "√(1 − ρ²)", "1 − |ρ|"], null,
    "La formule qui remplace le seuil fixe de 0,707 : ce chiffre n'est que le cas ρ = 0. Une corrélation de −0,06 impose 0,686, et l'application en a mesuré 0,68 — tout était en ordre, là où un seuil à 0,707 aurait crié au creusement du centre.",
    "The formula that replaces the fixed 0.707 threshold: that figure is merely the case rho = 0. A correlation of -0.06 imposes 0.686, and the application measured 0.68 — everything was in order, where a threshold at 0.707 would have cried that the centre was hollowed.", 2),
  formule("rms",
    "Comment se calcule la valeur efficace d'un signal ?",
    "How is a signal's root-mean-square value computed?",
    [
      "la racine carrée de la moyenne des carrés des échantillons",
      "la moyenne des valeurs absolues des échantillons",
      "la moyenne des carrés des échantillons",
      "le carré de la moyenne des échantillons",
    ],
    [
      "the square root of the mean of the squared samples",
      "the mean of the absolute values of the samples",
      "the mean of the squared samples",
      "the square of the mean of the samples",
    ],
    "L'ordre des trois opérations est le sigle lui-même, lu à l'envers : Root Mean Square. La quatrième proposition vaut zéro sur tout signal symétrique, ce qui est le cas de presque tous les sons — c'est justement pourquoi on passe par les carrés.",
    "The order of the three operations is the acronym itself, read backwards: Root Mean Square. The fourth option is zero for any symmetric signal, which is the case for almost every sound — precisely why one goes through the squares."),
  formule("logistique",
    "Quelle est la suite logistique ?",
    "What is the logistic map?",
    ["xₙ₊₁ = r · xₙ · (1 − xₙ)", "xₙ₊₁ = r · xₙ² + 1", "xₙ₊₁ = r · sin(π · xₙ)", "xₙ₊₁ = xₙ + r · (1 − xₙ)"], null,
    "Le modèle d'une population qui se reproduit et sature : une seule ligne, et pourtant la porte du chaos. En dessous de r = 3, la suite se fixe ; au-delà de 3,57, elle ne se répète plus jamais tout en restant bornée — c'est de là que plusieurs nœuds tirent leurs variations.",
    "The model of a population that breeds and saturates: a single line, and yet the door to chaos. Below r = 3 the sequence settles; beyond 3.57 it never repeats again while staying bounded — this is where several nodes draw their variations from."),
  formule("karplus-retard",
    "Dans une corde de Karplus-Strong, quelle doit être la longueur de la ligne à retard pour la note f ?",
    "In a Karplus-Strong string, what must the delay line length be for note f?",
    ["fₑ / f échantillons", "f / fₑ échantillons", "fₑ · f échantillons", "fₑ / (2 · f) échantillons"],
    ["fₛ / f samples", "f / fₛ samples", "fₛ · f samples", "fₛ / (2 · f) samples"],
    "Le temps d'un aller-retour dans la corde EST la période de la note. À 44 100 Hz, un la 440 demande cent échantillons — et c'est pourquoi la justesse devient grossière dans l'aigu, où il faudrait un retard fractionnaire.",
    "The time of one round trip in the string IS the note's period. At 44 100 Hz an A 440 needs a hundred samples — and that is why tuning becomes coarse in the treble, where a fractional delay would be needed.", 2),
  formule("temps-par-temps",
    "Combien de temps dure un temps à 120 battements par minute ?",
    "How long does one beat last at 120 beats per minute?",
    ["0,5 s", "2 s", "0,12 s", "1,2 s"],
    ["0.5 s", "2 s", "0.12 s", "1.2 s"],
    "60 / BPM. C'est le calcul qu'on refait cent fois par séance — une double-croche à 120 dure 125 millisecondes, ce qui est aussi l'ordre de grandeur d'un pré-délai de réverbération qu'on voudrait accorder au tempo.",
    "60 / BPM. It is the calculation one redoes a hundred times a session — a sixteenth note at 120 lasts 125 milliseconds, which is also the order of magnitude of a reverb pre-delay one might want tempo-locked."),
  formule("peigne",
    "Un filtre en peigne dont le retard vaut D échantillons creuse des encoches tous les :",
    "A comb filter whose delay is D samples cuts notches every:",
    ["fₑ / D hertz", "D / fₑ hertz", "fₑ · D hertz", "fₑ / (2 · D) hertz"],
    ["fₛ / D hertz", "D / fₛ hertz", "fₛ · D hertz", "fₛ / (2 · D) hertz"],
    "Plus le retard est court, plus les encoches sont espacées. À un millième de seconde, elles tombent tous les mille hertz et s'entendent comme une couleur ; à un centième, tous les cent hertz et l'on entend un bourdon. C'est aussi ce qui arrive par accident quand deux micros captent la même source.",
    "The shorter the delay, the wider the notch spacing. At a thousandth of a second they fall every thousand hertz and are heard as a colour; at a hundredth, every hundred hertz and a drone is heard. It is also what happens by accident when two microphones catch the same source.", 2),
  formule("longueur-onde",
    "Quelle est la longueur d'onde d'un son de 100 Hz dans l'air ?",
    "What is the wavelength of a 100 Hz sound in air?",
    ["environ 3,4 m", "environ 34 cm", "environ 34 m", "environ 3,4 cm"],
    ["about 3.4 m", "about 34 cm", "about 34 m", "about 3.4 cm"],
    "λ = c/f, avec c ≈ 343 m/s. Le chiffre est utile en dehors du calcul : un grave de 100 Hz fait trois mètres et demi, c'est-à-dire la taille d'une pièce — d'où les modes et les bosses qu'aucun égaliseur ne corrige vraiment.",
    "Lambda = c/f, with c around 343 m/s. The figure is useful beyond the arithmetic: a 100 Hz bass is three and a half metres, that is, the size of a room — hence the modes and bumps no equalizer really fixes.", 2),
  formule("demi-ton",
    "Quel rapport de fréquences vaut un demi-ton du tempérament égal ?",
    "What frequency ratio is one equal-tempered semitone?",
    ["2^(1/12) ≈ 1,0595", "1,5 / 12 ≈ 1,125", "2 / 12 ≈ 1,167", "3/2 ≈ 1,5"],
    ["2^(1/12) ≈ 1.0595", "1.5 / 12 ≈ 1.125", "2 / 12 ≈ 1.167", "3/2 ≈ 1.5"],
    "Douze demi-tons égaux multiplient la fréquence par deux : chacun vaut donc la racine douzième de deux, environ six pour cent. C'est ce qui rend le tempérament égal transposable sans limite — et ce qui rend ses tierces un peu fausses.",
    "Twelve equal semitones multiply the frequency by two: each is therefore the twelfth root of two, about six per cent. That is what makes equal temperament transposable without limit — and what makes its thirds slightly out."),
  formule("comma",
    "Comment s'obtient le comma pythagoricien ?",
    "How is the Pythagorean comma obtained?",
    [
      "en comparant douze quintes justes à sept octaves : 3¹² / 2¹⁹",
      "en comparant trois tierces justes à une octave : 5³ / 2⁷",
      "en comparant deux quintes justes à une octave : 3² / 2³",
      "en comparant une quinte juste à une quinte tempérée",
    ],
    [
      "by comparing twelve pure fifths with seven octaves: 3¹² / 2¹⁹",
      "by comparing three pure thirds with one octave: 5³ / 2⁷",
      "by comparing two pure fifths with one octave: 3² / 2³",
      "by comparing a pure fifth with a tempered fifth",
    ],
    "3¹²/2¹⁹ = 531441/524288, soit 23,46 cents. Cet écart est le nœud de toute l'histoire des tempéraments : il faut bien le mettre quelque part, et chaque tempérament n'est qu'une façon de le répartir.",
    "3¹² / 2¹⁹ = 531441/524288, that is 23.46 cents. That gap is the knot of the whole history of temperaments: it has to go somewhere, and each temperament is merely a way of distributing it.", 2),
  formule("hann",
    "Quelle est la fenêtre de Hann ?",
    "What is the Hann window?",
    [
      "0,5 · (1 − cos(2πn/N))",
      "1 − |2n/N − 1|",
      "exp(−(n − N/2)² / 2σ²)",
      "0,54 − 0,46 · cos(2πn/N)",
    ],
    [
      "0.5 · (1 − cos(2πn/N))",
      "1 − |2n/N − 1|",
      "exp(−(n − N/2)² / 2σ²)",
      "0.54 − 0.46 · cos(2πn/N)",
    ],
    "Un cosinus surélevé, nul aux deux bords. Sans fenêtrage, les bords d'une trame font des discontinuités dont la FFT rend des raies parasites partout. La dernière proposition est la fenêtre de Hamming, qui ne s'annule pas aux bords — proche, et différente.",
    "A raised cosine, zero at both edges. Without windowing, a frame's edges make discontinuities whose FFT returns spurious lines everywhere. The last option is the Hamming window, which does not vanish at the edges — close, and different.", 2),
  formule("centroide-calcul",
    "Comment se calcule le centroïde spectral ?",
    "How is the spectral centroid computed?",
    [
      "Σ(fᵢ · aᵢ) / Σaᵢ",
      "Σ(fᵢ · aᵢ) / Σfᵢ",
      "Σ(fᵢ²· aᵢ) / Σaᵢ",
      "Σfᵢ / Σaᵢ",
    ], null,
    "Une moyenne des fréquences PONDÉRÉE par les amplitudes : exactement un centre de gravité, d'où le nom. Diviser par la somme des amplitudes est ce qui le rend indépendant du volume — sans cette division, monter le son déplacerait le centroïde.",
    "A mean of the frequencies WEIGHTED by the amplitudes: exactly a centre of gravity, hence the name. Dividing by the sum of the amplitudes is what makes it independent of loudness — without that division, raising the level would move the centroid."),
  formule("correlation",
    "Comment se calcule la corrélation entre deux canaux ?",
    "How is the correlation between two channels computed?",
    [
      "Σ(aᵢ · bᵢ) / √(Σaᵢ² · Σbᵢ²)",
      "Σ(aᵢ · bᵢ) / Σ(aᵢ² + bᵢ²)",
      "Σ(aᵢ − bᵢ)² / Σaᵢ²",
      "Σ(aᵢ · bᵢ) / n",
    ], null,
    "La normalisation par les deux énergies est ce qui borne le résultat entre −1 et 1 et le rend indépendant du volume : un vaut deux canaux identiques, donc une source ponctuelle ; zéro, un son sans position repérable. Sans elle, monter le son monterait la « corrélation ».",
    "Normalising by both energies is what bounds the result between -1 and 1 and makes it level-independent: one means two identical channels, hence a point source; zero, a sound with no locatable position. Without it, raising the level would raise the « correlation »."),
  formule("doppler",
    "Quelle est la fréquence entendue d'une source qui s'approche à la vitesse v ?",
    "What frequency is heard from a source approaching at speed v?",
    [
      "f · c / (c − v)",
      "f · c / (c + v)",
      "f · (c − v) / c",
      "f · (1 + v/c)²",
    ], null,
    "C'est l'auditeur qui reçoit les crêtes plus serrées, d'où le dénominateur qui diminue. Attic ne l'applique pourtant pas telle quelle : le nœud pose le RETARD égal au temps de parcours et laisse le décalage en sortir, ce qui donne la bascule juste au moment du passage — là où un rapport fixe se tromperait, la vitesse radiale s'inversant.",
    "It is the listener who receives the crests more tightly packed, hence the shrinking denominator. Attic does not apply it as such, though: the node sets the DELAY equal to the travel time and lets the shift come out of it, which gives the right flip at the moment of passing — where a fixed ratio would be wrong, radial speed reversing there.", 2),
  formule("quinte-juste",
    "Combien de cents vaut une quinte juste, de rapport 3/2 ?",
    "How many cents is a pure fifth, of ratio 3/2?",
    ["702", "700", "686", "720"], null,
    "1200 · log₂(1,5) = 701,955. La quinte du tempérament égal vaut exactement 700 : deux cents plus étroite, un écart qu'on n'entend pas seul mais qui, accumulé douze fois, fait le comma pythagoricien.",
    "1200 · log2(1.5) = 701.955. The equal-tempered fifth is exactly 700: two cents narrower, a gap not heard on its own but which, piled up twelve times, makes the Pythagorean comma."),
  formule("cases-utiles",
    "Combien de cases utiles porte le spectre d'une FFT de 2048 points sur un signal réel ?",
    "How many useful bins does the spectrum of a 2048-point FFT on a real signal carry?",
    ["1025", "2048", "1024", "4096"], null,
    "N/2 + 1 : la moitié, plus la composante continue et la fréquence de Nyquist. Le spectre d'un signal réel est symétrique — la seconde moitié ne porte aucune information nouvelle, et la calculer serait la calculer deux fois.",
    "N/2 + 1: half, plus the DC component and the Nyquist frequency. A real signal's spectrum is symmetric — the second half carries no new information, and computing it would be computing it twice.", 2),
];
