// quiz/notions.ts — Les notions, c'est-à-dire ce qui reste quand on a oublié les sigles.
//
// LE SEUL THÈME OÙ LES PROPOSITIONS SONT TRADUITES, parce que ce sont des phrases et non des
// noms. C'est aussi le thème le plus difficile à écrire honnêtement : une notion mal découpée
// donne une question à deux bonnes réponses, et l'utilisateur a raison contre le quiz.
//
// DEUX RÈGLES QUE CHAQUE QUESTION D'ICI RESPECTE :
//
//  1. UNE SEULE PROPOSITION EST VRAIE, et les trois autres sont FAUSSES — pas « moins précises ».
//     Un leurre qui serait vrai à moitié rend la question injuste, et un test ne peut pas
//     attraper cela : il n'y a que la relecture.
//  2. LA QUESTION PORTE SUR CE QUI DISTINGUE, jamais sur une définition à réciter. « Ce qui
//     distingue le ducking d'un compresseur » s'apprend une fois pour toutes ; « qu'est-ce qu'un
//     compresseur » ne s'évalue pas en quatre lignes.
//
// Beaucoup de ces notions ont leur nœud dans le catalogue. L'explication le dit quand c'est le
// cas : le quiz sert aussi à savoir ce qu'on a sous la main.

import type { Question } from "./types";

const notion = (
  id: string,
  enonce: string, enonceEn: string,
  choix: [string, string, string, string], choixEn: [string, string, string, string],
  pourquoi: string, pourquoiEn: string, niveau: 1 | 2 = 1,
): Question => ({
  id: `notion-${id}`, theme: "notions", niveau,
  enonce, enonceEn, choix, choixEn, pourquoi, pourquoiEn,
});

export const NOTIONS: Question[] = [
  notion("precedence",
    "Une réflexion qui arrive moins de quarante millisecondes après le son direct est :",
    "A reflection arriving less than forty milliseconds after the direct sound is:",
    [
      "fusionnée avec lui : on entend un seul son, mais plus gros",
      "entendue comme un écho distinct",
      "annulée par interférence avec le son direct",
      "perçue une octave au-dessus du son direct",
    ],
    [
      "fused with it: one single sound is heard, but a bigger one",
      "heard as a distinct echo",
      "cancelled by interference with the direct sound",
      "perceived an octave above the direct sound",
    ],
    "C'est l'effet de précédence, et c'est tout le principe du nœud « Ampleur » : on ajoute des réflexions pour grossir le son, pas pour l'entendre se répéter. Au-delà d'une centaine de millisecondes, elles commencent à se détacher et deviennent des échos.",
    "This is the precedence effect, and it is the whole principle of the « Spaciousness » node: reflections are added to make the sound bigger, not to hear it repeat. Beyond a hundred milliseconds or so they start to stand out and become echoes."),
  notion("bande-critique",
    "Qu'est-ce qu'une bande critique ?",
    "What is a critical band?",
    [
      "la largeur en deçà de laquelle deux sons se disputent la même région de la cochlée",
      "une bande de fréquences que l'oreille n'entend pas",
      "la largeur de bande d'un filtre d'égaliseur paramétrique",
      "l'écart maximal entre deux notes que l'on juge consonantes",
    ],
    [
      "the width below which two sounds compete for the same region of the cochlea",
      "a band of frequencies the ear cannot hear",
      "the bandwidth of a parametric equalizer filter",
      "the largest interval between two notes judged consonant",
    ],
    "La notion qui explique à la fois la dissonance et le masquage : deux sons dans la même bande critique battent et se masquent, deux sons éloignés cohabitent. Zwicker (1961) en a donné la largeur ; Plomp et Levelt (1965) en ont tiré la courbe de rugosité.",
    "The notion that explains both dissonance and masking: two sounds in the same critical band beat and mask each other, two distant ones coexist. Zwicker (1961) gave its width; Plomp and Levelt (1965) drew the roughness curve from it."),
  notion("masquage-asymetrie",
    "Un son fort masque surtout :",
    "A loud sound mainly masks:",
    [
      "les sons plus aigus que lui",
      "les sons plus graves que lui",
      "les sons de même fréquence, et eux seuls",
      "indifféremment les deux côtés, le masquage étant symétrique",
    ],
    [
      "sounds higher than itself",
      "sounds lower than itself",
      "sounds at the same frequency, and those alone",
      "both sides equally, masking being symmetric",
    ],
    "L'onde progresse du grave vers l'aigu dans la cochlée : un son masque donc largement vers le haut et très peu vers le bas. Mesuré dans le nœud « Masquage » sur deux sons à une bande critique d'écart : 100 % de l'énergie masquée quand le masquant est en dessous, 0,0 % quand il est au-dessus.",
    "The wave travels from low to high in the cochlea: a sound therefore masks widely upward and very little downward. Measured in the « Masking » node on two sounds one critical band apart: 100 % of the energy masked when the masker is below, 0.0 % when it is above."),
  notion("velours",
    "Qu'est-ce que le bruit de velours ?",
    "What is velvet noise?",
    [
      "une impulsion de ±1 par case d'une grille régulière, placée au hasard dans sa case",
      "un bruit blanc filtré en passe-bas très doux",
      "un bruit dont le spectre décroît de 3 dB par octave",
      "une suite d'impulsions régulièrement espacées et d'amplitudes décroissantes",
    ],
    [
      "one impulse of plus or minus 1 per cell of a regular grid, placed at random within its cell",
      "white noise filtered by a very gentle low-pass",
      "noise whose spectrum falls by 3 dB per octave",
      "a train of evenly spaced impulses with decreasing amplitudes",
    ],
    "Sa RARETÉ est ce qui le rend utile : quelques dizaines d'impulsions par seconde décorrèlent sans colorer, là où un bruit dense s'entendrait comme un souffle et un peigne régulier comme un timbre. Välimäki et ses collègues (IEEE TASLP, 2013) en ont fait la brique des réverbérations et des élargisseurs.",
    "Its SPARSENESS is what makes it useful: a few dozen impulses per second decorrelate without colouring, where dense noise would be heard as hiss and a regular comb as a timbre. Valimaki and colleagues (IEEE TASLP, 2013) made it the building block of reverbs and wideners.", 2),
  notion("ms-mono",
    "Pourquoi un élargisseur stéréo M-S ne fait-il rien sur une source mono ?",
    "Why does an M-S stereo widener do nothing to a mono source?",
    [
      "parce que le côté vaut la différence des deux canaux, donc zéro, et qu'amplifier zéro donne zéro",
      "parce qu'il exige une fréquence d'échantillonnage de 48 kHz",
      "parce qu'il travaille en dessous de 200 Hz seulement",
      "parce que le milieu et le côté sont alors en opposition de phase",
    ],
    [
      "because the side is the difference of the two channels, hence zero, and amplifying zero gives zero",
      "because it requires a 48 kHz sample rate",
      "because it works below 200 Hz only",
      "because mid and side are then in opposite phase",
    ],
    "Vérifié dans l'application : l'élargisseur M-S à 200 % laisse une source mono au goniomètre à r = 1,00, c'est-à-dire intacte. Élargir suppose une différence qui existe déjà ; la CRÉER demande d'ajouter quelque chose de différent à chaque canal — c'est ce que fait le nœud « Ampleur ».",
    "Verified in the application: the M-S widener at 200 % leaves a mono source at r = 1.00 on the goniometer, that is, untouched. Widening presumes a difference that already exists; CREATING one requires adding something different to each channel — which is what the « Spaciousness » node does."),
  notion("camelot",
    "À quoi sert la roue de Camelot ?",
    "What is the Camelot wheel for?",
    [
      "à ranger les tonalités de sorte que deux voisines s'enchaînent sans heurt",
      "à mesurer le tempo d'un morceau par autocorrélation",
      "à choisir les fréquences de coupure d'un égaliseur",
      "à répartir les percussions sur une grille de seize pas",
    ],
    [
      "to arrange keys so that two neighbours follow one another without a jolt",
      "to measure a piece's tempo by autocorrelation",
      "to choose an equalizer's cutoff frequencies",
      "to lay drums out on a sixteen-step grid",
    ],
    "C'est le cycle des quintes rhabillé pour le mixage : douze positions, deux anneaux (mineur et majeur), et la règle qu'on ne se déplace que d'un cran. Le nœud « Cercle pulsant » s'en sert autrement — il fait correspondre la roue des teintes à celle-ci, de sorte que deux couleurs voisines donnent deux tonalités compatibles.",
    "It is the circle of fifths dressed for mixing: twelve positions, two rings (minor and major), and the rule that one moves by a single step. The « Pulsing Circle » node uses it differently — it maps the hue wheel onto this one, so that two neighbouring colours give two compatible keys."),
  notion("tonnetz",
    "Qu'est-ce que le Tonnetz ?",
    "What is the Tonnetz?",
    [
      "un réseau où les accords voisins partagent deux de leurs trois notes",
      "une table des fréquences des tempéraments historiques",
      "la matrice des douze transpositions d'une série dodécaphonique",
      "un graphe des enchaînements d'accords les plus fréquents du jazz",
    ],
    [
      "a lattice where neighbouring chords share two of their three notes",
      "a table of the frequencies of historical temperaments",
      "the matrix of the twelve transpositions of a twelve-tone row",
      "a graph of the commonest chord successions in jazz",
    ],
    "Le réseau d'Euler, repris par la théorie néo-riemannienne : les trois mouvements P, L et R ne déplacent qu'une seule voix, d'un demi-ton ou d'un ton. C'est pourquoi la suite P, L, R coûte deux demi-tons par enchaînement — la mesure que donne le nœud « Distance de conduite de voix ».",
    "Euler's lattice, taken up by neo-Riemannian theory: the three moves P, L and R shift one single voice, by a semitone or a tone. That is why the sequence P, L, R costs two semitones per step — the measure given by the « Voice-Leading Distance » node.", 2),
  notion("resultante",
    "Comment s'obtient une résultante de Schillinger ?",
    "How is a Schillinger resultant obtained?",
    [
      "en superposant deux pulsations régulières et en gardant toutes les attaques",
      "en répartissant k frappes le plus également possible sur n pas",
      "en retirant une frappe sur deux d'un motif régulier",
      "en tirant les positions au hasard selon une loi de Poisson",
    ],
    [
      "by superposing two regular pulses and keeping every attack",
      "by spreading k hits as evenly as possible over n steps",
      "by removing every second hit from a regular pattern",
      "by drawing positions at random from a Poisson law",
    ],
    "Trois contre deux donne 2-1-1-2, la figure la plus citée du système ; quatre contre trois donne 3-1-2-2-1-3. La deuxième proposition décrit le rythme EUCLIDIEN, qui est l'autre grande famille : l'un répartit, l'autre superpose — et leurs résultats diffèrent presque toujours.",
    "Three against two gives 2-1-1-2, the most cited figure of the system; four against three gives 3-1-2-2-1-3. The second option describes the EUCLIDEAN rhythm, which is the other great family: one spreads, the other superposes — and their results almost always differ.", 2),
  notion("waveset",
    "Qu'est-ce qu'un waveset, chez Wishart ?",
    "What is a waveset, in Wishart's sense?",
    [
      "le segment compris entre un passage par zéro montant et le suivant",
      "un grain de durée fixe découpé sur une grille régulière",
      "une trame d'analyse de 2048 points fenêtrée par une cloche de Hann",
      "la partie d'un son comprise entre deux transitoires détectés",
    ],
    [
      "the segment between one rising zero crossing and the next",
      "a fixed-length grain cut on a regular grid",
      "a 2048-point analysis frame windowed by a Hann bell",
      "the part of a sound between two detected transients",
    ],
    "Un passage par zéro sur deux, de sorte que chaque waveset contienne une alternance complète — un lobe positif puis un lobe négatif, soit une pseudo-période. C'est ce qui le distingue d'un grain : il ÉPOUSE la forme d'onde au lieu de la couper, et le répéter fait descendre la hauteur sans changer la durée.",
    "Every other zero crossing, so that each waveset holds a complete alternation — a positive lobe then a negative one, that is, a pseudo-period. That is what distinguishes it from a grain: it FOLLOWS the waveform instead of cutting it, and repeating it lowers the pitch without changing the duration.", 2),
  notion("formant",
    "Ce qui distingue un « A » d'un « I », c'est :",
    "What tells an « A » from an « I » is:",
    [
      "la position des formants, qui ne dépend pas de la hauteur chantée",
      "la fréquence fondamentale de la voix",
      "la durée d'attaque du son",
      "le nombre de passages par zéro par seconde",
    ],
    [
      "the position of the formants, which does not depend on the pitch sung",
      "the fundamental frequency of the voice",
      "the attack time of the sound",
      "the number of zero crossings per second",
    ],
    "Le conduit vocal est un tuyau dont la langue et les lèvres changent la géométrie, et cette géométrie place trois ou quatre bosses dans le spectre. C'est pourquoi la même voyelle se reconnaît chantée grave ou aiguë — et pourquoi transposer un échantillon de voix donne l'effet « Chipmunk » : les formants sont emportés avec la note.",
    "The vocal tract is a tube whose geometry tongue and lips change, and that geometry places three or four bumps in the spectrum. That is why the same vowel is recognisable sung low or high — and why transposing a voice sample gives the « Chipmunk » effect: the formants are carried along with the note."),
  notion("centroide",
    "Que mesure le centroïde spectral ?",
    "What does the spectral centroid measure?",
    [
      "le centre de gravité du spectre, qui s'entend comme la brillance",
      "la fréquence fondamentale de la note jouée",
      "la fréquence en dessous de laquelle se trouve 85 % de l'énergie",
      "l'écart-type des amplitudes du spectre",
    ],
    [
      "the spectrum's centre of gravity, which is heard as brightness",
      "the fundamental frequency of the note played",
      "the frequency below which 85 % of the energy lies",
      "the standard deviation of the spectrum's amplitudes",
    ],
    "Mesuré dans l'application : un sinus de 440 Hz donne un centroïde de 440 Hz, une scie de 2093 Hz un centroïde de 9343 Hz — la mesure sépare bien le sourd du brillant. La troisième proposition décrit le ROLLOFF, qui est une autre mesure et un autre nœud.",
    "Measured in the application: a 440 Hz sine gives a centroid of 440 Hz, a 2093 Hz sawtooth a centroid of 9343 Hz — the measure does separate dull from bright. The third option describes the ROLLOFF, which is another measure and another node."),
  notion("cepstre",
    "Qu'est-ce que le cepstre ?",
    "What is the cepstrum?",
    [
      "une transformée du logarithme du spectre, qui sépare l'enveloppe de la structure fine",
      "le spectre du spectre, calculé sans logarithme",
      "la moyenne des spectres de toutes les trames d'un son",
      "le spectre d'un son dont la phase a été mise à zéro",
    ],
    [
      "a transform of the logarithm of the spectrum, which separates the envelope from the fine structure",
      "the spectrum of the spectrum, computed without a logarithm",
      "the average of the spectra of all a sound's frames",
      "the spectrum of a sound whose phase has been zeroed",
    ],
    "Le logarithme est ce qui fait tout : il transforme le PRODUIT de la source et du filtre en une SOMME, que la transformée suivante sépare enfin. Les coefficients bas décrivent l'enveloppe — donc le timbre —, les hauts la périodicité, donc la hauteur. C'est de là que viennent les MFCC.",
    "The logarithm is what does everything: it turns the PRODUCT of source and filter into a SUM, which the following transform can at last separate. Low coefficients describe the envelope — hence timbre —, high ones the periodicity, hence pitch. This is where MFCCs come from.", 2),
  notion("chroma",
    "Que donne un chromagramme ?",
    "What does a chromagram give?",
    [
      "l'énergie de chacune des douze classes de hauteur, toutes octaves confondues",
      "la suite des notes jouées, avec leur durée",
      "la couleur dominante associée à chaque instant du son",
      "l'énergie de chaque bande critique de l'oreille",
    ],
    [
      "the energy of each of the twelve pitch classes, all octaves merged",
      "the sequence of notes played, with their durations",
      "the dominant colour associated with each instant of the sound",
      "the energy of each critical band of the ear",
    ],
    "Replier les octaves est exactement ce qui le rend utile : la tonalité d'un morceau ne dépend pas du registre où les notes sont jouées. Douze des quarante caractéristiques d'une piste sont son chroma.",
    "Folding the octaves is precisely what makes it useful: a piece's key does not depend on the register in which the notes are played. Twelve of a track's forty features are its chroma."),
  notion("griffin-lim",
    "À quoi sert l'algorithme de Griffin-Lim ?",
    "What is the Griffin-Lim algorithm for?",
    [
      "à retrouver une phase plausible à partir d'un spectre d'amplitudes seul",
      "à aligner deux interprétations d'un même morceau",
      "à séparer les parties harmonique et percussive d'un son",
      "à estimer le tempo d'un enregistrement",
    ],
    [
      "to recover a plausible phase from a magnitude spectrum alone",
      "to align two performances of the same piece",
      "to separate a sound's harmonic and percussive parts",
      "to estimate the tempo of a recording",
    ],
    "Un spectrogramme d'amplitudes ne suffit pas à refaire un son : il manque la phase. Griffin-Lim la cherche par allers-retours entre les deux domaines, cent fois s'il faut. PGHI fait mieux en une passe, en intégrant le gradient de phase depuis les régions les plus fortes.",
    "A magnitude spectrogram is not enough to remake a sound: the phase is missing. Griffin-Lim looks for it by going back and forth between the two domains, a hundred times if need be. PGHI does better in a single pass, by integrating the phase gradient from the strongest regions.", 2),
  notion("hpss-geometrie",
    "Dans un spectrogramme, une note tenue dessine :",
    "In a spectrogram, a held note draws:",
    [
      "une ligne horizontale, là où une frappe dessine une ligne verticale",
      "une ligne verticale, là où une frappe dessine une ligne horizontale",
      "une tache diagonale montante",
      "un nuage sans forme repérable",
    ],
    [
      "a horizontal line, where a hit draws a vertical one",
      "a vertical line, where a hit draws a horizontal one",
      "a rising diagonal patch",
      "a cloud with no recognisable shape",
    ],
    "C'est toute l'astuce de la séparation harmonique/percussive : un filtre médian horizontal garde les notes tenues, un filtre médian vertical garde les frappes. Deux lignes de code plutôt qu'un réseau de neurones (Fitzgerald, DAFx-10).",
    "This is the whole trick of harmonic/percussive separation: a horizontal median filter keeps held notes, a vertical median filter keeps hits. Two lines of code rather than a neural network (Fitzgerald, DAFx-10)."),
  notion("paulstretch",
    "Ce qui permet à Paulstretch d'étirer un son cinquante fois sans qu'on entende un hachage :",
    "What lets Paulstretch stretch a sound fifty times without any chopping being heard:",
    [
      "les phases de chaque trame sont retirées au hasard",
      "les trames sont ré-échantillonnées par interpolation cubique",
      "un filtre passe-bas suit la durée d'étirement",
      "les transitoires sont détectés puis réinjectés à l'identique",
    ],
    [
      "each frame's phases are drawn at random",
      "frames are resampled by cubic interpolation",
      "a low-pass filter follows the stretch factor",
      "transients are detected then reinjected unchanged",
    ],
    "Répéter une trame à l'identique fabrique une périodicité que l'oreille entend aussitôt comme un bourdonnement. Randomiser les phases garde le spectre — donc le timbre — et détruit la périodicité : ce qui reste est une nappe, et c'est l'effet cherché.",
    "Repeating a frame unchanged manufactures a periodicity the ear hears at once as a buzz. Randomising the phases keeps the spectrum — hence the timbre — and destroys the periodicity: what remains is a pad, and that is the sought effect.", 2),
  notion("aliasing",
    "Que devient une fréquence synthétisée au-dessus de la limite de Nyquist ?",
    "What becomes of a frequency synthesized above the Nyquist limit?",
    [
      "elle se replie et s'entend plus bas, à une fréquence qui n'a rien à voir",
      "elle est simplement inaudible et sans conséquence",
      "elle sature et produit de la distorsion harmonique",
      "elle est transposée à l'octave inférieure, donc juste",
    ],
    [
      "it folds back and is heard lower, at a frequency unrelated to it",
      "it is simply inaudible and harmless",
      "it clips and produces harmonic distortion",
      "it is transposed one octave down, and therefore in tune",
    ],
    "Le repliement de spectre : au-delà de la moitié de la fréquence d'échantillonnage, une sinusoïde est indiscernable d'une autre, plus basse. C'est pourquoi une onde en dents de scie calculée naïvement sonne faux dans l'aigu — ses harmoniques dépassent la limite et retombent n'importe où.",
    "Spectral folding: beyond half the sample rate, a sinusoid is indistinguishable from another, lower one. That is why a naively computed sawtooth sounds out of tune in the treble — its harmonics pass the limit and fall back anywhere."),
  notion("ducking",
    "Ce qui distingue le ducking d'un compresseur :",
    "What distinguishes ducking from a compressor:",
    [
      "il écoute un AUTRE signal que celui qu'il traite",
      "il agit sur les graves seulement",
      "il monte le niveau au lieu de le baisser",
      "il travaille sur le spectre au lieu du temps",
    ],
    [
      "it listens to ANOTHER signal than the one it processes",
      "it acts on the bass only",
      "it raises the level instead of lowering it",
      "it works on the spectrum rather than on time",
    ],
    "Un compresseur, un limiteur, une porte écoutent tous le signal qu'ils traitent : aucun ne sait baisser la musique quand la voix parle. Mesuré dans le nœud « Ducking » sur une cible d'énergie CONSTANTE — donc qu'aucun compresseur ne toucherait : elle creuse à 0,035 là où le déclencheur parle et remonte à 0,346 entre les phrases.",
    "A compressor, a limiter, a gate all listen to the signal they process: none can lower the music when the voice speaks. Measured in the « Ducking » node on a target of CONSTANT energy — which no compressor would touch: it dips to 0.035 where the trigger speaks and returns to 0.346 between phrases."),
  notion("harmonie-negative",
    "Comment s'obtient l'harmonie négative ?",
    "How is negative harmony obtained?",
    [
      "par réflexion des hauteurs autour de l'axe qui joint la tonique et la dominante",
      "en inversant l'ordre des accords d'une progression",
      "en jouant chaque accord une quinte plus bas",
      "en remplaçant chaque accord majeur par son mineur relatif",
    ],
    [
      "by reflecting pitches about the axis joining tonic and dominant",
      "by reversing the order of a progression's chords",
      "by playing every chord a fifth lower",
      "by replacing every major chord with its relative minor",
    ],
    "Une symétrie, pas une transposition : la réflexion échange les degrés de part et d'autre de l'axe, si bien qu'un majeur devient mineur et qu'une dominante trouve un substitut inattendu mais fonctionnel. L'idée remonte à Riemann, et son usage courant à Jacob Collier.",
    "A symmetry, not a transposition: the reflection swaps the degrees on either side of the axis, so that a major becomes minor and a dominant finds an unexpected but functional substitute. The idea goes back to Riemann, and its current use to Jacob Collier.", 2),
  notion("mosaiquage",
    "En quoi consiste le mosaïquage audio ?",
    "What does audio mosaicing consist of?",
    [
      "remplacer chaque grain d'un son par le grain le plus proche pris dans un autre son",
      "coller bout à bout des extraits de plusieurs sons, en fondu enchaîné",
      "répartir un son sur plusieurs canaux selon sa fréquence",
      "recomposer un son à partir de sinusoïdes pures",
    ],
    [
      "replacing each grain of a sound with the nearest grain taken from another sound",
      "gluing excerpts of several sounds end to end, with crossfades",
      "spreading a sound over several channels according to frequency",
      "rebuilding a sound out of pure sinusoids",
    ],
    "On garde la FORME d'un son et la MATIÈRE d'un autre : une phrase parlée jouée par des bruits de pas, une mélodie jouée par des portes qui claquent. La ressemblance se mesure sur des descripteurs — énergie, centroïde, coefficients cepstraux — et non sur les échantillons.",
    "The FORM of one sound is kept and the MATTER of another: a spoken phrase played by footsteps, a melody played by slamming doors. Similarity is measured on descriptors — energy, centroid, cepstral coefficients — not on samples.", 2),
  notion("b-format",
    "Que portent les quatre canaux W, X, Y, Z de l'ambisonique ?",
    "What do ambisonics' four channels W, X, Y, Z carry?",
    [
      "la pression et les trois composantes de la vitesse, indépendamment de tout haut-parleur",
      "les quatre haut-parleurs d'un système quadriphonique",
      "les quatre premières harmoniques du signal",
      "les canaux gauche, droit, arrière et caisson de basses",
    ],
    [
      "pressure and the three velocity components, independently of any loudspeaker",
      "the four loudspeakers of a quadraphonic system",
      "the signal's first four harmonics",
      "the left, right, rear and subwoofer channels",
    ],
    "C'est ce qui fait la force du format : il décrit le CHAMP et non un dispositif d'écoute, si bien que la même prise se décode sur un casque, quatre enceintes ou trente. Et faire tourner la scène entière coûte deux multiplications par échantillon — la pression W et la hauteur Z ne bougeant pas.",
    "That is the format's strength: it describes the FIELD rather than a listening setup, so the same recording decodes onto headphones, four speakers or thirty. And rotating the whole scene costs two multiplications per sample — pressure W and height Z not moving.", 2),
  notion("doppler-emission",
    "Dans un effet Doppler, la distance doit être prise à l'instant :",
    "In a Doppler effect, the distance must be taken at the instant:",
    [
      "où le son a été ÉMIS",
      "où le son ARRIVE à l'auditeur",
      "du passage au plus près, une fois pour toutes",
      "du début du fichier, la distance étant une constante",
    ],
    [
      "the sound was EMITTED",
      "the sound ARRIVES at the listener",
      "of closest approach, once and for all",
      "of the file's start, distance being a constant",
    ],
    "La faute a été faite ici et mesurée : prendre la distance à l'arrivée revient à faire bouger l'AUDITEUR plutôt que la source — 491,2 Hz rendus au lieu de 498,1, soit vingt-quatre centièmes de demi-ton. Après correction : 498,0 Hz pour 498,1 attendus.",
    "The mistake was made here and measured: taking the distance on arrival amounts to moving the LISTENER rather than the source — 491.2 Hz returned instead of 498.1, that is, twenty-four hundredths of a semitone. After correction: 498.0 Hz for 498.1 expected.", 2),
  notion("karplus-strong",
    "Comment fabrique-t-on une corde pincée par la méthode de Karplus-Strong ?",
    "How is a plucked string made by the Karplus-Strong method?",
    [
      "un bruit très bref circule dans une ligne à retard rebouclée par un filtre passe-bas",
      "on additionne une vingtaine de sinusoïdes d'amplitudes décroissantes",
      "on module la fréquence d'un oscillateur par un autre oscillateur",
      "on lit un échantillon de corde à des vitesses différentes",
    ],
    [
      "a very brief noise circulates in a delay line fed back through a low-pass filter",
      "some twenty sinusoids of decreasing amplitude are added",
      "one oscillator's frequency is modulated by another oscillator",
      "a string sample is played back at different speeds",
    ],
    "La longueur du retard fait la hauteur — fréquence d'échantillonnage divisée par la note —, et le filtre fait l'extinction : les aigus perdent plus vite, comme sur une vraie corde. Trois lignes de code pour un son que la synthèse additive n'atteint pas.",
    "The delay length makes the pitch — sample rate divided by the note — and the filter makes the decay: highs die faster, as on a real string. Three lines of code for a sound additive synthesis does not reach."),
  notion("fm-indice",
    "Dans la synthèse FM, à quoi sert l'indice de modulation ?",
    "In FM synthesis, what is the modulation index for?",
    [
      "il commande le nombre et la force des bandes latérales, donc la richesse du timbre",
      "il fixe la hauteur perçue de la note",
      "il règle la durée de l'attaque",
      "il détermine la largeur stéréo du résultat",
    ],
    [
      "it commands the number and strength of the sidebands, hence the timbre's richness",
      "it sets the perceived pitch of the note",
      "it sets the attack time",
      "it determines the stereo width of the result",
    ],
    "Chowning (1973) : le rapport des fréquences décide de l'harmonicité — entier, le son est une note ; non entier, une cloche ou un bruit —, et l'indice décide de la richesse. Deux réglages, une infinité de timbres, et un coût de calcul minuscule : c'est ce qui a fait le DX7.",
    "Chowning (1973): the frequency ratio decides harmonicity — integer, the sound is a note; non-integer, a bell or a noise — and the index decides richness. Two controls, an infinity of timbres, and a tiny computational cost: that is what made the DX7.", 2),
  notion("risset",
    "Comment un glissando peut-il monter indéfiniment ?",
    "How can a glissando rise indefinitely?",
    [
      "plusieurs octaves montent en parallèle, les extrêmes naissant et mourant sous une cloche spectrale",
      "la fréquence est doublée puis divisée par deux à chaque seconde",
      "un filtre en peigne remonte pendant que le son descend",
      "le son est lu à l'envers une fois sur deux",
    ],
    [
      "several octaves rise in parallel, the extremes being born and dying under a spectral bell",
      "the frequency is doubled then halved every second",
      "a comb filter rises while the sound falls",
      "the sound is played backwards every other time",
    ],
    "L'oreille suit la MASSE du spectre et non une composante : tant que la cloche fait apparaître une octave en bas quand une autre s'éteint en haut, la montée ne se referme jamais. Risset l'a tiré du paradoxe de Shepard, écrit pour des notes discrètes.",
    "The ear follows the MASS of the spectrum rather than one component: as long as the bell brings in an octave at the bottom when another dies at the top, the rise never closes. Risset drew it from Shepard's paradox, written for discrete notes.", 2),
  notion("cribles",
    "Qu'est-ce qu'un crible, chez Xenakis ?",
    "What is a sieve, in Xenakis's sense?",
    [
      "une réunion de classes de restes modulo, qui engendre une échelle ou un rythme non périodique",
      "un filtre en peigne appliqué à une percussion",
      "une suite de nombres tirés selon une loi de Poisson",
      "un tableau de probabilités de transition entre deux notes",
    ],
    [
      "a union of residue classes modulo n, generating a non-periodic scale or rhythm",
      "a comb filter applied to a drum",
      "a sequence of numbers drawn from a Poisson law",
      "a table of transition probabilities between two notes",
    ],
    "De l'arithmétique modulaire mise au service de la composition : réunir « les multiples de 3 » et « les multiples de 4 décalés de 1 » donne une structure régulière sans être périodique à courte échelle. Xenakis s'en servait pour écrire échelles et rythmes du même geste.",
    "Modular arithmetic put to compositional use: uniting « the multiples of 3 » and « the multiples of 4 offset by 1 » gives a structure that is regular without being periodic at a short scale. Xenakis used it to write scales and rhythms in the same gesture.", 2),
  notion("fux",
    "Qu'est-ce que le contrepoint d'espèces ?",
    "What is species counterpoint?",
    [
      "une progression pédagogique en cinq degrés de liberté croissante, de la ronde au contrepoint fleuri",
      "l'étude des cinq modes d'église du plain-chant",
      "une classification des accords selon leur nombre de notes",
      "la règle qui interdit les quintes parallèles, et elle seule",
    ],
    [
      "a teaching progression in five degrees of increasing freedom, from the whole note to florid counterpoint",
      "the study of the five church modes of plainchant",
      "a classification of chords by their number of notes",
      "the rule forbidding parallel fifths, and that alone",
    ],
    "Fux, « Gradus ad Parnassum » (1725) : on commence par une note contre une note, puis deux, puis quatre, puis les syncopes, puis tout à la fois. Chaque espèce ajoute une liberté et garde les règles précédentes — c'est ce qui en fait une progression et non une liste d'interdits.",
    "Fux, « Gradus ad Parnassum » (1725): one starts with note against note, then two, then four, then syncopations, then everything at once. Each species adds a freedom and keeps the previous rules — which is what makes it a progression rather than a list of prohibitions.", 2),
  notion("quinte-du-loup",
    "Pourquoi un tempérament mésotonique comporte-t-il une « quinte du loup » ?",
    "Why does a meantone temperament contain a « wolf fifth »?",
    [
      "parce que onze quintes ont été rognées pour rendre les tierces justes, et que l'erreur s'accumule sur la douzième",
      "parce qu'une des douze notes est volontairement laissée fausse d'un quart de ton",
      "parce que le clavier de l'époque ne comptait que onze touches par octave",
      "parce que les octaves y sont légèrement plus grandes que le double",
    ],
    [
      "because eleven fifths were narrowed to make the thirds pure, and the error piles up on the twelfth",
      "because one of the twelve notes is deliberately left a quarter-tone out",
      "because the keyboards of the time had only eleven keys per octave",
      "because the octaves there are slightly larger than a doubling",
    ],
    "Douze quintes justes dépassent sept octaves de vingt-trois cents et demi — le comma pythagoricien. Il faut bien que cet écart aille quelque part : le tempérament égal l'étale sur les douze, le mésotonique le concentre sur une seule, qui devient inutilisable.",
    "Twelve pure fifths exceed seven octaves by twenty-three and a half cents — the Pythagorean comma. That gap has to go somewhere: equal temperament spreads it over all twelve, meantone concentrates it on one, which becomes unusable.", 2),
  notion("shruti",
    "Qu'est-ce qu'une shruti ?",
    "What is a shruti?",
    [
      "l'un des vingt-deux degrés de l'octave indienne, en intonation juste",
      "un cycle rythmique de la musique carnatique",
      "un mode de la musique arabe, à tierce neutre",
      "l'intervalle d'un quart de ton du gamelan javanais",
    ],
    [
      "one of the twenty-two degrees of the Indian octave, in just intonation",
      "a rhythmic cycle of Carnatic music",
      "a mode of Arabic music, with a neutral third",
      "the quarter-tone interval of Javanese gamelan",
    ],
    "Vingt-deux et non douze, et en rapports justes et non en divisions égales : c'est pourquoi un raga ne s'écrit pas au clavier. Le nœud « Gammes du monde » rend les degrés en CENTS pour cette raison, et sa sortie MIDI a été retirée — le MIDI n'aurait gardé que des demi-tons.",
    "Twenty-two rather than twelve, and in pure ratios rather than equal divisions: that is why a raga cannot be written on a keyboard. The « World Scales » node returns degrees in CENTS for that reason, and its MIDI output was removed — MIDI would have kept only semitones.", 2),
  notion("maqam-midi",
    "Pourquoi un maqam Rast ne peut-il pas s'écrire en MIDI ?",
    "Why can a Rast maqam not be written in MIDI?",
    [
      "parce que sa tierce neutre tombe entre deux demi-tons, et que le MIDI ne connaît que des demi-tons",
      "parce qu'il compte plus de douze degrés par octave",
      "parce que ses durées ne sont pas des multiples du temps",
      "parce que le MIDI n'admet pas les gammes descendantes",
    ],
    [
      "because its neutral third falls between two semitones, and MIDI knows only semitones",
      "because it has more than twelve degrees per octave",
      "because its durations are not multiples of the beat",
      "because MIDI does not allow descending scales",
    ],
    "Arrondir la tierce neutre au demi-ton le plus proche transforme le maqam en gamme occidentale, c'est-à-dire en exactement ce que le nœud sert à ne pas faire. Une sortie MIDI a donc été retirée du nœud « Gammes du monde » plutôt que déplacée ailleurs.",
    "Rounding the neutral third to the nearest semitone turns the maqam into a Western scale, that is, into exactly what the node exists to avoid. A MIDI output was therefore removed from the « World Scales » node rather than moved elsewhere.", 2),
  notion("sethares",
    "Que montre une courbe de dissonance à la Sethares ?",
    "What does a Sethares dissonance curve show?",
    [
      "que la gamme consonante dépend du SPECTRE du timbre employé",
      "que la consonance décroît régulièrement avec l'intervalle",
      "que l'oreille préfère les intervalles de nombres premiers",
      "que le tempérament égal est le plus consonant de tous",
    ],
    [
      "that the consonant scale depends on the SPECTRUM of the timbre used",
      "that consonance decreases steadily with interval size",
      "that the ear prefers intervals of prime numbers",
      "that equal temperament is the most consonant of all",
    ],
    "Mesuré dans l'application sur une scie de 200 Hz — un vrai son, analysé : les creux tombent à 265, 319, 387, 495, 584 et 701 cents, c'est-à-dire l'intonation juste, qu'aucune ligne du code n'écrit. Un timbre étiré de 2,1 déplace la quinte de cinquante cents : la gamme suit le spectre.",
    "Measured in the application on a 200 Hz sawtooth — a real sound, analysed: the dips fall at 265, 319, 387, 495, 584 and 701 cents, that is, just intonation, which no line of the code writes. A timbre stretched by 2.1 moves the fifth by fifty cents: the scale follows the spectrum.", 2),
  notion("gel-spectral",
    "Ce qui distingue le gel spectral du gel granulaire :",
    "What distinguishes spectral freeze from granular freeze:",
    [
      "le gel spectral tient une ANALYSE, le granulaire boucle un morceau de signal",
      "le gel spectral ne fonctionne que sur les sons percussifs",
      "le gel granulaire conserve la hauteur, le spectral la perd",
      "le gel spectral travaille en stéréo, le granulaire en mono",
    ],
    [
      "spectral freeze holds an ANALYSIS, granular freeze loops a piece of signal",
      "spectral freeze works on percussive sounds only",
      "granular freeze keeps the pitch, spectral freeze loses it",
      "spectral freeze works in stereo, granular in mono",
    ],
    "La conséquence s'entend : boucler un morceau de signal fait entendre la boucle, sa période et ses raccords ; tenir une analyse laisse les phases continuer d'avancer, comme si le son se prolongeait. Ni période, ni raccord, ni battement — l'immobilité et non la répétition.",
    "The consequence is audible: looping a piece of signal makes the loop, its period and its joins heard; holding an analysis lets the phases keep advancing, as if the sound went on. No period, no join, no beating — stillness rather than repetition.", 2),
  notion("declipping",
    "Que fait un déclipeur ?",
    "What does a declipper do?",
    [
      "il reconstruit les crêtes écrasées en cherchant le signal le plus parcimonieux compatible avec ce qui reste",
      "il baisse le niveau général jusqu'à ce que plus rien ne sature",
      "il remplace les parties saturées par du silence",
      "il applique un filtre passe-bas aux passages saturés",
    ],
    [
      "it rebuilds the crushed peaks by seeking the sparsest signal compatible with what remains",
      "it lowers the overall level until nothing clips any more",
      "it replaces the clipped parts with silence",
      "it applies a low-pass filter to the clipped passages",
    ],
    "Baisser le niveau ne rend pas ce qui a été coupé : l'information est perdue, il faut l'inventer de façon contrainte. Les échantillons non saturés sont connus, les saturés seulement bornés par le dessous : parmi tous les signaux compatibles, on retient celui dont le spectre est le plus creux.",
    "Lowering the level does not give back what was cut: the information is lost and has to be invented under constraint. Unclipped samples are known, clipped ones only bounded from below: among all compatible signals, the one with the sparsest spectrum is kept.", 2),
  notion("meta-composant",
    "À quoi sert un méta-composant, dans Attic ?",
    "What is a meta-component for, in Attic?",
    [
      "à replier tout un sous-graphe en un seul nœud, réutilisable comme n'importe quel autre",
      "à exécuter deux nœuds en parallèle sur deux cœurs",
      "à documenter un graphe sans l'exécuter",
      "à convertir un nœud audio en nœud MIDI",
    ],
    [
      "to fold a whole subgraph into a single node, reusable like any other",
      "to run two nodes in parallel on two cores",
      "to document a graph without running it",
      "to convert an audio node into a MIDI node",
    ],
    "Un graphe qui marche devient une brique. C'est aussi ce qui permet le régime d'économie de mémoire : les nœuds intermédiaires d'un méta-composant n'ont plus à garder leur aperçu, puisque personne ne les regarde.",
    "A graph that works becomes a building block. It is also what makes the memory-saving regime possible: the intermediate nodes of a meta-component no longer have to keep their preview, since nobody is looking at them."),
  notion("graine",
    "Pourquoi les nœuds qui tirent au sort portent-ils un paramètre « Graine » ?",
    "Why do the nodes that draw at random carry a « Seed » parameter?",
    [
      "pour qu'un résultat obtenu par hasard puisse être retrouvé à l'identique",
      "pour accélérer le calcul en évitant un appel système",
      "pour garantir que deux nœuds voisins ne tirent pas la même chose",
      "pour choisir la loi de probabilité du tirage",
    ],
    [
      "so that a result obtained by chance can be found again exactly",
      "to speed up the computation by avoiding a system call",
      "to guarantee that two neighbouring nodes do not draw the same thing",
      "to choose the probability law of the draw",
    ],
    "Sans elle, le rendu qu'on voulait garder est perdu à la première réexécution. La graine se règle sur le nœud, se sauvegarde avec le projet comme n'importe quel paramètre, et n'engage que lui. La convention du dépôt : à zéro, le nœud tire une graine et l'AFFICHE, faute de quoi elle serait introuvable.",
    "Without it, the render one wanted to keep is lost on the first re-run. The seed is set on the node, saved with the project like any parameter, and commits that node alone. The repository's convention: at zero the node draws a seed and DISPLAYS it, failing which it would be unfindable."),
  notion("regime-memoire",
    "Dans Attic, que signifie un nœud de régime mémoire « totale » ?",
    "In Attic, what does a node with « total » memory regime mean?",
    [
      "il ne peut pas commencer son calcul avant d'avoir le signal entier",
      "il charge tous les modèles d'intelligence artificielle au démarrage",
      "il garde son résultat en mémoire jusqu'à la fermeture",
      "il refuse de tourner au-delà de dix minutes de piste",
    ],
    [
      "it cannot start computing before it has the entire signal",
      "it loads every AI model at start-up",
      "it keeps its result in memory until the application closes",
      "it refuses to run beyond ten minutes of track",
    ],
    "Un étirement lit la fin pour écrire le début : il lui faut tout. Un nœud de régime « flux » avance échantillon par échantillon et pourra, au-delà de dix minutes, travailler par blocs. Typer les nœuds ainsi est ce qui permet d'économiser la mémoire sans rien casser.",
    "A stretch reads the end to write the beginning: it needs everything. A « stream » regime node advances sample by sample and can, beyond ten minutes, work in blocks. Typing nodes this way is what allows saving memory without breaking anything.", 2),
];
