// quiz/notions-suite.ts — La seconde moitie de la banque des notions.
//
// POURQUOI UNE SUITE, ET NON UN REGROUPEMENT PAR SUJET. Le quiz tire sa serie par une graine sur
// la banque : reordonner les questions changerait ce qu'une graine donnee produit, et la promesse
// « meme entree, meme serie » avec. La coupe est donc positionnelle, et `NOTIONS` reste la
// concatenation des deux moities, dans l'ordre d'origine.

import type { Question } from "./types";
import { notion } from "./notion-question";

export const NOTIONS_SUITE: Question[] = [
  notion("harmonie-negative",
    "Comment s'obtient l'harmonie négative ?",
    "How is negative harmony obtained?",
    [
      "par réflexion des hauteurs autour de l'axe qui joint la tonique et la dominante",
      "en inversant l'ordre des accords d'une progression",
      "en jouant chaque accord une quinte plus bas",
      "en remplaçant chaque accord majeur par son mineur relatif",
    ],
    [
      "by reflecting pitches about the axis joining tonic and dominant",
      "by reversing the order of a progression's chords",
      "by playing every chord a fifth lower",
      "by replacing every major chord with its relative minor",
    ],
    "Une symétrie, pas une transposition : la réflexion échange les degrés de part et d'autre de l'axe, si bien qu'un majeur devient mineur et qu'une dominante trouve un substitut inattendu mais fonctionnel. L'idée remonte à Riemann, et son usage courant à Jacob Collier.",
    "A symmetry, not a transposition: the reflection swaps the degrees on either side of the axis, so that a major becomes minor and a dominant finds an unexpected but functional substitute. The idea goes back to Riemann, and its current use to Jacob Collier.", 2),
  notion("mosaiquage",
    "En quoi consiste le mosaïquage audio ?",
    "What does audio mosaicing consist of?",
    [
      "remplacer chaque grain d'un son par le grain le plus proche pris dans un autre son",
      "coller bout à bout des extraits de plusieurs sons, en fondu enchaîné",
      "répartir un son sur plusieurs canaux selon sa fréquence",
      "recomposer un son à partir de sinusoïdes pures",
    ],
    [
      "replacing each grain of a sound with the nearest grain taken from another sound",
      "gluing excerpts of several sounds end to end, with crossfades",
      "spreading a sound over several channels according to frequency",
      "rebuilding a sound out of pure sinusoids",
    ],
    "On garde la FORME d'un son et la MATIÈRE d'un autre : une phrase parlée jouée par des bruits de pas, une mélodie jouée par des portes qui claquent. La ressemblance se mesure sur des descripteurs — énergie, centroïde, coefficients cepstraux — et non sur les échantillons.",
    "The FORM of one sound is kept and the MATTER of another: a spoken phrase played by footsteps, a melody played by slamming doors. Similarity is measured on descriptors — energy, centroid, cepstral coefficients — not on samples.", 2),
  notion("b-format",
    "Que portent les quatre canaux W, X, Y, Z de l'ambisonique ?",
    "What do ambisonics' four channels W, X, Y, Z carry?",
    [
      "la pression et les trois composantes de la vitesse, indépendamment de tout haut-parleur",
      "les quatre haut-parleurs d'un système quadriphonique",
      "les quatre premières harmoniques du signal",
      "les canaux gauche, droit, arrière et caisson de basses",
    ],
    [
      "pressure and the three velocity components, independently of any loudspeaker",
      "the four loudspeakers of a quadraphonic system",
      "the signal's first four harmonics",
      "the left, right, rear and subwoofer channels",
    ],
    "C'est ce qui fait la force du format : il décrit le CHAMP et non un dispositif d'écoute, si bien que la même prise se décode sur un casque, quatre enceintes ou trente. Et faire tourner la scène entière coûte deux multiplications par échantillon — la pression W et la hauteur Z ne bougeant pas.",
    "That is the format's strength: it describes the FIELD rather than a listening setup, so the same recording decodes onto headphones, four speakers or thirty. And rotating the whole scene costs two multiplications per sample — pressure W and height Z not moving.", 2),
  notion("doppler-emission",
    "Dans un effet Doppler, la distance doit être prise à l'instant :",
    "In a Doppler effect, the distance must be taken at the instant:",
    [
      "où le son a été ÉMIS",
      "où le son ARRIVE à l'auditeur",
      "du passage au plus près, une fois pour toutes",
      "du début du fichier, la distance étant une constante",
    ],
    [
      "the sound was EMITTED",
      "the sound ARRIVES at the listener",
      "of closest approach, once and for all",
      "of the file's start, distance being a constant",
    ],
    "La faute a été faite ici et mesurée : prendre la distance à l'arrivée revient à faire bouger l'AUDITEUR plutôt que la source — 491,2 Hz rendus au lieu de 498,1, soit vingt-quatre centièmes de demi-ton. Après correction : 498,0 Hz pour 498,1 attendus.",
    "The mistake was made here and measured: taking the distance on arrival amounts to moving the LISTENER rather than the source — 491.2 Hz returned instead of 498.1, that is, twenty-four hundredths of a semitone. After correction: 498.0 Hz for 498.1 expected.", 2),
  notion("karplus-strong",
    "Comment fabrique-t-on une corde pincée par la méthode de Karplus-Strong ?",
    "How is a plucked string made by the Karplus-Strong method?",
    [
      "un bruit très bref circule dans une ligne à retard rebouclée par un filtre passe-bas",
      "on additionne une vingtaine de sinusoïdes d'amplitudes décroissantes",
      "on module la fréquence d'un oscillateur par un autre oscillateur",
      "on lit un échantillon de corde à des vitesses différentes",
    ],
    [
      "a very brief noise circulates in a delay line fed back through a low-pass filter",
      "some twenty sinusoids of decreasing amplitude are added",
      "one oscillator's frequency is modulated by another oscillator",
      "a string sample is played back at different speeds",
    ],
    "La longueur du retard fait la hauteur — fréquence d'échantillonnage divisée par la note —, et le filtre fait l'extinction : les aigus perdent plus vite, comme sur une vraie corde. Trois lignes de code pour un son que la synthèse additive n'atteint pas.",
    "The delay length makes the pitch — sample rate divided by the note — and the filter makes the decay: highs die faster, as on a real string. Three lines of code for a sound additive synthesis does not reach."),
  notion("fm-indice",
    "Dans la synthèse FM, à quoi sert l'indice de modulation ?",
    "In FM synthesis, what is the modulation index for?",
    [
      "il commande le nombre et la force des bandes latérales, donc la richesse du timbre",
      "il fixe la hauteur perçue de la note",
      "il règle la durée de l'attaque",
      "il détermine la largeur stéréo du résultat",
    ],
    [
      "it commands the number and strength of the sidebands, hence the timbre's richness",
      "it sets the perceived pitch of the note",
      "it sets the attack time",
      "it determines the stereo width of the result",
    ],
    "Chowning (1973) : le rapport des fréquences décide de l'harmonicité — entier, le son est une note ; non entier, une cloche ou un bruit —, et l'indice décide de la richesse. Deux réglages, une infinité de timbres, et un coût de calcul minuscule : c'est ce qui a fait le DX7.",
    "Chowning (1973): the frequency ratio decides harmonicity — integer, the sound is a note; non-integer, a bell or a noise — and the index decides richness. Two controls, an infinity of timbres, and a tiny computational cost: that is what made the DX7.", 2),
  notion("risset",
    "Comment un glissando peut-il monter indéfiniment ?",
    "How can a glissando rise indefinitely?",
    [
      "plusieurs octaves montent en parallèle, les extrêmes naissant et mourant sous une cloche spectrale",
      "la fréquence est doublée puis divisée par deux à chaque seconde",
      "un filtre en peigne remonte pendant que le son descend",
      "le son est lu à l'envers une fois sur deux",
    ],
    [
      "several octaves rise in parallel, the extremes being born and dying under a spectral bell",
      "the frequency is doubled then halved every second",
      "a comb filter rises while the sound falls",
      "the sound is played backwards every other time",
    ],
    "L'oreille suit la MASSE du spectre et non une composante : tant que la cloche fait apparaître une octave en bas quand une autre s'éteint en haut, la montée ne se referme jamais. Risset l'a tiré du paradoxe de Shepard, écrit pour des notes discrètes.",
    "The ear follows the MASS of the spectrum rather than one component: as long as the bell brings in an octave at the bottom when another dies at the top, the rise never closes. Risset drew it from Shepard's paradox, written for discrete notes.", 2),
  notion("cribles",
    "Qu'est-ce qu'un crible, chez Xenakis ?",
    "What is a sieve, in Xenakis's sense?",
    [
      "une réunion de classes de restes modulo, qui engendre une échelle ou un rythme non périodique",
      "un filtre en peigne appliqué à une percussion",
      "une suite de nombres tirés selon une loi de Poisson",
      "un tableau de probabilités de transition entre deux notes",
    ],
    [
      "a union of residue classes modulo n, generating a non-periodic scale or rhythm",
      "a comb filter applied to a drum",
      "a sequence of numbers drawn from a Poisson law",
      "a table of transition probabilities between two notes",
    ],
    "De l'arithmétique modulaire mise au service de la composition : réunir « les multiples de 3 » et « les multiples de 4 décalés de 1 » donne une structure régulière sans être périodique à courte échelle. Xenakis s'en servait pour écrire échelles et rythmes du même geste.",
    "Modular arithmetic put to compositional use: uniting « the multiples of 3 » and « the multiples of 4 offset by 1 » gives a structure that is regular without being periodic at a short scale. Xenakis used it to write scales and rhythms in the same gesture.", 2),
  notion("fux",
    "Qu'est-ce que le contrepoint d'espèces ?",
    "What is species counterpoint?",
    [
      "une progression pédagogique en cinq degrés de liberté croissante, de la ronde au contrepoint fleuri",
      "l'étude des cinq modes d'église du plain-chant",
      "une classification des accords selon leur nombre de notes",
      "la règle qui interdit les quintes parallèles, et elle seule",
    ],
    [
      "a teaching progression in five degrees of increasing freedom, from the whole note to florid counterpoint",
      "the study of the five church modes of plainchant",
      "a classification of chords by their number of notes",
      "the rule forbidding parallel fifths, and that alone",
    ],
    "Fux, « Gradus ad Parnassum » (1725) : on commence par une note contre une note, puis deux, puis quatre, puis les syncopes, puis tout à la fois. Chaque espèce ajoute une liberté et garde les règles précédentes — c'est ce qui en fait une progression et non une liste d'interdits.",
    "Fux, « Gradus ad Parnassum » (1725): one starts with note against note, then two, then four, then syncopations, then everything at once. Each species adds a freedom and keeps the previous rules — which is what makes it a progression rather than a list of prohibitions.", 2),
  notion("quinte-du-loup",
    "Pourquoi un tempérament mésotonique comporte-t-il une « quinte du loup » ?",
    "Why does a meantone temperament contain a « wolf fifth »?",
    [
      "parce que onze quintes ont été rognées pour rendre les tierces justes, et que l'erreur s'accumule sur la douzième",
      "parce qu'une des douze notes est volontairement laissée fausse d'un quart de ton",
      "parce que le clavier de l'époque ne comptait que onze touches par octave",
      "parce que les octaves y sont légèrement plus grandes que le double",
    ],
    [
      "because eleven fifths were narrowed to make the thirds pure, and the error piles up on the twelfth",
      "because one of the twelve notes is deliberately left a quarter-tone out",
      "because the keyboards of the time had only eleven keys per octave",
      "because the octaves there are slightly larger than a doubling",
    ],
    "Douze quintes justes dépassent sept octaves de vingt-trois cents et demi — le comma pythagoricien. Il faut bien que cet écart aille quelque part : le tempérament égal l'étale sur les douze, le mésotonique le concentre sur une seule, qui devient inutilisable.",
    "Twelve pure fifths exceed seven octaves by twenty-three and a half cents — the Pythagorean comma. That gap has to go somewhere: equal temperament spreads it over all twelve, meantone concentrates it on one, which becomes unusable.", 2),
  notion("shruti",
    "Qu'est-ce qu'une shruti ?",
    "What is a shruti?",
    [
      "l'un des vingt-deux degrés de l'octave indienne, en intonation juste",
      "un cycle rythmique de la musique carnatique",
      "un mode de la musique arabe, à tierce neutre",
      "l'intervalle d'un quart de ton du gamelan javanais",
    ],
    [
      "one of the twenty-two degrees of the Indian octave, in just intonation",
      "a rhythmic cycle of Carnatic music",
      "a mode of Arabic music, with a neutral third",
      "the quarter-tone interval of Javanese gamelan",
    ],
    "Vingt-deux et non douze, et en rapports justes et non en divisions égales : c'est pourquoi un raga ne s'écrit pas au clavier. Le nœud « Gammes du monde » rend les degrés en CENTS pour cette raison, et sa sortie MIDI a été retirée — le MIDI n'aurait gardé que des demi-tons.",
    "Twenty-two rather than twelve, and in pure ratios rather than equal divisions: that is why a raga cannot be written on a keyboard. The « World Scales » node returns degrees in CENTS for that reason, and its MIDI output was removed — MIDI would have kept only semitones.", 2),
  notion("maqam-midi",
    "Pourquoi un maqam Rast ne peut-il pas s'écrire en MIDI ?",
    "Why can a Rast maqam not be written in MIDI?",
    [
      "parce que sa tierce neutre tombe entre deux demi-tons, et que le MIDI ne connaît que des demi-tons",
      "parce qu'il compte plus de douze degrés par octave",
      "parce que ses durées ne sont pas des multiples du temps",
      "parce que le MIDI n'admet pas les gammes descendantes",
    ],
    [
      "because its neutral third falls between two semitones, and MIDI knows only semitones",
      "because it has more than twelve degrees per octave",
      "because its durations are not multiples of the beat",
      "because MIDI does not allow descending scales",
    ],
    "Arrondir la tierce neutre au demi-ton le plus proche transforme le maqam en gamme occidentale, c'est-à-dire en exactement ce que le nœud sert à ne pas faire. Une sortie MIDI a donc été retirée du nœud « Gammes du monde » plutôt que déplacée ailleurs.",
    "Rounding the neutral third to the nearest semitone turns the maqam into a Western scale, that is, into exactly what the node exists to avoid. A MIDI output was therefore removed from the « World Scales » node rather than moved elsewhere.", 2),
  notion("sethares",
    "Que montre une courbe de dissonance à la Sethares ?",
    "What does a Sethares dissonance curve show?",
    [
      "que la gamme consonante dépend du SPECTRE du timbre employé",
      "que la consonance décroît régulièrement avec l'intervalle",
      "que l'oreille préfère les intervalles de nombres premiers",
      "que le tempérament égal est le plus consonant de tous",
    ],
    [
      "that the consonant scale depends on the SPECTRUM of the timbre used",
      "that consonance decreases steadily with interval size",
      "that the ear prefers intervals of prime numbers",
      "that equal temperament is the most consonant of all",
    ],
    "Mesuré dans l'application sur une scie de 200 Hz — un vrai son, analysé : les creux tombent à 265, 319, 387, 495, 584 et 701 cents, c'est-à-dire l'intonation juste, qu'aucune ligne du code n'écrit. Un timbre étiré de 2,1 déplace la quinte de cinquante cents : la gamme suit le spectre.",
    "Measured in the application on a 200 Hz sawtooth — a real sound, analysed: the dips fall at 265, 319, 387, 495, 584 and 701 cents, that is, just intonation, which no line of the code writes. A timbre stretched by 2.1 moves the fifth by fifty cents: the scale follows the spectrum.", 2),
  notion("gel-spectral",
    "Ce qui distingue le gel spectral du gel granulaire :",
    "What distinguishes spectral freeze from granular freeze:",
    [
      "le gel spectral tient une ANALYSE, le granulaire boucle un morceau de signal",
      "le gel spectral ne fonctionne que sur les sons percussifs",
      "le gel granulaire conserve la hauteur, le spectral la perd",
      "le gel spectral travaille en stéréo, le granulaire en mono",
    ],
    [
      "spectral freeze holds an ANALYSIS, granular freeze loops a piece of signal",
      "spectral freeze works on percussive sounds only",
      "granular freeze keeps the pitch, spectral freeze loses it",
      "spectral freeze works in stereo, granular in mono",
    ],
    "La conséquence s'entend : boucler un morceau de signal fait entendre la boucle, sa période et ses raccords ; tenir une analyse laisse les phases continuer d'avancer, comme si le son se prolongeait. Ni période, ni raccord, ni battement — l'immobilité et non la répétition.",
    "The consequence is audible: looping a piece of signal makes the loop, its period and its joins heard; holding an analysis lets the phases keep advancing, as if the sound went on. No period, no join, no beating — stillness rather than repetition.", 2),
  notion("declipping",
    "Que fait un déclipeur ?",
    "What does a declipper do?",
    [
      "il reconstruit les crêtes écrasées en cherchant le signal le plus parcimonieux compatible avec ce qui reste",
      "il baisse le niveau général jusqu'à ce que plus rien ne sature",
      "il remplace les parties saturées par du silence",
      "il applique un filtre passe-bas aux passages saturés",
    ],
    [
      "it rebuilds the crushed peaks by seeking the sparsest signal compatible with what remains",
      "it lowers the overall level until nothing clips any more",
      "it replaces the clipped parts with silence",
      "it applies a low-pass filter to the clipped passages",
    ],
    "Baisser le niveau ne rend pas ce qui a été coupé : l'information est perdue, il faut l'inventer de façon contrainte. Les échantillons non saturés sont connus, les saturés seulement bornés par le dessous : parmi tous les signaux compatibles, on retient celui dont le spectre est le plus creux.",
    "Lowering the level does not give back what was cut: the information is lost and has to be invented under constraint. Unclipped samples are known, clipped ones only bounded from below: among all compatible signals, the one with the sparsest spectrum is kept.", 2),
  notion("meta-composant",
    "À quoi sert un méta-composant, dans Attic ?",
    "What is a meta-component for, in Attic?",
    [
      "à replier tout un sous-graphe en un seul nœud, réutilisable comme n'importe quel autre",
      "à exécuter deux nœuds en parallèle sur deux cœurs",
      "à documenter un graphe sans l'exécuter",
      "à convertir un nœud audio en nœud MIDI",
    ],
    [
      "to fold a whole subgraph into a single node, reusable like any other",
      "to run two nodes in parallel on two cores",
      "to document a graph without running it",
      "to convert an audio node into a MIDI node",
    ],
    "Un graphe qui marche devient une brique. C'est aussi ce qui permet le régime d'économie de mémoire : les nœuds intermédiaires d'un méta-composant n'ont plus à garder leur aperçu, puisque personne ne les regarde.",
    "A graph that works becomes a building block. It is also what makes the memory-saving regime possible: the intermediate nodes of a meta-component no longer have to keep their preview, since nobody is looking at them."),
  notion("graine",
    "Pourquoi les nœuds qui tirent au sort portent-ils un paramètre « Graine » ?",
    "Why do the nodes that draw at random carry a « Seed » parameter?",
    [
      "pour qu'un résultat obtenu par hasard puisse être retrouvé à l'identique",
      "pour accélérer le calcul en évitant un appel système",
      "pour garantir que deux nœuds voisins ne tirent pas la même chose",
      "pour choisir la loi de probabilité du tirage",
    ],
    [
      "so that a result obtained by chance can be found again exactly",
      "to speed up the computation by avoiding a system call",
      "to guarantee that two neighbouring nodes do not draw the same thing",
      "to choose the probability law of the draw",
    ],
    "Sans elle, le rendu qu'on voulait garder est perdu à la première réexécution. La graine se règle sur le nœud, se sauvegarde avec le projet comme n'importe quel paramètre, et n'engage que lui. La convention du dépôt : à zéro, le nœud tire une graine et l'AFFICHE, faute de quoi elle serait introuvable.",
    "Without it, the render one wanted to keep is lost on the first re-run. The seed is set on the node, saved with the project like any parameter, and commits that node alone. The repository's convention: at zero the node draws a seed and DISPLAYS it, failing which it would be unfindable."),
  notion("regime-memoire",
    "Dans Attic, que signifie un nœud de régime mémoire « totale » ?",
    "In Attic, what does a node with « total » memory regime mean?",
    [
      "il ne peut pas commencer son calcul avant d'avoir le signal entier",
      "il charge tous les modèles d'intelligence artificielle au démarrage",
      "il garde son résultat en mémoire jusqu'à la fermeture",
      "il refuse de tourner au-delà de dix minutes de piste",
    ],
    [
      "it cannot start computing before it has the entire signal",
      "it loads every AI model at start-up",
      "it keeps its result in memory until the application closes",
      "it refuses to run beyond ten minutes of track",
    ],
    "Un étirement lit la fin pour écrire le début : il lui faut tout. Un nœud de régime « flux » avance échantillon par échantillon et pourra, au-delà de dix minutes, travailler par blocs. Typer les nœuds ainsi est ce qui permet d'économiser la mémoire sans rien casser.",
    "A stretch reads the end to write the beginning: it needs everything. A « stream » regime node advances sample by sample and can, beyond ten minutes, work in blocks. Typing nodes this way is what allows saving memory without breaking anything.", 2),
];
