// quiz/notions.ts — Les notions, c'est-à-dire ce qui reste quand on a oublié les sigles.
//
// LE SEUL THÈME OÙ LES PROPOSITIONS SONT TRADUITES, parce que ce sont des phrases et non des
// noms. C'est aussi le thème le plus difficile à écrire honnêtement : une notion mal découpée
// donne une question à deux bonnes réponses, et l'utilisateur a raison contre le quiz.
//
// DEUX RÈGLES QUE CHAQUE QUESTION D'ICI RESPECTE :
//
//  1. UNE SEULE PROPOSITION EST VRAIE, et les trois autres sont FAUSSES — pas « moins précises ».
//     Un leurre qui serait vrai à moitié rend la question injuste, et un test ne peut pas
//     attraper cela : il n'y a que la relecture.
//  2. LA QUESTION PORTE SUR CE QUI DISTINGUE, jamais sur une définition à réciter. « Ce qui
//     distingue le ducking d'un compresseur » s'apprend une fois pour toutes ; « qu'est-ce qu'un
//     compresseur » ne s'évalue pas en quatre lignes.
//
// Beaucoup de ces notions ont leur nœud dans le catalogue. L'explication le dit quand c'est le
// cas : le quiz sert aussi à savoir ce qu'on a sous la main.

import type { Question } from "./types";

// Le constructeur vit dans `notion-question.ts` : le garder ici créait un cycle à l'exécution avec
// la suite, qui s'en sert aussi.
import { notion } from "./notion-question";
import { NOTIONS_SUITE } from "./notions-suite";

export const NOTIONS_PREMIERES: Question[] = [
  notion("precedence",
    "Une réflexion qui arrive moins de quarante millisecondes après le son direct est :",
    "A reflection arriving less than forty milliseconds after the direct sound is:",
    [
      "fusionnée avec lui : on entend un seul son, mais plus gros",
      "entendue comme un écho distinct",
      "annulée par interférence avec le son direct",
      "perçue une octave au-dessus du son direct",
    ],
    [
      "fused with it: one single sound is heard, but a bigger one",
      "heard as a distinct echo",
      "cancelled by interference with the direct sound",
      "perceived an octave above the direct sound",
    ],
    "C'est l'effet de précédence, et c'est tout le principe du nœud « Ampleur » : on ajoute des réflexions pour grossir le son, pas pour l'entendre se répéter. Au-delà d'une centaine de millisecondes, elles commencent à se détacher et deviennent des échos.",
    "This is the precedence effect, and it is the whole principle of the « Spaciousness » node: reflections are added to make the sound bigger, not to hear it repeat. Beyond a hundred milliseconds or so they start to stand out and become echoes."),
  notion("bande-critique",
    "Qu'est-ce qu'une bande critique ?",
    "What is a critical band?",
    [
      "la largeur en deçà de laquelle deux sons se disputent la même région de la cochlée",
      "une bande de fréquences que l'oreille n'entend pas",
      "la largeur de bande d'un filtre d'égaliseur paramétrique",
      "l'écart maximal entre deux notes que l'on juge consonantes",
    ],
    [
      "the width below which two sounds compete for the same region of the cochlea",
      "a band of frequencies the ear cannot hear",
      "the bandwidth of a parametric equalizer filter",
      "the largest interval between two notes judged consonant",
    ],
    "La notion qui explique à la fois la dissonance et le masquage : deux sons dans la même bande critique battent et se masquent, deux sons éloignés cohabitent. Zwicker (1961) en a donné la largeur ; Plomp et Levelt (1965) en ont tiré la courbe de rugosité.",
    "The notion that explains both dissonance and masking: two sounds in the same critical band beat and mask each other, two distant ones coexist. Zwicker (1961) gave its width; Plomp and Levelt (1965) drew the roughness curve from it."),
  notion("masquage-asymetrie",
    "Un son fort masque surtout :",
    "A loud sound mainly masks:",
    [
      "les sons plus aigus que lui",
      "les sons plus graves que lui",
      "les sons de même fréquence, et eux seuls",
      "indifféremment les deux côtés, le masquage étant symétrique",
    ],
    [
      "sounds higher than itself",
      "sounds lower than itself",
      "sounds at the same frequency, and those alone",
      "both sides equally, masking being symmetric",
    ],
    "L'onde progresse du grave vers l'aigu dans la cochlée : un son masque donc largement vers le haut et très peu vers le bas. Mesuré dans le nœud « Masquage » sur deux sons à une bande critique d'écart : 100 % de l'énergie masquée quand le masquant est en dessous, 0,0 % quand il est au-dessus.",
    "The wave travels from low to high in the cochlea: a sound therefore masks widely upward and very little downward. Measured in the « Masking » node on two sounds one critical band apart: 100 % of the energy masked when the masker is below, 0.0 % when it is above."),
  notion("velours",
    "Qu'est-ce que le bruit de velours ?",
    "What is velvet noise?",
    [
      "une impulsion de ±1 par case d'une grille régulière, placée au hasard dans sa case",
      "un bruit blanc filtré en passe-bas très doux",
      "un bruit dont le spectre décroît de 3 dB par octave",
      "une suite d'impulsions régulièrement espacées et d'amplitudes décroissantes",
    ],
    [
      "one impulse of plus or minus 1 per cell of a regular grid, placed at random within its cell",
      "white noise filtered by a very gentle low-pass",
      "noise whose spectrum falls by 3 dB per octave",
      "a train of evenly spaced impulses with decreasing amplitudes",
    ],
    "Sa RARETÉ est ce qui le rend utile : quelques dizaines d'impulsions par seconde décorrèlent sans colorer, là où un bruit dense s'entendrait comme un souffle et un peigne régulier comme un timbre. Välimäki et ses collègues (IEEE TASLP, 2013) en ont fait la brique des réverbérations et des élargisseurs.",
    "Its SPARSENESS is what makes it useful: a few dozen impulses per second decorrelate without colouring, where dense noise would be heard as hiss and a regular comb as a timbre. Valimaki and colleagues (IEEE TASLP, 2013) made it the building block of reverbs and wideners.", 2),
  notion("ms-mono",
    "Pourquoi un élargisseur stéréo M-S ne fait-il rien sur une source mono ?",
    "Why does an M-S stereo widener do nothing to a mono source?",
    [
      "parce que le côté vaut la différence des deux canaux, donc zéro, et qu'amplifier zéro donne zéro",
      "parce qu'il exige une fréquence d'échantillonnage de 48 kHz",
      "parce qu'il travaille en dessous de 200 Hz seulement",
      "parce que le milieu et le côté sont alors en opposition de phase",
    ],
    [
      "because the side is the difference of the two channels, hence zero, and amplifying zero gives zero",
      "because it requires a 48 kHz sample rate",
      "because it works below 200 Hz only",
      "because mid and side are then in opposite phase",
    ],
    "Vérifié dans l'application : l'élargisseur M-S à 200 % laisse une source mono au goniomètre à r = 1,00, c'est-à-dire intacte. Élargir suppose une différence qui existe déjà ; la CRÉER demande d'ajouter quelque chose de différent à chaque canal — c'est ce que fait le nœud « Ampleur ».",
    "Verified in the application: the M-S widener at 200 % leaves a mono source at r = 1.00 on the goniometer, that is, untouched. Widening presumes a difference that already exists; CREATING one requires adding something different to each channel — which is what the « Spaciousness » node does."),
  notion("camelot",
    "À quoi sert la roue de Camelot ?",
    "What is the Camelot wheel for?",
    [
      "à ranger les tonalités de sorte que deux voisines s'enchaînent sans heurt",
      "à mesurer le tempo d'un morceau par autocorrélation",
      "à choisir les fréquences de coupure d'un égaliseur",
      "à répartir les percussions sur une grille de seize pas",
    ],
    [
      "to arrange keys so that two neighbours follow one another without a jolt",
      "to measure a piece's tempo by autocorrelation",
      "to choose an equalizer's cutoff frequencies",
      "to lay drums out on a sixteen-step grid",
    ],
    "C'est le cycle des quintes rhabillé pour le mixage : douze positions, deux anneaux (mineur et majeur), et la règle qu'on ne se déplace que d'un cran. Le nœud « Cercle pulsant » s'en sert autrement — il fait correspondre la roue des teintes à celle-ci, de sorte que deux couleurs voisines donnent deux tonalités compatibles.",
    "It is the circle of fifths dressed for mixing: twelve positions, two rings (minor and major), and the rule that one moves by a single step. The « Pulsing Circle » node uses it differently — it maps the hue wheel onto this one, so that two neighbouring colours give two compatible keys."),
  notion("tonnetz",
    "Qu'est-ce que le Tonnetz ?",
    "What is the Tonnetz?",
    [
      "un réseau où les accords voisins partagent deux de leurs trois notes",
      "une table des fréquences des tempéraments historiques",
      "la matrice des douze transpositions d'une série dodécaphonique",
      "un graphe des enchaînements d'accords les plus fréquents du jazz",
    ],
    [
      "a lattice where neighbouring chords share two of their three notes",
      "a table of the frequencies of historical temperaments",
      "the matrix of the twelve transpositions of a twelve-tone row",
      "a graph of the commonest chord successions in jazz",
    ],
    "Le réseau d'Euler, repris par la théorie néo-riemannienne : les trois mouvements P, L et R ne déplacent qu'une seule voix, d'un demi-ton ou d'un ton. C'est pourquoi la suite P, L, R coûte deux demi-tons par enchaînement — la mesure que donne le nœud « Distance de conduite de voix ».",
    "Euler's lattice, taken up by neo-Riemannian theory: the three moves P, L and R shift one single voice, by a semitone or a tone. That is why the sequence P, L, R costs two semitones per step — the measure given by the « Voice-Leading Distance » node.", 2),
  notion("resultante",
    "Comment s'obtient une résultante de Schillinger ?",
    "How is a Schillinger resultant obtained?",
    [
      "en superposant deux pulsations régulières et en gardant toutes les attaques",
      "en répartissant k frappes le plus également possible sur n pas",
      "en retirant une frappe sur deux d'un motif régulier",
      "en tirant les positions au hasard selon une loi de Poisson",
    ],
    [
      "by superposing two regular pulses and keeping every attack",
      "by spreading k hits as evenly as possible over n steps",
      "by removing every second hit from a regular pattern",
      "by drawing positions at random from a Poisson law",
    ],
    "Trois contre deux donne 2-1-1-2, la figure la plus citée du système ; quatre contre trois donne 3-1-2-2-1-3. La deuxième proposition décrit le rythme EUCLIDIEN, qui est l'autre grande famille : l'un répartit, l'autre superpose — et leurs résultats diffèrent presque toujours.",
    "Three against two gives 2-1-1-2, the most cited figure of the system; four against three gives 3-1-2-2-1-3. The second option describes the EUCLIDEAN rhythm, which is the other great family: one spreads, the other superposes — and their results almost always differ.", 2),
  notion("waveset",
    "Qu'est-ce qu'un waveset, chez Wishart ?",
    "What is a waveset, in Wishart's sense?",
    [
      "le segment compris entre un passage par zéro montant et le suivant",
      "un grain de durée fixe découpé sur une grille régulière",
      "une trame d'analyse de 2048 points fenêtrée par une cloche de Hann",
      "la partie d'un son comprise entre deux transitoires détectés",
    ],
    [
      "the segment between one rising zero crossing and the next",
      "a fixed-length grain cut on a regular grid",
      "a 2048-point analysis frame windowed by a Hann bell",
      "the part of a sound between two detected transients",
    ],
    "Un passage par zéro sur deux, de sorte que chaque waveset contienne une alternance complète — un lobe positif puis un lobe négatif, soit une pseudo-période. C'est ce qui le distingue d'un grain : il ÉPOUSE la forme d'onde au lieu de la couper, et le répéter fait descendre la hauteur sans changer la durée.",
    "Every other zero crossing, so that each waveset holds a complete alternation — a positive lobe then a negative one, that is, a pseudo-period. That is what distinguishes it from a grain: it FOLLOWS the waveform instead of cutting it, and repeating it lowers the pitch without changing the duration.", 2),
  notion("formant",
    "Ce qui distingue un « A » d'un « I », c'est :",
    "What tells an « A » from an « I » is:",
    [
      "la position des formants, qui ne dépend pas de la hauteur chantée",
      "la fréquence fondamentale de la voix",
      "la durée d'attaque du son",
      "le nombre de passages par zéro par seconde",
    ],
    [
      "the position of the formants, which does not depend on the pitch sung",
      "the fundamental frequency of the voice",
      "the attack time of the sound",
      "the number of zero crossings per second",
    ],
    "Le conduit vocal est un tuyau dont la langue et les lèvres changent la géométrie, et cette géométrie place trois ou quatre bosses dans le spectre. C'est pourquoi la même voyelle se reconnaît chantée grave ou aiguë — et pourquoi transposer un échantillon de voix donne l'effet « Chipmunk » : les formants sont emportés avec la note.",
    "The vocal tract is a tube whose geometry tongue and lips change, and that geometry places three or four bumps in the spectrum. That is why the same vowel is recognisable sung low or high — and why transposing a voice sample gives the « Chipmunk » effect: the formants are carried along with the note."),
  notion("centroide",
    "Que mesure le centroïde spectral ?",
    "What does the spectral centroid measure?",
    [
      "le centre de gravité du spectre, qui s'entend comme la brillance",
      "la fréquence fondamentale de la note jouée",
      "la fréquence en dessous de laquelle se trouve 85 % de l'énergie",
      "l'écart-type des amplitudes du spectre",
    ],
    [
      "the spectrum's centre of gravity, which is heard as brightness",
      "the fundamental frequency of the note played",
      "the frequency below which 85 % of the energy lies",
      "the standard deviation of the spectrum's amplitudes",
    ],
    "Mesuré dans l'application : un sinus de 440 Hz donne un centroïde de 440 Hz, une scie de 2093 Hz un centroïde de 9343 Hz — la mesure sépare bien le sourd du brillant. La troisième proposition décrit le ROLLOFF, qui est une autre mesure et un autre nœud.",
    "Measured in the application: a 440 Hz sine gives a centroid of 440 Hz, a 2093 Hz sawtooth a centroid of 9343 Hz — the measure does separate dull from bright. The third option describes the ROLLOFF, which is another measure and another node."),
  notion("cepstre",
    "Qu'est-ce que le cepstre ?",
    "What is the cepstrum?",
    [
      "une transformée du logarithme du spectre, qui sépare l'enveloppe de la structure fine",
      "le spectre du spectre, calculé sans logarithme",
      "la moyenne des spectres de toutes les trames d'un son",
      "le spectre d'un son dont la phase a été mise à zéro",
    ],
    [
      "a transform of the logarithm of the spectrum, which separates the envelope from the fine structure",
      "the spectrum of the spectrum, computed without a logarithm",
      "the average of the spectra of all a sound's frames",
      "the spectrum of a sound whose phase has been zeroed",
    ],
    "Le logarithme est ce qui fait tout : il transforme le PRODUIT de la source et du filtre en une SOMME, que la transformée suivante sépare enfin. Les coefficients bas décrivent l'enveloppe — donc le timbre —, les hauts la périodicité, donc la hauteur. C'est de là que viennent les MFCC.",
    "The logarithm is what does everything: it turns the PRODUCT of source and filter into a SUM, which the following transform can at last separate. Low coefficients describe the envelope — hence timbre —, high ones the periodicity, hence pitch. This is where MFCCs come from.", 2),
  notion("chroma",
    "Que donne un chromagramme ?",
    "What does a chromagram give?",
    [
      "l'énergie de chacune des douze classes de hauteur, toutes octaves confondues",
      "la suite des notes jouées, avec leur durée",
      "la couleur dominante associée à chaque instant du son",
      "l'énergie de chaque bande critique de l'oreille",
    ],
    [
      "the energy of each of the twelve pitch classes, all octaves merged",
      "the sequence of notes played, with their durations",
      "the dominant colour associated with each instant of the sound",
      "the energy of each critical band of the ear",
    ],
    "Replier les octaves est exactement ce qui le rend utile : la tonalité d'un morceau ne dépend pas du registre où les notes sont jouées. Douze des quarante caractéristiques d'une piste sont son chroma.",
    "Folding the octaves is precisely what makes it useful: a piece's key does not depend on the register in which the notes are played. Twelve of a track's forty features are its chroma."),
  notion("griffin-lim",
    "À quoi sert l'algorithme de Griffin-Lim ?",
    "What is the Griffin-Lim algorithm for?",
    [
      "à retrouver une phase plausible à partir d'un spectre d'amplitudes seul",
      "à aligner deux interprétations d'un même morceau",
      "à séparer les parties harmonique et percussive d'un son",
      "à estimer le tempo d'un enregistrement",
    ],
    [
      "to recover a plausible phase from a magnitude spectrum alone",
      "to align two performances of the same piece",
      "to separate a sound's harmonic and percussive parts",
      "to estimate the tempo of a recording",
    ],
    "Un spectrogramme d'amplitudes ne suffit pas à refaire un son : il manque la phase. Griffin-Lim la cherche par allers-retours entre les deux domaines, cent fois s'il faut. PGHI fait mieux en une passe, en intégrant le gradient de phase depuis les régions les plus fortes.",
    "A magnitude spectrogram is not enough to remake a sound: the phase is missing. Griffin-Lim looks for it by going back and forth between the two domains, a hundred times if need be. PGHI does better in a single pass, by integrating the phase gradient from the strongest regions.", 2),
  notion("hpss-geometrie",
    "Dans un spectrogramme, une note tenue dessine :",
    "In a spectrogram, a held note draws:",
    [
      "une ligne horizontale, là où une frappe dessine une ligne verticale",
      "une ligne verticale, là où une frappe dessine une ligne horizontale",
      "une tache diagonale montante",
      "un nuage sans forme repérable",
    ],
    [
      "a horizontal line, where a hit draws a vertical one",
      "a vertical line, where a hit draws a horizontal one",
      "a rising diagonal patch",
      "a cloud with no recognisable shape",
    ],
    "C'est toute l'astuce de la séparation harmonique/percussive : un filtre médian horizontal garde les notes tenues, un filtre médian vertical garde les frappes. Deux lignes de code plutôt qu'un réseau de neurones (Fitzgerald, DAFx-10).",
    "This is the whole trick of harmonic/percussive separation: a horizontal median filter keeps held notes, a vertical median filter keeps hits. Two lines of code rather than a neural network (Fitzgerald, DAFx-10)."),
  notion("paulstretch",
    "Ce qui permet à Paulstretch d'étirer un son cinquante fois sans qu'on entende un hachage :",
    "What lets Paulstretch stretch a sound fifty times without any chopping being heard:",
    [
      "les phases de chaque trame sont retirées au hasard",
      "les trames sont ré-échantillonnées par interpolation cubique",
      "un filtre passe-bas suit la durée d'étirement",
      "les transitoires sont détectés puis réinjectés à l'identique",
    ],
    [
      "each frame's phases are drawn at random",
      "frames are resampled by cubic interpolation",
      "a low-pass filter follows the stretch factor",
      "transients are detected then reinjected unchanged",
    ],
    "Répéter une trame à l'identique fabrique une périodicité que l'oreille entend aussitôt comme un bourdonnement. Randomiser les phases garde le spectre — donc le timbre — et détruit la périodicité : ce qui reste est une nappe, et c'est l'effet cherché.",
    "Repeating a frame unchanged manufactures a periodicity the ear hears at once as a buzz. Randomising the phases keeps the spectrum — hence the timbre — and destroys the periodicity: what remains is a pad, and that is the sought effect.", 2),
  notion("aliasing",
    "Que devient une fréquence synthétisée au-dessus de la limite de Nyquist ?",
    "What becomes of a frequency synthesized above the Nyquist limit?",
    [
      "elle se replie et s'entend plus bas, à une fréquence qui n'a rien à voir",
      "elle est simplement inaudible et sans conséquence",
      "elle sature et produit de la distorsion harmonique",
      "elle est transposée à l'octave inférieure, donc juste",
    ],
    [
      "it folds back and is heard lower, at a frequency unrelated to it",
      "it is simply inaudible and harmless",
      "it clips and produces harmonic distortion",
      "it is transposed one octave down, and therefore in tune",
    ],
    "Le repliement de spectre : au-delà de la moitié de la fréquence d'échantillonnage, une sinusoïde est indiscernable d'une autre, plus basse. C'est pourquoi une onde en dents de scie calculée naïvement sonne faux dans l'aigu — ses harmoniques dépassent la limite et retombent n'importe où.",
    "Spectral folding: beyond half the sample rate, a sinusoid is indistinguishable from another, lower one. That is why a naively computed sawtooth sounds out of tune in the treble — its harmonics pass the limit and fall back anywhere."),
  notion("ducking",
    "Ce qui distingue le ducking d'un compresseur :",
    "What distinguishes ducking from a compressor:",
    [
      "il écoute un AUTRE signal que celui qu'il traite",
      "il agit sur les graves seulement",
      "il monte le niveau au lieu de le baisser",
      "il travaille sur le spectre au lieu du temps",
    ],
    [
      "it listens to ANOTHER signal than the one it processes",
      "it acts on the bass only",
      "it raises the level instead of lowering it",
      "it works on the spectrum rather than on time",
    ],
    "Un compresseur, un limiteur, une porte écoutent tous le signal qu'ils traitent : aucun ne sait baisser la musique quand la voix parle. Mesuré dans le nœud « Ducking » sur une cible d'énergie CONSTANTE — donc qu'aucun compresseur ne toucherait : elle creuse à 0,035 là où le déclencheur parle et remonte à 0,346 entre les phrases.",
    "A compressor, a limiter, a gate all listen to the signal they process: none can lower the music when the voice speaks. Measured in the « Ducking » node on a target of CONSTANT energy — which no compressor would touch: it dips to 0.035 where the trigger speaks and returns to 0.346 between phrases."),
];

// LA BANQUE EST LA CONCATENATION DES DEUX MOITIES, dans l'ordre d'origine : voir `notions-suite.ts`.
export const NOTIONS: Question[] = [...NOTIONS_PREMIERES, ...NOTIONS_SUITE];
