// quiz/sigles.ts — Les sigles qu'Attic emploie, et ce qu'ils cachent.
//
// LA LISTE N'EST PAS UNE LISTE DE CULTURE GÉNÉRALE AUDIO : chaque sigle interrogé ici est un
// sigle que le logiciel écrit quelque part — dans une notice, sur un port, dans un nom de nœud.
// Un test le vérifie contre l'inventaire que tient déjà `docs/style-documentation.test.ts`, qui
// est la liste des sigles autorisés dans la documentation. Le quiz ne peut donc pas dériver vers
// des sigles qu'Attic n'utilise pas, et il ne peut pas non plus rester en retard sur lui.
//
// LES PROPOSITIONS NE SONT PAS TRADUITES, et c'est délibéré : le développement d'un sigle anglais
// est sa forme, pas son sens. « Head-Related Transfer Function » s'apprend tel quel, et le
// traduire dans la version française du quiz aurait appris un mot qui n'existe nulle part.
//
// LES LEURRES SONT PLAUSIBLES, jamais comiques. Un leurre absurde laisse trouver la réponse sans
// rien savoir, ce qui vide la question ; les leurres écrits ici sont des développements que
// quelqu'un pourrait donner de bonne foi — « Short-Term Frequency Transform » pour STFT, par
// exemple, qui inverse exactement les deux mots qui comptent.

import type { Question } from "./types";

/** Une question de sigle : la bonne réponse, trois leurres, et ce qu'il faut en retenir. */
const sigle = (
  s: string, bonne: string, leurres: [string, string, string],
  pourquoi: string, pourquoiEn: string, niveau: 1 | 2 = 1,
): Question => ({
  id: `sigle-${s.toLowerCase().replace(/[^a-z0-9]/g, "")}`,
  theme: "sigles", niveau,
  enonce: `Que signifie le sigle « ${s} » ?`,
  enonceEn: `What does the acronym « ${s} » stand for?`,
  choix: [bonne, ...leurres],
  pourquoi, pourquoiEn,
});

export const SIGLES: Question[] = [
  sigle("FFT", "Fast Fourier Transform",
    ["Full Frequency Transform", "Filtered Fourier Transform", "Fast Frequency Tracking"],
    "L'algorithme de Cooley et Tukey (1965) calcule la transformée de Fourier discrète en N·log₂(N) opérations au lieu de N². Sur une fenêtre de 2048 points, c'est vingt-deux mille multiplications au lieu de quatre millions — sans quoi aucune analyse spectrale en temps réel ne serait possible.",
    "Cooley and Tukey's algorithm (1965) computes the discrete Fourier transform in N·log2(N) operations instead of N squared. On a 2048-point window that is twenty-two thousand multiplications instead of four million — without which no real-time spectral analysis would be possible."),
  sigle("IFFT", "Inverse Fast Fourier Transform",
    ["Integrated Fast Fourier Transform", "Infinite Frequency Filter Transform", "Iterative Fourier Frequency Transform"],
    "Le chemin du retour : d'un spectre vers un signal. Tout ce qui, dans Attic, modifie un son « dans le spectre » — traçage, flou, gel, masquage, vocodeur de phase — fait le même aller-retour : FFT, transformation, IFFT.",
    "The way back: from a spectrum to a signal. Everything in Attic that alters a sound « in the spectrum » — tracing, blur, freeze, masking, phase vocoder — makes the same round trip: FFT, transformation, IFFT."),
  sigle("STFT", "Short-Time Fourier Transform",
    ["Short-Term Frequency Transform", "Spectral Transform of Fourier Type", "Sliding Tone Frequency Transform"],
    "Une FFT par tranche de temps, et non une seule sur tout le son : c'est ce qui permet de voir le spectre CHANGER. Le prix en est le compromis fondamental de l'analyse — une fenêtre longue situe bien les fréquences et mal les instants, une fenêtre courte l'inverse.",
    "One FFT per slice of time rather than a single one over the whole sound: that is what lets the spectrum be seen CHANGING. The price is analysis's fundamental trade-off — a long window locates frequencies well and instants badly, a short one the reverse.", 2),
  sigle("DSP", "Digital Signal Processing",
    ["Digital Sound Production", "Direct Signal Path", "Dynamic Spectral Processing"],
    "Le traitement numérique du signal : tout ce qui se calcule sur des échantillons plutôt que sur une tension. Attic est un atelier de DSP à interface graphique — chaque nœud est un traitement, chaque arête un signal.",
    "Digital signal processing: everything computed on samples rather than on a voltage. Attic is a DSP workshop with a graphical interface — each node is a process, each edge a signal."),
  sigle("MFCC", "Mel-Frequency Cepstral Coefficients",
    ["Multi-Frequency Correlation Coefficients", "Mel-Filtered Chroma Components", "Mean Frequency Cepstral Contour"],
    "La description du TIMBRE la plus employée en apprentissage automatique : le spectre est replié sur l'échelle mel, passé au logarithme, puis décorrélé par une transformée en cosinus. Attic en garde treize, dont il donne moyenne et variance — vingt-six des quarante caractéristiques d'une piste.",
    "The most widely used description of TIMBRE in machine learning: the spectrum is folded onto the mel scale, passed through a logarithm, then decorrelated by a cosine transform. Attic keeps thirteen of them, reporting mean and variance — twenty-six of a track's forty features.", 2),
  sigle("ZCR", "Zero-Crossing Rate",
    ["Zero Compression Ratio", "Zonal Correlation Rate", "Zero-Crossing Resolution"],
    "Le nombre de fois par seconde où le signal change de signe. Mesure grossière et presque gratuite de la brillance : un sinus grave en compte deux par période, un bruit blanc des milliers. C'est aussi ce qui découpe les wavesets de Wishart.",
    "How many times per second the signal changes sign. A coarse and almost free measure of brightness: a low sine crosses twice per period, white noise thousands of times. It is also what cuts Wishart's wavesets."),
  sigle("RMS", "Root Mean Square",
    ["Relative Maximum Scale", "Running Mean Signal", "Root Modulation Spectrum"],
    "La racine de la moyenne des carrés : la mesure d'énergie qui correspond à ce qu'on entend, là où le maximum d'un signal ne dit rien de sa force perçue. Un son peut culminer à 0 dB et rester discret si son RMS est bas.",
    "The square root of the mean of the squares: the energy measure that matches what is heard, where a signal's peak says nothing about its perceived strength. A sound can peak at 0 dB and stay discreet if its RMS is low."),
  sigle("LUFS", "Loudness Units relative to Full Scale",
    ["Level Units of Full Signal", "Loudness Unit Frequency Scale", "Linear Units for Sound"],
    "L'unité de sonie des normes de diffusion (ITU-R BS.1770). Elle diffère du RMS par deux choses : une pondération fréquentielle qui suit la sensibilité de l'oreille, et une porte qui écarte les silences — sans quoi un morceau très aéré serait déclaré plus faible qu'il ne s'entend.",
    "The loudness unit of broadcast standards (ITU-R BS.1770). It differs from RMS in two ways: a frequency weighting that follows the ear's sensitivity, and a gate that discards silences — without which a very airy piece would be declared quieter than it sounds.", 2),
  sigle("LRA", "Loudness Range",
    ["Level Ratio Average", "Loudness Reduction Amount", "Left-Right Attenuation"],
    "L'étendue de sonie d'un programme : la différence entre ses passages forts et ses passages faibles, mesurée en unités de sonie. Un LRA très faible est la signature d'un mastering écrasé.",
    "A programme's loudness range: the difference between its loud and quiet passages, measured in loudness units. A very low LRA is the signature of a crushed master.", 2),
  sigle("ADSR", "Attack, Decay, Sustain, Release",
    ["Attack, Delay, Sustain, Resonance", "Amplitude, Duration, Slope, Ratio", "Attack, Decay, Silence, Repeat"],
    "Les quatre segments de l'enveloppe des synthétiseurs, et la plus vieille abstraction du métier. Attention au piège : les trois premiers sont des DURÉES, mais « Sustain » est un NIVEAU — celui auquel le son se tient tant que la touche est enfoncée.",
    "The four segments of the synthesizer envelope, and the oldest abstraction in the craft. Beware the trap: the first three are DURATIONS, but « Sustain » is a LEVEL — the one the sound holds while the key is down."),
  sigle("LFO", "Low-Frequency Oscillator",
    ["Linear Filter Oscillator", "Local Frequency Offset", "Looped Frequency Operator"],
    "Un oscillateur assez lent pour ne pas s'entendre comme un son, mais pour faire bouger un réglage : la hauteur, et c'est un vibrato ; le volume, un trémolo ; la coupure d'un filtre, un wah-wah. La même mécanique, trois effets distincts au catalogue.",
    "An oscillator slow enough not to be heard as a sound, but to make a control move: pitch, and it is a vibrato; volume, a tremolo; a filter's cutoff, a wah-wah. The same mechanism, three distinct effects in the catalogue."),
  sigle("HRTF", "Head-Related Transfer Function",
    ["High-Resolution Transfer Filter", "Head Rotation Tracking Function", "Harmonic Resonance Transfer Function"],
    "Le filtrage que votre tête, vos épaules et le pli de vos oreilles font subir à un son selon sa direction. C'est ce filtrage, et non un simple réglage de balance, qui permet d'entendre au casque qu'un son vient de derrière ou d'en haut.",
    "The filtering that your head, shoulders and the folds of your ears apply to a sound according to its direction. It is that filtering, not a mere balance control, that makes a sound audibly come from behind or above on headphones."),
  sigle("IR", "Impulse Response",
    ["Infinite Reverberation", "Internal Resonance", "Immediate Response"],
    "La réponse d'un lieu — ou d'un appareil — à un claquement infiniment bref. Elle le décrit entièrement s'il est linéaire : convoluer un son avec l'IR d'une cathédrale, c'est le jouer dans la cathédrale. C'est le principe de la réverbération à convolution.",
    "The response of a place — or a device — to an infinitely brief click. It describes it completely if it is linear: convolving a sound with a cathedral's IR is playing it in the cathedral. That is the principle of convolution reverb."),
  sigle("RT60", "Reverberation Time to −60 dB",
    ["Room Tone at 60 Hz", "Reverberation Tail of 60 frames", "Real-Time 60 ms window"],
    "Le temps que met la réverbération d'un lieu à perdre soixante décibels, c'est-à-dire à devenir mille fois plus faible. Deux secondes pour une église, un tiers de seconde pour un studio traité.",
    "The time a room's reverberation takes to lose sixty decibels, that is, to become a thousand times weaker. Two seconds for a church, a third of a second for a treated studio."),
  sigle("FDN", "Feedback Delay Network",
    ["Frequency Domain Noise", "Filtered Diffusion Network", "Full Dynamic Normalization"],
    "Un réseau de retards rebouclés par une matrice de mélange : la façon la plus économique de fabriquer une réverbération dense qui ne sonne pas comme un écho. Jot et Chaigne (AES, 1991) ont montré comment y régler le temps de décroissance fréquence par fréquence.",
    "A network of delays fed back through a mixing matrix: the cheapest way to build a dense reverberation that does not sound like an echo. Jot and Chaigne (AES, 1991) showed how to set its decay time frequency by frequency there.", 2),
  sigle("FIR", "Finite Impulse Response",
    ["Fixed Interval Resampling", "Filtered Input Response", "Frequency Independent Rolloff"],
    "Un filtre dont la réponse s'éteint après un nombre fini d'échantillons, parce qu'il ne se reboucle pas sur sa propre sortie. Toujours stable, phase contrôlable — mais coûteux : une pente raide demande des milliers de coefficients.",
    "A filter whose response dies out after a finite number of samples, because it does not feed back on its own output. Always stable, phase controllable — but costly: a steep slope needs thousands of coefficients.", 2),
  sigle("IIR", "Infinite Impulse Response",
    ["Iterative Impulse Reduction", "Internal Interpolated Resonator", "Inverse Impulse Response"],
    "Un filtre qui réinjecte sa sortie : sa réponse ne s'arrête jamais tout à fait. Quelques coefficients suffisent là où un FIR en demanderait mille, mais il peut devenir instable et sa phase n'est pas libre. Ce sont les filtres des égaliseurs.",
    "A filter that reinjects its output: its response never quite stops. A handful of coefficients do what a FIR would need a thousand for, but it can become unstable and its phase is not free. These are the filters in equalizers.", 2),
  sigle("PGHI", "Phase Gradient Heap Integration",
    ["Phase Gradient Harmonic Interpolation", "Partial Group Handling and Integration", "Progressive Global Harmonic Inversion"],
    "La reconstruction de phase de Průša, Balazs et Søndergaard (2017) : la phase est intégrée depuis les régions les plus énergiques vers les plus faibles, en suivant le gradient, l'ordre étant donné par un tas. Elle fait en une passe ce que Griffin-Lim cherche en cent itérations.",
    "The phase reconstruction of Prusa, Balazs and Sondergaard (2017): phase is integrated from the most energetic regions towards the weakest, following the gradient, the order being given by a heap. It does in one pass what Griffin-Lim looks for in a hundred iterations.", 2),
  sigle("HPSS", "Harmonic/Percussive Source Separation",
    ["High-Pass Spectral Subtraction", "Harmonic Phase Spectrum Synthesis", "Hybrid Peak and Sustain Separation"],
    "La séparation qui repose sur une observation de géométrie : dans un spectrogramme, une note tenue fait une ligne HORIZONTALE et une frappe une ligne VERTICALE. Un filtre médian dans chaque direction suffit donc à les séparer (Fitzgerald, DAFx-10).",
    "The separation that rests on a geometric observation: in a spectrogram a held note draws a HORIZONTAL line and a hit a VERTICAL one. A median filter in each direction is therefore enough to separate them (Fitzgerald, DAFx-10).", 2),
  sigle("STN", "Sines, Transients and Noise",
    ["Spectral Time Normalization", "Short-Term Noise", "Sinusoidal Tracking Network"],
    "La décomposition en trois parties plutôt que deux : les sinusoïdes tenues, les transitoires, et ce qui n'est ni l'un ni l'autre. Fierro et Välimäki l'obtiennent par deux passes de séparation harmonique/percussive à des résolutions différentes — un transitoire est vertical à fenêtre longue, un bruit ne l'est à aucune.",
    "The decomposition into three parts rather than two: held sinusoids, transients, and what is neither. Fierro and Valimaki obtain it with two harmonic/percussive passes at different resolutions — a transient is vertical at a long window, noise is vertical at none.", 2),
  sigle("CQT", "Constant-Q Transform",
    ["Continuous Quadrature Transform", "Cepstral Quantization Transform", "Correlated Quality Transform"],
    "Une analyse dont les bandes sont espacées géométriquement, à qualité constante : chaque demi-ton reçoit la même largeur relative. C'est la bonne analyse pour la MUSIQUE, là où la FFT, aux bandes régulières, donne cinq points pour la première octave et six cents pour la dernière.",
    "An analysis whose bands are geometrically spaced, at constant quality: each semitone gets the same relative width. It is the right analysis for MUSIC, where the FFT, with its regular bands, gives five points to the first octave and six hundred to the last.", 2),
  sigle("NSGT", "Non-Stationary Gabor Transform",
    ["Noise-Suppressing Gain Transform", "Normalized Spectral Gain Threshold", "Non-Symmetric Global Transform"],
    "Une transformée dont la fenêtre change au fil de l'analyse, tout en restant inversible exactement. C'est ce qui permet d'avoir une résolution fine dans le grave et rapide dans l'aigu sans renoncer à reconstruire le son.",
    "A transform whose window changes along the analysis while remaining exactly invertible. That is what allows fine resolution in the bass and fast resolution in the treble without giving up reconstructing the sound.", 2),
  sigle("EMD", "Empirical Mode Decomposition",
    ["Envelope Modulation Detection", "Extended Modal Decomposition", "Energy Minimization Descent"],
    "Une décomposition sans base fixée d'avance : on extrait la modulation la plus rapide du signal, on la retire, et on recommence sur le reste. Contrairement à Fourier, elle ne suppose ni sinusoïdes ni stationnarité.",
    "A decomposition with no basis fixed in advance: the signal's fastest modulation is extracted, removed, and the process starts again on the remainder. Unlike Fourier, it assumes neither sinusoids nor stationarity.", 2),
  sigle("LPC", "Linear Predictive Coding",
    ["Low-Pass Comb filtering", "Linear Phase Correction", "Level Peak Compression"],
    "Prédire chaque échantillon comme une combinaison linéaire des précédents : les coefficients décrivent alors le conduit vocal, et l'erreur de prédiction la source. C'est la séparation source/filtre, et le fondement du vocodeur et de la synthèse de parole.",
    "Predicting each sample as a linear combination of the previous ones: the coefficients then describe the vocal tract, and the prediction error the source. This is the source/filter split, and the foundation of the vocoder and of speech synthesis.", 2),
  sigle("FOF", "Fonction d'Onde Formantique",
    ["Frequency Oscillator Filter", "Formant Oscillation Function", "Filtered Overlapping Formants"],
    "Le procédé de Xavier Rodet (IRCAM, programme chant, 1984) : au lieu de filtrer une source, on additionne les réponses impulsionnelles des formants, redéclenchées à chaque période. Une voyelle chantée dont les formants ne bougent pas quand la note monte — c'est-à-dire pas d'effet « Chipmunk ».",
    "Xavier Rodet's method (IRCAM, chant program, 1984): instead of filtering a source, the formants' impulse responses are added, retriggered at every period. A sung vowel whose formants do not move when the note rises — that is, no « Chipmunk » effect.", 2),
  sigle("SSB", "Single-SideBand modulation",
    ["Sub-Sonic Band", "Sampled Signal Buffer", "Spectral Splitting Bandwidth"],
    "La modulation qui ne garde qu'un côté du spectre produit. C'est ce qui distingue le décaleur de fréquence du transposeur : décaler ajoute le même nombre de hertz à tous les partiels, ce qui détruit l'harmonicité, là où transposer les multiplie.",
    "The modulation that keeps only one side of the spectrum produced. It is what distinguishes a frequency shifter from a pitch shifter: shifting adds the same number of hertz to every partial, destroying harmonicity, where transposing multiplies them.", 2),
  sigle("PLL", "Phase-Locked Loop",
    ["Peak Level Limiter", "Phase Linear Latency", "Partial Loop Lock"],
    "Une boucle qui asservit un oscillateur à la phase d'un signal d'entrée. Elle sert à se caler sur une pulsation ou une fréquence porteuse, et à la suivre quand elle dérive.",
    "A loop that slaves an oscillator to the phase of an input signal. It serves to lock onto a pulse or a carrier frequency, and to follow it as it drifts.", 2),
  sigle("THD", "Total Harmonic Distortion",
    ["Time-Held Delay", "Threshold of Harmonic Detection", "Transient High-frequency Damping"],
    "La part d'énergie qu'un appareil ajoute aux multiples de la fréquence d'entrée. Un chiffre qu'on cherche à baisser dans un amplificateur — et à monter dans une saturation à bande, où c'est précisément l'effet recherché.",
    "The share of energy a device adds at multiples of the input frequency. A figure to be lowered in an amplifier — and raised in tape saturation, where it is precisely the desired effect."),
  sigle("SNR", "Signal-to-Noise Ratio",
    ["Spectral Noise Reduction", "Sampled Noise Rejection", "Signal Normalization Ratio"],
    "Le rapport entre ce qu'on veut entendre et ce qu'on ne veut pas, en décibels. C'est la mesure par laquelle se juge un débruiteur : elle dit ce qu'il a gagné, mais pas ce qu'il a abîmé au passage.",
    "The ratio between what one wants to hear and what one does not, in decibels. It is the measure by which a denoiser is judged: it says what was gained, but not what was damaged along the way."),
  sigle("PWM", "Pulse-Width Modulation",
    ["Peak Weighted Mixing", "Phase Width Multiplier", "Partial Wave Modulation"],
    "Faire varier la largeur du créneau d'une onde carrée. Le spectre change sans que la hauteur bouge : c'est le son épais et mouvant des synthétiseurs analogiques, et il ne demande qu'un seul oscillateur.",
    "Varying the width of a square wave's pulse. The spectrum changes without the pitch moving: this is the thick, shifting sound of analogue synthesizers, and it needs only one oscillator."),
  sigle("CV", "Control Voltage",
    ["Carrier Vibrato", "Channel Volume", "Curve Value"],
    "La tension de commande des synthétiseurs modulaires, où un même câble peut porter un son ou un réglage. Les entrées « Modulation » d'Attic en sont l'héritage direct : un signal de contrôle y branche comme un signal audio.",
    "The control voltage of modular synthesizers, where one and the same cable can carry a sound or a control. Attic's « Modulation » inputs are its direct heir: a control signal plugs in there like an audio signal."),
  sigle("OSC", "Open Sound Control",
    ["Oscillator Sync Clock", "Ordered Signal Chain", "Output Sample Counter"],
    "Le protocole réseau qui succède au MIDI pour la commande d'instruments : des adresses en forme de chemin, des nombres à virgule, et pas de limite à sept bits.",
    "The network protocol that succeeds MIDI for instrument control: path-shaped addresses, floating-point numbers, and no seven-bit limit.", 2),
  sigle("MIDI", "Musical Instrument Digital Interface",
    ["Music Instrument Data Input", "Modular Instrument Digital Interconnect", "Multi-Instrument Direct Interface"],
    "La norme de 1983 qui transporte des GESTES et non du son : quelle note, quand, avec quelle force. C'est pourquoi un fichier MIDI ne porte pas de volume mais des vélocités, et pourquoi il ne connaît que des demi-tons — ce qui interdit d'y écrire un maqam.",
    "The 1983 standard that carries GESTURES rather than sound: which note, when, how hard. That is why a MIDI file has no volume but velocities, and why it knows only semitones — which makes it impossible to write a maqam in it."),
  sigle("GM", "General MIDI",
    ["Global Mixing", "Generated Music", "Grouped Modulation"],
    "La convention qui fixe quel numéro de programme correspond à quel instrument, et quel numéro de note à quelle percussion. Sans elle, un fichier MIDI sonnerait différemment sur chaque machine. C'est elle qui donne 36 pour la grosse caisse et 38 pour la caisse claire.",
    "The convention that fixes which program number means which instrument, and which note number which drum. Without it a MIDI file would sound different on every machine. It is what gives 36 for the kick and 38 for the snare."),
  sigle("DAW", "Digital Audio Workstation",
    ["Direct Audio Writer", "Dynamic Audio Waveform", "Digital Amplitude Window"],
    "Le logiciel de studio organisé en pistes et en temps. Attic n'en est pas un : il s'organise en graphe de traitements, ce qui convient à la fabrication d'un son et non à l'assemblage d'un morceau.",
    "The studio software organised in tracks and time. Attic is not one: it is organised as a graph of processes, which suits making a sound rather than assembling a piece."),
  sigle("VST", "Virtual Studio Technology",
    ["Variable Sound Transform", "Virtual Sound Toolkit", "Vector Synthesis Table"],
    "Le format de greffons de Steinberg, celui qui a fait du studio un logiciel. Attic n'en héberge pas : ses nœuds sont ses greffons, et son format d'échange est un .zip de nœud.",
    "Steinberg's plug-in format, the one that turned the studio into software. Attic does not host any: its nodes are its plug-ins, and its exchange format is a node .zip."),
  sigle("IPA", "International Phonetic Alphabet",
    ["Instrument Performance Analysis", "Integrated Pitch Adjustment", "Inter-Phoneme Alignment"],
    "L'alphabet qui note un son de parole indépendamment de l'orthographe. C'est ce qui permet à une synthèse vocale de dire un mot étranger, et de chanter une voyelle qu'aucune lettre française n'écrit.",
    "The alphabet that writes a speech sound independently of spelling. It is what lets a speech synthesizer say a foreign word, and sing a vowel that no French letter writes."),
  sigle("TTS", "Text-To-Speech",
    ["Time-To-Sample", "Tone Tracking System", "Transient Time Stretch"],
    "La synthèse de parole à partir d'un texte écrit. Attic en embarque plusieurs, dont le choix ne tient pas qu'à la qualité : une voix locale tourne sans réseau, et c'est souvent ce qui décide.",
    "Speech synthesis from written text. Attic embeds several, and the choice does not rest on quality alone: a local voice runs without a network, and that is often what decides."),
  sigle("ASR", "Automatic Speech Recognition",
    ["Adaptive Signal Reduction", "Audio Sample Rate", "Automatic Sound Restoration"],
    "La reconnaissance de la parole : le chemin inverse de la synthèse. Le sigle STT — Speech-To-Text — désigne la même chose du point de vue de l'application.",
    "Speech recognition: the reverse road from synthesis. The acronym STT — speech-to-text — names the same thing from the application's point of view."),
  sigle("VAD", "Voice Activity Detection",
    ["Variable Amplitude Decay", "Vocal Attack Duration", "Volume Automation Descriptor"],
    "Repérer où quelqu'un parle et où personne ne parle. C'est ce qui découpe un enregistrement en phrases, et ce qui évite de faire tourner une reconnaissance coûteuse sur du silence.",
    "Finding where someone speaks and where nobody does. It is what cuts a recording into phrases, and what avoids running a costly recognition over silence.", 2),
  sigle("ONNX", "Open Neural Network Exchange",
    ["Optimized Neural Network Executor", "Open Node Network Extension", "Ordered Neural Network Export"],
    "Le format de modèle qui permet d'exécuter un réseau entraîné ailleurs sans embarquer la bibliothèque qui l'a entraîné. C'est ce format qu'Attic embarque, et c'est ce qui rend ses modèles utilisables hors ligne.",
    "The model format that allows running a network trained elsewhere without embedding the library that trained it. That is the format Attic embeds, and what makes its models usable offline."),
  sigle("DDSP", "Differentiable Digital Signal Processing",
    ["Dynamic Digital Sound Processor", "Direct Digital Synthesis Path", "Discrete Domain Signal Prediction"],
    "Mettre un oscillateur et un filtre À L'INTÉRIEUR d'un réseau de neurones, de sorte que l'apprentissage règle des paramètres de synthèse plutôt que de fabriquer des échantillons. Le réseau apprend alors avec mille fois moins de données, parce que la physique du son ne lui est pas cachée.",
    "Putting an oscillator and a filter INSIDE a neural network, so that learning sets synthesis parameters rather than manufacturing samples. The network then learns from a thousand times less data, because the physics of sound is not hidden from it.", 2),
  sigle("VAE", "Variational Autoencoder",
    ["Vector Audio Encoder", "Variable Amplitude Estimator", "Vocal Attribute Extractor"],
    "Un auto-encodeur dont l'espace latent est contraint à être continu : deux points voisins y donnent deux sons voisins, ce qui rend l'interpolation possible. C'est ce qui permet de fondre un son dans un autre par le milieu de l'espace.",
    "An autoencoder whose latent space is constrained to be continuous: two neighbouring points there give two neighbouring sounds, which makes interpolation possible. That is what allows melting one sound into another through the middle of the space.", 2),
  sigle("GAN", "Generative Adversarial Network",
    ["Generalized Additive Network", "Gated Attention Network", "Global Audio Normalizer"],
    "Deux réseaux qui s'opposent : l'un fabrique, l'autre juge, et le premier s'améliore en trompant le second. C'est ce qui a produit les premiers vocodeurs neuronaux rapides.",
    "Two networks set against each other: one manufactures, the other judges, and the first improves by fooling the second. That is what produced the first fast neural vocoders.", 2),
  sigle("CNN", "Convolutional Neural Network",
    ["Cascaded Neural Network", "Centered Normalization Network", "Continuous Node Network"],
    "Un réseau qui applique les mêmes petits filtres partout dans l'image — ou dans le spectrogramme. C'est ce qui lui permet de reconnaître un motif où qu'il se trouve, et pourquoi il est l'outil des classificateurs de genre.",
    "A network that applies the same small filters everywhere in the image — or in the spectrogram. That is what lets it recognise a pattern wherever it sits, and why it is the tool of genre classifiers."),
  sigle("RNN", "Recurrent Neural Network",
    ["Random Node Network", "Reduced Noise Network", "Resonant Neural Network"],
    "Un réseau qui garde un état d'un pas de temps au suivant : il peut donc traiter une suite dont la longueur n'est pas fixée. C'est la famille dont LSTM et GRU sont les deux membres utiles.",
    "A network that keeps a state from one time step to the next: it can therefore process a sequence of unfixed length. It is the family of which LSTM and GRU are the two useful members."),
  sigle("LSTM", "Long Short-Term Memory",
    ["Linear Spectral Time Model", "Layered Sequence Transfer Method", "Local Short-Time Modulation"],
    "Le réseau récurrent muni de portes qui décident ce qu'il garde et ce qu'il oublie. Son nom dit exactement son objet : une mémoire à court terme, mais LONGUE — de quoi tenir une phrase musicale plutôt que deux notes.",
    "The recurrent network fitted with gates that decide what it keeps and what it forgets. Its name says exactly its purpose: a short-term memory, but a LONG one — enough to hold a musical phrase rather than two notes.", 2),
  sigle("GRU", "Gated Recurrent Unit",
    ["Global Recurrent Update", "Grouped Regression Unit", "Gaussian Recurrent Update"],
    "Une simplification du LSTM : deux portes au lieu de trois, pas de cellule séparée. Presque aussi efficace, sensiblement plus rapide — ce qui compte quand le modèle doit tourner sur un ordinateur personnel.",
    "A simplification of the LSTM: two gates instead of three, no separate cell. Almost as effective, appreciably faster — which matters when the model has to run on a personal computer.", 2),
  sigle("PCA", "Principal Component Analysis",
    ["Partial Correlation Analysis", "Periodic Component Averaging", "Pitch Class Analysis"],
    "La projection qui garde le plus de variance possible en peu de dimensions. Elle sert ici à ramener les quarante caractéristiques d'une piste à deux, pour voir une collection entière comme un nuage de points.",
    "The projection that keeps as much variance as possible in few dimensions. Here it serves to bring a track's forty features down to two, so that a whole collection can be seen as a cloud of points.", 2),
  sigle("ICA", "Independent Component Analysis",
    ["Inverse Correlation Analysis", "Integrated Channel Alignment", "Instantaneous Component Averaging"],
    "La séparation de mélanges par l'indépendance statistique des sources, et non par leur spectre. C'est la réponse classique au problème du cocktail : plusieurs voix, autant de micros.",
    "The separation of mixtures by the statistical independence of the sources rather than by their spectrum. It is the classic answer to the cocktail party problem: several voices, as many microphones.", 2),
  sigle("DTW", "Dynamic Time Warping",
    ["Discrete Tone Weighting", "Dual Track Windowing", "Dynamic Threshold Window"],
    "L'alignement de deux suites qui vont à des vitesses différentes, par une déformation du temps qui minimise l'écart total. C'est ce qui permet de faire correspondre deux interprétations d'un même morceau.",
    "The alignment of two sequences that run at different speeds, by a warping of time that minimises the total distance. It is what lets two performances of the same piece be matched up.", 2),
  sigle("GMM", "Gaussian Mixture Model",
    ["Global Mean Model", "Grouped Median Method", "Generalized Markov Model"],
    "Décrire une population comme une somme de gaussiennes. Contrairement aux k-moyennes, un point n'appartient pas à un groupe mais à chacun avec une probabilité — ce qui convient à des pistes qui tiennent de deux genres.",
    "Describing a population as a sum of Gaussians. Unlike k-means, a point does not belong to one cluster but to each with a probability — which suits tracks that partake of two genres.", 2),
  sigle("MSE", "Mean Squared Error",
    ["Maximum Signal Energy", "Mel Spectral Envelope", "Mean Spectral Estimate"],
    "La moyenne des carrés des écarts. Sa faiblesse en audio est instructive : deux sons de MSE identique peuvent s'entendre comme le jour et la nuit, parce qu'elle ignore tout du masquage et de la phase.",
    "The mean of the squared differences. Its weakness in audio is instructive: two sounds with the same MSE can sound like night and day, because it knows nothing of masking or phase."),
  sigle("IFS", "Iterated Function System",
    ["Integrated Filter Stage", "Inverse Fourier Series", "Incremental Frequency Shift"],
    "Un jeu de transformations affines appliquées au hasard, dont l'orbite dessine une figure auto-similaire — la fougère de Barnsley, le triangle de Sierpiński. Attic en tire une image ET un son.",
    "A set of affine transformations applied at random, whose orbit draws a self-similar figure — Barnsley's fern, Sierpinski's triangle. Attic draws an image AND a sound from it.", 2),
  sigle("WASM", "WebAssembly",
    ["Web Audio Sample Manager", "Windowed Adaptive Spectral Method", "Wave Assembly"],
    "Le format binaire qui fait tourner du code compilé à vitesse quasi native dans un navigateur. C'est ce qui permet d'embarquer ici des bibliothèques écrites en C — un moteur Csound, un décodeur — sans les réécrire.",
    "The binary format that runs compiled code at near-native speed in a browser. It is what allows embedding libraries written in C here — a Csound engine, a decoder — without rewriting them."),
  sigle("NRT", "Non-Real-Time",
    ["Normalized Response Time", "Node Runtime", "Noise Reduction Threshold"],
    "Le rendu hors temps réel : le calcul prend le temps qu'il faut, puisque personne n'écoute pendant. C'est le régime d'Attic, et c'est ce qui l'autorise à des traitements qu'aucun greffon de studio ne pourrait tenir.",
    "Rendering outside real time: the computation takes as long as it needs, since nobody is listening meanwhile. That is Attic's regime, and what allows it processes no studio plug-in could sustain.", 2),
  {
    id: "sigle-yin", theme: "sigles", niveau: 2,
    enonce: "« YIN », l'estimateur de fréquence fondamentale, est-il un sigle ?",
    enonceEn: "Is « YIN », the fundamental frequency estimator, an acronym?",
    choix: [
      "Non : le nom renvoie au yin et au yang, pour l'équilibre entre autocorrélation et annulation",
      "Oui : « Yearly Instantaneous Notation »",
      "Oui : « Yield Interpolated Note »",
      "Oui : « Y-axis Interval Navigator »",
    ],
    choixEn: [
      "No: the name refers to yin and yang, for the balance between autocorrelation and cancellation",
      "Yes: « Yearly Instantaneous Notation »",
      "Yes: « Yield Interpolated Note »",
      "Yes: « Y-axis Interval Navigator »",
    ],
    pourquoi: "De Cheveigné et Kawahara (JASA 111(4), 2002) ont nommé leur estimateur d'après le couple yin-yang : leur méthode équilibre deux vues complémentaires du même signal, l'autocorrélation et la fonction de différence qui l'annule. Attic en emploie la variante pYIN, qui garde plusieurs candidats par trame au lieu d'un seul.",
    pourquoiEn: "De Cheveigne and Kawahara (JASA 111(4), 2002) named their estimator after the yin-yang pair: their method balances two complementary views of the same signal, autocorrelation and the difference function that cancels it. Attic uses the pYIN variant, which keeps several candidates per frame instead of one.",
  },
];
