// quiz/sources.ts — Qui a trouvé quoi. Le thème le plus facile à vérifier, et le plus utile.
//
// POURQUOI CE THÈME EXISTE. Un nœud dont on connaît l'auteur et l'article est un nœud qu'on peut
// aller vérifier, discuter, étendre ; un nœud anonyme est une boîte qu'on croit ou qu'on ne croit
// pas. Les notices d'Attic citent presque toutes une source, et ce thème est la façon la plus
// directe de rendre ce travail utile à celui qui s'en sert : savoir que la séparation
// harmonique/percussive tient à un filtre médian de Fitzgerald, c'est savoir qu'on peut la relire.
//
// CHAQUE BONNE RÉPONSE EST CITÉE QUELQUE PART DANS LE DÉPÔT, et un test le vérifie : le quiz ne
// peut donc pas interroger sur une source qu'Attic n'emploie pas. Les LEURRES, eux, sont des
// auteurs RÉELS du domaine — certains cités ailleurs dans Attic, d'autres non. Un leurre inventé
// se repérerait sans rien savoir, et l'on n'apprendrait rien de l'écarter ; ici, se tromper revient
// à confondre deux travaux qui existent tous les deux, et l'explication dit alors ce que l'autre a
// fait. C'est pour cela que plusieurs d'entre elles nomment « le leurre juste ».
//
// LES NOMS NE SE TRADUISENT PAS. L'énoncé et l'explication, si.

import type { Question } from "./types";

const source = (
  id: string, enonce: string, enonceEn: string,
  choix: [string, string, string, string],
  pourquoi: string, pourquoiEn: string, niveau: 1 | 2 = 1,
): Question => ({
  id: `source-${id}`, theme: "sources", niveau, enonce, enonceEn, choix, pourquoi, pourquoiEn,
});

export const SOURCES: Question[] = [
  source("audible-design",
    "Qui a écrit « Audible Design » (1994), dont Attic tire ses transformations spectrales et ses wavesets ?",
    "Who wrote « Audible Design » (1994), from which Attic draws its spectral transformations and wavesets?",
    ["Trevor Wishart", "Curtis Roads", "Iannis Xenakis", "Denis Smalley"],
    "Le livre est un manuel de composition autant qu'un catalogue de procédés, et il vient avec les programmes du Composers Desktop Project — `spec trace`, `blur blur`, `blur freeze`, `brassage`, `envel extract`. Six nœuds d'Attic en descendent directement.",
    "The book is a composition manual as much as a catalogue of processes, and it comes with the Composers Desktop Project's programs — `spec trace`, `blur blur`, `blur freeze`, `brassage`, `envel extract`. Six of Attic's nodes descend directly from it."),
  source("velours",
    "Qui a étudié le bruit de velours et ses variantes, dont Attic tire son élargisseur ?",
    "Who studied velvet noise and its variants, from which Attic draws its widener?",
    ["Vesa Välimäki", "Jean-Marc Jot", "Manfred Schroeder", "Julius O. Smith"],
    "Välimäki, Lehtonen et Takanen, IEEE TASLP 21(7), 2013, pour l'étude perceptive ; Välimäki, Holm-Rasmussen, Alary et Lehtonen, Applied Sciences 7(5), 2017, pour la réverbération tardive. Schroeder est un leurre plausible : il a bien travaillé sur la réverbération, mais sur ses filtres en peigne et passe-tout.",
    "Valimaki, Lehtonen and Takanen, IEEE TASLP 21(7), 2013, for the perceptual study; Valimaki, Holm-Rasmussen, Alary and Lehtonen, Applied Sciences 7(5), 2017, for late reverberation. Schroeder is a plausible decoy: he did work on reverberation, but on its comb and allpass filters.", 2),
  source("dissonance-timbre",
    "Qui a montré que la gamme consonante dépend du spectre du timbre employé ?",
    "Who showed that the consonant scale depends on the spectrum of the timbre used?",
    ["William Sethares", "Hermann von Helmholtz", "Godfried Toussaint", "Eberhard Zwicker"],
    "« Local consonance and the relationship between timbre and scale », JASA 94(3), 1993, puis « Tuning, Timbre, Spectrum, Scale » (1998). Helmholtz est le leurre juste : il a fondé l'étude physique de la consonance, mais la thèse de la gamme qui SUIT le spectre — et donc des gammes non occidentales pour des timbres non harmoniques — est de Sethares.",
    "« Local consonance and the relationship between timbre and scale », JASA 94(3), 1993, then « Tuning, Timbre, Spectrum, Scale » (1998). Helmholtz is the fair decoy: he founded the physical study of consonance, but the thesis of the scale FOLLOWING the spectrum — hence non-Western scales for non-harmonic timbres — is Sethares's.", 2),
  source("bandes-critiques",
    "Qui a donné la subdivision de l'audible en bandes critiques ?",
    "Who gave the subdivision of the audible range into critical bands?",
    ["Eberhard Zwicker", "Reinier Plomp", "Manfred Schroeder", "Harvey Fletcher"],
    "« Subdivision of the Audible Frequency Range into Critical Bands », JASA 33, 1961 — d'où l'échelle des barks, qui porte le nom de Barkhausen. Fletcher est le leurre juste : les courbes d'isosonie sont de lui, et non les bandes critiques.",
    "« Subdivision of the Audible Frequency Range into Critical Bands », JASA 33, 1961 — hence the bark scale, named after Barkhausen. Fletcher is the fair decoy: the equal-loudness contours are his, not the critical bands.", 2),
  source("consonance-tonale",
    "Qui a relié la consonance tonale à la largeur de bande critique, en 1965 ?",
    "Who linked tonal consonance to critical bandwidth, in 1965?",
    ["Plomp & Levelt", "Zwicker & Fastl", "Schroeder & Atal", "Sethares & Smith"],
    "« Tonal Consonance and Critical Bandwidth », JASA 38(4), 1965 : deux sons battent tant qu'ils tombent dans la même bande critique, et c'est cette rugosité qui s'entend comme de la dissonance. Sethares est parti de leur courbe pour en tirer les gammes.",
    "« Tonal Consonance and Critical Bandwidth », JASA 38(4), 1965: two sounds beat as long as they fall in the same critical band, and it is that roughness that is heard as dissonance. Sethares started from their curve to derive scales.", 2),
  source("etalement",
    "Qui a donné la fonction d'étalement du masquage employée par les codeurs perceptifs ?",
    "Who gave the masking spreading function used by perceptual coders?",
    ["Schroeder, Atal & Hall", "Zwicker & Terhardt", "Moore & Glasberg", "Fletcher & Munson"],
    "« Optimizing digital speech coders by exploiting masking properties of the human ear », JASA 66, 1979. C'est l'article qui a rendu le masquage CALCULABLE, et ouvert la voie à tous les codeurs à perte — le MP3 compris.",
    "« Optimizing digital speech coders by exploiting masking properties of the human ear », JASA 66, 1979. It is the paper that made masking COMPUTABLE, and opened the way to every lossy coder — MP3 included.", 2),
  source("geometrie-accords",
    "Qui a montré que la conduite de voix minimale entre deux accords ne demande aucun croisement ?",
    "Who showed that minimal voice leading between two chords requires no crossing?",
    ["Dmitri Tymoczko", "Richard Cohn", "David Lewin", "Hugo Riemann"],
    "« The Geometry of Musical Chords », Science 313, 2006. Le théorème rend le calcul court : il suffit d'essayer les rotations d'un accord contre l'autre — n essais au lieu de n factoriel. Un test l'éprouve ici sur deux cents paires tirées au sort contre les 720 permutations : les rotations gagnent à chaque fois.",
    "« The Geometry of Musical Chords », Science 313, 2006. The theorem makes the computation short: it is enough to try one chord's rotations against the other — n trials instead of n factorial. A test checks it here on two hundred randomly drawn pairs against all 720 permutations: the rotations win every time.", 2),
  source("geometrie-rythme",
    "Qui a écrit « The Geometry of Musical Rhythm » (2013) ?",
    "Who wrote « The Geometry of Musical Rhythm » (2013)?",
    ["Godfried Toussaint", "Joseph Schillinger", "Curtis Roads", "Simha Arom"],
    "Le livre d'où viennent les mesures du nœud « Analyse rythmique » : intervalles successifs, histogramme des distances, profondeur, uniformité, collier et bracelet. Toutes se comptent SUR LE CERCLE, parce qu'un rythme se répète — et c'est ce qui fait qu'un rythme et ses rotations sont le même objet.",
    "The book from which the « Rhythm Analysis » node's measures come: successive intervals, distance histogram, depth, evenness, necklace and bracelet. All are counted ON THE CIRCLE, because a rhythm repeats — and that is what makes a rhythm and its rotations the same object.", 2),
  source("resultante",
    "À qui doit-on les rythmes résultants, obtenus par interférence de deux pulsations ?",
    "To whom do we owe resultant rhythms, obtained by interference of two pulses?",
    ["Joseph Schillinger", "Olivier Messiaen", "Henry Cowell", "Conlon Nancarrow"],
    "« The Schillinger System of Musical Composition », Carl Fischer, 1946, livre I. Attic en livre la résultante, mais PAS le fractionnement : une première version en a été écrite puis retirée, faute de pouvoir la confronter à une figure publiée — livrer une invention sous une autorité empruntée aurait été pire que l'omission.",
    "« The Schillinger System of Musical Composition », Carl Fischer, 1946, book I. Attic ships the resultant, but NOT the fractioning: a first version was written then withdrawn, for want of being able to check it against a published figure — shipping an invention under a borrowed authority would have been worse than the omission.", 2),
  source("ambisonique",
    "Qui a fondé l'ambisonique et le B-format ?",
    "Who founded ambisonics and the B-format?",
    ["Michael Gerzon", "Alan Blumlein", "Jean-Marc Jot", "John Chowning"],
    "« Periphony: With-Height Sound Reproduction », JAES 21(1), 1973. Blumlein est le leurre juste : la stéréophonie et son couple de micros sont de lui, quarante ans plus tôt. Chowning, lui, a travaillé sur le déplacement de sources — et sur la FM.",
    "« Periphony: With-Height Sound Reproduction », JAES 21(1), 1973. Blumlein is the fair decoy: stereophony and its microphone pair are his, forty years earlier. Chowning, for his part, worked on moving sources — and on FM.", 2),
  source("yin",
    "Qui a proposé l'estimateur de fréquence fondamentale YIN ?",
    "Who proposed the YIN fundamental frequency estimator?",
    ["de Cheveigné & Kawahara", "Mauch & Dixon", "Serra & Smith", "Noll & Schroeder"],
    "JASA 111(4), 2002. Mauch et Dixon est le leurre le plus proche : ils en ont tiré pYIN (ICASSP 2014), qui garde plusieurs candidats par trame au lieu d'un seul — et c'est cette variante qu'Attic emploie, parce qu'un seul minimum se trompe d'une octave sur les sons riches.",
    "JASA 111(4), 2002. Mauch and Dixon is the closest decoy: they derived pYIN from it (ICASSP 2014), which keeps several candidates per frame instead of one — and it is that variant Attic uses, because a single minimum is octave-wrong on rich sounds.", 2),
  source("hpss",
    "Qui a proposé la séparation harmonique/percussive par filtrage médian ?",
    "Who proposed harmonic/percussive separation by median filtering?",
    ["Derry Fitzgerald", "Nobutaka Ono", "Emmanuel Vincent", "Paris Smaragdis"],
    "DAFx-10, en une page et demie : un filtre médian horizontal garde les notes tenues, un filtre médian vertical garde les frappes. C'est l'exemple type d'une méthode qui bat des approches beaucoup plus lourdes parce qu'elle exploite une géométrie évidente du spectrogramme.",
    "DAFx-10, in a page and a half: a horizontal median filter keeps held notes, a vertical median filter keeps hits. It is the type case of a method that beats far heavier approaches because it exploits an obvious geometry of the spectrogram.", 2),
  source("pghi",
    "Qui a proposé la reconstruction de phase par intégration du gradient sur un tas (PGHI) ?",
    "Who proposed phase reconstruction by heap integration of the gradient (PGHI)?",
    ["Průša, Balazs & Søndergaard", "Griffin & Lim", "Le Roux & Vincent", "Laroche & Dolson"],
    "IEEE/ACM TASLP 25(5), 2017. Griffin et Lim sont le leurre juste : leur méthode itérative (1984) est celle que PGHI remplace, en faisant en une passe ce qu'elle cherche en cent.",
    "IEEE/ACM TASLP 25(5), 2017. Griffin and Lim are the fair decoy: their iterative method (1984) is the one PGHI replaces, doing in a single pass what it seeks in a hundred.", 2),
  source("declipping",
    "Qui a proposé le déclipage par parcimonie et coparcimonie (A-SPADE) ?",
    "Who proposed declipping by sparsity and cosparsity (A-SPADE)?",
    ["Kitić, Bertin & Gribonval", "Adler & Emiya", "Janssen & Veldhuis", "Defraene & Moonen"],
    "LVA/ICA 2015. Adler et Emiya sont le leurre le plus proche : leur article de 2012 (IEEE TASLP 20(3)) traite du même problème par une autre voie, et Attic cite les deux.",
    "LVA/ICA 2015. Adler and Emiya are the closest decoy: their 2012 paper (IEEE TASLP 20(3)) treats the same problem by another route, and Attic cites both.", 2),
  source("fdn",
    "Qui a posé les réseaux de retards rebouclés pour la réverbération artificielle ?",
    "Who set out feedback delay networks for artificial reverberation?",
    ["Jot & Chaigne", "Schroeder & Logan", "Moorer", "Gardner"],
    "AES Convention, 1991 : la contribution décisive est d'y régler le temps de décroissance FRÉQUENCE PAR FRÉQUENCE, ce qui distingue une réverbération crédible d'un écho dense. Schroeder et Logan sont le leurre juste — les filtres en peigne et passe-tout, l'étage précédent.",
    "AES Convention, 1991: the decisive contribution is to set the decay time FREQUENCY BY FREQUENCY there, which separates a credible reverberation from a dense echo. Schroeder and Logan are the fair decoy — the comb and allpass filters, the previous stage.", 2),
  source("decaleur",
    "Qui a décrit le décaleur de fréquence audio par transformée de Hilbert ?",
    "Who described the audio frequency shifter by Hilbert transform?",
    ["Scott Wardle", "Harald Bode", "Vesa Välimäki", "Udo Zölzer"],
    "DAFx-98. Bode est le leurre juste : le décaleur analogique des années soixante est de lui, et c'est le même effet par un autre chemin. Décaler n'est pas transposer : ajouter le même nombre de hertz à tous les partiels détruit l'harmonicité, et c'est l'effet cherché.",
    "DAFx-98. Bode is the fair decoy: the analogue shifter of the sixties is his, and it is the same effect by another route. Shifting is not transposing: adding the same number of hertz to every partial destroys harmonicity, and that is the desired effect.", 2),
  source("stn",
    "Qui a proposé la décomposition floue d'un son en sinusoïdes, transitoires et bruit ?",
    "Who proposed the fuzzy decomposition of a sound into sines, transients and noise?",
    ["Fierro & Välimäki", "Serra & Smith", "Verma & Meng", "Daudet & Torrésani"],
    "JAES 71(7-8), 2023. Serra et Smith sont le leurre juste : la décomposition sinusoïdes + bruit est d'eux (1990), et la troisième partie — les transitoires — est ce que les travaux suivants ont ajouté. Le mot « floue » compte : un point du spectrogramme appartient aux trois classes avec des poids, et non à une seule.",
    "JAES 71(7-8), 2023. Serra and Smith are the fair decoy: the sines-plus-noise decomposition is theirs (1990), and the third part — transients — is what later work added. The word « fuzzy » matters: a point of the spectrogram belongs to all three classes with weights, rather than to one.", 2),
  source("sms",
    "Qui a proposé la synthèse par modélisation spectrale — sinusoïdes plus bruit ?",
    "Who proposed spectral modeling synthesis — sines plus noise?",
    ["Serra & Smith", "Fierro & Välimäki", "McAulay & Quatieri", "Portnoff"],
    "Xavier Serra et Julius O. Smith, 1990. McAulay et Quatieri sont le leurre juste : leur codage sinusoïdal (1986) suit les partiels mais ne modélise pas séparément la partie bruitée, qui est justement ce que SMS ajoute.",
    "Xavier Serra and Julius O. Smith, 1990. McAulay and Quatieri are the fair decoy: their sinusoidal coding (1986) tracks partials but does not model the noisy part separately, which is precisely what SMS adds.", 2),
  source("cribles",
    "À qui doit-on la théorie des cribles, où une échelle naît de classes de restes ?",
    "To whom do we owe the theory of sieves, where a scale is born of residue classes?",
    ["Iannis Xenakis", "Milton Babbitt", "Pierre Boulez", "Karlheinz Stockhausen"],
    "« Sieves » (1990), le procédé apparaissant dès « Nomos alpha ». Xenakis est présent deux fois dans Attic : par ses cribles, et par la synthèse stochastique dynamique de Gendy3 (1991), où c'est la FORME D'ONDE elle-même qui est tirée au sort.",
    "« Sieves » (1990), the process appearing as early as « Nomos alpha ». Xenakis is present twice in Attic: through his sieves, and through the dynamic stochastic synthesis of Gendy3 (1991), where it is the WAVEFORM itself that is drawn at random.", 2),
  source("pulsars",
    "Qui a formulé la synthèse par pulsars, dans « Microsound » ?",
    "Who formulated pulsar synthesis, in « Microsound »?",
    ["Curtis Roads", "Barry Truax", "Trevor Wishart", "Dennis Gabor"],
    "« Microsound » (2001). Gabor est le leurre juste et profond : le grain sonore est de lui (1946), et toute la granulation en descend — mais les pulsars, où une impulsion formantique se répète à une cadence propre, sont de Roads.",
    "« Microsound » (2001). Gabor is the fair and deep decoy: the sound grain is his (1946), and all granulation descends from it — but pulsars, where a formant impulse repeats at its own rate, are Roads's.", 2),
  source("lucier",
    "Qui a composé « I Am Sitting in a Room » (1969), dont Attic tire un nœud ?",
    "Who composed « I Am Sitting in a Room » (1969), from which Attic draws a node?",
    ["Alvin Lucier", "Steve Reich", "La Monte Young", "Pauline Oliveros"],
    "Le principe tient en une phrase : enregistrer une voix dans une pièce, rejouer l'enregistrement dans la même pièce, le réenregistrer, et recommencer. Les résonances de la pièce s'accumulent jusqu'à ce que les mots disparaissent — la pièce finit par chanter à la place de la voix.",
    "The principle fits in one sentence: record a voice in a room, play the recording back in the same room, record it again, and start over. The room's resonances pile up until the words vanish — the room ends up singing in the voice's place.", 2),
  source("nancarrow",
    "Quel compositeur a écrit les « Studies for Player Piano », dont Attic tire ses canons à vitesses irrationnelles ?",
    "Which composer wrote the « Studies for Player Piano », from which Attic draws its irrational-ratio canons?",
    ["Conlon Nancarrow", "György Ligeti", "Henry Cowell", "Charles Ives"],
    "Des tempos dans des rapports comme 2:√2, injouables par des interprètes humains et parfaitement exécutables par un piano mécanique. Ligeti est le leurre juste : il a revendiqué cette influence, et son « Poème symphonique » pour cent métronomes en est le cousin.",
    "Tempos in ratios such as 2:sqrt(2), unplayable by human performers and perfectly executable by a mechanical piano. Ligeti is the fair decoy: he claimed that influence, and his « Poeme symphonique » for a hundred metronomes is its cousin.", 2),
  source("stockhausen",
    "Qui a formulé, en composant « Kontakte » (1960), l'idée que hauteur, timbre et rythme sont un seul continuum ?",
    "Who formulated, while composing « Kontakte » (1960), the idea that pitch, timbre and rhythm are a single continuum?",
    ["Karlheinz Stockhausen", "Pierre Schaeffer", "Edgard Varèse", "Iannis Xenakis"],
    "Ralentir une impulsion répétée assez pour qu'on cesse d'entendre une hauteur et qu'on commence à entendre un rythme : il n'y a pas de frontière, seulement une échelle de temps. Schaeffer est le leurre juste — l'objet sonore et le solfège des objets sont de lui, mais pas ce continuum-là.",
    "Slowing a repeated impulse enough that a pitch stops being heard and a rhythm starts: there is no boundary, only a time scale. Schaeffer is the fair decoy — the sound object and its solfege are his, but not that continuum.", 2),
  source("chowning",
    "Qui a publié la synthèse par modulation de fréquence audio, en 1973 ?",
    "Who published audio frequency modulation synthesis, in 1973?",
    ["John Chowning", "Max Mathews", "Jean-Claude Risset", "Miller Puckette"],
    "JAES 21(7) : deux oscillateurs, deux réglages, une infinité de timbres et un coût de calcul minuscule — d'où le DX7 et toute la décennie qui a suivi. Risset est le leurre juste : il travaillait dans le même laboratoire, et Attic lui doit son glissando sans fin.",
    "JAES 21(7): two oscillators, two controls, an infinity of timbres and a tiny computational cost — hence the DX7 and the whole decade that followed. Risset is the fair decoy: he worked in the same laboratory, and Attic owes him its endless glissando.", 2),
  source("risset",
    "À qui doit-on le glissando qui monte sans fin, version continue du paradoxe des hauteurs ?",
    "To whom do we owe the endlessly rising glissando, the continuous version of the pitch paradox?",
    ["Jean-Claude Risset", "Roger Shepard", "Diana Deutsch", "Albert Bregman"],
    "Shepard est le leurre exact, et la distinction vaut d'être sue : le paradoxe de Shepard (1964) porte sur des notes DISCRÈTES, et Risset en a tiré la version CONTINUE — un glissando, non une gamme. Attic nomme le nœud d'après Risset pour cette raison.",
    "Shepard is the exact decoy, and the distinction is worth knowing: Shepard's paradox (1964) concerns DISCRETE notes, and Risset derived the CONTINUOUS version — a glissando, not a scale. Attic names the node after Risset for that reason.", 2),
  source("fux",
    "Qui a écrit « Gradus ad Parnassum » (1725), d'où vient le contrepoint d'espèces ?",
    "Who wrote « Gradus ad Parnassum » (1725), from which species counterpoint comes?",
    ["Johann Joseph Fux", "Jean-Philippe Rameau", "Heinrich Schenker", "Hugo Riemann"],
    "Un dialogue entre un maître et un élève, en cinq espèces de liberté croissante. Haydn, Mozart et Beethoven l'ont tous étudié — c'est pourquoi les règles que le nœud vérifie ne sont pas une invention moderne mais la grammaire qu'ils avaient en tête.",
    "A dialogue between a master and a pupil, in five species of increasing freedom. Haydn, Mozart and Beethoven all studied it — which is why the rules the node checks are not a modern invention but the grammar they had in mind.", 2),
  source("effets-adaptatifs",
    "Qui a formalisé les effets audio adaptatifs, où un descripteur du son commande le traitement ?",
    "Who formalised adaptive audio effects, where a descriptor of the sound drives the processing?",
    ["Verfaille, Zölzer & Arfib", "Jot & Chaigne", "Wishart & Roads", "Puckette & Brown"],
    "IEEE TASLP 14(5), 2006. L'idée est plus générale qu'elle n'y paraît : un compresseur est déjà adaptatif — c'est l'énergie du signal qui commande son gain. Formaliser la famille, c'est pouvoir remplacer l'énergie par le centroïde, la hauteur ou la rugosité.",
    "IEEE TASLP 14(5), 2006. The idea is more general than it looks: a compressor is already adaptive — the signal's energy drives its gain. Formalising the family means being able to replace energy by centroid, pitch or roughness.", 2),
];
