// plugins/automate-cellulaire.ts — Nœud de génération musicale par automate cellulaire.
import type { FicheAudio } from "../audio/types-domaine";
import {
  genererAutomateCellulaire,
  normaliserCle,
  normaliserGamme,
  normaliserTimbre,
  normaliserTopologie,
  normaliserModeVoix,
  normaliserMapping,
  REGLES_1D,
} from "../audio/automate-cellulaire";
import { traduire } from "../i18n";
import { avecDoc } from "./notices";

const reglesOptions = ["Personnalisée", ...REGLES_1D.map(String)];
const reglesOptionsEn = ["Custom", ...REGLES_1D.map(String)];

const FICHES: FicheAudio[] = [
  {
    id: "automate-cellulaire",
    nom: "Automate cellulaire",
    nomEn: "Cellular automaton",
    univers: "Entrées",
    famille: "Génération",
    resume: "Génère une séquence musicale à partir d'un automate cellulaire 1D ou 2D.",
    resumeEn: "Generates a musical sequence from a 1D or 2D cellular automaton.",
    entrees: [],
    sorties: [
      { nom: "Audio", type: "audio", sousType: "stereo" },
      { nom: "MIDI", type: "midi" },
    ],
    parametres: [
      {
        nom: "Topologie",
        nomEn: "Topology",
        type: "choix",
        options: ["1D", "2D Conway", "2D Highlife"],
        defaut: "1D",
        optionsEn: ["1D", "2D Conway", "2D Highlife"],
        defautEn: "1D",
        doc: "1D : règles élémentaires 0-255. 2D Conway/Highlife : jeu de la vie et variantes.",
        docEn: "1D: elementary rules 0-255. 2D Conway/Highlife: Game of Life and variants.",
      },
      {
        nom: "Règle",
        nomEn: "Rule",
        type: "choix",
        options: reglesOptions,
        defaut: "90",
        optionsEn: reglesOptionsEn,
        defautEn: "90",
        doc: "Règle 1D classique. Choisissez Personnalisée pour utiliser la valeur numérique ci-dessous.",
        docEn: "Classic 1D rule. Choose Custom to use the numeric value below.",
      },
      {
        nom: "Règle personnalisée",
        nomEn: "Custom rule",
        type: "nombre",
        plage: [0, 255],
        pas: 1,
        defaut: 90,
        doc: "Numéro de règle 1D utilisé quand Règle = Personnalisée. Ignoré en mode 2D.",
        docEn: "1D rule number used when Rule = Custom. Ignored in 2D mode.",
      },
      {
        nom: "Mode voix",
        nomEn: "Voice mode",
        type: "choix",
        options: ["Polyphonie", "Mélodie", "Arpège"],
        defaut: "Polyphonie",
        optionsEn: ["Polyphony", "Melody", "Arpeggio"],
        defautEn: "Polyphony",
        doc: "Polyphonie joue toutes les cellules actives. Mélodie en choisit une par pas. Arpège les joue dans l'ordre.",
        docEn: "Polyphony plays all active cells. Melody picks one per step. Arpeggio plays them in order.",
      },
      {
        nom: "Mapping",
        nomEn: "Mapping",
        type: "choix",
        options: ["Hauteur", "Vélocité", "Durée", "Hauteur + vélocité"],
        defaut: "Hauteur",
        optionsEn: ["Pitch", "Velocity", "Duration", "Pitch + velocity"],
        defautEn: "Pitch",
        doc: "Ce que représente la position des cellules actives. Hauteur + vélocité combine les deux.",
        docEn: "What the position of active cells represents. Pitch + velocity combines both.",
      },
      {
        nom: "Largeur",
        nomEn: "Width",
        type: "nombre",
        plage: [4, 64],
        pas: 1,
        defaut: 16,
        unite: "cellules",
        doc: "Nombre de cellules par ligne.",
        docEn: "Number of cells per row.",
      },
      {
        nom: "Hauteur",
        nomEn: "Height",
        type: "nombre",
        plage: [4, 64],
        pas: 1,
        defaut: 16,
        unite: "cellules",
        doc: "Hauteur de la grille en mode 2D. En 1D, utilisez Générations.",
        docEn: "Grid height in 2D mode. In 1D, use Generations.",
      },
      {
        nom: "Générations",
        nomEn: "Generations",
        type: "nombre",
        plage: [4, 256],
        pas: 1,
        defaut: 32,
        unite: "pas",
        doc: "Nombre de pas / générations de l'automate (1D) ou itérations de la grille (2D).",
        docEn: "Number of steps / generations of the automaton (1D) or grid iterations (2D).",
      },
      {
        nom: "Graine",
        nomEn: "Seed",
        type: "nombre",
        plage: [0, 9999],
        pas: 1,
        defaut: 0,
        doc: "0 = graine simple au centre. Sinon initialisation aléatoire.",
        docEn: "0 = simple centered seed. Otherwise random initialization.",
      },
      {
        nom: "Clé",
        nomEn: "Key",
        type: "choix",
        options: ["Do", "Do#", "Ré", "Mi♭", "Mi", "Fa", "Fa#", "Sol", "Sol#", "La", "Si♭", "Si"],
        defaut: "Do",
        optionsEn: ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "G#", "A", "Bb", "B"],
        defautEn: "C",
        doc: "Clé de la gamme utilisée pour mapper les cellules en notes.",
        docEn: "Key of the scale used to map cells to notes.",
      },
      {
        nom: "Gamme",
        nomEn: "Scale",
        type: "choix",
        options: ["Majeur", "Mineur naturel", "Pentatonique majeure", "Pentatonique mineure", "Chromatique"],
        defaut: "Pentatonique majeure",
        optionsEn: ["Major", "Natural minor", "Major pentatonic", "Minor pentatonic", "Chromatic"],
        defautEn: "Major pentatonic",
        doc: "Gamme utilisée pour convertir les positions de cellules en hauteurs de notes.",
        docEn: "Scale used to convert cell positions into note pitches.",
      },
      {
        nom: "Octave",
        nomEn: "Octave",
        type: "nombre",
        plage: [1, 6],
        pas: 1,
        defaut: 4,
        doc: "Octave de base des notes MIDI générées.",
        docEn: "Base octave of the generated MIDI notes.",
      },
      {
        nom: "Durée note",
        nomEn: "Note duration",
        type: "nombre",
        plage: [0.05, 2],
        pas: 0.05,
        defaut: 0.2,
        unite: "s",
        doc: "Durée de base de chaque pas en secondes.",
        docEn: "Base duration of each step in seconds.",
      },
      {
        nom: "Vélocité",
        nomEn: "Velocity",
        type: "nombre",
        plage: [1, 127],
        pas: 1,
        defaut: 100,
        doc: "Vélocité MIDI de base des notes générées (1-127).",
        docEn: "Base MIDI velocity of the generated notes (1-127).",
      },
      {
        nom: "Volume",
        nomEn: "Volume",
        type: "nombre",
        plage: [0, 100],
        pas: 1,
        defaut: 80,
        unite: "%",
      },
      {
        nom: "Densité max",
        nomEn: "Max density",
        type: "nombre",
        plage: [1, 16],
        pas: 1,
        defaut: 4,
        doc: "Nombre maximum de notes simultanées en mode polyphonie.",
        docEn: "Maximum number of simultaneous notes in polyphony mode.",
      },
      {
        nom: "Probabilité mutation",
        nomEn: "Mutation probability",
        type: "nombre",
        plage: [0, 0.5],
        pas: 0.01,
        defaut: 0,
        doc: "Probabilité d'inverser aléatoirement une cellule à chaque génération.",
        docEn: "Probability of randomly flipping a cell at each generation.",
      },
      {
        nom: "Synthèse",
        nomEn: "Synthesis",
        type: "choix",
        options: ["FM/Oscillateurs", "SoundFont"],
        defaut: "FM/Oscillateurs",
        optionsEn: ["FM/Oscillators", "SoundFont"],
        defautEn: "FM/Oscillators",
        doc: "Moteur audio pour le rendu : FM/oscillateurs intégrés ou SoundFont global chargé.",
        docEn: "Audio engine for rendering: built-in FM/oscillators or loaded global SoundFont.",
      },
    ],
    async executer(ctx: any) {
      const regleTexte = ctx.paramTexte("Règle", "90");
      const regle = regleTexte === "Personnalisée" || regleTexte === "Custom"
        ? ctx.paramNombre("Règle personnalisée", 90)
        : parseInt(regleTexte, 10) || 90;
      const res = await genererAutomateCellulaire({
        regle,
        reglePersonnalisee: ctx.paramNombre("Règle personnalisée", 90),
        topologie: normaliserTopologie(ctx.paramTexte("Topologie", "1D")),
        modeVoix: normaliserModeVoix(ctx.paramTexte("Mode voix", "Polyphonie")),
        mapping: normaliserMapping(ctx.paramTexte("Mapping", "Hauteur")),
        largeur: ctx.paramNombre("Largeur", 16),
        hauteur: ctx.paramNombre("Hauteur", 16),
        generations: ctx.paramNombre("Générations", 32),
        graine: ctx.paramNombre("Graine", 0),
        cle: normaliserCle(ctx.paramTexte("Clé", "Do")),
        gamme: normaliserGamme(ctx.paramTexte("Gamme", "Pentatonique majeure")),
        octave: ctx.paramNombre("Octave", 4),
        dureeNote: ctx.paramNombre("Durée note", 0.2),
        velocite: ctx.paramNombre("Vélocité", 100),
        volume: ctx.paramNombre("Volume", 80),
        timbre: normaliserTimbre(ctx.paramTexte("Synthèse", "FM/Oscillateurs")),
        densiteMax: ctx.paramNombre("Densité max", 4),
        probabilite: ctx.paramNombre("Probabilité mutation", 0),
      });
      return {
        valeurs: [res.audio, res.midi],
        message: traduire("msg.automate_cellulaire", res.notes.length, res.audio.duration.toFixed(1)),
      };
    },
  },
];

export const fiches: FicheAudio[] = FICHES.map(avecDoc) as FicheAudio[];
