// plugins/effets.ts — Effets de dynamique, de distorsion et de reverberation.
//
// Les fiches sont rangees par nature du traitement, et non par famille : les quarante-trois
// effets declarent la meme, « Effets », ce qui ne decoupe rien. Les fabriques partagees vivent
// dans `effets-aides.ts`.


import { normaliserSonie } from "../audio/normalisation-sonie";
import type { FicheAudio } from "../audio/types-domaine";
import { traduire } from "../i18n";
import { avecDoc } from "./notices";
import { creerAleatoire } from "../core";
import { appliquerDelay, appliquerReverberation, appliquerDistorsion, appliquerFlanger, appliquerChorus, compresser, normaliser, supprimerClics, dererverberer, changerTempo, changerTonalite, changerTonaliteVoie, glissandoTonalite, glissandoTonaliteVoie, bitcrusher, gateExpandeur, deEsser, ringModulator, reverberationFractale, limiter, transientShaper, compresserMultiBande, exciter, harmoniser, harmoniserVoie, type OptionsHarmoniser, type OptionsGlissando, vocoder } from "../audio";
import { quadrafuzz } from "../audio/quadrafuzz";

import { MODULATION_MIX, bornesModulation, effet, melangeModule, param, portModulation } from "./effets-aides";

export const fiches: FicheAudio[] = ([
  effet("delay-stereo", "Delay stéréo", "Stereo Delay", "Delay indépendant gauche/droite.", "Independent left/right delay.",
    [param("Temps G", 250, "Time L", "ms", "Délai canal gauche.", "Left channel delay."), param("Temps D", 375, "Time R", "ms", "Délai canal droit.", "Right channel delay."), param("Feedback", 40, "Feedback", "%", "Quantité de signal réinjecté.", "Amount of signal fed back."), param("Mix", 35, "Mix", "%", "Équilibre signal original / delay.", "Dry/wet balance.")],
    (a,tg,td,fb,mix) => appliquerDelay(a, tg, td, fb, mix),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("reverberation", "Réverbération", "Reverb", "Réverbération à convolution.", "Convolution reverb.",
    [param("Taille", 50, "Size", "%", "Taille de la pièce simulée.", "Simulated room size."), param("Decay", 2, "Decay", "s", "Temps de déclin de la réverbération.", "Reverb decay time."), param("Mix", 50, "Mix", "%", "Équilibre son direct / réverbération.", "Dry/wet balance."), { ...param("Graine", 42, "Seed", "", "Graine du bruit de la réponse impulsionnelle. Valeur par défaut fixe : une réverbération qui change de pièce à chaque exécution serait un défaut. La changer donne une autre pièce, de mêmes dimensions.", "Seed for the impulse-response noise. The default is fixed: a reverb that moves to a different room on every run would be a defect. Changing it gives another room of the same dimensions.", [0, 999999], 1), graine: true }],
    (a, taille, decay, mix, graine) => appliquerReverberation(a, taille, decay, mix, creerAleatoire(graine)),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("reverb-fractale", "Réverbération fractale", "Fractal Reverb", "Réverbération à convolution dont la réponse impulsionnelle est générée par un motif fractal.", "Convolution reverb whose impulse response is generated by a fractal pattern.",
    [param("Decay", 3, "Decay", "s", "Durée totale de la réponse impulsionnelle.", "Total duration of the impulse response."), param("Pré-delay", 20, "Pre-delay", "ms", "Délai avant l'arrivée des premières réflexions.", "Delay before the first reflections arrive."), param("Densité", 5, "Density", "", "Profondeur de récursion fractale (1-8). Plus élevé = plus de réflexions.", "Fractal recursion depth (1-8). Higher = more reflections.", [1, 8], 1), param("Atténuation", 70, "Decay gain", "%", "Atténuation de l'amplitude à chaque niveau de récursion.", "Amplitude attenuation at each recursion level.", [10, 95], 5), param("Diffusion", 60, "Diffusion", "%", "Étalement stéréo des réflexions.", "Stereo spread of reflections."), param("Damping", 30, "Damping", "%", "Absorption des hautes fréquences.", "High-frequency absorption."), param("Mix", 40, "Mix", "%", "Équilibre son direct / réverbération.", "Dry/wet balance.")],
    (a, decay, preDelay, densite, attenuation, diffusion, damping, mix) => reverberationFractale(a, { decay, preDelay, densite, gainDecay: attenuation / 100, diffusion, damping, graine: 42 }, mix)),
  effet("distorsion", "Distorsion", "Distortion", "Saturation / overdrive.", "Saturation / overdrive.",
    [param("Gain", 50, "Gain", "%", "Quantité de saturation.", "Amount of saturation drive.")],
    (a,gain) => appliquerDistorsion(a, gain)),
  effet("bitcrusher", "Bitcrusher", "Bitcrusher", "Quantification + sous-échantillonnage (lo-fi).", "Bit quantization + downsampling (lo-fi).",
    [param("Bits", 8, "Bits", "", "Résolution en bits (1-16). 8 = son 8-bit rétro ; 4 = très crunch.", "Bit resolution (1-16). 8 = retro 8-bit sound; 4 = very crunchy.", [1, 16], 1),
     param("Fréquence", 22050, "Rate", "Hz", "Fréquence d'échantillonnage simulée. Plus basse = son plus cassé/aliased.", "Simulated sample rate. Lower = more broken/aliased sound.", [1000, 44100], 100),
     param("Mix", 100, "Mix", "%", "Équilibre signal original / effet. 100% = effet seul.", "Dry/wet balance. 100% = effect only.")],
    (a, bits, freq, mix) => bitcrusher(a, bits, freq, mix),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("quadrafuzz", "Quadrafuzz", "Quadrafuzz",
    "Distorsion à quatre bandes : chaque registre sature séparément.",
    "Four-band distortion: each register saturates independently.",
    [param("Graves", 60, "Low", "%", "Saturation de la bande grave, sous la première coupure.", "Saturation of the low band, below the first crossover.", [0, 100], 1),
     param("Bas médiums", 40, "Low mids", "%", "Saturation entre la première et la deuxième coupure.", "Saturation between the first and second crossovers.", [0, 100], 1),
     param("Hauts médiums", 40, "High mids", "%", "Saturation entre la deuxième et la troisième coupure.", "Saturation between the second and third crossovers.", [0, 100], 1),
     param("Aigus", 20, "High", "%", "Saturation de la bande aiguë, au-dessus de la troisième coupure. À garder basse : c'est elle qui rend un fuzz strident.", "Saturation of the high band, above the third crossover. Keep it low: this is what makes a fuzz shrill.", [0, 100], 1),
     param("Coupure 1", 160, "Crossover 1", "Hz", "Limite entre graves et bas médiums.", "Boundary between low and low mids.", [40, 800], 10),
     param("Coupure 2", 1000, "Crossover 2", "Hz", "Limite entre bas et hauts médiums.", "Boundary between low mids and high mids.", [200, 4000], 50),
     param("Coupure 3", 4000, "Crossover 3", "Hz", "Limite entre hauts médiums et aigus.", "Boundary between high mids and high.", [1000, 12000], 100),
     param("Mix", 100, "Mix", "%", "Équilibre signal original / effet. 0 % rend le signal d'origine tel quel.", "Dry/wet balance. 0% returns the original signal untouched.", [0, 100], 1),
     param("Sortie", -6, "Output", "dB", "Gain de sortie. Une saturation fait monter le niveau : ce réglage le rattrape.", "Output gain. Saturation raises the level: this brings it back.", [-24, 12], 0.5)],
    (a, graves, basMediums, hautsMediums, aigus, f1, f2, f3, mix, sortie) =>
      quadrafuzz(a, { graves, basMediums, hautsMediums, aigus, f1, f2, f3, mix, sortie }),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("exciter", "Exciter / Aural enhancer", "Exciter / Aural Enhancer", "Ajoute de la présence par distorsion harmonique dans les hauts médiums.", "Adds presence via harmonic distortion in the high mids.",
    [param("Amount", 50, "Amount", "%", "Intensité de la distorsion asymétrique.", "Intensity of the asymmetrical distortion.", [0, 100], 1), param("Fréquence", 3000, "Frequency", "Hz", "Fréquence de coupure du passe-haut après distorsion.", "High-pass cutoff after distortion.", [500, 10000], 100), param("Mix", 30, "Mix", "%", "Équilibre signal original / effet.", "Dry/wet balance.", [0, 100], 1)],
    (a, amount, freq, mix) => exciter(a, amount, freq, mix),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("flanger", "Flanger", "Flanger", "Modulation par délai variable.", "Variable delay modulation.",
    [param("Mix", 50, "Mix", "%", "Équilibre signal original / effet.", "Dry/wet balance."), param("Vitesse", 0.5, "Speed", "Hz", "Vitesse de modulation LFO.", "LFO modulation speed."), param("Profondeur", 3, "Depth", "ms", "Amplitude du balayage.", "Modulation depth in ms.")],
    (a,mix,v,p) => appliquerFlanger(a, v, p, mix),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("chorus", "Chorus", "Chorus", "Doublement stéréo modulé.", "Modulated stereo doubling.",
    [param("Mix", 40, "Mix", "%", "Équilibre signal original / effet.", "Dry/wet balance."), param("Vitesse", 0.8, "Speed", "Hz", "Vitesse de modulation LFO.", "LFO modulation speed."), param("Profondeur", 5, "Depth", "ms", "Amplitude du détimbrage.", "Detuning depth in ms.")],
    (a,mix,v,p) => appliquerChorus(a, v, p, mix),
    undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  effet("compresseur", "Compresseur", "Compressor", "Compresseur feed-forward.", "Feed-forward compressor.",
    [param("Seuil", -20, "Threshold", "dB", "Niveau au-dessus duquel la compression s'active.", "Level above which compression engages.", [-60, 0], 1), param("Ratio", 4, "Ratio", "∶1", "Taux de compression.", "Compression ratio.", [1, 20], 0.5), param("Attaque", 5, "Attack", "ms", "Temps de réaction du compresseur.", "Compressor attack time.", [0, 200], 1), param("Relâchement", 100, "Release", "ms", "Temps de retour au gain normal.", "Compressor release time.", [5, 1000], 5), param("Gain", 0, "Gain", "dB", "Gain de sortie (make-up gain).", "Output makeup gain.", [-12, 24], 1)],
    (a,seuil,ratio,att,rel,gain) => compresser(a, seuil, ratio, att, rel, gain)),
  effet("limiteur", "Limiteur", "Limiter", "Limiteur de crête pour le mastering.", "Peak limiter for mastering.",
    [param("Seuil", -3, "Threshold", "dB", "Niveau au-dessus duquel la limitation s'active.", "Level above which limiting engages.", [-40, 0], 1), param("Relâchement", 50, "Release", "ms", "Temps de retour au gain normal après un pic.", "Time to return to normal gain after a peak.", [1, 1000], 1), param("Plafond", -1, "Ceiling", "dB", "Niveau maximal de sortie.", "Maximum output level.", [-40, 0], 0.5)],
    (a, seuil, relachement, plafond) => limiter(a, seuil, relachement, plafond)),
  effet("compresseur-multibande", "Compresseur multibande", "Multiband Compressor", "Compresseur 3 bandes indépendantes (low/mid/high).", "3-band compressor with independent thresholds/ratios.",
    [
      param("Seuil Low", -20, "Low threshold", "dB", "Seuil du compresseur sur la bande grave.", "Compressor threshold for the low band.", [-60, 0], 1),
      param("Ratio Low", 4, "Low ratio", "∶1", "Ratio du compresseur sur la bande grave.", "Compressor ratio for the low band.", [1, 20], 0.5),
      param("Seuil Mid", -20, "Mid threshold", "dB", "Seuil du compresseur sur la bande médium.", "Compressor threshold for the mid band.", [-60, 0], 1),
      param("Ratio Mid", 4, "Mid ratio", "∶1", "Ratio du compresseur sur la bande médium.", "Compressor ratio for the mid band.", [1, 20], 0.5),
      param("Seuil High", -20, "High threshold", "dB", "Seuil du compresseur sur la bande aiguë.", "Compressor threshold for the high band.", [-60, 0], 1),
      param("Ratio High", 4, "High ratio", "∶1", "Ratio du compresseur sur la bande aiguë.", "Compressor ratio for the high band.", [1, 20], 0.5),
      param("Attaque", 5, "Attack", "ms", "Temps de réaction commun aux trois bandes.", "Common attack time for all bands.", [0, 200], 1),
      param("Relâchement", 100, "Release", "ms", "Temps de retour commun aux trois bandes.", "Common release time for all bands.", [5, 1000], 5),
      param("Fréq Low", 250, "Low freq", "Hz", "Fréquence de coupure entre les bandes low et mid.", "Crossover between low and mid bands.", [40, 1000], 10),
      param("Fréq High", 4000, "High freq", "Hz", "Fréquence de coupure entre les bandes mid et high.", "Crossover between mid and high bands.", [1000, 12000], 100),
    ],
    (a, seuilLow, ratioLow, seuilMid, ratioMid, seuilHigh, ratioHigh, attaque, relachement, freqLow, freqHigh) => compresserMultiBande(a, seuilLow, ratioLow, seuilMid, ratioMid, seuilHigh, ratioHigh, attaque, relachement, freqLow, freqHigh)),
  {
    id: "gate-expandeur", nom: "Gate/Expandeur", nomEn: "Gate/Expander",
    memoire: "flux", // enveloppe recursive, un seul scalaire
    univers: "Traitement", famille: "Effets",
    resume: "Gate ou expandeur dynamique (coupe ou atténue le signal sous un seuil).",
    resumeEn: "Dynamic gate or expander (cuts or attenuates signal below a threshold).",
    entrees: [{ nom: "Audio", type: "audio", sousType: "stereo" }],
    sorties: [{ nom: "Audio", type: "audio", sousType: "stereo" }],
    parametres: [
      { nom: "Mode", nomEn: "Mode", type: "choix", options: ["Gate", "Expandeur"], optionsEn: ["Gate", "Expander"], optionIds: ["gate", "expander"], defaut: "Gate",
        doc: "Gate = coupe le signal sous le seuil (atténuation fixe vers le plancher). Expandeur = atténue progressivement le signal sous le seuil selon le ratio (compresseur inversé).",
        docEn: "Gate = cuts signal below threshold (fixed attenuation to floor). Expander = gradually attenuates signal below threshold by ratio (reverse compressor).", defautEn: "Gate" },
      { nom: "Seuil", nomEn: "Threshold", plage: [-80, 0], pas: 1, defaut: -40, unite: "dB",
        doc: "Niveau en dessous duquel le gate/expandeur s'active.", docEn: "Level below which the gate/expander engages." },
      { nom: "Ratio", nomEn: "Ratio", plage: [1, 20], pas: 0.5, defaut: 4, unite: "∶1",
        doc: "Expandeur uniquement : taux d'expansion sous le seuil. Ignoré en mode Gate.", docEn: "Expander only: expansion ratio below threshold. Ignored in Gate mode." },
      { nom: "Attaque", nomEn: "Attack", plage: [0.1, 100], pas: 0.1, defaut: 1, unite: "ms",
        doc: "Temps de réaction quand le signal passe sous le seuil.", docEn: "Reaction time when signal drops below threshold." },
      { nom: "Relâchement", nomEn: "Release", plage: [1, 1000], pas: 1, defaut: 100, unite: "ms",
        doc: "Temps de retour quand le signal repasse au-dessus du seuil.", docEn: "Recovery time when signal rises above threshold." },
      { nom: "Atténuation", nomEn: "Attenuation", plage: [0, 80], pas: 1, defaut: 40, unite: "dB",
        doc: "Atténuation maximale du plancher. Gate = niveau de coupure ; Expandeur = limite d'atténuation.", docEn: "Maximum floor attenuation. Gate = cut level; Expander = attenuation limit." },
    ],
    async executer(ctx: any) {
      const audio = ctx.entree(0);
      if (!(audio instanceof AudioBuffer)) return { valeurs: [null], message: traduire("msg.aucune_entr_e") };
      const mode = ctx.paramTexte("Mode", "gate");
      const seuil = ctx.paramNombre("Seuil", -40);
      const ratio = ctx.paramNombre("Ratio", 4);
      const attaque = ctx.paramNombre("Attaque", 1);
      const relachement = ctx.paramNombre("Relâchement", 100);
      const attenuation = ctx.paramNombre("Atténuation", 40);
      const r = gateExpandeur(audio, mode, seuil, ratio, attaque, relachement, attenuation);
      return { valeurs: [r], message: traduire("msg.var_0_seuil_var_1_db_var_2", mode === "gate" ? "Gate" : "Expandeur", seuil, mode === "expander" ? ` · ratio ${ratio}:1` : "") };
   },
  },
  effet("transient-shaper", "Transient Shaper", "Transient Shaper", "Contrôle indépendant de l'attaque et du sustain.", "Independent attack and sustain control.",
    [param("Attaque", 0, "Attack", "dB", "Gain appliqué à l'attaque des transitoires. Positif = plus de punch ; négatif = moins agressif.", "Gain applied to transient attacks. Positive = more punch; negative = less aggressive.", [-12, 12], 0.5), param("Sustain", 0, "Sustain", "dB", "Gain appliqué au corps/sustain. Positif = plus de tenue ; négatif = plus court.", "Gain applied to the sustain body. Positive = more sustain; negative = shorter.", [-12, 12], 0.5), param("Temps attaque", 1, "Attack time", "ms", "Temps de réaction du détecteur de transitoires. Sans effet tant qu'Attaque et Sustain sont tous deux à 0 dB : le nœud laisse alors passer le son tel quel.", "Transient detector reaction time. No effect while Attack and Sustain are both at 0 dB: the node then passes the sound through unchanged.", [0.1, 50], 0.1), param("Temps sustain", 100, "Sustain time", "ms", "Temps de réaction du détecteur de sustain. Sans effet tant qu'Attaque et Sustain sont tous deux à 0 dB.", "Sustain detector reaction time. No effect while Attack and Sustain are both at 0 dB.", [10, 500], 1)],
    (a, attaque, sustain, tAttaque, tSustain) => transientShaper(a, attaque, sustain, tAttaque, tSustain),
    undefined,
    { parametre: "Attaque", bornes: [-12, 12], unite: "dB" }),
  effet("de-esser", "De-esser", "De-esser", "Compression dynamique des sibilances.", "Dynamic sibilance compression.",
    [param("Fréquence", 7000, "Frequency", "Hz", "Fréquence centrale de la bande cible (sibilances : 5-9 kHz).", "Center frequency of the target band (sibilances: 5-9 kHz).", [2000, 12000], 100),
     param("Largeur", 2000, "Width", "Hz", "Largeur de la bande cible (Q = fréquence/largeur).", "Width of the target band (Q = frequency/width).", [200, 6000], 100),
     param("Seuil", -20, "Threshold", "dB", "Niveau de la bande au-dessus duquel l'atténuation s'active.", "Band level above which attenuation engages.", [-60, 0], 1),
     param("Ratio", 3, "Ratio", "∶1", "Taux de réduction des sibilances.", "Sibilance reduction ratio.", [1, 10], 0.5),
     param("Attaque", 1, "Attack", "ms", "Temps de réaction (court = précis, long = doux).", "Reaction time (short = precise, long = smooth).", [0.1, 50], 0.1),
     param("Relâchement", 50, "Release", "ms", "Temps de retour au gain normal.", "Recovery time to normal gain.", [5, 500], 1)],
    (a,freq,largeur,seuil,ratio,att,rel) => deEsser(a, freq, largeur, seuil, ratio, att, rel),
    undefined,
    { parametre: "Seuil", bornes: [-60, 0], unite: "dB" }),
  effet("ring-modulator", "Ring modulator", "Ring Modulator", "Modulation en anneau (multiplication par porteuse).", "Ring modulation (carrier multiplication).",
    [param("Fréquence", 200, "Frequency", "Hz", "Fréquence de la porteuse. Produit des sommes et différences de fréquences (sidebands).", "Carrier frequency. Produces sum and difference frequencies (sidebands).", [1, 8000], 1),
     param("Mix", 100, "Mix", "%", "Équilibre signal original / effet.", "Dry/wet balance.")],
    (a,freq,mix) => ringModulator(a, freq, mix), undefined,
    { parametre: "Mix", bornes: [0, 100], unite: "%" }),
  {
    id: "vocoder", nom: "Vocoder", nomEn: "Vocoder",
    univers: "Traitement", famille: "Effets",
    resume: "Vocoder filterbank : modulateur + porteuse → effet robot.",
    resumeEn: "Filterbank vocoder: modulator + carrier → robot voice effect.",
    entrees: [{ nom: "Modulateur", nomEn: "Modulator", type: "audio" }, { nom: "Porteuse", nomEn: "Carrier", type: "audio" }, portModulation("Mix")],
    sorties: [{ nom: "Audio", type: "audio", sousType: "stereo" }],
    parametres: [
      { nom: "Bandes", nomEn: "Bands", type: "nombre", plage: [4, 16], pas: 1, defaut: 8, unite: "",
        doc: "Nombre de bandes passe-bande du vocoder. Plus de bandes = plus de précision spectrale.", docEn: "Number of vocoder filter bands. More bands = more spectral precision." },
      { nom: "Fréq min", nomEn: "Min freq", type: "nombre", plage: [80, 1000], pas: 10, defaut: 100, unite: "Hz",
        doc: "Fréquence la plus basse des bandes.", docEn: "Lowest band frequency." },
      { nom: "Fréq max", nomEn: "Max freq", type: "nombre", plage: [2000, 16000], pas: 100, defaut: 8000, unite: "Hz",
        doc: "Fréquence la plus haute des bandes.", docEn: "Highest band frequency." },
      { nom: "Q", nomEn: "Q", type: "nombre", plage: [0.5, 12], pas: 0.1, defaut: 2, unite: "",
        doc: "Facteur de qualité des filtres passe-bande. Plus élevé = bandes plus étroites.", docEn: "Bandpass filter quality factor. Higher = narrower bands." },
      { nom: "Mix", nomEn: "Mix", type: "nombre", plage: [0, 100], pas: 1, defaut: 50, unite: "%",
        doc: "Équilibre modulateur original / vocoder.",
        docEn: "Dry/wet balance." },
      ...bornesModulation(MODULATION_MIX),
    ],
    async executer(ctx: any) {
      const modulateur = ctx.entree(0);
      const porteuse = ctx.entree(1);
      if (!(modulateur instanceof AudioBuffer) || !(porteuse instanceof AudioBuffer)) return { valeurs: [null], message: traduire("msg.aucune_entr_e_audio") };
      const bands = ctx.paramNombre("Bandes", 8);
      const fMin = ctx.paramNombre("Fréq min", 100);
      const fMax = ctx.paramNombre("Fréq max", 8000);
      const Q = ctx.paramNombre("Q", 2);
      // LA SORTIE S'ARRÊTE AU PLUS COURT DES DEUX SONS, et la courbe se lit sur cette longueur :
      // l'étirer sur le modulateur seul la décalerait dès que la porteuse est plus brève.
      const mix = melangeModule(ctx, Math.min(modulateur.length, porteuse.length), 2,
        { reglage: "Mix", defaut: 50, rendu: "pourCent" });
      const out = await vocoder(modulateur, porteuse, bands, fMin, fMax, Q, mix);
      return { valeurs: [out] };
    },
  },
  // DEUX MODES, ET LE SECOND MANQUAIT DEPUIS LE DÉBUT. Attic MESURAIT la sonie — le VU-mètre rend
  // des LUFS — sans savoir y amener un son : normaliser à la crête est la réponse d'avant 2015.
  {
    id: "normaliseur", nom: "Normaliseur", nomEn: "Normalizer",
    univers: "Traitement", famille: "Effets",
    resume: "Amène le son à un niveau cible, en crête ou en sonie (LUFS).",
    resumeEn: "Brings the sound to a target level, by peak or by loudness (LUFS).",
    entrees: [{ nom: "Audio", type: "audio", sousType: "stereo" }],
    sorties: [{ nom: "Audio", type: "audio", sousType: "stereo" }],
    parametres: [
      { nom: "Mode", nomEn: "Mode", type: "choix",
        options: ["Crête", "Sonie (LUFS)"], optionsEn: ["Peak", "Loudness (LUFS)"],
        optionIds: ["crete", "sonie"], defaut: "Crête", defautEn: "Peak",
        doc: "Crête aligne le plus grand échantillon ; sonie aligne ce qui s'entend. Deux morceaux normalisés à la même crête peuvent différer de quinze décibels à l'oreille, une batterie sèche et une nappe compressée culminant toutes deux à 0 dBFS.",
        docEn: "Peak aligns the largest sample; loudness aligns what is heard. Two pieces normalised to the same peak can differ by fifteen decibels to the ear, a dry drum kit and a compressed pad both topping out at 0 dBFS." },
      { nom: "Niveau", nomEn: "Level", type: "curseur", plage: [-40, 0], pas: 0.5, defaut: -3, unite: "dB",
        doc: "Crête cible, en mode Crête. Ce réglage ne sert pas en mode Sonie.",
        docEn: "Target peak, in Peak mode. This setting does nothing in Loudness mode." },
      { nom: "Sonie cible", nomEn: "Target loudness", type: "curseur", plage: [-36, -6], pas: 0.5, defaut: -14, unite: "LUFS",
        doc: "Sonie visée, en mode Sonie. −14 est la cible des plateformes de diffusion, −23 celle de la norme EBU R 128 pour la télévision, −16 un usage courant en balado.",
        docEn: "Target loudness, in Loudness mode. -14 is the streaming platforms' target, -23 the EBU R 128 broadcast standard, -16 a common podcast value." },
      { nom: "Plafond", nomEn: "Ceiling", type: "curseur", plage: [-6, 0], pas: 0.1, defaut: -1, unite: "dBTP",
        doc: "Vrai pic à ne pas dépasser, en mode Sonie. Si la cible demandait de le franchir, le plafond gagne et le composant annonce que la cible n'est pas atteinte : il préfère le dire plutôt qu'écrêter en silence ou glisser un limiteur derrière un bouton qui promet seulement de normaliser. Mettez un limiteur en amont si vous voulez les deux.",
        docEn: "True peak not to be exceeded, in Loudness mode. If the target required crossing it, the ceiling wins and the node announces that the target was not reached: it prefers saying so to clipping silently or slipping a limiter behind a button that only promises to normalise. Put a limiter upstream if you want both." },
    ],
    async executer(ctx: any) {
      const audio = ctx.entree(0);
      if (!(audio instanceof AudioBuffer)) return { valeurs: [null], message: traduire("msg.aucune_entr_e") };
      if (ctx.paramTexte("Mode", "crete") === "crete") {
        const niveau = ctx.paramNombre("Niveau", -3);
        return { valeurs: [normaliser(audio, niveau)], message: traduire("msg.normaliseur.crete", niveau.toFixed(1)) };
      }
      const r = normaliserSonie(audio, ctx.paramNombre("Sonie cible", -14), { plafondDb: ctx.paramNombre("Plafond", -1) });
      const resume = traduire("msg.normaliseur.sonie",
        r.lufsAvant.toFixed(1), r.lufsApres.toFixed(1), (r.gainDb >= 0 ? "+" : "") + r.gainDb.toFixed(1), r.vraiPicDb.toFixed(1));
      return {
        valeurs: [r.audio],
        message: r.plafonne ? `${resume} — ${traduire("msg.normaliseur.plafonne")}` : resume,
      };
    },
  },
  effet("suppression-clics", "Suppression de clics", "Click Removal", "Détection et suppression de clicks.", "Click detection and removal.",
    [param("Seuil", 5, "Threshold", "×", "Sensibilité de détection (multiple de la dérivée médiane). Plus élevé = moins sensible (détecte seulement les gros clics). Plus bas = plus sensible.", "Detection sensitivity (multiple of median derivative). Higher = less sensitive (only big clicks). Lower = more sensitive.", [1, 50], 1),
     param("Fenêtre", 5, "Window", "ms", "Largeur de la fenêtre de remplacement.", "Replacement window width.")],
    (a,s,f) => supprimerClics(a, s, f),
    undefined,
    { parametre: "Seuil", bornes: [1, 50], unite: "×" }),
  effet("dereverberation", "Déréverbération", "Dereverb", "Atténuation de la réverbération.", "Reverb attenuation.",
    [param("Réduction", 60, "Reduction", "%", "Force de l'atténuation de la réverb.", "Reverb reduction strength.")],
    (a,r) => dererverberer(a, r)),
  effet("changement-tempo", "Changement de tempo", "Tempo Change", "Time-stretch via vocodeur de phase.", "Time-stretch via phase vocoder.",
    [param("Tempo (%)", 100, "Tempo (%)", "%", "Tempo cible. 100=normal, 50=moitié, 200=double.", "Target tempo. 100=normal, 50=half, 200=double.", [25, 400], 5), param("Fenêtre", 50, "Window", "ms", "Taille de la fenêtre d'analyse, ramenée à la puissance de deux d'échantillons la plus proche. Courte (10 à 30 ms), les attaques restent nettes mais les sons graves se brouillent ; longue (80 à 200 ms), les sons tenus restent lisses mais les attaques s'étalent.", "Analysis window size, rounded to the nearest power of two in samples. Short (10 to 30 ms), attacks stay sharp but low sounds blur; long (80 to 200 ms), held sounds stay smooth but attacks smear.", [5, 400], 5)],
    (a,t,f) => changerTempo(a, t, f)),
  effet("changement-tonalite", "Changement de tonalité", "Pitch Shift", "Pitch-shift.", "Pitch shift.",
    [param("Demi-tons", 2, "Semitones", "", "Transposition en demi-tons.", "Transposition in semitones.", [-24, 24], 1)],
    (a,d) => changerTonalite(a, d),
    {
      creerWorker: () => new Worker(new URL("../workers/tonalite-worker.ts", import.meta.url), { type: "module" }),
      voix: (x, o) => changerTonaliteVoie(x, o.demiTons),
      cles: ["demiTons"],
    }),
  effet("glissando-tonalite", "Glissando de tonalité", "Pitch Glissando", "Pitch-shift glissant d'une tonalité à une autre.", "Pitch glissando from one pitch to another.",
    [param("Début", 0, "Start", "st", "Hauteur de départ en demi-tons.", "Start pitch in semitones.", [-24, 24], 0.5),
     param("Fin", 12, "End", "st", "Hauteur d'arrivée en demi-tons.", "End pitch in semitones.", [-24, 24], 0.5)],
    (a,debut,fin) => glissandoTonalite(a, debut, fin),
    {
      creerWorker: () => new Worker(new URL("../workers/glissando-worker.ts", import.meta.url), { type: "module" }),
      voix: (x, o) => glissandoTonaliteVoie(x, o as unknown as OptionsGlissando),
      cles: ["debut", "fin"],
    }),
  effet("harmonizer", "Harmonizer / Octaver", "Harmonizer / Octaver", "Ajoute des voix pitch-shiftées (octave, quinte…) sous l'original.", "Adds pitch-shifted voices (octave, fifth…) under the original.",
    [param("Voix 1", 12, "Voice 1", "st", "Intervalle de la première voix en demi-tons. 12 = octave supérieure, -12 = octave inférieure, 7 = quinte.", "Interval of first voice in semitones. 12 = octave up, -12 = octave down, 7 = fifth.", [-24, 24], 1), param("Mix 1", 30, "Mix 1", "%", "Niveau de la première voix.", "Level of first voice.", [0, 100], 1), param("Voix 2", -12, "Voice 2", "st", "Intervalle de la deuxième voix en demi-tons.", "Interval of second voice in semitones.", [-24, 24], 1), param("Mix 2", 30, "Mix 2", "%", "Niveau de la deuxième voix.", "Level of second voice.", [0, 100], 1)],
    (a, v1, m1, v2, m2) => harmoniser(a, v1, m1, v2, m2),
    {
      creerWorker: () => new Worker(new URL("../workers/harmoniser-worker.ts", import.meta.url), { type: "module" }),
      voix: (x, o) => harmoniserVoie(x, o as unknown as OptionsHarmoniser),
      cles: ["interval1", "mix1", "interval2", "mix2"],
    }),
] as FicheAudio[]).map(avecDoc);
