// plugins/notices.ts — Couche de documentation (spec §3.9).
// Complète les fiches en « notice » (texte long, un clic) et en documentation
// de paramètres, de façon centralisée. Appliqué à l'enregistrement via
// `avecDoc(def)` : n'écrase jamais une doc déjà présente sur la fiche.
import type { FicheAudio } from "../audio/types-domaine";

type Bilingue = { fr: string; en: string };

// Notice par identifiant de composant.
const NOTICES: Record<string, Bilingue> = {
  // ── Entrées ──
  "entree-audio": { fr: "Charge un fichier audio (WAV, MP3, FLAC, OGG…) depuis l'inspecteur et le décode en signal exploitable par les autres blocs.", en: "Loads an audio file (WAV, MP3, FLAC, OGG…) from the inspector and decodes it into a signal usable by other blocks." },
  "enregistreur-audio": { fr: "Enregistre depuis le microphone ou l'entrée ligne. Choisissez le périphérique, lancez puis arrêtez l'enregistrement : le son capté devient la source audio du bloc.", en: "Records from the microphone or line input. Pick the device, start then stop recording: the captured sound becomes the block's audio source." },
  "capture-systeme-audio": { fr: "Capture le son du système (ce qui sort des haut-parleurs). Au lancement, Windows ouvre une boîte de dialogue de partage d'écran : sélectionnez l'écran ou la fenêtre, et assurez-vous que « Partager l'audio » est coché. Le son de n'importe quelle application (navigateur, lecteur, jeu) est alors capturé. Cliquez sur Arrêter pour finir la capture.", en: "Captures system audio (what comes out of the speakers). On start, Windows opens a screen share dialog: select the screen or window, and make sure « Share audio » is checked. Audio from any application (browser, player, game) is then captured. Click Stop to finish." },
  "explorateur-musique": { fr: "Parcourt un dossier de musiques du projet et charge le fichier choisi comme source audio (Electron).", en: "Browses a project music folder and loads the chosen file as an audio source (Electron)." },
  "lecteur-midi": { fr: "Charge un fichier MIDI depuis l'inspecteur et le synthétise en audio (FM ou SoundFont). Le fichier MIDI est aussi transmis sur la sortie MIDI, ce qui permet de le brancher sur un Transposeur/Quantiseur, un Arpégiateur ou une Sortie MIDI.", en: "Loads a MIDI file from the inspector and synthesizes it to audio (FM or SoundFont). The MIDI file is also passed on the MIDI output, allowing it to be connected to a Transposer/Quantizer, an Arpeggiator or a MIDI Output." },
  // ── Générateurs ──
  "generateur-accords": { fr: "Génère une progression d'accords à partir de la clé, la gamme et le genre. Chaque accord est arpégé sur trois octaves.", en: "Generates a chord progression from the key, scale and genre. Each chord is arpeggiated across three octaves." },
  "melodie-aleatoire": { fr: "Compose une mélodie aléatoire dans la clé et la gamme choisies, sur le nombre de mesures indiqué.", en: "Composes a random melody in the chosen key and scale, over the given number of bars." },
  "generateur-fractal": { fr: "Construit une pièce par récursion d'un motif d'intervalles sur plusieurs niveaux de profondeur, produisant une structure auto-similaire.", en: "Builds a piece by recursively applying an interval motif over several depth levels, producing a self-similar structure." },
  "boite-rythmes": { fr: "Génère une piste rythmique à partir d'un patron (Rock, Funk, House…) ou d'un code personnalisé, avec réglage du volume de chaque percussion.", en: "Generates a drum track from a pattern (Rock, Funk, House…) or a custom code, with per-drum volume control." },
  "clavier-melodie": { fr: "Rejoue une séquence de notes enregistrée au clavier virtuel du bloc et la synthétise en audio.", en: "Replays a sequence of notes recorded on the block's virtual keyboard and synthesizes it to audio." },
  "sampler-personnalise": { fr: "Utilise un échantillon audio comme instrument mélodique : l'échantillon est transposé pour jouer une mélodie dans la gamme choisie.", en: "Uses an audio sample as a melodic instrument: the sample is pitched to play a melody in the chosen scale." },
  // ── Effets ──
  "delay-stereo": { fr: "Répète le signal avec un délai réglable indépendamment à gauche et à droite, créant un effet d'écho stéréo. Le feedback règle le nombre de répétitions.", en: "Repeats the signal with an independently adjustable left/right delay, creating a stereo echo. Feedback sets the number of repeats." },
  "echo-ping-pong": { fr: "Écho dont les répétitions rebondissent alternativement entre les canaux gauche et droit.", en: "Echo whose repeats bounce alternately between the left and right channels." },
  "reverberation": { fr: "Simule l'acoustique d'une pièce par convolution. La taille et le decay définissent l'ampleur et la durée de la queue de réverbération.", en: "Simulates room acoustics via convolution. Size and decay set the extent and length of the reverb tail." },
  "reverbe-convolution": { fr: "Réverbération à convolution : génère une réponse impulsionnelle (IR) synthétique à partir de vos réglages (type de pièce, taille, decay, pre-delay, damping) et la convolue avec le signal. L'IR est la « signature acoustique » d'un espace : le convoleur la superpose au signal pour recréer son acoustique. Vous pouvez aussi charger un fichier IR externe (WAV) via le bouton du nœud — dans ce cas les paramètres de synthèse sont ignorés. Réglez le mix pour équilibrer le son direct et la réverbération.", en: "Convolution reverb: generates a synthetic impulse response (IR) from your settings (room type, size, decay, pre-delay, damping) and convolves it with the signal. The IR is the « acoustic signature » of a space: the convolver superimposes it onto the signal to recreate its acoustics. You can also load an external IR file (WAV) via the node button — in that case the synthesis parameters are ignored. Adjust the mix to balance dry and wet signals." },
  "reverb-progressive": { fr: "Réverbération dont le mélange évolue progressivement du son sec vers le son réverbéré sur une durée de fondu réglable.", en: "Reverb whose mix gradually evolves from dry to wet over an adjustable fade duration." },
  "dereverberation": { fr: "Atténue la réverbération d'un enregistrement par traitement spectral, pour resserrer un son trop réverbérant.", en: "Attenuates the reverberation of a recording via spectral processing, tightening an overly reverberant sound." },
  "distorsion": { fr: "Sature le signal pour ajouter de l'harmonique et du grain, du léger overdrive à la distorsion franche.", en: "Saturates the signal to add harmonics and grit, from light overdrive to full distortion." },
  "bitcrusher": { fr: "Simule la basse résolution des convertisseurs N/A anciens en réduisant le nombre de bits (quantification) et la fréquence d'échantillonnage (sous-échantillonnage). À 8 bits, on retrouve le son des consoles 8-bit ; à 4 bits, le son devient très crunch et aliased. Réduire la fréquence d'échantillonnage ajoute de l'aliasing (repliement de spectre) caractéristique. Idéal pour un effet rétro, lo-fi ou destructif. Le mix permet de doser l'effet sur le signal original.", en: "Simulates the low resolution of old D/A converters by reducing the bit depth (quantization) and sample rate (downsampling). At 8 bits, you get the 8-bit console sound; at 4 bits, the sound becomes very crunchy and aliased. Reducing the sample rate adds characteristic aliasing (spectral folding). Ideal for a retro, lo-fi or destructive effect. The mix controls the dry/wet balance." },
  "flanger": { fr: "Module un court délai variable pour produire un balayage caractéristique en « jet d'avion ».", en: "Modulates a short variable delay to produce the characteristic jet-plane sweep." },
  "chorus": { fr: "Superpose des copies légèrement désaccordées et modulées du signal pour l'épaissir et l'élargir en stéréo.", en: "Layers slightly detuned, modulated copies of the signal to thicken and widen it in stereo." },
  "compresseur": { fr: "Réduit la dynamique en atténuant les passages au-dessus du seuil, selon le ratio, l'attaque et le relâchement choisis.", en: "Reduces dynamics by attenuating passages above the threshold, according to the chosen ratio, attack and release." },
  "gate-expandeur": { fr: "Deux effets dynamiques en un seul nœud. Gate : coupe le signal quand il passe sous un seuil (utile pour éliminer le bruit de fond entre les phrases, le souffle, les résidus de réverbération). Expandeur : atténue渐进ment le signal sous le seuil selon un ratio (compresseur inversé — plus doux qu'un gate). Réglez le seuil (en dB), l'attaque et le relâchement (temps de transition), l'atténuation maximale du plancher (le niveau de coupure en mode Gate, la limite en mode Expandeur) et le ratio (mode Expandeur uniquement). Idéal pour nettoyer un enregistrement vocal ou instrumental.", en: "Two dynamic effects in one node. Gate: cuts the signal when it drops below a threshold (useful for removing background noise between phrases, hiss, reverb tails). Expander: gradually attenuates signal below threshold by a ratio (reverse compressor — gentler than a gate). Set the threshold (in dB), attack and release (transition times), maximum floor attenuation (cut level in Gate mode, limit in Expander mode) and ratio (Expander mode only). Ideal for cleaning up a vocal or instrumental recording." },
  "de-esser": { fr: "Atténue dynamiquement les sibilances (s, ch, sh, t, z) qui ressortent trop dans un enregistrement vocal. Fonctionne comme un compresseur ciblé sur une bande de fréquences étroite (typiquement 5-9 kHz) : un filtre passe-bande extrait l'énergie de la bande cible, et quand elle dépasse le seuil, un gain réducteur est appliqué au signal complet. Réglez la fréquence centrale et la largeur de la bande, le seuil (niveau d'activation), le ratio (force de la réduction), l'attaque et le relâchement. Attaque courte = réaction précise sur les transitoires ; relâchement moyen = transition naturelle.", en: "Dynamically attenuates sibilants (s, ch, sh, t, z) that stand out too much in a vocal recording. Works like a compressor targeted at a narrow frequency band (typically 5-9 kHz): a bandpass filter extracts the target band's energy, and when it exceeds the threshold, a reducing gain is applied to the full signal. Set the center frequency and band width, threshold (activation level), ratio (reduction strength), attack and release. Short attack = precise reaction to transients; medium release = natural transition." },
  "ring-modulator": { fr: "Multiplie le signal par une onde sinusoïdale (porteuse), produisant des sidebands — les sommes et différences de fréquences entre le signal et la porteuse. À une fréquence de porteuse donnée (ex. 200 Hz), une note de 440 Hz produit des composantes à 240 et 640 Hz. Effet caractéristique des sonneries de téléphone, des voix métalliques/robotiques et des textures alien. Réglez la fréquence de la porteuse (1-8000 Hz) et le mix (100% = effet seul).", en: "Multiplies the signal by a sine wave (carrier), producing sidebands — the sum and difference frequencies between the signal and the carrier. At a given carrier frequency (e.g. 200 Hz), a 440 Hz note produces components at 240 and 640 Hz. Characteristic effect of telephone rings, metallic/robotic voices and alien textures. Set the carrier frequency (1-8000 Hz) and mix (100% = effect only)." },
  "normaliseur": { fr: "Ajuste le gain global pour amener la crête du signal au niveau cible, sans modifier la dynamique.", en: "Adjusts overall gain to bring the signal peak to the target level, without changing dynamics." },
  "amplificateur": { fr: "Applique un gain constant en décibels pour amplifier ou atténuer l'ensemble du signal.", en: "Applies a constant gain in decibels to amplify or attenuate the whole signal." },
  "suppression-clics": { fr: "Détecte les clics et crépitements brefs et les remplace par une interpolation du signal voisin.", en: "Detects brief clicks and crackles and replaces them with an interpolation of the neighbouring signal." },
  "reduction-bruit": { fr: "Soustrait le bruit de fond du signal à partir d'un profil de bruit capturé sur un passage silencieux (bloc « Profil de bruit »).", en: "Subtracts background noise from the signal using a noise profile captured on a silent passage (« Noise Profile » block)." },
  "profil-bruit": { fr: "Analyse un passage de bruit seul et en produit un profil spectral, à brancher sur « Réduction de bruit ».", en: "Analyses a noise-only passage and produces a spectral profile, to feed into « Noise Reduction »." },
  "reponse-filtre": { fr: "Filtre le signal selon le type choisi (passe-bas, passe-haut, passe-bande, coupe-bande) avec une fréquence de coupure et une résonance (Q) réglables. La vue affiche en temps réel la courbe de réponse en fréquence du filtre (gain en dB par fréquence) — utile pour comprendre visuellement ce que le filtre fait au spectre. La courbe se met à jour instantanément quand on règle les paramètres, même avant exécution.", en: "Filters the signal by the chosen type (lowpass, highpass, bandpass, notch) with adjustable cutoff frequency and resonance (Q). The view displays the filter's frequency response curve (gain in dB per frequency) in real time — useful to visually understand what the filter does to the spectrum. The curve updates instantly as you change parameters, even before execution." },
  "equaliseur": { fr: "Égaliseur trois bandes : ajuste indépendamment le gain des basses, des médiums et des aigus.", en: "Three-band equalizer: independently adjusts the gain of lows, mids and highs." },
  "changement-tempo": { fr: "Accélère ou ralentit la piste en préservant la hauteur (vocodeur de phase). La durée change en proportion inverse de la vitesse.", en: "Speeds up or slows down the track while preserving pitch (phase vocoder). Duration changes inversely to speed." },
  "changement-tonalite": { fr: "Transpose la hauteur d'un nombre de demi-tons donné, sans modifier la durée de la piste.", en: "Transposes the pitch by a given number of semitones, without changing the track duration." },
  "inverseur-audio": { fr: "Inverse le signal dans le temps : la piste est lue de la fin vers le début.", en: "Reverses the signal in time: the track plays from end to start." },
  "echange-canaux": { fr: "Permute les canaux gauche et droit d'un signal stéréo.", en: "Swaps the left and right channels of a stereo signal." },
  "extraction-centre-cote": { fr: "Sépare la composante centrale (mono, commune aux deux canaux) des composantes latérales, avec dosage indépendant.", en: "Separates the center component (mono, common to both channels) from the side components, with independent balance." },
  "fondu": { fr: "Applique un fondu d'ouverture au début et un fondu de fermeture à la fin de la piste, de durées réglables.", en: "Applies a fade-in at the start and a fade-out at the end of the track, with adjustable durations." },
  "aligneur-piste": { fr: "Ajuste la longueur d'une piste à celle d'une référence. Entrée 1 (haut) = référence (passe inchangée). Entrée 2 (bas) = piste à aligner. Si la piste est trop courte : du silence est ajouté — au début (« Avant ») ou à la fin (« Après »). Si la piste est trop longue : un fade est appliqué — fade d'ouverture (« Avant », garde le début) ou fade de fermeture (« Après », garde la fin). La sortie 1 = référence inchangée, la sortie 2 = piste alignée (même longueur que la référence). Utile pour synchroniser des pistes de durées différentes avant de les fusionner ou les comparer.", en: "Aligns a track's length to a reference. Input 1 (top) = reference (passed through unchanged). Input 2 (bottom) = track to align. If the track is too short: silence is added — at the start (« Before ») or end (« After »). If too long: a fade is applied — fade in (« Before », keeps the start) or fade out (« After », keeps the end). Output 1 = reference unchanged, output 2 = aligned track (same length as reference). Useful for synchronizing tracks of different durations before merging or comparing them." },
  "extraire-zone": { fr: "Découpe une portion de la piste à partir d'un début et d'une durée, avec un léger fondu aux bords pour éviter les clics.", en: "Cuts out a portion of the track from a start and a duration, with a slight fade at the edges to avoid clicks." },
  "shift-formants": { fr: "Décalage formantique par analyse LPC. Sépare la voix en source glottale (hauteur) et filtre vocal (formants). Change la hauteur et les formants indépendamment — pas d'effet helium. Pour homme→femme : Hauteur +12, Formants 120%. Pour femme→homme : Hauteur −12, Formants 80%.", en: "Formant shifting via LPC analysis. Separates voice into glottal source (pitch) and vocal tract filter (formants). Change pitch and formants independently — no helium effect. For male→female: Pitch +12, Formants 120%. For female→male: Pitch −12, Formants 80%." },
  "ajouter-silence": { fr: "Ajoute du silence au début et/ou à la fin de la piste audio. Réglez indépendamment les durées de silence avant et après (en secondes, 0 à 60s). Utile pour caler une piste dans un mixage, créer un intro/outro silencieux, ou synchroniser avec une référence.", en: "Adds silence at the beginning and/or end of the audio track. Independently set the silence durations before and after (in seconds, 0 to 60s). Useful for fitting a track in a mix, creating a silent intro/outro, or syncing with a reference." },
  "tremolo": { fr: "Modulation d'amplitude : fait varier le volume périodiquement. Réglez la fréquence (vitesse des vibrations, 0.1 à 20 Hz), la profondeur (intensité, 0 à 100%) et la forme de l'onde (sinus, carré, triangle, sawtooth). Un effet classique pour les guitares et les orgues.", en: "Amplitude modulation: varies the volume periodically. Adjust the rate (vibration speed, 0.1 to 20 Hz), depth (intensity, 0 to 100%) and waveform shape (sine, square, triangle, sawtooth). A classic effect for guitars and organs." },
  "etirement-glissant": { fr: "Étirement temporel dont le facteur varie progressivement du début à la fin. Crée un effet d'accélération ou de décélération continue (effet « slide »). Réglez le facteur de début et de fin (0.25x à 4x) : par exemple début=1 (normal) et fin=4 (ralenti) crée un ralenti progressif. L'algorithme découpe le signal en segments, applique un phase vocoder avec un facteur interpolé, et recolle les segments avec un crossfade.", en: "Time-stretch with a factor that gradually changes from start to end. Creates a continuous acceleration or deceleration effect (\"slide\"). Set the start and end factors (0.25x to 4x): e.g. start=1 (normal) and end=4 (slow) creates a gradual slowdown. The algorithm slices the signal into segments, applies a phase vocoder with an interpolated factor, and rejoins segments with a crossfade." },
  "spatialisation-stereo": { fr: "Positionne un son mono ou stéréo dans l'espace stéréo. Utilise un PannerNode HRTF (Head-Related Transfer Function) pour une spatialisation binaurale réaliste. Position (-100% à 100%) contrôle la gauche/droite, Largeur (0% à 100%) contrôle l'étendue de l'effet. Utile pour placer un instrument dans un mixage ou créer un effet de mouvement spatial.", en: "Positions a mono or stereo sound in stereo space. Uses an HRTF PannerNode for realistic binaural spatialization. Position (-100% to 100%) controls left/right, Width (0% to 100%) controls the effect range. Useful for placing an instrument in a mix or creating a spatial movement effect." },
  "auto-pan": { fr: "Balayage stéréo automatique : le son se déplace périodiquement entre gauche et droite. Réglez la fréquence (vitesse du balayage, 0.1 à 20 Hz) et la profondeur (amplitude, 0 à 100%). À faible fréquence, crée un effet de flottement ; à haute fréquence, approche un effet Leslie/vibrato stéréo.", en: "Automatic stereo sweep: the sound moves periodically between left and right. Adjust the rate (sweep speed, 0.1 to 20 Hz) and depth (amplitude, 0 to 100%). At low frequencies, creates a floating effect; at high frequencies, approaches a Leslie/vibrato stereo effect." },
  "wahwah": { fr: "Filtre passe-bande dont la fréquence centrale est modulée par un LFO — l'effet pédale wah-wah classique. La fréquence centrale oscille entre 200 Hz et 2500 Hz. Réglez la vitesse (0.1 à 10 Hz), la profondeur (amplitude du balayage), la résonance (Q du filtre, élevé = wah prononcé) et le mix. Idéal sur les guitares électriques et les claviers.", en: "Bandpass filter with a LFO-modulated center frequency — the classic wah-wah pedal effect. The center frequency oscillates between 200 Hz and 2500 Hz. Adjust the rate (0.1 to 10 Hz), depth (sweep range), resonance (filter Q, high = pronounced wah) and mix. Ideal on electric guitars and keyboards." },
  "phaser": { fr: "Filtres passe-tout en cascade dont la fréquence de coupure est modulée par un LFO. Crée des crêtes et creux mobiles dans le spectre — l'effet « planant » caractéristique des synthés analogiques et des guitares (Van Halen, Pink Floyd). Réglez la vitesse, la profondeur, le nombre d'étages (2 à 8, plus = plus prononcé) et le mix.", en: "All-pass filter cascade with a LFO-modulated cutoff frequency. Creates moving peaks and notches in the spectrum — the \"sweeping\" effect characteristic of analog synths and guitars (Van Halen, Pink Floyd). Adjust rate, depth, number of stages (2 to 8, more = stronger) and mix." },
  "vibrato": { fr: "Modulation de hauteur par LFO : la note oscille autour de sa hauteur d'origine. Différent du pitch shift (qui transpose fixe) — le vibrato fait varier la hauteur périodiquement. Réglez la fréquence (vitesse, 0.1 à 20 Hz) et la profondeur (amplitude, 0 à ±2 demi-tons). Utilise un delay modulé pour préserver le timbre.", en: "Pitch modulation by LFO: the note oscillates around its original pitch. Different from pitch shift (which transposes statically) — vibrato varies the pitch periodically. Adjust the rate (speed, 0.1 to 20 Hz) and depth (amplitude, 0 to ±2 semitones). Uses a modulated delay to preserve timbre." },
  "octaver": { fr: "Ajoute une octave supérieure (doublement de fréquence par détection de zéros) et/ou une octave inférieure (décimation par 2). Réglez indépendamment le niveau de chaque octave et du signal original. Effet guitare classique (Boss OC-3, eventide). L'octave inférieure fonctionne mieux sur des signaux monophoniques (une note à la fois).", en: "Adds an upper octave (frequency doubling via zero-crossing) and/or a lower octave (decimation by 2). Adjust each octave level and dry signal independently. Classic guitar effect (Boss OC-3, eventide). The lower octave works best on monophonic signals (one note at a time)." },
  "chopper": { fr: "Gate rythmique qui coupe le son périodiquement — effet stutter/DJ. Réglez la fréquence (coups par seconde, 0.5 à 20 Hz), la durée du segment ON (1% = staccissimo, 50% = carré, 99% = quasi continu) et le type (Dur = coupure nette, Fondu = transition douce). Idéal pour créer des effets de pompage, de gating rythmique ou de tremolo extrême.", en: "Rhythmic gate that chops the sound periodically — stutter/DJ effect. Adjust the rate (cuts per second, 0.5 to 20 Hz), ON segment length (1% = very short, 50% = square, 99% = near continuous) and type (Hard = abrupt, Soft = smooth). Ideal for pumping effects, rhythmic gating or extreme tremolo." },
  "generateur-paroles": { fr: "Génère des paroles de chanson structurées (couplets, refrain, pont, outro) sans modèle d'IA — par templates et tirage aléatoire dans des dictionnaires de mots. Saisissez un thème, une émotion, choisissez la langue (FR/EN) et le nombre de lignes par section. La structure varie aléatoirement (4 modèles). Chaque ligne est générée à partir de 12 modèles de phrases combinant sujets, verbes, objets, adjectifs, lieux, émotions et connecteurs. La graine permet de reproduire exactement les mêmes paroles. Instantané, hors-ligne, aucun téléchargement. Résultat à brancher sur une Sortie texte ou un TTS.", en: "Generates structured song lyrics (verse, chorus, bridge, outro) without an AI model — using templates and random word selection from dictionaries. Enter a theme, an emotion, choose the language (FR/EN) and the number of lines per section. The structure varies randomly (4 models). Each line is generated from 12 sentence templates combining subjects, verbs, objects, adjectives, places, emotions and connectors. The seed allows reproducing the exact same lyrics. Instant, offline, no download. Output to connect to a Text Output or TTS node." },
  "melangeur": { fr: "Mélange plusieurs pistes en une seule sortie. Ajoutez autant d'entrées que nécessaire.", en: "Mixes several tracks into a single output. Add as many inputs as needed." },
  "reinserer-zone": { fr: "Replace une zone traitée à sa position d'origine dans la piste complète, avec un fondu enchaîné aux raccords. La position vient d'« Extraire durée » ou du sélecteur de zones.", en: "Puts a processed zone back at its original position in the full track, with a crossfade at the joins. The position comes from « Extract duration » or the zone selector." },
  "selecteur-multi-zones": { fr: "Affiche la forme d'onde et permet de sélectionner plusieurs zones (glisser puis « Ajouter »). La liste des zones est transmise sur la sortie « Zones ».", en: "Displays the waveform and lets you select several zones (drag then « Add »). The list of zones is passed on the « Zones » output." },
  "noms-instruments": { fr: "Émet sur sa sortie « Texte » une liste de noms d'instruments de musique (une centaine, réparties par famille : cordes, bois, cuivres, percussions, claviers, électronique, voix & monde). Choisissez une famille pour filtrer, et le format (virgule, retour ligne, puces). Utile comme source de texte ou de référence.", en: "Outputs a list of musical instrument names on its « Text » output (about a hundred, grouped by family: strings, woodwinds, brass, percussion, keyboards, electronic, voice & world). Pick a family to filter, and the format (comma, newline, bullets). Handy as a text or reference source." },
  "styles-musicaux": { fr: "Émet sur sa sortie « Texte » une large collection de styles musicaux (plus de 200, répartis par catégorie : rock, métal, pop, électronique, hip-hop/rap, jazz, blues/soul/funk, country/folk, reggae/latin, classique/contemporain, world/traditionnel). Choisissez une catégorie pour filtrer, et le format (virgule, retour ligne, puces). Utile comme source de texte, pour l'étiquetage ou la classification.", en: "Outputs a large collection of musical styles on its « Text » output (over 200, grouped by category: rock, metal, pop, electronic, hip-hop/rap, jazz, blues/soul/funk, country/folk, reggae/latin, classical/contemporary, world/traditional). Pick a category to filter, and the format (comma, newline, bullets). Handy as a text source, for tagging or classification." },
  "emotions": { fr: "Émet sur sa sortie « Texte » une collection d'émotions humaines (environ 160, réparties par catégorie : joie/bonheur, tristesse/mélancolie, colère/frustration, peur/anxiété, amour/tendresse, surprise/émerveillement, dégoût/rejet, mixte/complexe). Utile pour l'étiquetage de morceaux, la classification de sentiments ou comme source de texte.", en: "Outputs a collection of human emotions on its « Text » output (about 160, grouped by category: joy/happiness, sadness/melancholy, anger/frustration, fear/anxiety, love/tenderness, surprise/wonder, disgust/rejection, mixed/complex). Handy for track tagging, sentiment classification or as a text source." },
  "tessitures-voix": { fr: "Émet sur sa sortie « Texte » une collection de tessitures vocales classées par groupe (hommes, femmes, enfants). Chaque tessiture est accompagnée de sa plage approximative en notes (du grave à l'aigu). Inclut les catégories lyriques classiques (basse, baryton, ténor, contralto, mezzo-soprano, soprano et leurs sous-types) ainsi que les voix d'enfants.", en: "Outputs a collection of vocal ranges on its « Text » output, grouped by category (men, women, children). Each range includes its approximate note span (low to high). Covers classical lyric categories (bass, baritone, tenor, contralto, mezzo-soprano, soprano and their subtypes) as well as children's voices." },
  "generateur-script-ia": { fr: "Génère un prompt structuré pour un applicatif IA de génération musicale (Suno, Udio…). Branchez les sorties texte des nodes « Noms d'instruments », « Styles musicaux », « Émotions » et « Tessitures de voix » sur les 4 entrées correspondantes. Le node pioche aléatoirement un nombre configurable d'éléments dans chaque liste et compose un script avec : style, instruments, émotions, voix, un prompt en phrase et des tags. Une graine permet de reproduire un tirage. Les entrées sont facultatives — si une n'est pas branchée, elle est simplement ignorée.", en: "Generates a structured prompt for a music AI app (Suno, Udio…). Connect the text outputs of « Instrument Names », « Musical Styles », « Emotions » and « Vocal Ranges » nodes to the 4 corresponding inputs. The node randomly picks a configurable number of items from each list and composes a script with: style, instruments, emotions, vocals, a sentence prompt and tags. A seed allows reproducing a draw. Inputs are optional — if one is not connected, it is simply ignored." },
  "musicgen": { fr: "Génère de la musique depuis un prompt texte en utilisant MusicGen-small (facebook/musicgen-small, 300M de paramètres), exécuté en ONNX via Transformers.js. Le modèle se télécharge automatiquement depuis HuggingFace lors de la première utilisation (~300 MB, mis en cache par le navigateur). La génération est auto-régressive (séquentielle) et tourne dans un Web Worker pour ne pas bloquer l'interface. Écrivez un prompt descriptif en anglais (ex. « A happy upbeat pop song with electric guitars »), choisissez la durée (3-30 s) et le guidance (force du conditionnement). La première exécution est plus longue (téléchargement + chargement du modèle). Idéalement branché sur un node « Sortie audio » pour écouter le résultat.", en: "Generates music from a text prompt using MusicGen-small (facebook/musicgen-small, 300M parameters), run in ONNX via Transformers.js. The model auto-downloads from HuggingFace on first use (~300 MB, cached by the browser). Generation is auto-regressive (sequential) and runs in a Web Worker to avoid blocking the UI. Write a descriptive prompt in English (e.g. « A happy upbeat pop song with electric guitars »), set the duration (3-30 s) and guidance (conditioning strength). First run is slower (download + model loading). Ideally connected to an « Audio Output » node to listen to the result." },
  "source-texte": { fr: "Émet un texte saisi par l'utilisateur sur sa sortie texte (port bleu). Branchez-le sur un node de synthèse vocale (SpeechT5, MMS-TTS), un générateur de script IA ou tout autre node acceptant une entrée texte.", en: "Outputs user-entered text on its text output (blue port). Connect it to a text-to-speech node (SpeechT5, MMS-TTS), an AI script generator or any node accepting a text input." },
  "tts-speecht5": { fr: "Synthèse vocale haute qualité utilisant Microsoft SpeechT5. Branchez un node « Source de texte » sur l'entrée texte (port bleu). Le modèle génère de la parole en anglais avec une voix naturelle. Choisissez parmi 7 voix prédéfinies (embeddings CMU Arctic) : 2 femmes américaines (SLT, CLB), 2 hommes américains (BDL, RMS), 1 homme canadien (JMK), 1 homme écossais (AWB) et 1 homme indien (KSP). Le modèle se télécharge depuis HuggingFace au premier usage (~150 MB, mis en cache). Tourne dans un Web Worker.", en: "High-quality text-to-speech using Microsoft SpeechT5. Connect a « Text Source » node to the text input (blue port). The model generates English speech with a natural voice. Choose from 7 preset voices (CMU Arctic embeddings): 2 US females (SLT, CLB), 2 US males (BDL, RMS), 1 Canadian male (JMK), 1 Scottish male (AWB) and 1 Indian male (KSP). The model downloads from HuggingFace on first use (~150 MB, cached). Runs in a Web Worker." },
  "tts-mms": { fr: "Synthèse vocale multilingue utilisant Meta MMS (Massively Multilingual Speech). Branchez un node « Source de texte » sur l'entrée texte (port bleu). Choisissez la langue parmi 10+ options (anglais, français, espagnol, allemand, italien, portugais, néerlandais, roumain, polonais, russe). Chaque langue utilise un modèle MMS dédié qui se télécharge au premier usage (~60 MB chacun, mis en cache). Tourne dans un Web Worker.", en: "Multilingual text-to-speech using Meta MMS (Massively Multilingual Speech). Connect a « Text Source » node to the text input (blue port). Choose from 10+ languages (English, French, Spanish, German, Italian, Portuguese, Dutch, Romanian, Polish, Russian). Each language uses a dedicated MMS model that downloads on first use (~60 MB each, cached). Runs in a Web Worker." },
  "whisper-en": { fr: "Transcription vocale en anglais utilisant OpenAI Whisper (base). Branchez un signal audio (port vert) — par exemple un node « Entrée audio » ou « Enregistreur ». Le modèle transcrit le discours en texte et l'émet sur la sortie texte (port bleu). Le modèle se télécharge depuis HuggingFace au premier usage (~75 MB, mis en cache). Tourne dans un Web Worker. L'audio est automatiquement mixé en mono et rééchantillonné à 16 kHz.", en: "English speech recognition using OpenAI Whisper (base). Connect an audio signal (green port) — e.g. an « Audio Input » or « Recorder » node. The model transcribes the speech to text and outputs it on the text output (blue port). The model downloads from HuggingFace on first use (~75 MB, cached). Runs in a Web Worker. Audio is automatically mixed to mono and resampled to 16 kHz." },
  "whisper-multilingue": { fr: "Transcription vocale multilingue utilisant OpenAI Whisper Large v2 (99 langues). Branchez un signal audio (port vert). Choisissez la langue (ou « Auto » pour la détection automatique) et l'option de traduction vers l'anglais. Le texte transcrit est émis sur la sortie texte (port bleu). Le modèle se télécharge au premier usage (~1.5 GB, mis en cache) — la première transcription est plus longue. Tourne dans un Web Worker.", en: "Multilingual speech recognition using OpenAI Whisper Large v2 (99 languages). Connect an audio signal (green port). Choose the language (or « Auto » for automatic detection) and the translation-to-English option. The transcribed text is output on the text output (blue port). The model downloads on first use (~1.5 GB, cached) — the first transcription is slower. Runs in a Web Worker." },
  "traduction-whisper": { fr: "Traduit un texte de n'importe quelle langue vers l'anglais en chaînant un TTS (texte → audio) puis Whisper en mode traduction (audio → texte anglais). Branchez un node « Source de texte » sur l'entrée (port bleu, minimum 35 caractères). Choisissez la langue du texte d'entrée pour guider le TTS intermédiaire. Le texte traduit en anglais est émis sur la sortie (port bleu). Utile pour traduire sans modèle de traduction directe — Whisper comprend 99 langues. La première exécution télécharge les modèles TTS + Whisper (~1.6 GB au total, mis en cache).", en: "Translates text from any language to English by chaining a TTS (text → audio) then Whisper in translate mode (audio → English text). Connect a « Text Source » node to the input (blue port, minimum 35 characters). Choose the input text language to guide the intermediate TTS. The translated English text is output on the blue port. Useful for translation without a direct translation model — Whisper understands 99 languages. First run downloads TTS + Whisper models (~1.6 GB total, cached)." },
  "traduction-opus": { fr: "Traduit un texte entre paires de langues en utilisant OPUS-MT (Helsinki-NLP, modèles Marian). Branchez un node « Source de texte » sur l'entrée (port bleu). Choisissez la paire de langues (18 paires disponibles : français↔anglais, anglais↔espagnol, allemand, italien, japonais, chinois, russe, portugais, néerlandais, arabe, hindi). Chaque paire utilise un modèle dédié léger (~30 MB) qui se télécharge au premier usage et est mis en cache. Tourne dans un Web Worker. Traduction rapide et directe texte→texte.", en: "Translates text between language pairs using OPUS-MT (Helsinki-NLP, Marian models). Connect a « Text Source » node to the input (blue port). Choose the language pair (18 pairs available: French↔English, English↔Spanish, German, Italian, Japanese, Chinese, Russian, Portuguese, Dutch, Arabic, Hindi). Each pair uses a dedicated lightweight model (~30 MB) that downloads on first use and is cached. Runs in a Web Worker. Fast direct text→text translation." },
  "prompt-vers-graphe": { fr: "Génère un graphe de nodes sur le canevas depuis un prompt en langage naturel. Saisissez une description (ex : « delay stéréo avec feedback court sur une réverbération hall puis compresseur et sortie ») ou branchez un node « Source de texte ». Le parser reconnaît ~40 mots-clés en français et anglais : sources (entrée audio, bruit, oscillateur, séquenceurs, réservoir, MusicGen…), effets (delay, réverbération, distorsion, compresseur, filtre, EQ, bitcrusher, gate, de-esser, ring mod…), analyse (spectre, spectrogramme, VU-mètre, accords…) et sorties (sortie audio, MP3, WAV, point d'écoute). Les nodes détectés sont connectés en chaîne (source → effets → analyse → sortie) et ajoutés au canevas. Magique pour découvrir les possibilités de l'app sans connaître le catalogue.", en: "Generates a node graph on the canvas from a natural language prompt. Enter a description (e.g. « stereo delay with short feedback on a hall reverb then compressor and output ») or connect a « Text Source » node. The parser recognizes ~40 keywords in French and English: sources (audio input, noise, oscillator, sequencers, reservoir, MusicGen…), effects (delay, reverb, distortion, compressor, filter, EQ, bitcrusher, gate, de-esser, ring mod…), analysis (spectrum, spectrogram, VU-meter, chords…) and outputs (audio output, MP3, WAV, listening point). Detected nodes are chained (source → effects → analysis → output) and added to the canvas. Magical for discovering the app's possibilities without knowing the catalog." },
  "generateur-bruit": { fr: "Génère du bruit — un signal aléatoire utile pour tester filtres et enveloppes, ou comme matière sonore. Blanc : toutes les fréquences au même niveau (spectre plat, sifflant). Rose : −3 dB par octave, perçu équilibré (proche de la pluie). Brownien : −6 dB par octave, grave et sourd. Branchez-le sur l'Analyseur de spectre ou le Spectrogramme pour visualiser la coloration.", en: "Generates noise — a random signal handy for testing filters and envelopes, or as raw sound material. White: all frequencies at equal level (flat, hissy spectrum). Pink: −3 dB per octave, perceptually balanced (rain-like). Brownian: −6 dB per octave, dark and muffled. Connect it to the Spectrum Analyzer or Spectrogram to visualize the coloration." },
  "generateur-frequence": { fr: "Génère une tonalité pure à une fréquence précise. Deux modes de saisie : en Hertz (20-20000 Hz) ou en note musicale (format A4, C#5, Bb3). Quatre formes d'onde : sinus (une seule fréquence, pur), carré (harmoniques impaires, son riche), dent de scie (toutes les harmoniques, brillant) et triangle (harmoniques impaires douces). Un fondu entrée/sortie de 10 ms évite les clics. Idéal pour étalonner l'oreille, tester des filtres, accorder un instrument ou comme référence. Branchez-le sur l'Oscillateur pédagogique ou l'Analyseur de spectre pour visualiser la forme d'onde et le spectre.", en: "Generates a pure tone at a precise frequency. Two input modes: in Hertz (20-20000 Hz) or as a musical note (format A4, C#5, Bb3). Four waveforms: sine (single frequency, pure), square (odd harmonics, rich), sawtooth (all harmonics, bright) and triangle (soft odd harmonics). A 10 ms fade in/out avoids clicks. Ideal for ear training, testing filters, tuning an instrument or as a reference. Connect it to the Oscillator or Spectrum Analyzer to visualize the waveform and spectrum." },
  "metronome": { fr: "Génère un signal audio de métronome : un clic régulier à un tempo donné (40-240 BPM), avec signature rythmique (4/4, 3/4, 2/4, 6/8, 5/4, 7/8). Le premier temps de chaque mesure est accentué (plus fort et plus aigu). Trois timbres au choix : Clic (transitoire court, bruit), Woodblock (résonance bois) et Bip (sinus bref). Utile pour s'entraîner, caler un tempo de référence ou générer une piste de clic pour un enregistrement.", en: "Generates a metronome audio signal: a steady click at a given tempo (40-240 BPM), with time signature (4/4, 3/4, 2/4, 6/8, 5/4, 7/8). The first beat of each bar is accented (louder and higher). Three timbres: Click (short transient, noise), Woodblock (woody resonance) and Beep (brief sine). Useful for practice, setting a reference tempo or generating a click track for recording." },
  "reservoir-musical": { fr: "Génère une mélodie émergente par réseau de neurones aléatoires (Reservoir Computing), inspiré du plugin EVY d'Allendia (startup Inria). Un « réservoir » de quelques neurones à poids aléatoires fixes (non entraînés) fait circuler une impulsion rythmique. Les activations sont mappées sur une gamme pour produire des motifs mélodiques. Aucun entraînement, aucun dataset, aucun copyright — les motifs émergent de la structure aléatoire du réseau, comme un kaléidoscope. Paramètres : nombre de neurones (5-50, peu = motifs accrocheurs, beaucoup = complexe), connectivité, mémoire (leaking), rayon spectral (<100% = stable, >100% = chaotique), gamme, clé, octave, tempo, résolution, densité de notes, répétition, silence et graine. Graine non nulle = même réseau = même mélodie. Graine 0 = nouveau réseau aléatoire à chaque exécution.", en: "Generates emergent melody via random neural networks (Reservoir Computing), inspired by Allendia's EVY plugin (Inria startup). A \"reservoir\" of a few neurons with fixed random weights (untrained) circulates a rhythmic impulse. Activations are mapped to a scale to produce melodic patterns. No training, no dataset, no copyright — patterns emerge from the random network structure, like a kaleidoscope. Parameters: neuron count (5-50, few = catchy patterns, many = complex), connectivity, memory (leaking), spectral radius (<100% = stable, >100% = chaotic), scale, key, octave, tempo, resolution, note density, repetition, silence and seed. Non-zero seed = same network = same melody. Seed 0 = new random network each run." },
  "reservoir-midi": { fr: "Version MIDI du réservoir neuronal : génère un fichier MIDI au lieu d'audio. Branchez sa sortie MIDI sur un Transposeur/Quantiseur, un Arpégiateur ou une Sortie MIDI pour transformer la mélodie ou l'écouter avec un SoundFont. Mêmes paramètres que le réservoir audio (neurones, connectivité, mémoire, spectre, gamme, graine, etc.) mais sans paramètres de timbre/volume. Permet de chaîner plusieurs réservoirs avec des transformations MIDI intermédiaires.", en: "MIDI version of the neural reservoir: generates a MIDI file instead of audio. Connect its MIDI output to a Transposer/Quantizer, an Arpeggiator or a MIDI Output to transform the melody or listen with a SoundFont. Same parameters as the audio reservoir (neurons, connectivity, memory, spectral radius, scale, seed, etc.) but without timbre/volume parameters. Allows chaining multiple reservoirs with intermediate MIDI transformations." },
  "multi-reservoirs": { fr: "Quatre réservoirs neuronaux en réseau, chacun avec un rôle musical distinct : mélodie (voix principale, octave 4), basse (octave grave, mémoire longue), harmonie (notes tenues, peu denses) et rythme (détermine quand les autres jouent). Les réservoirs s'influencent mutuellement via le paramètre « Influence » : le rythme filtre les pas actifs des autres voix, créant une cohérence polyphonique émergente. Chaque réservoir a ses propres paramètres (neurones, connectivité) + paramètres globaux (clé, gamme, tempo, timbre, graine). Aucun entraînement — l'émergence naît de l'interaction entre réseaux aléatoires. Inspiré d'Allendia/EVY, poussé vers le polyphonique.", en: "Four neural reservoirs in network, each with a distinct musical role: melody (lead voice, octave 4), bass (low octave, long memory), harmony (held notes, sparse) and rhythm (determines when others play). The reservoirs influence each other via the « Influence » parameter: rhythm filters the active steps of other voices, creating emergent polyphonic coherence. Each reservoir has its own parameters (neurons, connectivity) + global parameters (key, scale, tempo, timbre, seed). No training — emergence arises from interaction between random networks. Inspired by Allendia/EVY, pushed towards polyphony." },
  "enveloppe-adsr": { fr: "Modèle le volume du son au cours du temps selon quatre réglages : Attaque (temps de montée au maximum), Déclin (descente vers le maintien), Maintien (niveau tenu, pas une durée) et Relâchement (retour au silence en fin de son). Attaque courte = son percussif ; longue = son qui gonfle. La courbe se met à jour en direct.", en: "Shapes the sound's volume over time with four controls: Attack (rise time to peak), Decay (fall to the sustain level), Sustain (held level, not a duration) and Release (return to silence at the end). Short attack = percussive; long = swelling. The curve updates live." },
  "sampler-midi": { fr: "Reçoit des notes MIDI en entrée et les joue avec un échantillon audio chargé dans l'inspecteur. Chaque note MIDI est transposée à partir de la « Note référence » (la hauteur d'origine de l'échantillon). La sortie audio contient la mélodie jouée avec le timbre de l'échantillon. La sortie MIDI passe les notes à travers inchangées, permettant de chaîner vers d'autres nodes MIDI. Branchez un Lecteur MIDI, un séquenceur ou un réservoir MIDI sur l'entrée, puis chargez un fichier audio court (percussion, voix, instrument) dans l'inspecteur.", en: "Receives MIDI notes at the input and plays them with an audio sample loaded from the inspector. Each MIDI note is transposed from the « Reference note » (the original pitch of the sample). The audio output contains the melody played with the sample's timbre. The MIDI output passes notes through unchanged, allowing chaining to other MIDI nodes. Connect a MIDI Player, a sequencer or a MIDI reservoir to the input, then load a short audio file (percussion, voice, instrument) in the inspector." },
  "point-ecoute-midi": { fr: "Point d'écoute intermédiaire pour le MIDI : permet d'auditionner le signal MIDI à un endroit de la chaîne sans l'interrompre. Le MIDI reçu est transmis tel quel sur la sortie.", en: "Intermediate listening point for MIDI: lets you audition the MIDI signal at a spot in the chain without interrupting it. The received MIDI is passed through unchanged to the output." },
  "sequenceur-batterie": { fr: "Programme un motif de batterie sur une grille pas-à-pas : cliquez les cases pour activer chaque instrument (grosse caisse, caisse claire, charleys, clap) à chaque pas. Les sons sont synthétisés (style boîte à rythmes), sans SoundFont. Réglez le tempo, le nombre de pas, le swing et le nombre de mesures ; la sortie audio boucle le motif.", en: "Programs a drum pattern on a step grid: click cells to trigger each instrument (kick, snare, hi-hats, clap) on each step. Sounds are synthesized (drum-machine style), no SoundFont. Set tempo, number of steps, swing and bars; the audio output loops the pattern." },
  "sequenceur-melodique": { fr: "Programme une mélodie sur une grille piano-roll pas-à-pas : chaque rangée est une note de la gamme (aigu en haut, grave en bas), chaque colonne est un pas. Cliquez les cases pour activer les notes. Les notes sont synthétisées au choix en triangle, carré, dent de scie ou sinus. Choisissez la clé, la gamme (majeur, mineur, pentatonique, blues), l'octave de départ, le tempo, le swing et le nombre de mesures ; la sortie audio boucle le motif. La fondamentale est surlignée en jaune dans les étiquettes.", en: "Programs a melody on a step-by-step piano-roll grid: each row is a scale note (high at top, low at bottom), each column is a step. Click cells to activate notes. Notes are synthesized with a choice of triangle, square, sawtooth or sine waveform. Choose the key, scale (major, minor, pentatonic, blues), starting octave, tempo, swing and number of bars; the audio output loops the pattern. The root note is highlighted in yellow in the labels." },
  "masque-zones": { fr: "Applique la liste de zones (venue du « Sélecteur multi-zones ») comme un masque sur l'audio. Option « Supprimer les zones » : le son est coupé dans les zones, le reste est conservé. Option « Conserver les zones » : seules les zones sont gardées, le reste est coupé. La piste garde sa durée ; un fondu aux bords évite les clics.", en: "Applies the zone list (from the « Multi-Zone Selector ») as a mask on the audio. « Mute zones » option: sound is cut inside the zones, the rest is kept. « Keep zones » option: only the zones are kept, the rest is cut. The track keeps its duration; an edge fade avoids clicks." },
  "extraire-zones-selecteur": { fr: "Extrait une zone temporelle précise de l'audio à partir de la liste de zones fournie par le « Sélecteur multi-zones ». Branchez la sortie « Zones » du sélecteur sur l'entrée « Zones » de ce node, et la sortie « Audio » du sélecteur sur l'entrée « Audio ». Choisissez le numéro de la zone à extraire (1 = première zone sélectionnée). Le node découpe l'audio exactement à cette position et applique un fondu aux bords. Contrairement au « Masque de zones » qui garde la durée totale, ce node ne renvoie que la zone extraite (durée = durée de la zone).", en: "Extracts a precise time zone from the audio based on the zone list provided by the « Multi-Zone Selector ». Connect the selector's « Zones » output to this node's « Zones » input, and the selector's « Audio » output to the « Audio » input. Choose the zone number to extract (1 = first selected zone). The node cuts the audio at that exact position and applies edge fades. Unlike « Zone Mask » which keeps the total duration, this node returns only the extracted zone (duration = zone duration)." },
  "placer-sons-zones": { fr: "Crée une piste silencieuse de la durée fournie et y insère une copie du son reçu, centrée sur chaque zone de la liste.", en: "Creates a silent track of the given duration and inserts a copy of the received sound, centered on each zone in the list." },
  // ── Analyse / Visualisation ──
  "analyse-audio": { fr: "Estime le tempo, la tonalité et le type (chanson / instrumental) de la piste et en produit une description texte.", en: "Estimates the tempo, key and type (song / instrumental) of the track and produces a text description." },
  "lecteur-analyse": { fr: "Affiche le résultat d'une analyse et permet d'écouter l'audio associé.", en: "Displays an analysis result and lets you listen to the associated audio." },
  "classificateur-genre": { fr: "Identifie le genre musical de la piste, par modèle ONNX ou par heuristiques sur les caractéristiques audio.", en: "Identifies the musical genre of the track, via an ONNX model or heuristics on audio features." },
  "transcripteur-midi": { fr: "Transcrit l'audio en notes MIDI, par détection de hauteur monophonique (FFT) ou polyphonique (Basic Pitch ONNX).", en: "Transcribes audio into MIDI notes, via monophonic pitch detection (FFT) or polyphonic (Basic Pitch ONNX)." },
  "detecteur-accords": { fr: "Analyse le signal audio et détecte la progression d'accords au fil du temps. Pour chaque fenêtre d'analyse, un chromagramme (vecteur de 12 classes de hauteur) est calculé puis comparé à des templates d'accords (majeur, mineur, 7ᵉ, mineur 7ᵉ, majeur 7ᵉ, diminué, augmenté, sus2, sus4, mineur 7♭5) par corrélation. Le résultat est une liste d'accords avec leur horodatage et durée. Réglez la fenêtre d'analyse : courte (0,2-0,5 s) pour détecter les changements rapides, longue (1-2 s) pour plus de stabilité. Le signal audio est retransmis inchangé sur la sortie Audio.", en: "Analyzes the audio signal and detects the chord progression over time. For each analysis window, a chromagram (12 pitch-class vector) is computed and compared against chord templates (major, minor, 7th, minor 7th, major 7th, diminished, augmented, sus2, sus4, minor 7b5) by correlation. The result is a list of chords with their timestamp and duration. Adjust the analysis window: short (0.2-0.5 s) for fast changes, long (1-2 s) for more stability. The audio signal is passed through unchanged on the Audio output." },
  "vu-metre": { fr: "Mesure et affiche les niveaux audio en temps réel. Quatre bargraphes verticaux : RMS (niveau moyen en dBFS), Peak (crête en dBFS), True Peak (crête interpolée 4× en dBTP, pour détecter l'inter-échantillon) et LUFS (loudness normalisée ITU-R BS.1770 avec filtre K-weighting). Affiche aussi le facteur de crête (crest factor = peak − RMS, indique la dynamique), la plage dynamique (LRA approximative) et les LUFS min/max momentanées. Le signal est retransmis inchangé. Utile pour vérifier les niveaux avant export, comparer des mixes ou calibrer du matériel.", en: "Measures and displays audio levels in real time. Four vertical bargraphs: RMS (average level in dBFS), Peak (in dBFS), True Peak (4× interpolated peak in dBTP, to detect inter-sample peaks) and LUFS (ITU-R BS.1770 loudness with K-weighting filter). Also shows the crest factor (peak − RMS, indicates dynamics), dynamic range (approximate LRA) and min/max momentary LUFS. The signal is passed through unchanged. Useful for checking levels before export, comparing mixes or calibrating equipment." },
  "colorsynth": { fr: "L'inverse du node « Combinaison de couleurs » : écoute le signal audio et déduit une palette de 6 couleurs à partir du spectre. Le spectre est divisé en 6 bandes (Sub, Bass, Low-Mid, Mid, High, Air) et chaque bande est mappée vers une couleur HSL : graves = couleurs chaudes (rouge/orange), médiums = vert, aigus = couleurs froides (bleu/violet). L'intensité lumineuse de chaque couleur = l'énergie de la bande. Pédagogique : « voir » le timbre — un son brillant aura des couleurs froides dominantes, un son grave des couleurs chaudes. Branchez-le après un filtre, un EQ ou un oscillateur pour visualiser comment le traitement modifie le spectre.", en: "The inverse of the « Color Combination » node: listens to the audio signal and derives a palette of 6 colors from the spectrum. The spectrum is divided into 6 bands (Sub, Bass, Low-Mid, Mid, High, Air) and each band is mapped to an HSL color: lows = warm colors (red/orange), mids = green, highs = cool colors (blue/violet). The brightness of each color = the band's energy. Educational: « see » the timbre — a bright sound will have dominant cool colors, a bass-heavy sound warm colors. Connect it after a filter, EQ or oscillator to visualize how processing modifies the spectrum." },
  "generateur-pochette": { fr: "Génère une pochette d'album procédurale par synthèse canvas — hors-ligne, instantané, sans GPU ni téléchargement. Saisissez un prompt (les couleurs sont déduites des mots-clés : feu/rouge, eau/bleu, nature/vert, nuit/noir, jour/jaune, rêve/violet, terre/marron…), un titre et un artiste (insérés dans l'image avec typographie), choisissez un style visuel (minimaliste, géométrique, vagues, grain, concentrique, bauhaus) et une graine. Le canvas génère un PNG 512×512 téléchargeable. Idéal pour créer rapidement une pochette stylée dans l'esprit des pochettes indépendantes/minimalistes. La graine permet de reproduire exactement la même pochette.", en: "Generates procedural album cover art via canvas synthesis — offline, instant, no GPU or download. Enter a prompt (colors derived from keywords: fire/red, water/blue, nature/green, night/black, day/yellow, dream/purple, earth/brown…), a title and artist (inserted in the image with typography), choose a visual style (minimalist, geometric, waves, grain, concentric, bauhaus) and a seed. The canvas generates a downloadable 512×512 PNG. Ideal for quickly creating stylish covers in the indie/minimalist spirit. The seed allows reproducing the exact same cover." },
  "gpt2-paroles": { fr: "Génère des paroles de chanson ou de la poésie par IA en utilisant DistilGPT-2 (Transformers.js, ONNX). Branchez une « Source de texte » ou saisissez un prompt directement. Le modèle génère du texte à partir du prompt (en anglais pour de meilleurs résultats). Réglez la longueur (30-300 tokens), la créativité (température 0.1-1.5) et la pénalité de répétition. Le modèle se télécharge depuis HuggingFace au premier usage (~330 MB, mis en cache). Tourne dans un Web Worker. Idéal pour amorcer une inspiration ou générer des paroles inhabituelles.", en: "Generates song lyrics or poetry via AI using DistilGPT-2 (Transformers.js, ONNX). Connect a « Text Source » or enter a prompt directly. The model generates text from the prompt (English for best results). Adjust length (30-300 tokens), creativity (temperature 0.1-1.5) and repetition penalty. The model downloads from HuggingFace on first use (~330 MB, cached). Runs in a Web Worker. Ideal for sparking inspiration or generating unusual lyrics." },
  "reservoir-textuel": { fr: "Génère du texte par réseau de neurones aléatoires (Reservoir Computing), sans aucun entraînement ni dataset. Un réservoir de quelques neurones à poids aléatoires fait circuler des impulsions. Les activations sont mappées vers des lettres d'un alphabet pour produire des mots émergents. Le résultat est du texte « alien » — des mots qui n'existent pas mais qui ont une structure phonétique cohérente. Inspiré d'Allendia/EVY appliqué au langage. Paramètres : neurones (5-50), connectivité, mémoire, nombre de mots, alphabet (latin, voyelles-first, français avec accents), mot d'amorce et graine. Utile pour générer des noms de chansons, des paroles phonétiques ou de la poésie concrète.", en: "Generates text via random neural networks (Reservoir Computing), with no training or dataset. A reservoir of a few neurons with random weights circulates impulses. Activations are mapped to alphabet letters to produce emergent words. The result is « alien » text — words that don't exist but have a coherent phonetic structure. Inspired by Allendia/EVY applied to language. Parameters: neurons (5-50), connectivity, memory, word count, alphabet (Latin, vowels-first, French with accents), seed word and seed. Useful for generating song titles, phonetic lyrics or concrete poetry." },
  "nllb-paroles": { fr: "Génère des paroles multilingues par IA en deux étapes : (1) DistilGPT-2 génère les paroles en anglais à partir du prompt, (2) OPUS-MT traduit les paroles vers la langue cible choisie (français, espagnol, allemand, italien, portugais, russe, japonais, chinois, arabe, hindi). Branchez une « Entrée texte » ou saisissez un prompt en anglais pour de meilleurs résultats. Le premier usage télécharge DistilGPT-2 (~330 MB) puis le modèle de traduction (~30 MB), tous deux mis en cache. Si la traduction échoue, les paroles en anglais sont renvoyées. Tourne dans des Web Workers.", en: "Generates multilingual lyrics via AI in two steps: (1) DistilGPT-2 generates lyrics in English from the prompt, (2) OPUS-MT translates the lyrics to the chosen target language (French, Spanish, German, Italian, Portuguese, Russian, Japanese, Chinese, Arabic, Hindi). Connect a « Text Input » or enter a prompt in English for best results. First use downloads DistilGPT-2 (~330 MB) then the translation model (~30 MB), both cached. If translation fails, the English lyrics are returned. Runs in Web Workers." },
  "galerie-exposition": { fr: "Génère une galerie HTML visuelle avec pochettes depuis un répertoire de MP3. Spécifiez le répertoire source (.mp3 uniquement), un répertoire de sortie et un titre. Le node crée un fichier index.html à la racine + copie les MP3 dans un sous-répertoire mp3/. Chaque piste a une pochette : extraite du tag ID3 du MP3 si disponible, sinon générée procéduralement (SVG). Nécessite Electron.", en: "Generates a visual HTML gallery with cover art from a directory of MP3 files. Each track cover is extracted from the MP3's ID3 tag if available, otherwise procedurally generated (SVG). Requires Electron." },
  "gestion-nodes": { fr: "Exporte un node existant en archive .zip ou importe un node depuis un .zip. Pour exporter : saisissez l'ID du node (ex : gpt2-paroles), le système extrait le manifest, le code executer, la notice et détecte les dépendances externes, puis génère un .zip. Pour importer : sélectionnez un .zip, le système décompresse, vérifie les dépendances et installe le node dans le catalogue. Les nodes installés sont persistés et survivent aux redémarrages.", en: "Exports an existing node as a .zip archive or imports a node from a .zip. To export: enter the node ID, the system extracts the manifest, executer code, notice and detects dependencies, then generates a .zip. To import: select a .zip, the system decompresses, checks dependencies and installs the node in the catalog. Installed nodes are persisted and survive restarts." },
  "python-processor": { fr: "Éditeur de code Python avec coloration syntaxique pour traiter l'audio. L'audio d'entrée est converti en WAV temporaire et passé au script via sys.argv[1]. Le script doit écrire le résultat dans le chemin donné par os.environ['ATTIC_OUTPUT_PATH']. Variables disponibles : ATTIC_SAMPLE_RATE, ATTIC_CHANNELS. Le code par défaut lit le WAV, double le volume et écrit le résultat. Nécessite Python + numpy installés sur la machine. La détection de Python est automatique (python, python3, py) ou via la variable d'environnement ATTIC_PYTHON. Timeout réglable (5-120s).", en: "Python code editor with syntax highlighting for audio processing. Input audio is converted to a temporary WAV and passed to the script via sys.argv[1]. The script must write the result to the path given by os.environ['ATTIC_OUTPUT_PATH']. Available variables: ATTIC_SAMPLE_RATE, ATTIC_CHANNELS. The default code reads the WAV, doubles the volume and writes the result. Requires Python + numpy installed on the machine. Python detection is automatic (python, python3, py) or via the ATTIC_PYTHON environment variable. Adjustable timeout (5-120s)." },
  "julia-processor": { fr: "Éditeur de code Julia avec coloration syntaxique pour traiter l'audio, le MIDI et le texte. Même architecture que le Python Processor. Variables : ARGS[2] = WAV d'entrée, ENV[\"ATTIC_OUTPUT_PATH\"] = WAV de sortie, ENV[\"ATTIC_SAMPLE_RATE\"], ENV[\"ATTIC_CHANNELS\"]. Nécessite Julia + le package WAV.jl installés sur la machine.", en: "Julia code editor with syntax highlighting for audio, MIDI and text processing. Same architecture as the Python Processor. Variables: ARGS[2] = input WAV, ENV[\"ATTIC_OUTPUT_PATH\"] = output WAV, ENV[\"ATTIC_SAMPLE_RATE\"], ENV[\"ATTIC_CHANNELS\"]. Requires Julia + WAV.jl package installed." },
  "couleur-suno-ia": { fr: "Génère un script Suno/Udio par IA en combinant la psychologie des couleurs et un LLM (DistilGPT-2). Sélectionnez 1 ou 2 couleurs — chaque couleur est mappée vers un profil musical (émotion, mode, tempo, instruments, styles, voix). Le profil structuré est ensuite enrichi par le LLM qui génère un prompt créatif et unique. La variabilité (0-100%) contrôle la température du LLM : élevée = scripts très créatifs et différents à chaque fois ; basse = scripts proches du template. La graine assure la reproductibilité. Le script final combine le profil structuré + le prompt IA + les tags. Dépendance : @huggingface/transformers (téléchargement du modèle au premier usage, ~330 MB, mis en cache).", en: "Generates a Suno/Udio script via AI by combining color psychology and a LLM (DistilGPT-2). Select 1 or 2 colors — each color is mapped to a musical profile (emotion, mode, tempo, instruments, styles, vocals). The structured profile is then enriched by the LLM which generates a creative and unique prompt. Variability (0-100%) controls the LLM temperature: high = very creative and different scripts each time; low = scripts close to the template. The seed ensures reproducibility. The final script combines the structured profile + AI prompt + tags. Dependency: @huggingface/transformers (model download on first use, ~330 MB, cached)." },
  "transposeur-quantiseur-midi": { fr: "Reçoit un fichier MIDI et le transforme : transposition (±24 demi-tons) et/ou quantification rythmique (alignement des départs de notes sur une grille : 1/4, 1/8, 1/16, 1/32, triplets). Option pour quantifier aussi les fins de notes. Le fichier transformé est émis sur la sortie MIDI — branchez-le sur un node « Sortie MIDI » pour l'écouter. Utile pour corriger un enregistrement humain imprécis ou adapter une mélodie à une autre tonalité.", en: "Takes a MIDI file and transforms it: transposition (±24 semitones) and/or rhythmic quantization (snapping note onsets to a grid: 1/4, 1/8, 1/16, 1/32, triplets). Option to also quantize note ends. The transformed file is output on the MIDI port — connect it to a « MIDI Output » node to listen. Useful for correcting imprecise human recordings or adapting a melody to another key." },
  "arpegiateur-midi": { fr: "Transforme les accords d'un fichier MIDI en arpèges. Détecte les notes simultanées (accords) et les réarpège selon une direction (montant, descendant, aller-retour, aléatoire), un motif de répétition intra-accord (1232, 1321…), une vitesse (1/8, 1/16, 1/32, triplets) et une amplitude en octaves (1-4, chaque octave ajoute +12 demi-tons). La durée des notes est réglable (staccato à legato). Le fichier transformé est émis sur la sortie MIDI — branchez-le sur un node « Sortie MIDI » pour l'écouter.", en: "Turns chords from a MIDI file into arpeggios. Detects simultaneous notes (chords) and arpeggiates them according to a direction (up, down, up-down, random), an intra-chord repetition pattern (1232, 1321…), a speed (1/8, 1/16, 1/32, triplets) and an octave span (1-4, each octave adds +12 semitones). Note length is adjustable (staccato to legato). The transformed file is output on the MIDI port — connect it to a « MIDI Output » node to listen." },
  "visualiseur-forme-onde": { fr: "Affiche la forme d'onde du signal reçu, avec zoom à la molette, et le retransmet inchangé.", en: "Displays the waveform of the received signal, with wheel zoom, and passes it through unchanged." },
  "analyseur-spectre": { fr: "Décompose le signal en ses fréquences (transformée de Fourier rapide) et en affiche le spectre : niveau (dB) par fréquence, moyenné sur toute la piste. Choisissez la taille de fenêtre FFT (résolution) et l'échelle (log/linéaire). Le signal est retransmis inchangé.", en: "Decomposes the signal into its frequencies (fast Fourier transform) and displays the spectrum: level (dB) per frequency, averaged over the whole track. Choose the FFT window size (resolution) and axis scale (log/linear). The signal is passed through unchanged." },
  "spectrogramme": { fr: "Affiche l'évolution du spectre dans le temps : axe horizontal = temps, axe vertical = fréquence, couleur = intensité (sombre → clair). On y voit apparaître les notes, harmoniques et transitoires. Réglez la fenêtre FFT (compromis temps/fréquence) et l'échelle. Le signal est retransmis inchangé.", en: "Shows how the spectrum evolves over time: horizontal = time, vertical = frequency, color = intensity (dark → bright). Notes, harmonics and transients appear. Set the FFT window (time/frequency trade-off) and scale. The signal is passed through unchanged." },
  "oscillateur": { fr: "Génère une forme d'onde pure par synthèse additive (somme d'harmoniques, sans repliement). La vue montre en haut quelques périodes de l'onde et en bas ses harmoniques : un sinus = une seule barre ; carré/triangle = harmoniques impaires ; dent de scie = toutes. Illustre le lien timbre ↔ harmoniques.", en: "Generates a pure waveform by additive synthesis (sum of harmonics, alias-free). The view shows a few periods of the wave on top and its harmonics below: a sine = a single bar; square/triangle = odd harmonics; sawtooth = all of them. Illustrates the timbre ↔ harmonics link." },
  "comparateur-ab": { fr: "Compare deux sources (A et B) en basculant l'écoute d'un bouton, à niveau égalisé pour une comparaison honnête (le plus fort semble sinon meilleur). Idéal pour juger l'effet d'un traitement : branchez le signal d'origine en A et le signal traité en B.", en: "Compares two sources (A and B) by toggling which one you hear, at matched level for a fair comparison (the louder one otherwise seems better). Ideal to judge the effect of a process: connect the original signal to A and the processed one to B." },
  // ── Conversion / Sorties ──
  "convertisseur-audio": { fr: "Encode le signal en MP3 téléchargeable à la qualité choisie, tout en le laissant passer sur la sortie audio.", en: "Encodes the signal into a downloadable MP3 at the chosen quality, while passing it through on the audio output." },
  "convertisseur-mp3-wav": { fr: "Met le signal à disposition en WAV téléchargeable, tout en le laissant passer sur la sortie audio.", en: "Makes the signal available as a downloadable WAV, while passing it through on the audio output." },
  "point-ecoute": { fr: "Point d'écoute intermédiaire : permet d'auditionner le signal à un endroit de la chaîne sans l'interrompre.", en: "Intermediate listening point: lets you audition the signal at a spot in the chain without interrupting it." },
  "sortie-audio": { fr: "Point d'écoute final : joue le signal reçu, applique le volume et permet l'export. Fournit aussi la durée de la piste.", en: "Final output: plays the received signal, applies the volume and enables export. Also provides the track duration." },
  "sortie-texte": { fr: "Affiche le texte reçu sur son entrée (port bleu). Le texte s'affiche dans le nœud avec un bouton de copie (⧉) pour le coller ailleurs. Branchez-y la sortie d'un générateur de script IA, d'un traducteur, d'un détecteur d'accords, de paroles générées par IA ou de tout autre node produisant du texte.", en: "Displays the text received on its input (blue port). The text is shown in the node with a copy button (⧉) to paste elsewhere. Connect the output of an AI script generator, translator, chord detector, AI-generated lyrics or any other text-producing node." },
  "sortie-midi": { fr: "Reçoit un fichier MIDI, le synthétise en audio (FM ou SoundFont) et transmet à la fois l'audio, le MIDI et la durée.", en: "Receives a MIDI file, synthesizes it to audio (FM or SoundFont) and passes along the audio, the MIDI and the duration." },
  // ── Collections ──
  "collection-vers-mp3": { fr: "Traite par lot un dossier : convertit tous les fichiers audio (WAV, OGG…) en MP3 dans le dossier de sortie (Electron).", en: "Batch-processes a folder: converts all audio files (WAV, OGG…) to MP3 in the output folder (Electron)." },
  "collection-mp3-vers-wav": { fr: "Traite par lot un dossier : convertit tous les MP3 en WAV dans le dossier de sortie (Electron).", en: "Batch-processes a folder: converts all MP3 files to WAV in the output folder (Electron)." },
  "collection-midi-vers-mp3": { fr: "Traite par lot un dossier : synthétise tous les fichiers MIDI et les exporte en MP3 dans le dossier de sortie (Electron).", en: "Batch-processes a folder: synthesizes all MIDI files and exports them as MP3 in the output folder (Electron)." },
};

// Documentation générique par nom de paramètre (commun à plusieurs blocs).
const DOCS_PARAM: Record<string, Bilingue> = {
  "Périphérique": { fr: "Périphérique d'entrée micro à utiliser pour l'enregistrement.", en: "Microphone input device to use for recording." },
  "Genre": { fr: "Style musical, qui oriente les choix harmoniques et rythmiques.", en: "Musical style, which guides the harmonic and rhythmic choices." },
  "Clé": { fr: "Note fondamentale (tonique) de la gamme.", en: "Root note (tonic) of the scale." },
  "Gamme": { fr: "Gamme utilisée pour choisir les notes (majeur, mineur, pentatonique…).", en: "Scale used to pick notes (major, minor, pentatonic…)." },
  "Tempo": { fr: "Vitesse en battements par minute (BPM).", en: "Speed in beats per minute (BPM)." },
  "Durée": { fr: "Durée générée, en secondes.", en: "Generated duration, in seconds." },
  "Volume": { fr: "Niveau de sortie, de 0 (silence) à 100 %.", en: "Output level, from 0 (silence) to 100%." },
  "Mesures": { fr: "Nombre de mesures à générer.", en: "Number of bars to generate." },
  "Signature temporelle": { fr: "Signature rythmique (4/4, 3/4, 6/8…).", en: "Time signature (4/4, 3/4, 6/8…)." },
  "Réduction": { fr: "Force de l'atténuation, de 0 à 100 %.", en: "Attenuation strength, from 0 to 100%." },
  "Mode": { fr: "Méthode utilisée (modèle IA ou heuristique).", en: "Method used (AI model or heuristic)." },
  "Synthèse": { fr: "Moteur de synthèse : FM/Oscillateurs (local) ou SoundFont (échantillons).", en: "Synthesis engine: FM/Oscillators (local) or SoundFont (samples)." },
  "Gain": { fr: "Gain appliqué au signal, en décibels.", en: "Gain applied to the signal, in decibels." },
  "Fondu": { fr: "Durée du fondu enchaîné aux raccords, pour éviter un clic audible.", en: "Crossfade duration at joins, to avoid an audible click." },
  "Qualité": { fr: "Débit d'encodage MP3, en kbps (plus élevé = meilleure qualité, fichier plus lourd).", en: "MP3 encoding bitrate, in kbps (higher = better quality, larger file)." },
  "Dossier entrée": { fr: "Dossier contenant les fichiers à traiter.", en: "Folder containing the files to process." },
  "Dossier sortie": { fr: "Dossier où écrire les fichiers convertis.", en: "Folder where the converted files are written." },
  "Motif": { fr: "Motif d'intervalles de base répété par récursion.", en: "Base interval motif repeated recursively." },
  "Intervalles": { fr: "Intervalles du motif personnalisé, en demi-tons séparés par des virgules (ex. 0,3,7,10).", en: "Intervals of the custom motif, in semitones separated by commas (e.g. 0,3,7,10)." },
  "Profondeur": { fr: "Nombre de niveaux de récursion (plus élevé = structure plus dense).", en: "Number of recursion levels (higher = denser structure)." },
  "Timbre": { fr: "Couleur sonore de la synthèse (douce, brillante, percutante).", en: "Tone color of the synthesis (soft, bright, percussive)." },
  "Patron": { fr: "Motif rythmique prédéfini, ou « Personnalisé » pour utiliser le code ci-dessous.", en: "Preset rhythmic pattern, or « Custom » to use the code below." },
  "Code personnalisé": { fr: "Grille rythmique personnalisée (utilisée si le patron est « Personnalisé »).", en: "Custom rhythm grid (used when the pattern is « Custom »)." },
  "Kick": { fr: "Volume de la grosse caisse, de 0 à 100 %.", en: "Kick drum volume, from 0 to 100%." },
  "Caisse claire": { fr: "Volume de la caisse claire, de 0 à 100 %.", en: "Snare volume, from 0 to 100%." },
  "Charley": { fr: "Volume du charleston (hi-hat), de 0 à 100 %.", en: "Hi-hat volume, from 0 to 100%." },
};

// Nom anglais par identifiant de composant (fiches sans nomEn).
const NOMS_EN: Record<string, string> = {
  "analyse-audio": "Audio Analysis",
  "lecteur-analyse": "Analysis Reader",
  "classificateur-genre": "Genre Classifier",
  "amplificateur": "Amplifier",
  "reinserer-zone": "Reinsert Zone",
  "selecteur-multi-zones": "Multi-Zone Selector",
  "melangeur": "Mixer",
  "visualiseur-forme-onde": "Waveform Viewer",
};

// Nom anglais par nom de paramètre commun (params sans nomEn).
const PARAMS_EN: Record<string, string> = {
  "Périphérique": "Device", "Réduction": "Reduction", "Mode": "Mode",
  "Durée": "Duration", "Gain": "Gain", "Fondu": "Fade",
  "Clé": "Key", "Gamme": "Scale", "Tempo": "Tempo", "Volume": "Volume",
  "Mesures": "Bars", "Genre": "Genre", "Qualité": "Quality",
  "Dossier entrée": "Input folder", "Dossier sortie": "Output folder",
  "Synthèse": "Synthesis",
};

export function avecDoc(def: FicheAudio): FicheAudio {
  const n = NOTICES[def.id];
  if (n && !def.notice) { def.notice = n.fr; def.noticeEn = n.en; }
  if (!def.nomEn && NOMS_EN[def.id]) def.nomEn = NOMS_EN[def.id];
  for (const p of def.parametres ?? []) {
    if (!p.doc && !p.docEn) {
      const d = DOCS_PARAM[p.nom];
      if (d) { p.doc = d.fr; p.docEn = d.en; }
    }
    if (!p.nomEn && PARAMS_EN[p.nom]) p.nomEn = PARAMS_EN[p.nom];
  }
  return def;
}
