// plugins/pure-data.ts — Nœud d'exécution d'un patch Pure Data (.pd).
import type { FicheAudio } from "../audio/types-domaine";
import { traduire } from "../i18n";
import { avecDoc } from "./notices";

export const fiches: FicheAudio[] = ([
  {
    id: "pure-data",
    nom: "Pure Data",
    nomEn: "Pure Data",
    univers: "Entrées",
    famille: "Génération",
    resume: "Génère un audio en exécutant un patch Pure Data (.pd).",
    resumeEn: "Generates audio by running a Pure Data patch (.pd).",
    entrees: [],
    sorties: [{ nom: "Audio", type: "audio" }],
    parametres: [
      {
        nom: "Bibliothèques",
        nomEn: "Libraries",
        type: "choix",
        options: ["vanilla", "cyclone", "else", "full"],
        optionsEn: ["vanilla", "cyclone", "else", "full"],
        defaut: "vanilla",
        doc: "Ensemble d'objets Pd disponibles pour le patch. vanilla = objets de base, cyclone/else = objets externes courants, full = tout.",
        docEn: "Set of Pd objects available to the patch. vanilla = core objects, cyclone/else = common externals, full = everything.", defautEn: "vanilla",
      },
      {
        nom: "Durée",
        nomEn: "Duration",
        type: "curseur",
        plage: [0.1, 10],
        pas: 0.1,
        defaut: 1,
        unite: "s",
        doc: "Durée de l'audio généré par le patch. Le patch est exécuté sur un buffer vide de cette durée.",
        docEn: "Duration of the audio generated by the patch. The patch runs on an empty buffer of this duration.",
      },
      {
        nom: "Canaux sortie",
        nomEn: "Output channels",
        type: "curseur",
        plage: [1, 8],
        pas: 1,
        defaut: 2,
        unite: "ch",
        doc: "Nombre de canaux de la sortie audio. Le patch doit écrire sur les canaux dac~ correspondants.",
        docEn: "Number of channels of the audio output. The patch must write to the matching dac~ channels.",
      },
      {
        nom: "Bang démarrage",
        nomEn: "Bang on start",
        type: "choix",
        options: ["oui", "non"],
        optionsEn: ["yes", "no"],
        optionIds: ["yes", "no"],
        defaut: "oui",
        doc: "Envoie un bang à l'objet [loadbang] au démarrage de l'audio.",
        docEn: "Send a bang to the [loadbang] object when audio starts.", defautEn: "yes",
      },
      {
        nom: "Ignorer objets GUI",
        nomEn: "Ignore GUI objects",
        type: "choix",
        options: ["oui", "non"],
        optionsEn: ["yes", "no"],
        optionIds: ["yes", "no"],
        defaut: "non",
        doc: "Supprime les objets graphiques (boutons, sliders, curseurs, tableaux…) du patch avant exécution. Certains patches desktop utilisent ces objets pour l'interface mais ils ne sont pas supportés par libpd en mode headless.",
        docEn: "Removes graphical objects (buttons, sliders, faders, arrays…) from the patch before execution. Some desktop patches use these for the UI but they are not supported by libpd in headless mode.", defautEn: "no",
      },
      {
        nom: "Patch",
        nomEn: "Patch",
        type: "texte",
        defaut: "",
        doc: "Identifiant du patch chargé (mis à jour automatiquement par le sélecteur de fichier). Sert à invalider le cache quand le fichier change.",
        docEn: "Identifier of the loaded patch (updated automatically by the file picker). Used to invalidate the cache when the file changes.", defautEn: "",
      },
    ],
    async executer(ctx: any) {
      const fichier = ctx.noeud.data.pureDataFichier as File | undefined;
      if (!fichier) {
        return { valeurs: [null], erreur: true, message: traduire("msg.aucun_patch_pure_data_charg") };
      }

      const patchSource = await fichier.text();
      if (!patchSource.trim()) {
        return { valeurs: [null], erreur: true, message: traduire("msg.patch_pure_data_vide") };
      }

      const packages = ctx.paramTexte("Bibliothèques", "vanilla");
      const duree = ctx.paramNombre("Durée", 1);
      const outputChannels = ctx.paramNombre("Canaux sortie", 2);
      const bangOnStart = ctx.paramTexte("Bang démarrage", "yes") === "yes";
      const ignorerGUI = ctx.paramTexte("Ignorer objets GUI", "no") === "yes";

      const sampleRate = 44100;
      const length = Math.max(1, Math.round(duree * sampleRate));
      const buffer = new AudioBuffer({ length, numberOfChannels: 1, sampleRate });

      try {
        const { appliquerPatchPureData } = await import("../audio/pure-data");
        const out = await appliquerPatchPureData(buffer, patchSource, {
          packages,
          outputChannels,
          bangOnStart,
          ignorerGUI,
        });
        return { valeurs: [out], message: traduire("msg.pure_data_var_0", fichier.name) };
      } catch (err: any) {
        return { valeurs: [null], erreur: true, message: traduire("msg.erreur_pure_data_var_0", err?.message ?? err) };
      }
    },
  },
] as FicheAudio[]).map(avecDoc);
