// parcours/exercices.ts — Le voyage lui-même : six chapitres, vingt-six étapes, six épreuves.
//
// CE QUI DISTINGUE UN EXERCICE D'UNE PAGE DE DOCUMENTATION. Une documentation explique ; un
// exercice fait faire, puis explique ce qu'on vient de faire. L'ordre est tout : la leçon n'est
// montrée qu'une fois le geste accompli, parce qu'une phrase sur la sonie lue avant d'avoir vu un
// vu-mètre bouger n'est qu'une phrase, et qu'après, c'est un souvenir.
//
// CHAQUE CHAPITRE SE FERME SUR UNE ÉPREUVE, et c'est la charnière du parcours. Les exercices
// disent quoi poser ; l'épreuve ne dit rien du chemin et exige un résultat mesuré — « un son à
// −14 LUFS sans dépasser −1 dBTP ». On peut y arriver au normaliseur, au compresseur suivi d'un
// gain, ou à la main : c'est l'élève qui choisit, et la mesure qui tranche. C'est la seule partie
// du parcours qui prouve quelque chose.
//
// LES LEÇONS DISENT « POURQUOI », JAMAIS « COMMENT ». Le comment est dans l'indice, qu'on ouvre si
// l'on veut ; la leçon, elle, porte la raison — pourquoi le limiteur va après le compresseur,
// pourquoi un grave large s'annule en mono, pourquoi la sonie ne se gagne pas au gain. C'est ce
// qui reste quand le geste est oublié, et c'est ce qui se transporte vers un autre logiciel.
//
// CE FICHIER EST TENU PAR SON TEST. `exercices.test.ts` vérifie contre le registre vivant que
// chaque identifiant de nœud cité existe, que chaque paramètre exigé existe sur ce nœud, et que
// chaque valeur de choix est l'une des valeurs possibles. Un nœud renommé ou un réglage disparu
// fait donc tomber le test, et non l'exercice en silence six mois plus tard.

import type { Chapitre, Exercice } from "./types";

export const CHAPITRES: Chapitre[] = [
  {
    id: "premier-son",
    titre: "Le premier son", titreEn: "The first sound",
    promesse: "Un graphe n'est pas un schéma : c'est un chemin que le son parcourt vraiment. À la fin de ce chapitre, vous aurez fabriqué un son, réglé sa hauteur, et regardé sa forme.",
    promesseEn: "A graph is not a diagram: it is a path the sound really travels. By the end of this chapter you will have made a sound, set its pitch, and looked at its shape.",
  },
  {
    id: "oreille",
    titre: "L'oreille", titreEn: "The ear",
    promesse: "Trois nœuds disent ce qu'une écoute ne peut pas trancher : combien c'est fort, où se trouve l'énergie, et si le changement qu'on vient de faire s'entend vraiment.",
    promesseEn: "Three nodes say what listening alone cannot settle: how loud it is, where the energy sits, and whether the change you just made is really audible.",
  },
  {
    id: "niveau",
    titre: "Le niveau", titreEn: "Level",
    promesse: "Gain, compression, limitation, normalisation : quatre gestes que l'on confond souvent, et qui ne font pas du tout la même chose.",
    promesseEn: "Gain, compression, limiting, normalising: four gestures often confused with one another, and doing entirely different things.",
  },
  {
    id: "couleur",
    titre: "La couleur", titreEn: "Colour",
    promesse: "Couper, creuser, souligner : le spectre est la matière du timbre, et trois décibels au bon endroit valent mieux que douze au mauvais.",
    promesseEn: "Cutting, scooping, lifting: the spectrum is what timbre is made of, and three decibels in the right place beat twelve in the wrong one.",
  },
  {
    id: "temps",
    titre: "Le temps", titreEn: "Time",
    promesse: "Retard, écho, réverbération, silence : le temps est la seule dimension qu'on ne remonte pas, et celle où se joue l'espace.",
    promesseEn: "Delay, echo, reverb, silence: time is the one dimension you cannot travel back along, and the one where space is played out.",
  },
  {
    id: "espace",
    titre: "L'espace", titreEn: "Space",
    promesse: "Deux canaux, et tout ce qu'on en tire : placer, élargir, et garder un grave qui tienne debout une fois sommé en mono.",
    promesseEn: "Two channels, and all you can draw from them: placing, widening, and keeping a low end that still stands once summed to mono.",
  },
  {
    id: "hauteur",
    titre: "La hauteur", titreEn: "Pitch",
    promesse: "La hauteur se mesure avant de se corriger, et transposer n'est pas accélérer. Ce chapitre sépare deux gestes que l'on confond partout.",
    promesseEn: "Pitch is measured before it is corrected, and transposing is not speeding up. This chapter separates two gestures confused everywhere.",
  },
  {
    id: "matiere",
    titre: "La matière", titreEn: "Matter",
    promesse: "Fabriquer un son au lieu de le traiter : une forme d'onde, une modulation, des grains, un étirement. Quatre façons de partir de rien.",
    promesseEn: "Making a sound instead of processing one: a waveform, a modulation, grains, a stretch. Four ways of starting from nothing.",
  },
  {
    id: "musique",
    titre: "La musique", titreEn: "Music",
    promesse: "Des notes, des accords, un rythme — et ce qu'une machine sait en relire. Le graphe devient un instrument qui joue.",
    promesseEn: "Notes, chords, a rhythm — and what a machine can read back from them. The graph becomes an instrument that plays.",
  },
  {
    id: "oeuvre",
    titre: "L'œuvre", titreEn: "The finished work",
    promesse: "Assembler, fondre, nommer, sauver. Et savoir ce que l'export fait au son, parce qu'il lui fait quelque chose.",
    promesseEn: "Assembling, fading, naming, saving. And knowing what exporting does to the sound, because it does something to it.",
  },
];

// ── Critères réutilisés ───────────────────────────────────────────────────────────────────────
// Écrits une fois : un exercice qui redéfinirait « un générateur de fréquence » à sa façon finirait
// par le nommer autrement dans la liste de contrôle, et l'élève croirait qu'on lui parle d'autre
// chose.

const GENERATEUR = { fiches: ["generateur-frequence"], quoi: "un générateur de fréquence", quoiEn: "a Frequency Generator" };
const GENERATEUR_LANCE = { ...GENERATEUR, rendu: true, quoi: "le générateur de fréquence", quoiEn: "the Frequency Generator" };
const REGARD = { univers: "Visualisation", famille: "Analyse", rendu: true, quoi: "un nœud de visualisation lancé", quoiEn: "a visualization node that has run" };
const EFFET = { famille: "Effets", quoi: "un effet", quoiEn: "an effect" };

export const EXERCICES: Exercice[] = [
  // ── Le premier son ──────────────────────────────────────────────────────────────────────────
  {
    id: "poser-source", chapitre: "premier-son",
    titre: "Poser une source", titreEn: "Place a source",
    enonce: "Pose un Générateur de fréquence dans l'atelier.",
    enonceEn: "Place a Frequency Generator in the workshop.",
    indice: "Le catalogue est à gauche. Tapez « fréquence » dans sa recherche, puis glissez la fiche sur le fond — ou double-cliquez-la.",
    indiceEn: "The catalog is on the left. Type « frequency » in its search box, then drag the card onto the canvas — or double-click it.",
    lecon: "Rien ne se produit sans nœud : Attic n'a ni piste ni canal, seulement des nœuds qui fabriquent, transforment ou regardent du son. Un générateur est une source, et cela se voit à une chose — il n'a aucune entrée. C'est la différence entre faire du son et en traiter.",
    leconEn: "Nothing happens without a node: Attic has no tracks and no channels, only nodes that make, transform or watch sound. A generator is a source, and one thing shows it — it has no input at all. That is the difference between making sound and processing it.",
    condition: { sorte: "present", critere: GENERATEUR },
  },
  {
    id: "lancer-source", chapitre: "premier-son",
    titre: "Lancer, et entendre", titreEn: "Run, and hear",
    enonce: "Lance le graphe, puis écoute le résultat sous le nœud.",
    enonceEn: "Run the graph, then listen to the result under the node.",
    indice: "Le bouton Lancer est en haut de la fenêtre. Une fois le calcul fini, un lecteur apparaît sous le générateur.",
    indiceEn: "The Run button sits at the top of the window. Once the computation ends, a player appears under the generator.",
    lecon: "Chaque nœud garde et montre ce qu'il a produit. On n'a donc pas besoin d'aller jusqu'au bout d'une chaîne pour entendre : on écoute où l'on veut, au milieu si l'on veut, et c'est ainsi qu'on trouve l'endroit exact où quelque chose a mal tourné.",
    leconEn: "Every node keeps and shows what it produced. You therefore never need to reach the end of a chain to hear: you listen wherever you like, halfway if you like, and that is how you find the exact place where something went wrong.",
    condition: { sorte: "present", critere: GENERATEUR_LANCE },
  },
  {
    id: "regler-source", chapitre: "premier-son",
    titre: "Descendre d'une octave", titreEn: "Drop an octave",
    enonce: "Règle le générateur sur 220 hertz, et fais-le durer au moins trois secondes.",
    enonceEn: "Set the generator to 220 hertz, and make it last at least three seconds.",
    indice: "Sélectionnez le nœud : ses réglages s'ouvrent dans l'inspecteur, à droite. Le point à côté d'un réglage modifié le remet à sa valeur d'origine.",
    indiceEn: "Select the node: its settings open in the inspector, on the right. The dot beside a changed setting puts it back to its original value.",
    lecon: "Doubler la fréquence monte d'une octave, la diviser par deux descend d'une octave : l'oreille entend des rapports et non des écarts. 440 et 220 hertz sont deux la ; 440 et 660, dans le même écart de 220 hertz, sont un la et un mi.",
    leconEn: "Doubling the frequency goes up an octave, halving it goes down one: the ear hears ratios, not differences. 440 and 220 hertz are both A; 440 and 660, the very same 220 hertz apart, are an A and an E.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "present", critere: { ...GENERATEUR, parametre: { nom: "Fréquence", nomEn: "Frequency", vaut: 220 }, quoi: "le générateur", quoiEn: "the generator" } },
        { sorte: "present", critere: { ...GENERATEUR, parametre: { nom: "Durée", nomEn: "Duration", min: 3 }, quoi: "le générateur", quoiEn: "the generator" } },
      ],
    },
  },
  {
    id: "voir-le-son", chapitre: "premier-son",
    titre: "Regarder ce qu'on entend", titreEn: "Look at what you hear",
    enonce: "Branche un Visualiseur, un Analyseur de spectre ou un Spectrogramme derrière le générateur, et relance.",
    enonceEn: "Wire a Waveform Viewer, a Spectrum Analyzer or a Spectrogram behind the generator, and run again.",
    indice: "Une arête se tire d'un point de sortie, à droite d'un nœud, vers un point d'entrée, à gauche d'un autre. Les couleurs disent le type : l'audio ne se branche que sur de l'audio.",
    indiceEn: "An edge is dragged from an output port, on a node's right, to an input port, on another node's left. Colours tell the type: audio only connects to audio.",
    lecon: "L'oreille juge, l'œil vérifie. Une onde carrée et une sinusoïde au même niveau se distinguent mal sur un petit haut-parleur, et ne se ressemblent en rien à l'écran. Toute la suite du parcours repose sur ce couple : écouter pour décider, regarder pour savoir de quoi l'on parle.",
    leconEn: "The ear judges, the eye checks. A square wave and a sine at the same level are hard to tell apart on a small speaker, and look nothing alike on screen. The whole journey rests on that pairing: listen to decide, look to know what you are talking about.",
    condition: { sorte: "relie", amont: GENERATEUR, aval: REGARD },
  },
  {
    id: "epreuve-premier-son", chapitre: "premier-son", epreuve: true,
    titre: "Épreuve — ta première preuve", titreEn: "Trial — your first proof",
    enonce: "Branche sur l'entrée « Copie » de ce nœud un son d'au moins deux secondes, audible et sans saturation.",
    enonceEn: "Wire into this node's « Copy » input a sound of at least two seconds, audible and without clipping.",
    indice: "Tirez une arête depuis la sortie de votre dernier nœud jusqu'à l'entrée « Copie », en haut à gauche de ce nœud. La mesure se fait dès que le son amont a été calculé — il n'y a rien à lancer ici.",
    indiceEn: "Drag an edge from your last node's output to the « Copy » input, at this node's top left. Measuring happens as soon as the upstream sound has been computed — there is nothing to run here.",
    lecon: "Les deux façons de rater un son sont le silence et la saturation, et l'une comme l'autre se mesurent avant de s'entendre. C'est tout le métier : vérifier ce qu'on croit avoir fait, plutôt que de l'espérer.",
    leconEn: "The two ways to fail a sound are silence and clipping, and both can be measured before they can be heard. That is the whole craft: checking what you think you made, rather than hoping for it.",
    cibles: [
      { grandeur: "duree", min: 2, exigence: "au moins deux secondes", exigenceEn: "at least two seconds" },
      { grandeur: "lufs", min: -45, exigence: "il y a bien du son, et non du silence", exigenceEn: "there really is sound, and not silence" },
      { grandeur: "crete", max: -0.5, exigence: "la crête reste sous −0,5 dBFS", exigenceEn: "the peak stays under -0.5 dBFS" },
    ],
  },

  // ── L'oreille ───────────────────────────────────────────────────────────────────────────────
  {
    id: "poser-vumetre", chapitre: "oreille",
    titre: "Mesurer la force", titreEn: "Measure loudness",
    enonce: "Branche un VU-mètre / LUFS sur ton son, et lance.",
    enonceEn: "Wire a VU-meter / LUFS onto your sound, and run.",
    indice: "Il se trouve dans Visualisation, rubrique Analyse. Il laisse passer le son inchangé : on peut le poser au milieu d'une chaîne sans rien casser.",
    indiceEn: "It lives under Visualization, Analysis section. It passes the sound through unchanged: you can drop it in the middle of a chain without breaking anything.",
    lecon: "Fort et haut ne sont pas la même chose. La crête est le plus grand échantillon du fichier ; la sonie, en LUFS, est ce que l'oreille perçoit, mesuré avec la pondération de la norme. Deux sons culminant tous deux à 0 dBFS peuvent différer de quinze décibels à l'écoute — une batterie sèche et une nappe compressée, par exemple.",
    leconEn: "Loud and high are not the same thing. The peak is the file's largest sample; loudness, in LUFS, is what the ear perceives, measured with the standard weighting. Two sounds both topping out at 0 dBFS can differ by fifteen decibels to the ear — a dry drum kit and a compressed pad, say.",
    condition: { sorte: "present", critere: { fiches: ["vu-metre"], rendu: true, quoi: "un vu-mètre lancé", quoiEn: "a VU-meter that has run" } },
  },
  {
    id: "voir-le-spectre", chapitre: "oreille",
    titre: "Voir où est l'énergie", titreEn: "See where the energy sits",
    enonce: "Regarde ton son au Spectrogramme, puis à l'Analyseur de spectre.",
    enonceEn: "Look at your sound with the Spectrogram, then with the Spectrum Analyzer.",
    indice: "Les deux prennent la même entrée audio ; rien n'empêche de les brancher tous deux sur le même nœud.",
    indiceEn: "Both take the same audio input; nothing stops you wiring both onto the same node.",
    lecon: "Le spectre montre un instant, le spectrogramme montre la durée. Un souffle constant saute aux yeux sur le second — une bande horizontale qui ne bouge jamais — alors qu'il se confond avec l'instrument sur le premier. On choisit donc selon la question : « quel timbre ? » se lit au spectre, « quand cela arrive-t-il ? » au spectrogramme.",
    leconEn: "The spectrum shows an instant, the spectrogram shows duration. Constant hiss jumps out on the second — a horizontal band that never moves — while it blends into the instrument on the first. So you pick by the question: « what timbre? » reads on the spectrum, « when does it happen? » on the spectrogram.",
    condition: { sorte: "present", critere: { fiches: ["spectrogramme", "analyseur-spectre"], rendu: true, quoi: "un spectrogramme ou un analyseur de spectre lancé", quoiEn: "a Spectrogram or Spectrum Analyzer that has run" } },
  },
  {
    id: "comparer", chapitre: "oreille",
    titre: "Comparer honnêtement", titreEn: "Compare honestly",
    enonce: "Mets un effet sur ton son, puis branche-le dans un Comparateur A/B et lance.",
    enonceEn: "Put an effect on your sound, then wire it into an A/B Comparator and run.",
    indice: "Le comparateur prend deux entrées : le son d'origine sur l'une, le son traité sur l'autre. Son réglage « Écoute » bascule de l'un à l'autre.",
    indiceEn: "The comparator takes two inputs: the original sound on one, the processed sound on the other. Its « Listen » setting switches between them.",
    lecon: "Le plus fort gagne toujours. Un effet qui ajoute un décibel paraît meilleur, même quand il n'apporte rien — c'est le biais le mieux documenté de l'écoute, et personne n'y échappe. Le comparateur aligne les niveaux avant de basculer : ce qu'on juge alors est le changement, et non le gain.",
    leconEn: "The louder one always wins. An effect that adds a decibel sounds better even when it brings nothing — the best documented bias in listening, and nobody is immune. The comparator aligns levels before switching: what you then judge is the change, and not the gain.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "relie", amont: EFFET, aval: { fiches: ["comparateur-ab"], quoi: "un comparateur A/B", quoiEn: "an A/B Comparator" } },
        { sorte: "present", critere: { fiches: ["comparateur-ab"], rendu: true, quoi: "le comparateur A/B", quoiEn: "the A/B Comparator" } },
      ],
    },
  },
  {
    id: "lire-les-chiffres", chapitre: "oreille",
    titre: "Faire parler le son", titreEn: "Make the sound talk",
    enonce: "Branche Caractéristiques de piste sur ton son, et sa sortie sur une Sortie texte.",
    enonceEn: "Wire Track Features onto your sound, and its output into a Text Output.",
    indice: "La Sortie texte attend du texte, pas de l'audio : c'est la sortie de gauche du nœud d'analyse qu'il faut y mener.",
    indiceEn: "Text Output expects text, not audio: it is the analysis node's left-hand output you need to lead there.",
    lecon: "Centroïde, plage dynamique, chroma, coefficients cepstraux : ce vecteur de caractéristiques est exactement ce que lisent les algorithmes qui classent, cherchent ou engendrent de la musique. Le voir écrit est la façon la plus directe de comprendre ce qu'une machine « entend » d'un son — et ce qu'elle n'en entend pas.",
    leconEn: "Centroid, dynamic range, chroma, cepstral coefficients: this feature vector is exactly what the algorithms that classify, search or generate music read. Seeing it written out is the most direct way to understand what a machine « hears » in a sound — and what it does not.",
    condition: {
      sorte: "relie",
      amont: { fiches: ["caracteristiques-piste"], quoi: "les caractéristiques de piste", quoiEn: "the Track Features node" },
      aval: { fiches: ["sortie-texte"], rendu: true, quoi: "une sortie texte lancée", quoiEn: "a Text Output that has run" },
    },
  },
  {
    id: "epreuve-fort-sans-crier", chapitre: "oreille", epreuve: true,
    titre: "Épreuve — fort sans crier", titreEn: "Trial — loud without shouting",
    enonce: "Amène un son qui s'entend fort — au moins −16 LUFS — mais dont la crête ne dépasse jamais −6 dBFS.",
    enonceEn: "Bring a sound that is heard loud — at least -16 LUFS — yet whose peak never passes -6 dBFS.",
    indice: "Un gain seul n'y parvient pas : il monte les deux en même temps. Un compresseur, ou un limiteur, réduit l'écart entre les crêtes et le reste — et c'est cet écart qui coûte la sonie.",
    indiceEn: "Gain alone will not do it: it raises both at once. A compressor, or a limiter, narrows the gap between peaks and the rest — and it is that gap which costs loudness.",
    lecon: "La sonie se gagne en réduisant l'écart entre les crêtes et le reste, jamais en montant le tout. Toute la guerre du volume tient dans cette mesure, et la fatigue qu'elle provoque aussi : un son sans écart n'a plus d'accents, et l'oreille cesse de croire à ses attaques.",
    leconEn: "Loudness is won by narrowing the gap between peaks and the rest, never by raising everything. The whole loudness war fits in that one measurement, and so does the fatigue it causes: a sound without gaps has no accents left, and the ear stops believing its attacks.",
    cibles: [
      { grandeur: "lufs", min: -16, exigence: "la sonie atteint −16 LUFS", exigenceEn: "loudness reaches -16 LUFS" },
      { grandeur: "crete", max: -6, exigence: "la crête reste sous −6 dBFS", exigenceEn: "the peak stays under -6 dBFS" },
    ],
  },

  // ── Le niveau ───────────────────────────────────────────────────────────────────────────────
  {
    id: "normaliser-en-sonie", chapitre: "niveau",
    titre: "Normaliser ce qui s'entend", titreEn: "Normalise what is heard",
    enonce: "Pose un Normaliseur, passe-le en mode Sonie (LUFS), et lance.",
    enonceEn: "Place a Normalizer, switch it to Loudness (LUFS) mode, and run.",
    indice: "Le mode se choisit dans l'inspecteur. En mode Sonie, c'est « Sonie cible » qui commande, et le réglage « Niveau » ne sert plus à rien.",
    indiceEn: "The mode is chosen in the inspector. In Loudness mode « Target loudness » is in charge, and the « Level » setting no longer does anything.",
    lecon: "Normaliser en crête aligne le plus grand échantillon ; normaliser en sonie aligne ce qui s'entend. Les plateformes de diffusion font le second, ce qui rend inutile de monter le niveau d'un morceau avant de l'envoyer : il sera ramené à leur cible, et tout ce qu'on aura gagné, c'est une dynamique écrasée.",
    leconEn: "Peak normalising aligns the largest sample; loudness normalising aligns what is heard. Streaming platforms do the second, which makes pushing a track's level before sending it pointless: it will be brought back to their target, and all you will have gained is a squashed dynamic.",
    condition: { sorte: "present", critere: { fiches: ["normaliseur"], parametre: { nom: "Mode", nomEn: "Mode", vaut: "sonie" }, rendu: true, quoi: "un normaliseur lancé", quoiEn: "a Normalizer that has run" } },
  },
  {
    id: "compresser", chapitre: "niveau",
    titre: "Rendre plus égal", titreEn: "Make it more even",
    enonce: "Ajoute un Compresseur réglé assez fort : seuil à −24 dB ou plus bas, rapport de 6 ou plus.",
    enonceEn: "Add a Compressor set firmly: threshold at -24 dB or lower, ratio of 6 or more.",
    indice: "Le seuil dit à partir de quel niveau le compresseur agit ; le rapport, de combien il réduit ce qui dépasse. Un rapport de 6 signifie que six décibels de trop n'en donnent plus qu'un.",
    indiceEn: "The threshold says from which level the compressor acts; the ratio, by how much it reduces what goes over. A ratio of 6 means six decibels too many come out as one.",
    lecon: "Un compresseur ne rend pas plus fort : il rend plus égal. C'est le gain qui suit qui rend plus fort. Confondre les deux mène à écraser un son sans savoir ce qu'on y gagne — et à s'étonner qu'il paraisse plus petit alors que le vu-mètre monte.",
    leconEn: "A compressor does not make things louder: it makes them more even. It is the gain that follows which makes them louder. Confusing the two leads to squashing a sound without knowing what it buys — and to wondering why it sounds smaller while the meter climbs.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "present", critere: { fiches: ["compresseur"], parametre: { nom: "Seuil", nomEn: "Threshold", max: -24 }, quoi: "le compresseur", quoiEn: "the compressor" } },
        { sorte: "present", critere: { fiches: ["compresseur"], parametre: { nom: "Ratio", nomEn: "Ratio", min: 6 }, rendu: true, quoi: "le compresseur", quoiEn: "the compressor" } },
      ],
    },
  },
  {
    id: "limiter-en-dernier", chapitre: "niveau",
    titre: "Le filet, en dernier", titreEn: "The safety net, last",
    enonce: "Place un Limiteur après le compresseur, de sorte que le son y passe en dernier.",
    enonceEn: "Place a Limiter after the compressor, so the sound passes through it last.",
    indice: "« Après » se lit sur les arêtes : le son doit sortir du compresseur et arriver au limiteur, directement ou en traversant d'autres nœuds.",
    indiceEn: "« After » is read on the edges: the sound must leave the compressor and reach the limiter, directly or through other nodes on the way.",
    lecon: "Le limiteur est le dernier filet : il garantit qu'aucun échantillon ne passe au-dessus du plafond. Le mettre avant le compresseur le fait travailler sur un signal que le compresseur va ensuite remonter — le filet est alors tendu au mauvais étage, et ne retient plus rien.",
    leconEn: "The limiter is the last safety net: it guarantees no sample passes above the ceiling. Putting it before the compressor makes it work on a signal the compressor will then raise — the net is strung on the wrong floor, and catches nothing.",
    condition: {
      sorte: "relie",
      amont: { fiches: ["compresseur"], quoi: "le compresseur", quoiEn: "the compressor" },
      aval: { fiches: ["limiteur"], rendu: true, quoi: "un limiteur lancé", quoiEn: "a Limiter that has run" },
    },
  },
  {
    id: "epreuve-diffusion", chapitre: "niveau", epreuve: true,
    titre: "Épreuve — prêt pour la diffusion", titreEn: "Trial — ready for release",
    enonce: "Amène un son calibré comme une plateforme l'exige : sonie entre −15 et −13 LUFS, vrai pic sous −1 dBTP.",
    enonceEn: "Bring a sound calibrated the way a platform asks: loudness between -15 and -13 LUFS, true peak under -1 dBTP.",
    indice: "Le Normaliseur en mode Sonie fait les deux d'un coup : cible à −14, plafond à −1. S'il annonce que la cible n'est pas atteinte, c'est que le plafond a gagné — mettez un limiteur devant.",
    indiceEn: "The Normalizer in Loudness mode does both at once: target at -14, ceiling at -1. If it reports the target was not reached, the ceiling won — put a limiter in front.",
    lecon: "−14 LUFS et −1 dBTP sont la convention de la plupart des plateformes. Le vrai pic se mesure entre les échantillons, là où le signal reconstruit dépasse ce que les échantillons montrent : un fichier qui affiche 0,0 dBFS peut faire saturer le décodeur du lecteur, et c'est pour cela que le plafond est à −1 et non à 0.",
    leconEn: "-14 LUFS and -1 dBTP are the convention on most platforms. True peak is measured between the samples, where the reconstructed signal goes past what the samples show: a file reading 0.0 dBFS can clip the listener's decoder, which is why the ceiling sits at -1 and not at 0.",
    cibles: [
      { grandeur: "lufs", min: -15, max: -13, exigence: "la sonie tient entre −15 et −13 LUFS", exigenceEn: "loudness holds between -15 and -13 LUFS" },
      { grandeur: "vraiPic", max: -1, exigence: "le vrai pic reste sous −1 dBTP", exigenceEn: "true peak stays under -1 dBTP" },
    ],
  },

  // ── La couleur ──────────────────────────────────────────────────────────────────────────────
  {
    id: "creuser-le-bas", chapitre: "couleur",
    titre: "Creuser le bas", titreEn: "Scoop the bottom",
    enonce: "Pose un Égaliseur sur ton son et descends la bande 32 Hz d'au moins 12 décibels.",
    enonceEn: "Place an Equalizer on your sound and pull the 32 Hz band down by at least 12 decibels.",
    indice: "Les neuf bandes vont de 32 hertz à 8 kilohertz, par octaves. Une valeur négative retire, une positive ajoute.",
    indiceEn: "The nine bands run from 32 hertz to 8 kilohertz, by octaves. A negative value takes away, a positive one adds.",
    lecon: "Sous quarante hertz, la plupart des sons ne portent que du bruit de pieds, du souffle de micro et de l'énergie qu'aucun haut-parleur ordinaire ne restitue — mais qui consomme la marge du limiteur. Couper là ne s'entend presque pas ; ce qui s'entend, c'est la place que cela libère pour le reste.",
    leconEn: "Below forty hertz, most sounds carry only footfall, microphone rumble and energy no ordinary speaker reproduces — yet which eats the limiter's headroom. Cutting there is barely audible; what is audible is the room it frees for everything else.",
    condition: { sorte: "present", critere: { fiches: ["equaliseur"], parametre: { nom: "32 Hz", nomEn: "32 Hz", max: -12 }, rendu: true, quoi: "un égaliseur lancé", quoiEn: "an Equalizer that has run" } },
  },
  {
    id: "souligner-la-presence", chapitre: "couleur",
    titre: "Souligner la présence", titreEn: "Lift presence",
    enonce: "Sur le même égaliseur, monte la bande 4 kHz de 6 décibels au moins, et écoute ce que cela change.",
    enonceEn: "On the same equalizer, push the 4 kHz band up by at least 6 decibels, and listen to what it changes.",
    indice: "Écoutez en basculant le nœud d'avant en arrière plutôt qu'en le jugeant seul : c'est là que le Comparateur A/B du chapitre précédent sert.",
    indiceEn: "Listen by switching back and forth rather than judging it alone: this is where the previous chapter's A/B Comparator earns its place.",
    lecon: "Autour de quatre kilohertz, l'oreille est la plus sensible — le conduit auditif y résonne, et la courbe d'égale sonie y creuse un puits. C'est ce qui rend cette bande si efficace, et si dangereuse : trois décibels y font le même effet que dix ailleurs, et l'agressivité y naît aussi vite que la présence.",
    leconEn: "Around four kilohertz the ear is at its most sensitive — the ear canal resonates there, and the equal-loudness curve digs a well. That is what makes the band so effective, and so dangerous: three decibels there do the work of ten elsewhere, and harshness appears as fast as presence.",
    condition: { sorte: "present", critere: { fiches: ["equaliseur"], parametre: { nom: "4 kHz", nomEn: "4 kHz", min: 6 }, rendu: true, quoi: "l'égaliseur", quoiEn: "the equalizer" } },
  },
  {
    id: "bruit-rose", chapitre: "couleur",
    titre: "Blanc contre rose", titreEn: "White against pink",
    enonce: "Pose un Générateur de bruit, mets-le en bruit rose, et compare-le au bruit blanc.",
    enonceEn: "Place a Noise Generator, set it to pink noise, and compare it with white noise.",
    indice: "Deux générateurs côte à côte, l'un blanc l'autre rose, s'écoutent l'un après l'autre sans rien rebrancher.",
    indiceEn: "Two generators side by side, one white and one pink, can be listened to one after the other without rewiring anything.",
    lecon: "Le bruit blanc porte autant d'énergie par hertz ; le bruit rose, autant par octave. Comme l'oreille entend par octaves — de 100 à 200 hertz est un pas aussi grand que de 1000 à 2000 —, c'est le rose qui paraît neutre, et le blanc qui semble siffler. Le rose est pour cela la référence des mesures de salle.",
    leconEn: "White noise carries equal energy per hertz; pink noise, equal energy per octave. Since the ear hears in octaves — 100 to 200 hertz is as wide a step as 1000 to 2000 — pink is the one that sounds neutral, and white the one that seems to hiss. That is why pink is the reference for room measurements.",
    condition: { sorte: "present", critere: { fiches: ["generateur-bruit"], parametre: { nom: "Type", nomEn: "Type", vaut: "Rose" }, rendu: true, quoi: "un générateur de bruit lancé", quoiEn: "a Noise Generator that has run" } },
  },
  {
    id: "epreuve-nettoyer-le-bas", chapitre: "couleur", epreuve: true,
    titre: "Épreuve — nettoyer le bas", titreEn: "Trial — clean the low end",
    enonce: "Amène un son dont moins de 5 % de l'énergie se trouve sous 200 hertz, sans qu'il devienne inaudible.",
    enonceEn: "Bring a sound with less than 5 % of its energy below 200 hertz, without it becoming inaudible.",
    indice: "L'égaliseur suffit si vous descendez les trois bandes basses. Un son aigu y arrive tout seul : l'épreuve est plus instructive sur un son qui contient vraiment du grave.",
    indiceEn: "The equalizer is enough if you pull the three low bands down. A treble sound passes on its own: the trial teaches more on a sound that really has low end in it.",
    lecon: "Une mesure de bande répond à une question que l'oreille pose mal. « Est-ce trop sourd ? » ne se discute pas ; « combien d'énergie sous deux cents hertz ? » se compare d'un son à l'autre, se note, et se retrouve le lendemain. C'est la différence entre un avis et un réglage.",
    leconEn: "A band measurement answers a question the ear asks badly. « Is it too muddy? » cannot be settled; « how much energy below two hundred hertz? » compares from one sound to the next, gets written down, and is still there tomorrow. That is the difference between an opinion and a setting.",
    cibles: [
      { grandeur: "partGrave", max: 5, exigence: "moins de 5 % de l'énergie sous 200 Hz", exigenceEn: "less than 5 % of the energy below 200 Hz" },
      { grandeur: "lufs", min: -40, exigence: "le son reste audible", exigenceEn: "the sound stays audible" },
    ],
  },

  // ── Le temps ────────────────────────────────────────────────────────────────────────────────
  {
    id: "echo-a-la-noire", chapitre: "temps",
    titre: "Un écho à la noire", titreEn: "An echo on the beat",
    enonce: "Pose un Echo et règle son temps autour de 500 millisecondes.",
    enonceEn: "Place an Echo and set its time around 500 milliseconds.",
    indice: "Le réglage « Temps » va de 50 à 2000 millisecondes ; « Feedback » décide du nombre de répétitions avant extinction.",
    indiceEn: "The « Time » setting runs from 50 to 2000 milliseconds; « Feedback » decides how many repeats there are before it dies away.",
    lecon: "Sous une cinquantaine de millisecondes, une répétition ne s'entend plus comme un écho mais comme un timbre : c'est l'effet de précédence, et c'est ce qui fait qu'un peigne coloré sonne comme un filtre et non comme un retard. Au-delà, elle se compte — et cinq cents millisecondes valent exactement une noire à cent vingt.",
    leconEn: "Below some fifty milliseconds, a repeat is no longer heard as an echo but as a timbre: that is the precedence effect, and it is why a coloured comb sounds like a filter rather than a delay. Beyond it, repeats can be counted — and five hundred milliseconds is exactly a quarter note at a hundred and twenty.",
    condition: { sorte: "present", critere: { fiches: ["echo"], parametre: { nom: "Temps", nomEn: "Time", min: 450, max: 550 }, rendu: true, quoi: "un écho lancé", quoiEn: "an Echo that has run" } },
  },
  {
    id: "reverbe-apres-echo", chapitre: "temps",
    titre: "La salle vient après", titreEn: "The room comes after",
    enonce: "Ajoute une Réverbération derrière l'écho, et écoute l'ordre que cela impose.",
    enonceEn: "Add a Reverb behind the echo, and listen to the order that imposes.",
    indice: "Derrière veut dire que le son sort de l'écho et entre dans la réverbération, et non l'inverse.",
    indiceEn: "Behind means the sound leaves the echo and enters the reverb, and not the other way round.",
    lecon: "L'écho répète, la réverbération diffuse : l'un rend des copies qu'on peut compter, l'autre une densité où plus rien ne se distingue. Dans cet ordre, les répétitions se produisent dans la salle — c'est ce que fait un vrai lieu. Dans l'ordre inverse, la salle est répétée, et chaque copie traîne sa propre queue.",
    leconEn: "Echo repeats, reverb diffuses: one gives copies you can count, the other a density where nothing stands apart. In this order the repeats happen in the room — which is what a real place does. Reversed, the room itself is repeated, and each copy drags its own tail along.",
    condition: {
      sorte: "relie",
      amont: { fiches: ["echo"], quoi: "l'écho", quoiEn: "the echo" },
      aval: { fiches: ["reverberation"], rendu: true, quoi: "une réverbération lancée", quoiEn: "a Reverb that has run" },
    },
  },
  {
    id: "rogner", chapitre: "temps",
    titre: "Retirer le blanc", titreEn: "Trim the blank",
    enonce: "Fais passer un son par Rogner les silences, et lance.",
    enonceEn: "Run a sound through Trim Silence, and run the graph.",
    indice: "Le nœud dit dans son message combien il a retiré. Sa marge de 50 millisecondes est volontaire : un seuil seul coupe toujours le début de l'attaque.",
    indiceEn: "The node reports in its message how much it removed. Its 50 millisecond margin is deliberate: a bare threshold always cuts into the start of the attack.",
    lecon: "Ce nœud mesure l'enveloppe et non l'échantillon, et c'est ce qui le rend utilisable. Une sinusoïde passe par zéro deux fois par période : un seuil appliqué aux échantillons découperait un la 440 en huit cent quatre-vingts morceaux par seconde. Beaucoup d'outils simples commettent exactement cette faute.",
    leconEn: "This node measures the envelope and not the sample, and that is what makes it usable. A sine crosses zero twice per period: a threshold applied to samples would cut a 440 hertz A into eight hundred and eighty pieces per second. Plenty of simple tools make exactly that mistake.",
    condition: { sorte: "present", critere: { fiches: ["rogner-silences"], rendu: true, quoi: "un rognage de silences lancé", quoiEn: "a Trim Silence that has run" } },
  },
  {
    id: "epreuve-quatre-secondes", chapitre: "temps", epreuve: true,
    titre: "Épreuve — quatre secondes", titreEn: "Trial — four seconds",
    enonce: "Amène un son qui dure quatre secondes, à un dixième de seconde près.",
    enonceEn: "Bring a sound that lasts four seconds, to within a tenth of a second.",
    indice: "Ajouter silence allonge, Rogner les silences raccourcit, Extraire une zone découpe, et la durée d'un générateur se règle directement.",
    indiceEn: "Add Silence lengthens, Trim Silence shortens, Extract a Region cuts, and a generator's duration is set directly.",
    lecon: "La durée est la seule chose qu'un montage doit tenir exactement. Un son qui tombe à côté de l'image, du tempo ou de la boucle est faux quelle que soit sa beauté — et c'est la raison pour laquelle tant de nœuds de montage annoncent leur durée d'entrée et de sortie plutôt que de vous laisser la deviner.",
    leconEn: "Duration is the one thing an edit has to hold exactly. A sound that lands beside the picture, the tempo or the loop is wrong however beautiful it is — which is why so many editing nodes announce their in and out durations rather than leaving you to guess.",
    cibles: [
      { grandeur: "duree", min: 3.9, max: 4.1, exigence: "la durée tient entre 3,9 et 4,1 secondes", exigenceEn: "duration holds between 3.9 and 4.1 seconds" },
    ],
  },

  // ── L'espace ────────────────────────────────────────────────────────────────────────────────
  {
    id: "placer", chapitre: "espace",
    titre: "Placer le son", titreEn: "Place the sound",
    enonce: "Place ton son ailleurs qu'au centre, avec un Hard panner ou une Spatialisation stéréo.",
    enonceEn: "Place your sound somewhere other than the centre, with a Hard panner or Stereo Spatialization.",
    indice: "Le Hard panner range tout d'un côté ; la Spatialisation stéréo dose la position et la largeur, et accepte une courbe pour bouger dans le temps.",
    indiceEn: "The Hard panner throws everything to one side; Stereo Spatialization meters position and width, and accepts a curve to move over time.",
    lecon: "Le panoramique ne déplace pas le son : il change le rapport des deux canaux, et l'oreille en tire une direction par différence d'intensité. C'est un tour de passe-passe remarquablement efficace entre deux haut-parleurs, et totalement inopérant sur un seul — ce qui explique qu'un mixage très large s'effondre sur un téléphone.",
    leconEn: "Panning does not move the sound: it changes the ratio of the two channels, and the ear draws a direction from the intensity difference. It is a remarkably effective trick between two speakers, and utterly powerless on one — which is why a very wide mix collapses on a phone.",
    condition: { sorte: "present", critere: { fiches: ["hard-panner", "spatialisation-stereo"], rendu: true, quoi: "un nœud de placement lancé", quoiEn: "a placement node that has run" } },
  },
  {
    id: "elargir", chapitre: "espace",
    titre: "Élargir, et le voir", titreEn: "Widen, and see it",
    enonce: "Élargis ton son avec Ampleur, puis branche le résultat sur un Goniomètre.",
    enonceEn: "Widen your sound with Spaciousness, then wire the result into a Goniometer.",
    indice: "Ampleur fabrique la différence entre canaux là où il n'y en a pas — un nœud de largeur classique, lui, ne peut qu'amplifier une différence existante, donc rien sur un son mono.",
    indiceEn: "Spaciousness manufactures the difference between channels where there is none — a classic width node can only amplify an existing difference, hence nothing at all on a mono sound.",
    lecon: "Le goniomètre dessine la corrélation des deux canaux : une diagonale serrée signifie mono, un nuage rond signifie décorrélé. Un son parfaitement décorrélé perd trois décibels quand on le somme en mono, et ce n'est pas un défaut — c'est le prix géométrique de la largeur, que la racine de (1 + r) sur 2 donne exactement.",
    leconEn: "The goniometer draws the correlation of the two channels: a tight diagonal means mono, a round cloud means decorrelated. A perfectly decorrelated sound loses three decibels when summed to mono, and that is no fault — it is the geometric price of width, given exactly by the square root of (1 + r) over 2.",
    condition: {
      sorte: "relie",
      amont: { fiches: ["ampleur"], quoi: "le nœud Ampleur", quoiEn: "the Spaciousness node" },
      aval: { fiches: ["goniometre"], rendu: true, quoi: "un goniomètre lancé", quoiEn: "a Goniometer that has run" },
    },
  },
  {
    id: "grave-solide", chapitre: "espace",
    titre: "Un grave qui tient debout", titreEn: "A low end that stands",
    enonce: "Ramène le bas du spectre au centre avec Grave en mono, et lance.",
    enonceEn: "Bring the bottom of the spectrum back to the centre with Bass Mono, and run.",
    indice: "Le nœud annonce de combien il a réduit le côté, et vérifie que le milieu n'a pas bougé : c'est un passe-haut sur la différence des canaux, et la somme mono reste identique au bit près.",
    indiceEn: "The node reports how much it reduced the side, and checks the mid has not moved: it is a high-pass on the channel difference, and the mono sum stays identical bit for bit.",
    lecon: "Un grave large est un grave qui s'annule : dès qu'on additionne les deux canaux — sur un téléphone, dans un club, à la radio —, ce qui était en opposition disparaît. Rendre le bas mono ne s'entend presque pas en stéréo, parce que sous cent cinquante hertz l'oreille ne localise plus guère : la longueur d'onde dépasse la largeur de la tête.",
    leconEn: "A wide low end is a low end that cancels: as soon as the two channels are summed — on a phone, in a club, on radio — whatever was in opposition disappears. Making the bottom mono is barely audible in stereo, because below a hundred and fifty hertz the ear hardly localises at all: the wavelength is wider than the head.",
    condition: { sorte: "present", critere: { fiches: ["mono-grave"], rendu: true, quoi: "un grave en mono lancé", quoiEn: "a Bass Mono that has run" } },
  },
  {
    id: "epreuve-large-et-solide", chapitre: "espace", epreuve: true,
    titre: "Épreuve — large et solide", titreEn: "Trial — wide and solid",
    enonce: "Amène un son stéréo large mais équilibré : corrélation sous 0,6, et moins de 1,5 dB d'écart entre les canaux.",
    enonceEn: "Bring a wide yet balanced stereo sound: correlation under 0.6, and less than 1.5 dB between the channels.",
    indice: "Ampleur décorrèle, le Hard panner déséquilibre : l'épreuve demande l'un sans l'autre. Le Goniomètre montre les deux d'un coup d'œil.",
    indiceEn: "Spaciousness decorrelates, the Hard panner unbalances: the trial asks for one without the other. The Goniometer shows both at a glance.",
    lecon: "La largeur se paie en corrélation et se surveille à l'équilibre. Un son peut être large et tirer à gauche : cela s'entend comme un défaut de réglage et non comme un espace, alors qu'aucune des deux mesures ne le dirait seule. C'est le cas général en audio — une grandeur isolée ne prouve presque jamais ce qu'on lui fait dire.",
    leconEn: "Width is paid for in correlation and watched through balance. A sound can be wide and still pull to the left: that is heard as a setting mistake rather than as space, while neither measurement alone would say so. It is the general case in audio — one figure on its own almost never proves what it is made to say.",
    cibles: [
      { grandeur: "canaux", min: 2, exigence: "le son est bien stéréo", exigenceEn: "the sound really is stereo" },
      { grandeur: "correlation", max: 0.6, exigence: "la corrélation reste sous 0,6", exigenceEn: "correlation stays under 0.6" },
      { grandeur: "equilibre", max: 1.5, exigence: "moins de 1,5 dB d'écart entre les canaux", exigenceEn: "less than 1.5 dB between the channels" },
    ],
  },

  // ── La hauteur ──────────────────────────────────────────────────────────────────────────────
  {
    id: "suivre-la-hauteur", chapitre: "hauteur",
    titre: "Mesurer avant de corriger", titreEn: "Measure before correcting",
    enonce: "Branche un Suiveur de hauteur sur un son tenu, et lance.",
    enonceEn: "Wire a Pitch Follower onto a sustained sound, and run.",
    indice: "Il rend trois sorties : la hauteur en courbe, le son inchangé, et la confiance. Le Visualiseur de courbe montre les deux courbes.",
    indiceEn: "It returns three outputs: pitch as a curve, the sound unchanged, and confidence. The Curve Viewer shows both curves.",
    lecon: "Le suiveur ne cherche pas une fréquence mais une période : il compare le signal à lui-même décalé, et retient le décalage qui se ressemble le plus. C'est pourquoi il rend aussi une confiance — sur du bruit, aucun décalage ne ressemble, et une hauteur annoncée serait une invention. Un suiveur qui ne dit pas sa confiance est un suiveur qu'on ne peut pas croire.",
    leconEn: "The follower does not look for a frequency but for a period: it compares the signal with a delayed copy of itself, and keeps the delay that matches best. That is why it also returns a confidence — on noise no delay matches, and an announced pitch would be an invention. A follower that does not state its confidence is one you cannot trust.",
    condition: { sorte: "present", critere: { fiches: ["suiveur-hauteur"], rendu: true, quoi: "un suiveur de hauteur lancé", quoiEn: "a Pitch Follower that has run" } },
  },
  {
    id: "corriger-vers-une-gamme", chapitre: "hauteur",
    titre: "Ramener sur une gamme", titreEn: "Snap onto a scale",
    enonce: "Pose une Correction de hauteur et règle-la sur la gamme majeure plutôt que sur la chromatique.",
    enonceEn: "Place a Pitch Correction and set it to the major scale rather than the chromatic one.",
    indice: "Une gamme chromatique accepte les douze demi-tons : elle corrige les défauts sans jamais changer de note. Une gamme majeure, elle, ramène aussi les notes étrangères.",
    indiceEn: "A chromatic scale accepts all twelve semitones: it fixes flaws without ever changing a note. A major scale also pulls foreign notes back in.",
    lecon: "La correction rejoue les périodes du son à un autre espacement — c'est le recollement synchrone, et il garde les formants, si bien qu'une voix corrigée ne prend pas l'accent de l'écureuil. Sa limite est géométrique et écrite dans la notice : au-delà de quatre demi-tons, deux copies d'un même grain s'annulent, et à l'octave la raie dominante tombe à un centième du niveau d'entrée.",
    leconEn: "Correction replays the sound's periods at a different spacing — that is synchronous overlap-add, and it keeps the formants, so a corrected voice does not take on a chipmunk accent. Its limit is geometric and written in the notice: beyond four semitones, two copies of one grain cancel, and at the octave the dominant line falls to a hundredth of the input level.",
    condition: { sorte: "present", critere: { fiches: ["correction-hauteur"], parametre: { nom: "Gamme", nomEn: "Scale", vaut: "majeure" }, rendu: true, quoi: "la correction de hauteur", quoiEn: "the Pitch Correction" } },
  },
  {
    id: "transposer-sans-accelerer", chapitre: "hauteur",
    titre: "Transposer sans accélérer", titreEn: "Transpose without speeding up",
    enonce: "Monte un son de cinq demi-tons au moins, sans changer sa durée.",
    enonceEn: "Raise a sound by at least five semitones, without changing its duration.",
    indice: "« Phase Vocoder Tonalité » et « SoundTouch Tonalité » font l'un et l'autre ce travail. Comparez la durée annoncée avant et après : elle ne doit pas bouger.",
    indiceEn: "« Phase Vocoder Pitch » and « SoundTouch Pitch » both do this job. Compare the duration reported before and after: it must not move.",
    lecon: "Lire un son plus vite le monte et le raccourcit d'un même facteur : c'est l'accordéon du magnétophone, et les deux effets y sont inséparables. Les séparer demande de reconstruire le son — par trames spectrales dont on tourne la phase, ou par grains qu'on répète. Toute transposition à durée constante paie ce travail en artefacts : c'est un compromis, jamais un tour de magie.",
    leconEn: "Playing a sound faster raises it and shortens it by the very same factor: that is the tape accordion, and there the two effects are inseparable. Separating them means rebuilding the sound — through spectral frames whose phase is rotated, or through grains that are repeated. Every constant-duration transposition pays for that work in artefacts: a trade-off, never magic.",
    condition: { sorte: "present", critere: { fiches: ["phase-vocoder-tonalite", "soundtouch-tonalite"], parametre: { nom: "Tonalité", nomEn: "Pitch", min: 5 }, rendu: true, quoi: "un transposeur à durée constante", quoiEn: "a constant-duration transposer" } },
  },
  {
    id: "harmoniser", chapitre: "hauteur",
    titre: "Ajouter une quinte", titreEn: "Add a fifth",
    enonce: "Avec l'Harmonizer, fais sonner une quinte au-dessus de ton son : sept demi-tons.",
    enonceEn: "With the Harmonizer, sound a fifth above your sound: seven semitones.",
    indice: "« Voix 1 » compte en demi-tons : 12 pour l'octave, 7 pour la quinte, 4 pour la tierce majeure. Le mélange de chaque voix se règle à part.",
    indiceEn: "« Voice 1 » counts in semitones: 12 for the octave, 7 for the fifth, 4 for the major third. Each voice's mix is set separately.",
    lecon: "La quinte juste est le rapport 3/2, soit 702 cents ; le tempérament égal la pose à 700, et ces deux cents d'écart sont ce qui rend un piano habitable dans toutes les tonalités. Empiler douze quintes justes ne retombe pas sur l'octave — il reste le quart de ton du comma pythagoricien, et toute l'histoire des tempéraments consiste à décider où le cacher.",
    leconEn: "The perfect fifth is the ratio 3/2, hence 702 cents; equal temperament sets it at 700, and those two cents are what makes a piano liveable in every key. Stacking twelve perfect fifths does not land back on the octave — a quarter tone of Pythagorean comma is left over, and the whole history of temperaments is about deciding where to hide it.",
    condition: { sorte: "present", critere: { fiches: ["harmonizer"], parametre: { nom: "Voix 1", nomEn: "Voice 1", vaut: 7 }, rendu: true, quoi: "l'harmonizer", quoiEn: "the Harmonizer" } },
  },
  {
    id: "epreuve-dix-cents", chapitre: "hauteur", epreuve: true,
    titre: "Épreuve — juste à dix cents", titreEn: "Trial — in tune to ten cents",
    enonce: "Amène un son tenu dont la hauteur tombe à moins de dix cents du demi-ton le plus proche.",
    enonceEn: "Bring a sustained sound whose pitch lands within ten cents of the nearest semitone.",
    indice: "Un générateur réglé sur une fréquence quelconque — 453 hertz, par exemple — échouera ; la correction de hauteur en gamme chromatique le ramène. La mesure est celle du suiveur du catalogue.",
    indiceEn: "A generator set to any old frequency — 453 hertz, say — will fail; pitch correction on the chromatic scale pulls it back. The measurement is the catalog follower's own.",
    lecon: "Le cent est le centième de demi-ton, soit un rapport de fréquences de 1,00058. Cinq cents sur une note seule ne s'entendent pas ; les mêmes cinq cents entre deux notes tenues ensemble donnent un battement, et vingt cents rendent un unisson franchement faux. La justesse n'est donc pas une propriété d'une note mais d'un intervalle.",
    leconEn: "A cent is a hundredth of a semitone, a frequency ratio of 1.00058. Five cents on a lone note cannot be heard; the same five cents between two notes held together give a beating, and twenty cents make a unison plainly wrong. Tuning is therefore not a property of a note but of an interval.",
    cibles: [
      { grandeur: "justesse", max: 10, exigence: "à moins de dix cents du demi-ton", exigenceEn: "within ten cents of the semitone" },
      { grandeur: "partVoisee", min: 40, exigence: "une hauteur se tient sur au moins 40 % du son", exigenceEn: "a pitch holds over at least 40 % of the sound" },
    ],
  },

  // ── La matière ──────────────────────────────────────────────────────────────────────────────
  {
    id: "forme-riche", chapitre: "matiere",
    titre: "Une forme qui contient tout", titreEn: "A waveform that holds everything",
    enonce: "Pose un Oscillateur et mets-le en dent de scie.",
    enonceEn: "Place an Oscillator and set it to sawtooth.",
    indice: "Écoutez la même note en sinus, en carré, puis en scie : c'est le contenu harmonique qui change, pas la hauteur.",
    indiceEn: "Listen to the same note as sine, square, then sawtooth: what changes is the harmonic content, not the pitch.",
    lecon: "Une dent de scie porte tous les harmoniques, d'amplitude en un sur n ; un carré n'a que les impairs ; une sinusoïde n'en a aucun. C'est pourquoi la synthèse soustractive part de la scie : on ne peut retirer que ce qui est déjà là, et un filtre sur une sinusoïde ne fait que baisser le volume.",
    leconEn: "A sawtooth carries every harmonic, with amplitude one over n; a square only the odd ones; a sine none at all. That is why subtractive synthesis starts from the sawtooth: you can only remove what is already there, and a filter on a sine merely lowers the volume.",
    condition: { sorte: "present", critere: { fiches: ["oscillateur"], parametre: { nom: "Forme", nomEn: "Waveform", vaut: "sawtooth" }, rendu: true, quoi: "un oscillateur lancé", quoiEn: "an Oscillator that has run" } },
  },
  {
    id: "moduler-fort", chapitre: "matiere",
    titre: "Moduler jusqu'au timbre", titreEn: "Modulate into timbre",
    enonce: "Sur le FM / AM Synth, pousse l'indice de modulation à 30 au moins, et écoute.",
    enonceEn: "On the FM / AM Synth, push the modulation index to at least 30, and listen.",
    indice: "« Harmonicity » est le rapport des deux fréquences : entier, le résultat reste harmonique ; non entier, il devient cloche ou métal.",
    indiceEn: "« Harmonicity » is the ratio of the two frequencies: whole, the result stays harmonic; not whole, it turns into a bell or metal.",
    lecon: "Chowning a découvert en 1973 qu'un vibrato poussé trop loin cesse d'être un vibrato et devient un timbre. L'indice de modulation décide du nombre de bandes latérales : à un, deux raies discrètes de part et d'autre ; à trente, un spectre entier. Un seul réglage traverse donc tout le chemin de l'effet au timbre, ce qui explique le succès commercial du procédé.",
    leconEn: "Chowning found in 1973 that a vibrato pushed too far stops being a vibrato and becomes a timbre. The modulation index decides the number of sidebands: at one, two discreet lines either side; at thirty, a whole spectrum. One setting therefore travels the entire road from effect to timbre, which explains the process's commercial success.",
    condition: { sorte: "present", critere: { fiches: ["fm-synth"], parametre: { nom: "Modulation index", nomEn: "Modulation index", min: 30 }, rendu: true, quoi: "le synthétiseur FM", quoiEn: "the FM synth" } },
  },
  {
    id: "grains-courts", chapitre: "matiere",
    titre: "Des grains si courts qu'ils perdent leur note", titreEn: "Grains so short they lose their note",
    enonce: "Avec le Granular freeze, descends la taille des grains à 20 millisecondes ou moins.",
    enonceEn: "With the Granular Freeze, bring the grain size down to 20 milliseconds or less.",
    indice: "« Position » choisit l'endroit du son que l'on gèle ; la taille décide de ce qu'on entend du grain lui-même.",
    indiceEn: "« Position » picks the point in the sound being frozen; size decides what you hear of the grain itself.",
    lecon: "Sous une cinquantaine de millisecondes, un grain n'a plus de hauteur propre : l'oreille a besoin de plusieurs périodes pour en juger, et deux périodes d'un la 440 ne font que cinq millisecondes. C'est la frontière que Gabor décrit en 1947 et que Xenakis puis Roads ont prise comme matériau : en dessous, on ne compose plus des notes mais une densité.",
    leconEn: "Below some fifty milliseconds a grain has no pitch of its own: the ear needs several periods to judge one, and two periods of a 440 hertz A last only five milliseconds. That is the boundary Gabor described in 1947 and which Xenakis, then Roads, took as material: below it you no longer compose notes but a density.",
    condition: { sorte: "present", critere: { fiches: ["granular-freeze"], parametre: { nom: "Taille", nomEn: "Grain size", max: 20 }, rendu: true, quoi: "le granular freeze", quoiEn: "the Granular Freeze" } },
  },
  {
    id: "etirer-loin", chapitre: "matiere",
    titre: "Étirer vingt fois", titreEn: "Stretch twenty times",
    enonce: "Passe un son dans Paulstretch avec un étirement de 20 au moins.",
    enonceEn: "Put a sound through Paulstretch with a stretch of at least 20.",
    indice: "Un son court suffit : une seconde étirée vingt fois en donne vingt. La fenêtre décide de la finesse du résultat.",
    indiceEn: "A short sound is enough: one second stretched twenty times gives twenty. The window decides how fine the result is.",
    lecon: "À ce facteur, ce n'est plus un étirement mais un changement de nature : les phases sont tirées au hasard à chaque trame, ce qui détruit les transitoires et ne garde que le spectre. C'est précisément ce qu'on veut — un étirement qui garderait les attaques donnerait un bégaiement. La graine est là pour que deux rendus du même réglage donnent le même son.",
    leconEn: "At that factor it is no longer a stretch but a change of nature: phases are drawn at random in every frame, which destroys transients and keeps only the spectrum. That is exactly what is wanted — a stretch that kept the attacks would give a stutter. The seed is there so two renders of the same setting give the same sound.",
    condition: { sorte: "present", critere: { fiches: ["paulstretch"], parametre: { nom: "Stretch", nomEn: "Stretch", min: 20 }, rendu: true, quoi: "le paulstretch", quoiEn: "the Paulstretch" } },
  },
  {
    id: "epreuve-matiere-vivante", chapitre: "matiere", epreuve: true,
    titre: "Épreuve — une matière, pas une note", titreEn: "Trial — matter, not a note",
    enonce: "Amène quatre secondes au moins d'une matière dense et colorée : facteur de crête sous 16 dB, et au moins 2 % de l'énergie au-dessus de 4 kHz.",
    enonceEn: "Bring at least four seconds of dense, coloured matter: crest factor under 16 dB, and at least 2 % of the energy above 4 kHz.",
    indice: "Une sinusoïde tenue échoue par le haut du spectre, qu'elle n'a pas. Une boucle de batterie échoue par l'autre bout — son facteur de crête dépasse vingt décibels, mesuré. Du bruit rose passé aux grains, ou une texture statistique, tiennent les deux.",
    indiceEn: "A held sine fails on the top of the spectrum, which it does not have. A drum loop fails from the other end — its crest factor passes twenty decibels, measured. Pink noise run through grains, or a statistical texture, hold both.",
    lecon: "Les deux mesures bornent la matière des deux côtés, et c'est ce qui les rend instructives ensemble. Le facteur de crête — l'écart entre la crête et le niveau moyen — dit la densité : trois décibels pour une sinusoïde, douze pour du bruit, plus de vingt pour une percussion sèche. La part d'aigu dit la couleur : un son sans rien au-dessus de quatre kilohertz s'entend comme sourd, quelle que soit sa densité. Une matière est dense et colorée à la fois ; une note n'a besoin d'être ni l'un ni l'autre.",
    leconEn: "The two measurements bound matter from both sides, and that is what makes them instructive together. The crest factor — the gap between peak and average level — states density: three decibels for a sine, twelve for noise, more than twenty for a dry percussion hit. The share of treble states colour: a sound with nothing above four kilohertz is heard as dull, whatever its density. Matter is dense as well as coloured; a note needs to be neither.",
    cibles: [
      { grandeur: "duree", min: 4, exigence: "au moins quatre secondes", exigenceEn: "at least four seconds" },
      { grandeur: "facteurCrete", max: 16, exigence: "facteur de crête sous 16 dB", exigenceEn: "crest factor under 16 dB" },
      { grandeur: "partAigu", min: 2, exigence: "au moins 2 % de l'énergie au-dessus de 4 kHz", exigenceEn: "at least 2 % of the energy above 4 kHz" },
    ],
  },

  // ── La musique ──────────────────────────────────────────────────────────────────────────────
  {
    id: "sequencer-une-melodie", chapitre: "musique",
    titre: "Une mélodie sans fausse note", titreEn: "A melody with no wrong note",
    enonce: "Pose un Séquenceur mélodique, mets-le en pentatonique mineure, et dessine quelques pas.",
    enonceEn: "Place a Melodic Sequencer, set it to the minor pentatonic, and draw a few steps.",
    indice: "La grille se clique directement dans le nœud. Chaque ligne est un degré de la gamme choisie, et non un demi-ton.",
    indiceEn: "The grid is clicked straight in the node. Each row is a degree of the chosen scale, and not a semitone.",
    lecon: "Une pentatonique n'a aucun demi-ton : aucune de ses notes ne frotte contre une autre, et c'est pourquoi n'importe quelle suite de pas y sonne juste. Ce n'est pas de la chance mais de la géométrie — en retirant les deux degrés qui portaient les frottements de la gamme majeure, on retire aussi la possibilité de se tromper. D'où son usage dans tous les instruments pour débutants.",
    leconEn: "A pentatonic has no semitone at all: none of its notes rubs against another, which is why any sequence of steps sounds right in it. That is not luck but geometry — by removing the two degrees that carried the major scale's rubbing, you also remove the chance of going wrong. Hence its use in every beginner's instrument.",
    condition: { sorte: "present", critere: { fiches: ["sequenceur-melodique"], parametre: { nom: "Gamme", nomEn: "Scale", vaut: "pentatonique mineur" }, rendu: true, quoi: "le séquenceur mélodique", quoiEn: "the Melodic Sequencer" } },
  },
  {
    id: "arpeger-des-accords", chapitre: "musique",
    titre: "Arpéger plutôt que plaquer", titreEn: "Arpeggiate rather than block",
    enonce: "Avec le Séquenceur d'accords, passe du mode Harmonie au mode Arpège.",
    enonceEn: "With the Chord Sequencer, switch from Harmony mode to Arpeggio mode.",
    indice: "Le même motif, les mêmes accords : seul le mode change. Écoutez les deux l'un après l'autre.",
    indiceEn: "Same pattern, same chords: only the mode changes. Listen to both one after the other.",
    lecon: "Un accord plaqué et son arpège portent les mêmes notes et ne disent pas la même chose : le premier donne une couleur, le second un mouvement. L'oreille fusionne les notes simultanées en un timbre unique — c'est le principe même de la synthèse additive — tandis qu'étalées dans le temps, elles redeviennent une mélodie. La même matière harmonique change de nature selon le rythme qu'on lui donne.",
    leconEn: "A block chord and its arpeggio carry the same notes and do not say the same thing: the first gives a colour, the second a movement. The ear fuses simultaneous notes into one timbre — the very principle of additive synthesis — whereas spread over time they become a melody again. The same harmonic material changes nature with the rhythm it is given.",
    condition: { sorte: "present", critere: { fiches: ["sequenceur-accords"], parametre: { nom: "Mode", nomEn: "Mode", vaut: "arpege" }, rendu: true, quoi: "le séquenceur d'accords", quoiEn: "the Chord Sequencer" } },
  },
  {
    id: "rythme-euclidien", chapitre: "musique",
    titre: "Sept frappes sur seize pas", titreEn: "Seven onsets over sixteen steps",
    enonce: "Règle le Rythme euclidien sur seize pas et sept frappes.",
    enonceEn: "Set the Euclidean Rhythm to sixteen steps and seven onsets.",
    indice: "Essayez ensuite la rotation : le même rythme, commencé ailleurs, devient un autre rythme à l'oreille.",
    indiceEn: "Then try the rotation: the same rhythm, started elsewhere, becomes another rhythm to the ear.",
    lecon: "Répartir k frappes sur n pas le plus uniformément possible est le même calcul que l'algorithme d'Euclide pour le plus grand commun diviseur, et Toussaint a montré en 2005 que les rythmes ainsi obtenus sont ceux qu'on trouve déjà en Afrique de l'Ouest, dans les Balkans et à Cuba. Trois frappes sur huit pas donnent le tresillo : personne ne l'a déduit d'un calcul, et le calcul le retrouve.",
    leconEn: "Spreading k onsets over n steps as evenly as possible is the same computation as Euclid's algorithm for the greatest common divisor, and Toussaint showed in 2005 that the rhythms so obtained are the ones already found in West Africa, the Balkans and Cuba. Three onsets over eight steps give the tresillo: nobody deduced it from a computation, and the computation finds it again.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "present", critere: { fiches: ["rythme-euclidien"], parametre: { nom: "Pas", nomEn: "Steps", vaut: 16 }, quoi: "le rythme euclidien", quoiEn: "the Euclidean Rhythm" } },
        { sorte: "present", critere: { fiches: ["rythme-euclidien"], parametre: { nom: "Frappes", nomEn: "Onsets", vaut: 7 }, rendu: true, quoi: "le rythme euclidien", quoiEn: "the Euclidean Rhythm" } },
      ],
    },
  },
  {
    id: "relire-l-harmonie", chapitre: "musique",
    titre: "Faire relire la machine", titreEn: "Have the machine read it back",
    enonce: "Branche un Détecteur d'accords ou une Analyse harmonique sur ta sortie musicale, et lance.",
    enonceEn: "Wire a Chord Detector or a Harmonic Analysis onto your musical output, and run.",
    indice: "Les deux prennent de l'audio et non du MIDI : c'est le son rendu qu'ils écoutent, comme le ferait quelqu'un d'autre.",
    indiceEn: "Both take audio and not MIDI: they listen to the rendered sound, as someone else would.",
    lecon: "La reconnaissance passe par un chromagramme : toutes les octaves sont repliées en douze classes de hauteur, ce qui efface la tessiture et l'instrument pour ne garder que les notes. Ce repliement est ce qui permet de reconnaître un accord joué au piano comme à la guitare — et aussi ce qui fait qu'un accord et son renversement se ressemblent tant pour la machine, alors qu'ils ne s'entendent pas pareil.",
    leconEn: "Recognition goes through a chromagram: every octave is folded into twelve pitch classes, which erases register and instrument to keep only the notes. That folding is what allows a chord played on piano to be recognised as one played on guitar — and also what makes a chord and its inversion so alike to the machine, when they do not sound alike at all.",
    condition: {
      sorte: "relie",
      amont: { univers: "Entrées", famille: "Génération", quoi: "une source musicale", quoiEn: "a musical source" },
      aval: { fiches: ["detecteur-accords", "tonal-analyse"], rendu: true, quoi: "une analyse harmonique lancée", quoiEn: "a harmonic analysis that has run" },
    },
  },
  {
    id: "epreuve-le-la", chapitre: "musique", epreuve: true,
    titre: "Épreuve — trois mesures à quatre-vingt-dix", titreEn: "Trial — three bars at ninety",
    enonce: "Amène une phrase jouée qui dure exactement trois mesures à quatre temps à 90 à la noire — huit secondes, à un dixième près.",
    enonceEn: "Bring a played phrase lasting exactly three four-beat bars at 90 to the quarter note — eight seconds, to within a tenth.",
    indice: "Une noire à 90 dure 60 divisé par 90, soit deux tiers de seconde ; quatre temps en font 2,667 s et trois mesures 8 s. Réglez le tempo et le nombre de mesures du séquenceur — puis regardez la durée mesurée, car elle ne tombera pas juste du premier coup.",
    indiceEn: "A quarter note at 90 lasts 60 divided by 90, that is two thirds of a second; four beats make 2.667 s and three bars 8 s. Set the sequencer's tempo and bar count — then look at the measured duration, because it will not land right first time.",
    lecon: "Le tempo n'est pas un réglage de vitesse mais une unité de durée : soixante divisé par le tempo donne la noire, et tout le reste s'en déduit par multiplication. C'est ce calcul qui fait tomber juste un délai, une boucle ou un montage, et c'est pourquoi un écho à 500 millisecondes est exactement une noire à 120 alors qu'il ne veut rien dire à 137.\n\nEt une surprise mesurée : un séquenceur réglé sur trois mesures à 90 rend 7,15 secondes, pas 8. Le rendu s'arrête à la dernière note, non à la barre de mesure — un son n'a aucune raison de savoir qu'une mesure se termine plus loin. Il faut donc compléter avec « Ajouter silence », ou poser une note sur le dernier pas. C'est exactement le genre de décalage qui fait qu'une boucle ne raccorde pas.",
    leconEn: "Tempo is not a speed setting but a unit of duration: sixty divided by the tempo gives the quarter note, and everything else follows by multiplication. That computation is what makes a delay, a loop or an edit land right, and it is why an echo at 500 milliseconds is exactly a quarter note at 120 while it means nothing at 137.\n\nAnd a measured surprise: a sequencer set to three bars at 90 returns 7.15 seconds, not 8. The render stops at the last note, not at the bar line — a sound has no reason to know a bar ends further on. So it has to be completed with « Add Silence », or a note placed on the last step. That is exactly the kind of gap that stops a loop from joining up.",
    condition: { sorte: "present", critere: { univers: "Entrées", famille: "Génération", rendu: true, quoi: "une source musicale lancée", quoiEn: "a musical source that has run" } },
    cibles: [
      { grandeur: "duree", min: 7.9, max: 8.1, exigence: "la durée tient entre 7,9 et 8,1 secondes", exigenceEn: "duration holds between 7.9 and 8.1 seconds" },
      { grandeur: "partVoisee", min: 15, exigence: "une hauteur se tient sur au moins 15 % du son", exigenceEn: "a pitch holds over at least 15 % of the sound" },
    ],
  },

  // ── L'œuvre ─────────────────────────────────────────────────────────────────────────────────
  {
    id: "faire-se-rencontrer", chapitre: "oeuvre",
    titre: "Faire se rencontrer deux sons", titreEn: "Make two sounds meet",
    enonce: "Pose deux sources, et fais-les arriver toutes les deux dans un nœud de montage.",
    enonceEn: "Place two sources, and have both of them arrive in one editing node.",
    indice: "Jointure audio met les sons l'un après l'autre, Fusionner en stéréo l'un à gauche et l'autre à droite, le Mélangeur les superpose.",
    indiceEn: "Audio Join puts the sounds one after the other, Merge to Stereo one left and one right, the Mixer lays them on top of each other.",
    lecon: "Additionner deux sons ajoute leurs énergies : deux signaux sans rapport donnent trois décibels de plus, deux copies du même en donnent six. C'est pourquoi un mélange demande de la marge avant de commencer — dix pistes à pleine échelle ne peuvent pas tenir dans une échelle, et baisser à la fin ne rattrape pas ce qui a déjà été écrêté.",
    leconEn: "Adding two sounds adds their energies: two unrelated signals give three decibels more, two copies of the same give six. That is why a mix needs headroom before it starts — ten tracks at full scale cannot fit in one scale, and pulling down at the end does not undo what has already been clipped.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "present", critere: { univers: "Entrées", famille: "Génération", quoi: "une source", quoiEn: "a source" }, nombre: 2 },
        { sorte: "present", critere: { famille: "Montage", rendu: true, quoi: "un nœud de montage lancé", quoiEn: "an editing node that has run" } },
      ],
    },
  },
  {
    id: "fondre-les-bords", chapitre: "oeuvre",
    titre: "Fondre le début et la fin", titreEn: "Fade the start and the end",
    enonce: "Pose un Fondu sur ton morceau, et lance.",
    enonceEn: "Place a Fade on your piece, and run.",
    indice: "Quelques millisecondes suffisent aux bords : le fondu sert ici à supprimer un clic, non à faire un effet.",
    indiceEn: "A few milliseconds are enough at the edges: the fade is here to remove a click, not to make an effect.",
    lecon: "Un morceau qui commence sur un échantillon non nul commence par une marche, et une marche contient toutes les fréquences : on l'entend comme un clic. Trois millisecondes de fondu suffisent à l'effacer. C'est la même raison qui oblige à couper les boucles au passage par zéro, et la même raison qui fait qu'un éditeur audio dessine toujours ses coupes en biais.",
    leconEn: "A piece starting on a non-zero sample starts with a step, and a step contains every frequency: it is heard as a click. Three milliseconds of fade are enough to erase it. It is the same reason loops must be cut at a zero crossing, and the same reason an audio editor always draws its cuts on a slant.",
    condition: { sorte: "present", critere: { fiches: ["fondu"], rendu: true, quoi: "un fondu lancé", quoiEn: "a Fade that has run" } },
  },
  {
    id: "sortir-et-nommer", chapitre: "oeuvre",
    titre: "Sortir, nommer, sauver", titreEn: "Output, name, save",
    enonce: "Mène ton son traité jusqu'à une Sortie audio, et lance.",
    enonceEn: "Lead your processed sound into an Audio output, and run.",
    indice: "C'est ce nœud qui porte le champ de nom de fichier et le bouton de sauvegarde, sous son lecteur.",
    indiceEn: "This node is the one carrying the filename field and the save button, under its player.",
    lecon: "Écrire un fichier 16 bits n'est pas une recopie : il faut passer de la virgule flottante à des entiers, donc arrondir, et un arrondi nu produit une distorsion corrélée au signal — audible sur les fins de réverbération. Attic ajoute donc un bruit de dispersion triangulaire avant d'arrondir : on échange une distorsion contre un souffle constant, très au-dessous de l'audible, et c'est un échange que l'oreille gagne largement.",
    leconEn: "Writing a 16-bit file is not a copy: floating point has to become integers, hence rounding, and bare rounding produces a distortion correlated with the signal — audible on reverb tails. Attic therefore adds a triangular dither noise before rounding: a distortion is traded for a constant hiss, far below audibility, and it is a trade the ear wins handsomely.",
    condition: {
      sorte: "relie",
      amont: { famille: "Effets", quoi: "un effet", quoiEn: "an effect" },
      aval: { fiches: ["sortie-audio"], rendu: true, quoi: "une sortie audio lancée", quoiEn: "an Audio output that has run" },
    },
  },
  {
    id: "epreuve-le-master", chapitre: "oeuvre", epreuve: true,
    titre: "Épreuve — le master", titreEn: "Trial — the master",
    enonce: "Amène un master complet : stéréo, sonie entre −17 et −14 LUFS, vrai pic sous −1 dBTP, facteur de crête d'au moins 6 dB, canaux équilibrés à 1 dB près.",
    enonceEn: "Bring a complete master: stereo, loudness between -17 and -14 LUFS, true peak under -1 dBTP, crest factor of at least 6 dB, channels balanced to within 1 dB.",
    indice: "Le facteur de crête écarte la solution facile : un limiteur poussé à fond atteint la sonie en écrasant tout, et tombe alors sous six décibels. Sur un son clairsemé — une boîte à rythmes, par exemple — il faut limiter avant de normaliser, sinon le plafond de vrai pic bloque le gain et le normaliseur vous le dira.",
    indiceEn: "The crest factor rules out the easy way: a limiter pushed to the floor reaches the loudness by squashing everything, and then falls under six decibels. On a sparse sound — a drum machine, say — you have to limit before normalising, otherwise the true-peak ceiling blocks the gain and the normaliser will tell you so.",
    lecon: "Cinq mesures qui se contredisent deux à deux, et c'est tout le métier du mastering : monter la sonie fait tomber le facteur de crête, tenir le vrai pic limite la sonie, élargir déséquilibre. Aucune ne s'optimise seule.\n\nLa fenêtre de sonie n'est pas à −14, et la raison est mesurée. Sur une boucle de batterie élargie, un limiteur à −24 puis une normalisation en sonie plafonnent à −17,9 LUFS ; à −30, −16,8 ; à −36, −16,1 — chaque fois avec le plafond de vrai pic qui bloque le gain. Atteindre les −14 LUFS des plateformes demanderait d'écraser le facteur de crête bien au-dessous de six décibels. C'est exactement pourquoi la radio travaille à −23 et le balado à −16 : la cible d'une plateforme n'est pas une cible de production.",
    leconEn: "Five measurements that contradict one another in pairs, and that is the whole craft of mastering: raising loudness drops the crest factor, holding true peak caps loudness, widening unbalances. None can be optimised alone.\n\nThe loudness window is not at -14, and the reason was measured. On a widened drum loop, a limiter at -24 followed by loudness normalising tops out at -17.9 LUFS; at -30, -16.8; at -36, -16.1 — each time with the true-peak ceiling blocking the gain. Reaching the platforms' -14 LUFS would mean crushing the crest factor far below six decibels. That is exactly why broadcast works at -23 and podcasts at -16: a platform's target is not a production target.",
    cibles: [
      { grandeur: "canaux", min: 2, exigence: "le master est stéréo", exigenceEn: "the master is stereo" },
      { grandeur: "lufs", min: -17, max: -14, exigence: "la sonie tient entre −17 et −14 LUFS", exigenceEn: "loudness holds between -17 and -14 LUFS" },
      { grandeur: "vraiPic", max: -1, exigence: "le vrai pic reste sous −1 dBTP", exigenceEn: "true peak stays under -1 dBTP" },
      { grandeur: "facteurCrete", min: 6, exigence: "le facteur de crête atteint 6 dB", exigenceEn: "the crest factor reaches 6 dB" },
      { grandeur: "equilibre", max: 1, exigence: "moins de 1 dB d'écart entre les canaux", exigenceEn: "less than 1 dB between the channels" },
    ],
  },
];
