// parcours/exercices-composition.ts — Les cinq derniers chapitres : l'espace, la hauteur, la matiere, la musique, l'oeuvre.
//
// POURQUOI UNE SUITE, ET NON UN REGROUPEMENT PAR SUJET. Le quiz tire sa serie par une graine sur
// la banque : reordonner les questions changerait ce qu'une graine donnee produit, et la promesse
// « meme entree, meme serie » avec. La coupe est donc positionnelle, et `EXERCICES` reste la
// concatenation des deux moities, dans l'ordre d'origine.

import type { Chapitre, Exercice } from "./types";
import { EFFET, GENERATEUR, GENERATEUR_LANCE, REGARD } from "./exercices-criteres";

export const EXERCICES_COMPOSITION: Exercice[] = [
  {
    id: "placer", chapitre: "espace",
    titre: "Placer le son", titreEn: "Place the sound",
    enonce: "Place ton son ailleurs qu'au centre, avec un Hard panner ou une Spatialisation stéréo.",
    enonceEn: "Place your sound somewhere other than the centre, with a Hard panner or Stereo Spatialization.",
    indice: "Le Hard panner range tout d'un côté ; la Spatialisation stéréo dose la position et la largeur, et accepte une courbe pour bouger dans le temps.",
    indiceEn: "The Hard panner throws everything to one side; Stereo Spatialization meters position and width, and accepts a curve to move over time.",
    lecon: "Le panoramique ne déplace pas le son : il change le rapport des deux canaux, et l'oreille en tire une direction par différence d'intensité. C'est un tour de passe-passe remarquablement efficace entre deux haut-parleurs, et totalement inopérant sur un seul — ce qui explique qu'un mixage très large s'effondre sur un téléphone.",
    leconEn: "Panning does not move the sound: it changes the ratio of the two channels, and the ear draws a direction from the intensity difference. It is a remarkably effective trick between two speakers, and utterly powerless on one — which is why a very wide mix collapses on a phone.",
    condition: { sorte: "present", critere: { fiches: ["hard-panner", "spatialisation-stereo"], rendu: true, quoi: "un composant de placement lancé", quoiEn: "a placement node that has run" } },
  },
  {
    id: "elargir", chapitre: "espace",
    titre: "Élargir, et le voir", titreEn: "Widen, and see it",
    enonce: "Élargis ton son avec Ampleur, puis branche le résultat sur un Goniomètre.",
    enonceEn: "Widen your sound with Spaciousness, then wire the result into a Goniometer.",
    indice: "Ampleur fabrique la différence entre canaux là où il n'y en a pas — un composant de largeur classique, lui, ne peut qu'amplifier une différence existante, donc rien sur un son mono.",
    indiceEn: "Spaciousness manufactures the difference between channels where there is none — a classic width node can only amplify an existing difference, hence nothing at all on a mono sound.",
    lecon: "Le goniomètre dessine la corrélation des deux canaux : une diagonale serrée signifie mono, un nuage rond signifie décorrélé. Un son parfaitement décorrélé perd trois décibels quand on le somme en mono, et ce n'est pas un défaut — c'est le prix géométrique de la largeur, que la racine de (1 + r) sur 2 donne exactement.",
    leconEn: "The goniometer draws the correlation of the two channels: a tight diagonal means mono, a round cloud means decorrelated. A perfectly decorrelated sound loses three decibels when summed to mono, and that is no fault — it is the geometric price of width, given exactly by the square root of (1 + r) over 2.",
    condition: {
      sorte: "relie",
      amont: { fiches: ["ampleur"], quoi: "le composant Ampleur", quoiEn: "the Spaciousness node" },
      aval: { fiches: ["goniometre"], rendu: true, quoi: "un goniomètre lancé", quoiEn: "a Goniometer that has run" },
    },
  },
  {
    id: "grave-solide", chapitre: "espace",
    titre: "Un grave qui tient debout", titreEn: "A low end that stands",
    enonce: "Ramène le bas du spectre au centre avec Grave en mono, et lance.",
    enonceEn: "Bring the bottom of the spectrum back to the centre with Bass Mono, and run.",
    indice: "Le composant annonce de combien il a réduit le côté, et vérifie que le milieu n'a pas bougé : c'est un passe-haut sur la différence des canaux, et la somme mono reste identique au bit près.",
    indiceEn: "The node reports how much it reduced the side, and checks the mid has not moved: it is a high-pass on the channel difference, and the mono sum stays identical bit for bit.",
    lecon: "Un grave large est un grave qui s'annule : dès qu'on additionne les deux canaux — sur un téléphone, dans un club, à la radio —, ce qui était en opposition disparaît. Rendre le bas mono ne s'entend presque pas en stéréo, parce que sous cent cinquante hertz l'oreille ne localise plus guère : la longueur d'onde dépasse la largeur de la tête.",
    leconEn: "A wide low end is a low end that cancels: as soon as the two channels are summed — on a phone, in a club, on radio — whatever was in opposition disappears. Making the bottom mono is barely audible in stereo, because below a hundred and fifty hertz the ear hardly localises at all: the wavelength is wider than the head.",
    condition: { sorte: "present", critere: { fiches: ["mono-grave"], rendu: true, quoi: "un grave en mono lancé", quoiEn: "a Bass Mono that has run" } },
  },
  {
    id: "epreuve-large-et-solide", chapitre: "espace", epreuve: true,
    titre: "Épreuve — large et solide", titreEn: "Trial — wide and solid",
    enonce: "Amène un son stéréo large mais équilibré : corrélation sous 0,6, et moins de 1,5 dB d'écart entre les canaux.",
    enonceEn: "Bring a wide yet balanced stereo sound: correlation under 0.6, and less than 1.5 dB between the channels.",
    indice: "Ampleur décorrèle, le Hard panner déséquilibre : l'épreuve demande l'un sans l'autre. Le Goniomètre montre les deux d'un coup d'œil.",
    indiceEn: "Spaciousness decorrelates, the Hard panner unbalances: the trial asks for one without the other. The Goniometer shows both at a glance.",
    lecon: "La largeur se paie en corrélation et se surveille à l'équilibre. Un son peut être large et tirer à gauche : cela s'entend comme un défaut de réglage et non comme un espace, alors qu'aucune des deux mesures ne le dirait seule. C'est le cas général en audio — une grandeur isolée ne prouve presque jamais ce qu'on lui fait dire.",
    leconEn: "Width is paid for in correlation and watched through balance. A sound can be wide and still pull to the left: that is heard as a setting mistake rather than as space, while neither measurement alone would say so. It is the general case in audio — one figure on its own almost never proves what it is made to say.",
    cibles: [
      { grandeur: "canaux", min: 2, exigence: "le son est bien stéréo", exigenceEn: "the sound really is stereo" },
      { grandeur: "correlation", max: 0.6, exigence: "la corrélation reste sous 0,6", exigenceEn: "correlation stays under 0.6" },
      { grandeur: "equilibre", max: 1.5, exigence: "moins de 1,5 dB d'écart entre les canaux", exigenceEn: "less than 1.5 dB between the channels" },
    ],
  },

  // ── La hauteur ──────────────────────────────────────────────────────────────────────────────
  {
    id: "suivre-la-hauteur", chapitre: "hauteur",
    titre: "Mesurer avant de corriger", titreEn: "Measure before correcting",
    enonce: "Branche un Suiveur de hauteur sur un son tenu, et lance.",
    enonceEn: "Wire a Pitch Follower onto a sustained sound, and run.",
    indice: "Il rend trois sorties : la hauteur en courbe, le son inchangé, et la confiance. Le Visualiseur de courbe montre les deux courbes.",
    indiceEn: "It returns three outputs: pitch as a curve, the sound unchanged, and confidence. The Curve Viewer shows both curves.",
    lecon: "Le suiveur ne cherche pas une fréquence mais une période : il compare le signal à lui-même décalé, et retient le décalage qui se ressemble le plus. C'est pourquoi il rend aussi une confiance — sur du bruit, aucun décalage ne ressemble, et une hauteur annoncée serait une invention. Un suiveur qui ne dit pas sa confiance est un suiveur qu'on ne peut pas croire.",
    leconEn: "The follower does not look for a frequency but for a period: it compares the signal with a delayed copy of itself, and keeps the delay that matches best. That is why it also returns a confidence — on noise no delay matches, and an announced pitch would be an invention. A follower that does not state its confidence is one you cannot trust.",
    condition: { sorte: "present", critere: { fiches: ["suiveur-hauteur"], rendu: true, quoi: "un suiveur de hauteur lancé", quoiEn: "a Pitch Follower that has run" } },
  },
  {
    id: "corriger-vers-une-gamme", chapitre: "hauteur",
    titre: "Ramener sur une gamme", titreEn: "Snap onto a scale",
    enonce: "Pose une Correction de hauteur et règle-la sur la gamme majeure plutôt que sur la chromatique.",
    enonceEn: "Place a Pitch Correction and set it to the major scale rather than the chromatic one.",
    indice: "Une gamme chromatique accepte les douze demi-tons : elle corrige les défauts sans jamais changer de note. Une gamme majeure, elle, ramène aussi les notes étrangères.",
    indiceEn: "A chromatic scale accepts all twelve semitones: it fixes flaws without ever changing a note. A major scale also pulls foreign notes back in.",
    lecon: "La correction rejoue les périodes du son à un autre espacement — c'est le recollement synchrone, et il garde les formants, si bien qu'une voix corrigée ne prend pas l'accent de l'écureuil. Sa limite est géométrique et écrite dans la notice : au-delà de quatre demi-tons, deux copies d'un même grain s'annulent, et à l'octave la raie dominante tombe à un centième du niveau d'entrée.",
    leconEn: "Correction replays the sound's periods at a different spacing — that is synchronous overlap-add, and it keeps the formants, so a corrected voice does not take on a chipmunk accent. Its limit is geometric and written in the notice: beyond four semitones, two copies of one grain cancel, and at the octave the dominant line falls to a hundredth of the input level.",
    condition: { sorte: "present", critere: { fiches: ["correction-hauteur"], parametre: { nom: "Gamme", nomEn: "Scale", vaut: "majeure" }, rendu: true, quoi: "la correction de hauteur", quoiEn: "the Pitch Correction" } },
  },
  {
    id: "transposer-sans-accelerer", chapitre: "hauteur",
    titre: "Transposer sans accélérer", titreEn: "Transpose without speeding up",
    enonce: "Monte un son de cinq demi-tons au moins, sans changer sa durée.",
    enonceEn: "Raise a sound by at least five semitones, without changing its duration.",
    indice: "« Phase Vocoder Tonalité » et « SoundTouch Tonalité » font l'un et l'autre ce travail. Comparez la durée annoncée avant et après : elle ne doit pas bouger.",
    indiceEn: "« Phase Vocoder Pitch » and « SoundTouch Pitch » both do this job. Compare the duration reported before and after: it must not move.",
    lecon: "Lire un son plus vite le monte et le raccourcit d'un même facteur : c'est l'accordéon du magnétophone, et les deux effets y sont inséparables. Les séparer demande de reconstruire le son — par trames spectrales dont on tourne la phase, ou par grains qu'on répète. Toute transposition à durée constante paie ce travail en artefacts : c'est un compromis, jamais un tour de magie.",
    leconEn: "Playing a sound faster raises it and shortens it by the very same factor: that is the tape accordion, and there the two effects are inseparable. Separating them means rebuilding the sound — through spectral frames whose phase is rotated, or through grains that are repeated. Every constant-duration transposition pays for that work in artefacts: a trade-off, never magic.",
    condition: { sorte: "present", critere: { fiches: ["phase-vocoder-tonalite", "soundtouch-tonalite"], parametre: { nom: "Tonalité", nomEn: "Pitch", min: 5 }, rendu: true, quoi: "un transposeur à durée constante", quoiEn: "a constant-duration transposer" } },
  },
  {
    id: "harmoniser", chapitre: "hauteur",
    titre: "Ajouter une quinte", titreEn: "Add a fifth",
    enonce: "Avec l'Harmonizer, fais sonner une quinte au-dessus de ton son : sept demi-tons.",
    enonceEn: "With the Harmonizer, sound a fifth above your sound: seven semitones.",
    indice: "« Voix 1 » compte en demi-tons : 12 pour l'octave, 7 pour la quinte, 4 pour la tierce majeure. Le mélange de chaque voix se règle à part.",
    indiceEn: "« Voice 1 » counts in semitones: 12 for the octave, 7 for the fifth, 4 for the major third. Each voice's mix is set separately.",
    lecon: "La quinte juste est le rapport 3/2, soit 702 cents ; le tempérament égal la pose à 700, et ces deux cents d'écart sont ce qui rend un piano habitable dans toutes les tonalités. Empiler douze quintes justes ne retombe pas sur l'octave — il reste le quart de ton du comma pythagoricien, et toute l'histoire des tempéraments consiste à décider où le cacher.",
    leconEn: "The perfect fifth is the ratio 3/2, hence 702 cents; equal temperament sets it at 700, and those two cents are what makes a piano liveable in every key. Stacking twelve perfect fifths does not land back on the octave — a quarter tone of Pythagorean comma is left over, and the whole history of temperaments is about deciding where to hide it.",
    condition: { sorte: "present", critere: { fiches: ["harmonizer"], parametre: { nom: "Voix 1", nomEn: "Voice 1", vaut: 7 }, rendu: true, quoi: "l'harmonizer", quoiEn: "the Harmonizer" } },
  },
  {
    id: "epreuve-dix-cents", chapitre: "hauteur", epreuve: true,
    titre: "Épreuve — juste à dix cents", titreEn: "Trial — in tune to ten cents",
    enonce: "Amène un son tenu dont la hauteur tombe à moins de dix cents du demi-ton le plus proche.",
    enonceEn: "Bring a sustained sound whose pitch lands within ten cents of the nearest semitone.",
    indice: "Un générateur réglé sur une fréquence quelconque — 453 hertz, par exemple — échouera ; la correction de hauteur en gamme chromatique le ramène. La mesure est celle du suiveur du catalogue.",
    indiceEn: "A generator set to any old frequency — 453 hertz, say — will fail; pitch correction on the chromatic scale pulls it back. The measurement is the catalog follower's own.",
    lecon: "Le cent est le centième de demi-ton, soit un rapport de fréquences de 1,00058. Cinq cents sur une note seule ne s'entendent pas ; les mêmes cinq cents entre deux notes tenues ensemble donnent un battement, et vingt cents rendent un unisson franchement faux. La justesse n'est donc pas une propriété d'une note mais d'un intervalle.",
    leconEn: "A cent is a hundredth of a semitone, a frequency ratio of 1.00058. Five cents on a lone note cannot be heard; the same five cents between two notes held together give a beating, and twenty cents make a unison plainly wrong. Tuning is therefore not a property of a note but of an interval.",
    cibles: [
      { grandeur: "justesse", max: 10, exigence: "à moins de dix cents du demi-ton", exigenceEn: "within ten cents of the semitone" },
      { grandeur: "partVoisee", min: 40, exigence: "une hauteur se tient sur au moins 40 % du son", exigenceEn: "a pitch holds over at least 40 % of the sound" },
    ],
  },

  // ── La matière ──────────────────────────────────────────────────────────────────────────────
  {
    id: "forme-riche", chapitre: "matiere",
    titre: "Une forme qui contient tout", titreEn: "A waveform that holds everything",
    enonce: "Pose un Oscillateur et mets-le en dent de scie.",
    enonceEn: "Place an Oscillator and set it to sawtooth.",
    indice: "Écoutez la même note en sinus, en carré, puis en scie : c'est le contenu harmonique qui change, pas la hauteur.",
    indiceEn: "Listen to the same note as sine, square, then sawtooth: what changes is the harmonic content, not the pitch.",
    lecon: "Une dent de scie porte tous les harmoniques, d'amplitude en un sur n ; un carré n'a que les impairs ; une sinusoïde n'en a aucun. C'est pourquoi la synthèse soustractive part de la scie : on ne peut retirer que ce qui est déjà là, et un filtre sur une sinusoïde ne fait que baisser le volume.",
    leconEn: "A sawtooth carries every harmonic, with amplitude one over n; a square only the odd ones; a sine none at all. That is why subtractive synthesis starts from the sawtooth: you can only remove what is already there, and a filter on a sine merely lowers the volume.",
    condition: { sorte: "present", critere: { fiches: ["oscillateur"], parametre: { nom: "Forme", nomEn: "Waveform", vaut: "sawtooth" }, rendu: true, quoi: "un oscillateur lancé", quoiEn: "an Oscillator that has run" } },
  },
  {
    id: "moduler-fort", chapitre: "matiere",
    titre: "Moduler jusqu'au timbre", titreEn: "Modulate into timbre",
    enonce: "Sur le FM / AM Synth, pousse l'indice de modulation à 30 au moins, et écoute.",
    enonceEn: "On the FM / AM Synth, push the modulation index to at least 30, and listen.",
    indice: "« Harmonicity » est le rapport des deux fréquences : entier, le résultat reste harmonique ; non entier, il devient cloche ou métal.",
    indiceEn: "« Harmonicity » is the ratio of the two frequencies: whole, the result stays harmonic; not whole, it turns into a bell or metal.",
    lecon: "Chowning a découvert en 1973 qu'un vibrato poussé trop loin cesse d'être un vibrato et devient un timbre. L'indice de modulation décide du nombre de bandes latérales : à un, deux raies discrètes de part et d'autre ; à trente, un spectre entier. Un seul réglage traverse donc tout le chemin de l'effet au timbre, ce qui explique le succès commercial du procédé.",
    leconEn: "Chowning found in 1973 that a vibrato pushed too far stops being a vibrato and becomes a timbre. The modulation index decides the number of sidebands: at one, two discreet lines either side; at thirty, a whole spectrum. One setting therefore travels the entire road from effect to timbre, which explains the process's commercial success.",
    condition: { sorte: "present", critere: { fiches: ["fm-synth"], parametre: { nom: "Modulation index", nomEn: "Modulation index", min: 30 }, rendu: true, quoi: "le synthétiseur FM", quoiEn: "the FM synth" } },
  },
  {
    id: "grains-courts", chapitre: "matiere",
    titre: "Des grains si courts qu'ils perdent leur note", titreEn: "Grains so short they lose their note",
    enonce: "Avec le Granular freeze, descends la taille des grains à 20 millisecondes ou moins.",
    enonceEn: "With the Granular Freeze, bring the grain size down to 20 milliseconds or less.",
    indice: "« Position » choisit l'endroit du son que l'on gèle ; la taille décide de ce qu'on entend du grain lui-même.",
    indiceEn: "« Position » picks the point in the sound being frozen; size decides what you hear of the grain itself.",
    lecon: "Sous une cinquantaine de millisecondes, un grain n'a plus de hauteur propre : l'oreille a besoin de plusieurs périodes pour en juger, et deux périodes d'un la 440 ne font que cinq millisecondes. C'est la frontière que Gabor décrit en 1947 et que Xenakis puis Roads ont prise comme matériau : en dessous, on ne compose plus des notes mais une densité.",
    leconEn: "Below some fifty milliseconds a grain has no pitch of its own: the ear needs several periods to judge one, and two periods of a 440 hertz A last only five milliseconds. That is the boundary Gabor described in 1947 and which Xenakis, then Roads, took as material: below it you no longer compose notes but a density.",
    condition: { sorte: "present", critere: { fiches: ["granular-freeze"], parametre: { nom: "Taille", nomEn: "Grain size", max: 20 }, rendu: true, quoi: "le granular freeze", quoiEn: "the Granular Freeze" } },
  },
  {
    id: "etirer-loin", chapitre: "matiere",
    titre: "Étirer vingt fois", titreEn: "Stretch twenty times",
    enonce: "Passe un son dans Paulstretch avec un étirement de 20 au moins.",
    enonceEn: "Put a sound through Paulstretch with a stretch of at least 20.",
    indice: "Un son court suffit : une seconde étirée vingt fois en donne vingt. La fenêtre décide de la finesse du résultat.",
    indiceEn: "A short sound is enough: one second stretched twenty times gives twenty. The window decides how fine the result is.",
    lecon: "À ce facteur, ce n'est plus un étirement mais un changement de nature : les phases sont tirées au hasard à chaque trame, ce qui détruit les transitoires et ne garde que le spectre. C'est précisément ce qu'on veut — un étirement qui garderait les attaques donnerait un bégaiement. La graine est là pour que deux rendus du même réglage donnent le même son.",
    leconEn: "At that factor it is no longer a stretch but a change of nature: phases are drawn at random in every frame, which destroys transients and keeps only the spectrum. That is exactly what is wanted — a stretch that kept the attacks would give a stutter. The seed is there so two renders of the same setting give the same sound.",
    condition: { sorte: "present", critere: { fiches: ["paulstretch"], parametre: { nom: "Stretch", nomEn: "Stretch", min: 20 }, rendu: true, quoi: "le paulstretch", quoiEn: "the Paulstretch" } },
  },
  {
    id: "epreuve-matiere-vivante", chapitre: "matiere", epreuve: true,
    titre: "Épreuve — une matière, pas une note", titreEn: "Trial — matter, not a note",
    enonce: "Amène quatre secondes au moins d'une matière dense et colorée : facteur de crête sous 16 dB, et au moins 2 % de l'énergie au-dessus de 4 kHz.",
    enonceEn: "Bring at least four seconds of dense, coloured matter: crest factor under 16 dB, and at least 2 % of the energy above 4 kHz.",
    indice: "Une sinusoïde tenue échoue par le haut du spectre, qu'elle n'a pas. Une boucle de batterie échoue par l'autre bout — son facteur de crête dépasse vingt décibels, mesuré. Du bruit rose passé aux grains, ou une texture statistique, tiennent les deux.",
    indiceEn: "A held sine fails on the top of the spectrum, which it does not have. A drum loop fails from the other end — its crest factor passes twenty decibels, measured. Pink noise run through grains, or a statistical texture, hold both.",
    lecon: "Les deux mesures bornent la matière des deux côtés, et c'est ce qui les rend instructives ensemble. Le facteur de crête — l'écart entre la crête et le niveau moyen — dit la densité : trois décibels pour une sinusoïde, douze pour du bruit, plus de vingt pour une percussion sèche. La part d'aigu dit la couleur : un son sans rien au-dessus de quatre kilohertz s'entend comme sourd, quelle que soit sa densité. Une matière est dense et colorée à la fois ; une note n'a besoin d'être ni l'un ni l'autre.",
    leconEn: "The two measurements bound matter from both sides, and that is what makes them instructive together. The crest factor — the gap between peak and average level — states density: three decibels for a sine, twelve for noise, more than twenty for a dry percussion hit. The share of treble states colour: a sound with nothing above four kilohertz is heard as dull, whatever its density. Matter is dense as well as coloured; a note needs to be neither.",
    cibles: [
      { grandeur: "duree", min: 4, exigence: "au moins quatre secondes", exigenceEn: "at least four seconds" },
      { grandeur: "facteurCrete", max: 16, exigence: "facteur de crête sous 16 dB", exigenceEn: "crest factor under 16 dB" },
      { grandeur: "partAigu", min: 2, exigence: "au moins 2 % de l'énergie au-dessus de 4 kHz", exigenceEn: "at least 2 % of the energy above 4 kHz" },
    ],
  },

  // ── La musique ──────────────────────────────────────────────────────────────────────────────
  {
    id: "sequencer-une-melodie", chapitre: "musique",
    titre: "Une mélodie sans fausse note", titreEn: "A melody with no wrong note",
    enonce: "Pose un Séquenceur mélodique, mets-le en pentatonique mineure, et dessine quelques pas.",
    enonceEn: "Place a Melodic Sequencer, set it to the minor pentatonic, and draw a few steps.",
    indice: "La grille se clique directement dans le composant. Chaque ligne est un degré de la gamme choisie, et non un demi-ton.",
    indiceEn: "The grid is clicked straight in the node. Each row is a degree of the chosen scale, and not a semitone.",
    lecon: "Une pentatonique n'a aucun demi-ton : aucune de ses notes ne frotte contre une autre, et c'est pourquoi n'importe quelle suite de pas y sonne juste. Ce n'est pas de la chance mais de la géométrie — en retirant les deux degrés qui portaient les frottements de la gamme majeure, on retire aussi la possibilité de se tromper. D'où son usage dans tous les instruments pour débutants.",
    leconEn: "A pentatonic has no semitone at all: none of its notes rubs against another, which is why any sequence of steps sounds right in it. That is not luck but geometry — by removing the two degrees that carried the major scale's rubbing, you also remove the chance of going wrong. Hence its use in every beginner's instrument.",
    condition: { sorte: "present", critere: { fiches: ["sequenceur-melodique"], parametre: { nom: "Gamme", nomEn: "Scale", vaut: "pentatonique mineur" }, rendu: true, quoi: "le séquenceur mélodique", quoiEn: "the Melodic Sequencer" } },
  },
  {
    id: "arpeger-des-accords", chapitre: "musique",
    titre: "Arpéger plutôt que plaquer", titreEn: "Arpeggiate rather than block",
    enonce: "Avec le Séquenceur d'accords, passe du mode Harmonie au mode Arpège.",
    enonceEn: "With the Chord Sequencer, switch from Harmony mode to Arpeggio mode.",
    indice: "Le même motif, les mêmes accords : seul le mode change. Écoutez les deux l'un après l'autre.",
    indiceEn: "Same pattern, same chords: only the mode changes. Listen to both one after the other.",
    lecon: "Un accord plaqué et son arpège portent les mêmes notes et ne disent pas la même chose : le premier donne une couleur, le second un mouvement. L'oreille fusionne les notes simultanées en un timbre unique — c'est le principe même de la synthèse additive — tandis qu'étalées dans le temps, elles redeviennent une mélodie. La même matière harmonique change de nature selon le rythme qu'on lui donne.",
    leconEn: "A block chord and its arpeggio carry the same notes and do not say the same thing: the first gives a colour, the second a movement. The ear fuses simultaneous notes into one timbre — the very principle of additive synthesis — whereas spread over time they become a melody again. The same harmonic material changes nature with the rhythm it is given.",
    condition: { sorte: "present", critere: { fiches: ["sequenceur-accords"], parametre: { nom: "Mode", nomEn: "Mode", vaut: "arpege" }, rendu: true, quoi: "le séquenceur d'accords", quoiEn: "the Chord Sequencer" } },
  },
  {
    id: "rythme-euclidien", chapitre: "musique",
    titre: "Sept frappes sur seize pas", titreEn: "Seven onsets over sixteen steps",
    enonce: "Règle le Rythme euclidien sur seize pas et sept frappes.",
    enonceEn: "Set the Euclidean Rhythm to sixteen steps and seven onsets.",
    indice: "Essayez ensuite la rotation : le même rythme, commencé ailleurs, devient un autre rythme à l'oreille.",
    indiceEn: "Then try the rotation: the same rhythm, started elsewhere, becomes another rhythm to the ear.",
    lecon: "Répartir k frappes sur n pas le plus uniformément possible est le même calcul que l'algorithme d'Euclide pour le plus grand commun diviseur, et Toussaint a montré en 2005 que les rythmes ainsi obtenus sont ceux qu'on trouve déjà en Afrique de l'Ouest, dans les Balkans et à Cuba. Trois frappes sur huit pas donnent le tresillo : personne ne l'a déduit d'un calcul, et le calcul le retrouve.",
    leconEn: "Spreading k onsets over n steps as evenly as possible is the same computation as Euclid's algorithm for the greatest common divisor, and Toussaint showed in 2005 that the rhythms so obtained are the ones already found in West Africa, the Balkans and Cuba. Three onsets over eight steps give the tresillo: nobody deduced it from a computation, and the computation finds it again.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "present", critere: { fiches: ["rythme-euclidien"], parametre: { nom: "Pas", nomEn: "Steps", vaut: 16 }, quoi: "le rythme euclidien", quoiEn: "the Euclidean Rhythm" } },
        { sorte: "present", critere: { fiches: ["rythme-euclidien"], parametre: { nom: "Frappes", nomEn: "Onsets", vaut: 7 }, rendu: true, quoi: "le rythme euclidien", quoiEn: "the Euclidean Rhythm" } },
      ],
    },
  },
  {
    id: "relire-l-harmonie", chapitre: "musique",
    titre: "Faire relire la machine", titreEn: "Have the machine read it back",
    enonce: "Branche un Détecteur d'accords ou une Analyse harmonique sur ta sortie musicale, et lance.",
    enonceEn: "Wire a Chord Detector or a Harmonic Analysis onto your musical output, and run.",
    indice: "Les deux prennent de l'audio et non du MIDI : c'est le son rendu qu'ils écoutent, comme le ferait quelqu'un d'autre.",
    indiceEn: "Both take audio and not MIDI: they listen to the rendered sound, as someone else would.",
    lecon: "La reconnaissance passe par un chromagramme : toutes les octaves sont repliées en douze classes de hauteur, ce qui efface la tessiture et l'instrument pour ne garder que les notes. Ce repliement est ce qui permet de reconnaître un accord joué au piano comme à la guitare — et aussi ce qui fait qu'un accord et son renversement se ressemblent tant pour la machine, alors qu'ils ne s'entendent pas pareil.",
    leconEn: "Recognition goes through a chromagram: every octave is folded into twelve pitch classes, which erases register and instrument to keep only the notes. That folding is what allows a chord played on piano to be recognised as one played on guitar — and also what makes a chord and its inversion so alike to the machine, when they do not sound alike at all.",
    condition: {
      sorte: "relie",
      amont: { univers: "Entrées", famille: "Génération", quoi: "une source musicale", quoiEn: "a musical source" },
      aval: { fiches: ["detecteur-accords", "tonal-analyse"], rendu: true, quoi: "une analyse harmonique lancée", quoiEn: "a harmonic analysis that has run" },
    },
  },
  {
    id: "epreuve-le-la", chapitre: "musique", epreuve: true,
    titre: "Épreuve — trois mesures à quatre-vingt-dix", titreEn: "Trial — three bars at ninety",
    enonce: "Amène une phrase jouée qui dure exactement trois mesures à quatre temps à 90 à la noire — huit secondes, à un dixième près.",
    enonceEn: "Bring a played phrase lasting exactly three four-beat bars at 90 to the quarter note — eight seconds, to within a tenth.",
    indice: "Une noire à 90 dure 60 divisé par 90, soit deux tiers de seconde ; quatre temps en font 2,667 s et trois mesures 8 s. Réglez le tempo et le nombre de mesures du séquenceur — puis regardez la durée mesurée, car elle ne tombera pas juste du premier coup.",
    indiceEn: "A quarter note at 90 lasts 60 divided by 90, that is two thirds of a second; four beats make 2.667 s and three bars 8 s. Set the sequencer's tempo and bar count — then look at the measured duration, because it will not land right first time.",
    lecon: "Le tempo n'est pas un réglage de vitesse mais une unité de durée : soixante divisé par le tempo donne la noire, et tout le reste s'en déduit par multiplication. C'est ce calcul qui fait tomber juste un délai, une boucle ou un montage, et c'est pourquoi un écho à 500 millisecondes est exactement une noire à 120 alors qu'il ne veut rien dire à 137.\n\nEt une surprise mesurée : un séquenceur réglé sur trois mesures à 90 rend 7,15 secondes, pas 8. Le rendu s'arrête à la dernière note, non à la barre de mesure — un son n'a aucune raison de savoir qu'une mesure se termine plus loin. Il faut donc compléter avec « Ajouter silence », ou poser une note sur le dernier pas. C'est exactement le genre de décalage qui fait qu'une boucle ne raccorde pas.",
    leconEn: "Tempo is not a speed setting but a unit of duration: sixty divided by the tempo gives the quarter note, and everything else follows by multiplication. That computation is what makes a delay, a loop or an edit land right, and it is why an echo at 500 milliseconds is exactly a quarter note at 120 while it means nothing at 137.\n\nAnd a measured surprise: a sequencer set to three bars at 90 returns 7.15 seconds, not 8. The render stops at the last note, not at the bar line — a sound has no reason to know a bar ends further on. So it has to be completed with « Add Silence », or a note placed on the last step. That is exactly the kind of gap that stops a loop from joining up.",
    condition: { sorte: "present", critere: { univers: "Entrées", famille: "Génération", rendu: true, quoi: "une source musicale lancée", quoiEn: "a musical source that has run" } },
    cibles: [
      { grandeur: "duree", min: 7.9, max: 8.1, exigence: "la durée tient entre 7,9 et 8,1 secondes", exigenceEn: "duration holds between 7.9 and 8.1 seconds" },
      { grandeur: "partVoisee", min: 15, exigence: "une hauteur se tient sur au moins 15 % du son", exigenceEn: "a pitch holds over at least 15 % of the sound" },
    ],
  },

  // ── L'œuvre ─────────────────────────────────────────────────────────────────────────────────
  {
    id: "faire-se-rencontrer", chapitre: "oeuvre",
    titre: "Faire se rencontrer deux sons", titreEn: "Make two sounds meet",
    enonce: "Pose deux sources, et fais-les arriver toutes les deux dans un composant de montage.",
    enonceEn: "Place two sources, and have both of them arrive in one editing node.",
    indice: "Jointure audio met les sons l'un après l'autre, Fusionner en stéréo l'un à gauche et l'autre à droite, le Mélangeur les superpose.",
    indiceEn: "Audio Join puts the sounds one after the other, Merge to Stereo one left and one right, the Mixer lays them on top of each other.",
    lecon: "Additionner deux sons ajoute leurs énergies : deux signaux sans rapport donnent trois décibels de plus, deux copies du même en donnent six. C'est pourquoi un mélange demande de la marge avant de commencer — dix pistes à pleine échelle ne peuvent pas tenir dans une échelle, et baisser à la fin ne rattrape pas ce qui a déjà été écrêté.",
    leconEn: "Adding two sounds adds their energies: two unrelated signals give three decibels more, two copies of the same give six. That is why a mix needs headroom before it starts — ten tracks at full scale cannot fit in one scale, and pulling down at the end does not undo what has already been clipped.",
    condition: {
      sorte: "toutes",
      conditions: [
        { sorte: "present", critere: { univers: "Entrées", famille: "Génération", quoi: "une source", quoiEn: "a source" }, nombre: 2 },
        { sorte: "present", critere: { famille: "Montage", rendu: true, quoi: "un composant de montage lancé", quoiEn: "an editing node that has run" } },
      ],
    },
  },
  {
    id: "fondre-les-bords", chapitre: "oeuvre",
    titre: "Fondre le début et la fin", titreEn: "Fade the start and the end",
    enonce: "Pose un Fondu sur ton morceau, et lance.",
    enonceEn: "Place a Fade on your piece, and run.",
    indice: "Quelques millisecondes suffisent aux bords : le fondu sert ici à supprimer un clic, non à faire un effet.",
    indiceEn: "A few milliseconds are enough at the edges: the fade is here to remove a click, not to make an effect.",
    lecon: "Un morceau qui commence sur un échantillon non nul commence par une marche, et une marche contient toutes les fréquences : on l'entend comme un clic. Trois millisecondes de fondu suffisent à l'effacer. C'est la même raison qui oblige à couper les boucles au passage par zéro, et la même raison qui fait qu'un éditeur audio dessine toujours ses coupes en biais.",
    leconEn: "A piece starting on a non-zero sample starts with a step, and a step contains every frequency: it is heard as a click. Three milliseconds of fade are enough to erase it. It is the same reason loops must be cut at a zero crossing, and the same reason an audio editor always draws its cuts on a slant.",
    condition: { sorte: "present", critere: { fiches: ["fondu"], rendu: true, quoi: "un fondu lancé", quoiEn: "a Fade that has run" } },
  },
  {
    id: "sortir-et-nommer", chapitre: "oeuvre",
    titre: "Sortir, nommer, sauver", titreEn: "Output, name, save",
    enonce: "Mène ton son traité jusqu'à une Sortie audio, et lance.",
    enonceEn: "Lead your processed sound into an Audio output, and run.",
    indice: "C'est ce composant qui porte le champ de nom de fichier et le bouton de sauvegarde, sous son lecteur.",
    indiceEn: "This node is the one carrying the filename field and the save button, under its player.",
    lecon: "Écrire un fichier n'est pas une recopie : il faut passer de la virgule flottante à des entiers, donc arrondir, et un arrondi nu produit une distorsion corrélée au signal — audible sur les fins de réverbération. Attic ajoute donc un bruit de dispersion triangulaire avant d'arrondir : on échange une distorsion contre un souffle constant, très au-dessous de l'audible, et c'est un échange que l'oreille gagne largement.\n\nLa profondeur se choisit dans la barre d'outils, et ce choix compte. Seize bits est une livraison de disque compact ; vingt-quatre est ce que réclame toute livraison professionnelle, et le défaut ici. Chaque bit vaut six décibels de précision : mesuré, la reconstruction passe de 88 dB en seize bits à 135 en vingt-quatre. Le trente-deux bits flottant, lui, ne quantifie rien du tout et garde même les dépassements du plein calibre — c'est le format d'un fichier qu'on retravaillera ailleurs, et le mauvais choix pour un fichier qu'on écoutera simplement.",
    leconEn: "Writing a file is not a copy: floating point has to become integers, hence rounding, and bare rounding produces a distortion correlated with the signal — audible on reverb tails. Attic therefore adds a triangular dither noise before rounding: a distortion is traded for a constant hiss, far below audibility, and it is a trade the ear wins handsomely.\n\nThe bit depth is chosen in the toolbar, and that choice matters. 16-bit is a compact disc delivery; 24-bit is what any professional delivery asks for, and the default here. Every bit is worth six decibels of precision: measured, reconstruction goes from 88 dB at 16-bit to 135 at 24. The 32-bit float format quantises nothing at all and keeps even the overshoots past full scale — it is the format for a file that will be worked on again elsewhere, and the wrong choice for a file that will simply be listened to.",
    condition: {
      sorte: "relie",
      amont: { famille: "Effets", quoi: "un effet", quoiEn: "an effect" },
      aval: { fiches: ["sortie-audio"], rendu: true, quoi: "une sortie audio lancée", quoiEn: "an Audio output that has run" },
    },
  },
  {
    id: "epreuve-le-master", chapitre: "oeuvre", epreuve: true,
    titre: "Épreuve — le master", titreEn: "Trial — the master",
    enonce: "Amène un master complet : stéréo, sonie entre −15 et −13 LUFS, vrai pic sous −1 dBTP, facteur de crête d'au moins 6 dB, canaux équilibrés à 1 dB près.",
    enonceEn: "Bring a complete master: stereo, loudness between -15 and -13 LUFS, true peak under -1 dBTP, crest factor of at least 6 dB, channels balanced to within 1 dB.",
    indice: "Le facteur de crête écarte la solution facile : un limiteur poussé à fond atteint la sonie en écrasant tout, et tombe alors sous six décibels. Sur un son clairsemé — une boîte à rythmes, par exemple — il faut limiter avant de normaliser, sinon le plafond de vrai pic bloque le gain et le normaliseur vous le dira.",
    indiceEn: "The crest factor rules out the easy way: a limiter pushed to the floor reaches the loudness by squashing everything, and then falls under six decibels. On a sparse sound — a drum machine, say — you have to limit before normalising, otherwise the true-peak ceiling blocks the gain and the normaliser will tell you so.",
    lecon: "Cinq mesures qui se contredisent deux à deux, et c'est tout le métier du mastering : monter la sonie fait tomber le facteur de crête, tenir le vrai pic limite la sonie, élargir déséquilibre. Aucune ne s'optimise seule.\n\nL'ordre compte, et il se mesure. Sur une boucle de batterie élargie, un limiteur à −24 dB placé en amont de la normalisation en sonie atteint −14,01 LUFS sous un plafond de −1 dBTP, en gardant 13,9 dB de facteur de crête. Sans lui, le normaliseur annonce que la cible n'est pas atteinte : le plafond de vrai pic bloque le gain, parce qu'une boucle clairsemée porte des crêtes très au-dessus de sa sonie. La cible des plateformes est donc tenable — mais parce qu'un limiteur a travaillé avant, et non parce qu'on a poussé le gain.",
    leconEn: "Five measurements that contradict one another in pairs, and that is the whole craft of mastering: raising loudness drops the crest factor, holding true peak caps loudness, widening unbalances. None can be optimised alone.\n\nOrder matters, and it can be measured. On a widened drum loop, a limiter at -24 dB placed ahead of loudness normalising reaches -14.01 LUFS under a -1 dBTP ceiling, keeping 13.9 dB of crest factor. Without it, the normaliser reports the target was not reached: the true-peak ceiling blocks the gain, because a sparse loop carries peaks far above its loudness. The platforms' target is therefore holdable — but because a limiter worked first, and not because gain was pushed.",
    cibles: [
      { grandeur: "canaux", min: 2, exigence: "le master est stéréo", exigenceEn: "the master is stereo" },
      { grandeur: "lufs", min: -15, max: -13, exigence: "la sonie tient entre −15 et −13 LUFS", exigenceEn: "loudness holds between -15 and -13 LUFS" },
      { grandeur: "vraiPic", max: -1, exigence: "le vrai pic reste sous −1 dBTP", exigenceEn: "true peak stays under -1 dBTP" },
      { grandeur: "facteurCrete", min: 6, exigence: "le facteur de crête atteint 6 dB", exigenceEn: "the crest factor reaches 6 dB" },
      { grandeur: "equilibre", max: 1, exigence: "moins de 1 dB d'écart entre les canaux", exigenceEn: "less than 1 dB between the channels" },
    ],
  },
];
